-- =============================================================================
-- Databricks ALTER Script: bronze etoro.History.CurrencyPriceMaxDateWithSplitView
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/History/Tables/History.CurrencyPriceMaxDateWithSplitView.md
-- Layer: bronze
-- UC Target: main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview
-- =============================================================================

-- ---- UC Target: main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview (business_group=bi_db) ----
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview SET TBLPROPERTIES (
    'comment' = 'Price cache table storing the last known split-adjusted bid/ask prices with spreads applied for 9,339 instruments - one row per instrument, used as a fast lookup for the most recent price including split adjustments. Source: etoro.History.CurrencyPriceMaxDateWithSplitView on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/History/Tables/History.CurrencyPriceMaxDateWithSplitView.md).'
);

ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'History',
    'source_table' = 'CurrencyPriceMaxDateWithSplitView',
    'business_group' = 'bi_db',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN InstrumentID COMMENT 'Instrument identifier. Clustered index key (one row per instrument). Implicit FK to Trade.InstrumentTbl. (Tier 1 - upstream wiki, etoro.History.CurrencyPriceMaxDateWithSplitView)';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN AskSpreaded COMMENT 'Ask price including spread (customer buy price). 8 decimal places for precision across all instrument types. (Tier 1 - upstream wiki, etoro.History.CurrencyPriceMaxDateWithSplitView)';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN BidSpreaded COMMENT 'Bid price with spread subtracted (customer sell price). (Tier 1 - upstream wiki, etoro.History.CurrencyPriceMaxDateWithSplitView)';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN Bid COMMENT 'Raw market bid price before spread is applied. NULL if not available. (Tier 1 - upstream wiki, etoro.History.CurrencyPriceMaxDateWithSplitView)';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN Ask COMMENT 'Raw market ask price before spread is applied. NULL if not available. (Tier 1 - upstream wiki, etoro.History.CurrencyPriceMaxDateWithSplitView)';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN PriceRateID COMMENT 'ID of the price tick from which this cached price was derived. Links to the price feed system. (Tier 1 - upstream wiki, etoro.History.CurrencyPriceMaxDateWithSplitView)';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN Occurred COMMENT 'Timestamp when this price was generated by the market. (Tier 1 - upstream wiki, etoro.History.CurrencyPriceMaxDateWithSplitView)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:35:25 UTC
-- Bronze deploy: etoro batch 1
-- ====================
