-- =============================================================================
-- Databricks ALTER Script: bronze etoro.History.PriceDetectionNotificationLog
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/History/Tables/History.PriceDetectionNotificationLog.md
-- Layer: bronze
-- UC Target: main.dealing.bronze_etoro_history_pricedetectionnotificationlog
-- =============================================================================

-- ---- UC Target: main.dealing.bronze_etoro_history_pricedetectionnotificationlog (business_group=dealing) ----
ALTER TABLE main.dealing.bronze_etoro_history_pricedetectionnotificationlog SET TBLPROPERTIES (
    'comment' = 'Companion alert log to PriceDetectionDifferenceLog, storing the human-readable subject and body of each price feed anomaly notification sent to operations teams. Source: etoro.History.PriceDetectionNotificationLog on the etoro production database, ingested via the Generic Pipeline (Append strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/History/Tables/History.PriceDetectionNotificationLog.md).'
);

ALTER TABLE main.dealing.bronze_etoro_history_pricedetectionnotificationlog SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'History',
    'source_table' = 'PriceDetectionNotificationLog',
    'business_group' = 'dealing',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Append',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.dealing.bronze_etoro_history_pricedetectionnotificationlog ALTER COLUMN NotificationLogID COMMENT 'Non-identity PK. Receives the IDENTITY value generated by History.PriceDetectionDifferenceLog.NotificationLogID (inserted by the price detection service with the same value). Enables direct 1:1 JOIN between the two tables. (Tier 1 - upstream wiki, etoro.History.PriceDetectionNotificationLog)';
ALTER TABLE main.dealing.bronze_etoro_history_pricedetectionnotificationlog ALTER COLUMN NotificationSeverityTypeID COMMENT 'Severity of the price discrepancy. FK to Dictionary.DowntimeSeverity: 1=Critical, 2=High, 3=Medium, 4=Low. Duplicated from DifferenceLog to allow standalone queries on this table without requiring a JOIN. (Tier 1 - upstream wiki, etoro.History.PriceDetectionNotificationLog)';
ALTER TABLE main.dealing.bronze_etoro_history_pricedetectionnotificationlog ALTER COLUMN Subject COMMENT 'Alert subject line. Format: "{InstrumentID} : {Low (Tier 1 - upstream wiki, etoro.History.PriceDetectionNotificationLog)';
ALTER TABLE main.dealing.bronze_etoro_history_pricedetectionnotificationlog ALTER COLUMN Body COMMENT 'Full alert body with structured feed comparison data. Contains: instrument ID, check timestamp, active feed provider name and price, secondary feed provider(s) and price(s). Used as email body content for operations notification. May be large (varchar max). Stored on TEXTIMAGE_ON [HISTORY]. (Tier 1 - upstream wiki, etoro.History.PriceDetectionNotificationLog)';
ALTER TABLE main.dealing.bronze_etoro_history_pricedetectionnotificationlog ALTER COLUMN Occurred COMMENT 'Local server timestamp when the notification was logged. DEFAULT getdate() (not UTC). Matches the "Time of check" field reported in the body. (Tier 1 - upstream wiki, etoro.History.PriceDetectionNotificationLog)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:35:25 UTC
-- Bronze deploy: etoro batch 1
-- ====================
