-- =============================================================================
-- Databricks ALTER Script: main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview  (TABLE)
-- Generated: 2026-05-19 | scaffold_alter_for_uc_targets.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/History/Tables/History.CurrencyPriceMaxDateWithSplitView.md
-- Target: Unity Catalog comments (1024 char limit per comment)
-- Drift guard: pre-flight uc_comment_validator.validate_alter_sql
-- =============================================================================

-- ---- Table comment intentionally not emitted (--cols-only) ----

-- ---- Column Comments ----
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN InstrumentID COMMENT 'Instrument identifier. Clustered index key (one row per instrument). Implicit FK to Trade.InstrumentTbl.';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN AskSpreaded COMMENT 'Ask price including spread (customer buy price). 8 decimal places for precision across all instrument types.';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN BidSpreaded COMMENT 'Bid price with spread subtracted (customer sell price).';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN Bid COMMENT 'Raw market bid price before spread is applied. NULL if not available.';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN Ask COMMENT 'Raw market ask price before spread is applied. NULL if not available.';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN PriceRateID COMMENT 'ID of the price tick from which this cached price was derived. Links to the price feed system.';
ALTER TABLE main.bi_db.bronze_etoro_history_currencypricemaxdatewithsplitview ALTER COLUMN Occurred COMMENT 'Timestamp when this price was generated by the market.';

-- NOTE: PII tags intentionally NOT emitted by scaffold_alter_for_uc_targets.py.
-- Blanket-tagging every column 'pii=none' would risk silently misclassifying
-- PII-masked columns. Run the dedicated PII classifier afterwards.

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-19 13:28:46 UTC
-- Statements: 7/7 succeeded
-- ====================
