-- =============================================================================
-- Databricks ALTER Script: EXW_dbo.EXW_FinanceReportsBalancesNew
-- Generated: 2026-04-21 | 15-phase pipeline
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew
-- Resolved via: Wiki property table
-- Classification: Non-standard
-- =============================================================================

ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew SET TBLPROPERTIES (
    'comment' = 'EXW_FinanceReportsBalancesNew is the central daily balance snapshot used by the eToro Wallet finance team to track crypto holdings across all active Wallet users. With 1.62 billion rows, it stores one record per GCID × WalletID × CryptoID × date, covering 689,733 distinct users across 173 cryptocurrency types as of the latest snapshot (2026-04-11). The table is driven by WalletBalancesReportDB''s daily reconciliation engine, which cross-checks wallet balances across three systems: the blockchain ledger (TotalReceive - TotalSend), eToro''s internal computed ledger (ComputedAmount), and third-party providers BitGo (ProviderValue) and Blox (WalletTrackerValue). The SP applies a priority rule to select the "best available" balance: if no discrepancy was detected (LevelId IS NULL), BloxBalance is used; if a discrepancy was classified, the BitGoValue or BloxValue is preferred based on LevelId. The result is stored in Balance, and multiplied by the daily average crypto price (EXW_PriceDaily.AvgPrice) to produce Bal...'
);

ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew SET TAGS (
    'domain' = 'general',
    'object_type' = 'table',
    'source_schema' = 'EXW_dbo',
    'refresh_frequency' = 'daily',
    'source_system' = 'Synapse',
    'synapse_distribution' = 'ROUND_ROBIN',
    'synapse_index' = 'CLUSTERED INDEX (BalanceDateID ASC, RealCID ASC)',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = '15-phase'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `GCID` COMMENT 'Global Customer ID -- identifies the wallet owner. Carried from the external table for denormalized customer-level querying without joining back to WalletDB. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `RealCID` COMMENT 'Customer ID - platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. Passthrough from DWH_dbo.Fact_SnapshotCustomer relay. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletID` COMMENT 'Crypto wallet identifier (GUID). Part of the composite business key (ReportId, WalletId, CryptoId). Used in CROSS APPLY joins by CreateNewReportRun and GetFinanceSnapshot to correlate with external table data. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `PublicAddress` COMMENT 'Blockchain address associated with this wallet-crypto pair. Passed through from the external table for traceability during discrepancy investigation. NULL for wallets without dedicated on-chain addresses. Renamed from FinanceReportRecords.Address. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `CryptoID` COMMENT 'Cryptocurrency asset identifier. Completes the composite business key. Same CryptoId may appear multiple times per run if a customer has multiple wallets for the same crypto. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `CryptoName` COMMENT 'Human-readable crypto asset name. Lookup from EXW_Wallet.CryptoTypes by CryptoID. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `BalanceDate` COMMENT 'Snapshot date for this balance record. Set to the @d input parameter of SP_EXW_FinanceReportsBalancesNew. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `BalanceDateID` COMMENT 'Integer representation of BalanceDate in YYYYMMDD format. Used as the primary filter key for incremental DELETE+INSERT. CLUSTERED INDEX key. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Price_Date` COMMENT 'Date of the price record used for USD conversion. Sourced from EXW_Wallet.EXW_PriceDaily.FullDate, matched by CryptoID + BalanceDateID. May differ from BalanceDate if no price is available for that exact date. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Rate` COMMENT 'Daily average crypto-to-USD price used to compute BalanceUSD. Sourced from EXW_Wallet.EXW_PriceDaily.AvgPrice for CryptoID on BalanceDateID. NULL if no price record exists for this crypto on this date. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ReportID` COMMENT 'FK to Wallet.FinanceReportRuns.Id identifying which reconciliation run produced this record. Constraint: FK__FinanceReportRecords__ReportId. Indexed in composite with LevelId and with WalletId+CryptoId. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `TotalReceive` COMMENT 'Total amount received into this wallet-crypto pair. Sourced from vu_GetWalletBalanceReport.TotalRecive (note: mapped from the misspelled column). Represents the cumulative incoming blockchain transactions. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `TotalSend` COMMENT 'Total amount sent from this wallet-crypto pair. Sourced from vu_GetWalletBalanceReport.TotalSend. Represents the cumulative outgoing blockchain transactions. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletDBBalance` COMMENT 'Blockchain-reported net balance (TotalReceive - TotalSend). Despite the name suggesting "Blox balance," this is actually the blockchain/computed balance from the external table''s TotalBalance column. The naming reflects the legacy system where Blox was the primary comparison source. Renamed from FinanceReportRecords.BloxBalance. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ComputedAmount` COMMENT 'Internally computed expected balance from eToro''s ledger system. Sourced from vu_GetWalletBalanceReport.TotalAmount. The reconciliation threshold check compares this against BloxBalance: ABS(ComputedAmount - BloxBalance) > @Threshold. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ProviderValue` COMMENT 'Balance amount reported by BitGo custody provider during the verification phase. Initially 0 (set by CreateNewReportRun). Updated by UpdateReportRecords with the actual BitGo API response. NULL/0 until the verification phase processes this record. Renamed from FinanceReportRecords.BitgoValue. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletTrackerValue` COMMENT 'Balance amount reported by Blox portfolio tracker during the verification phase. Initially 0 (set by CreateNewReportRun). Updated by UpdateReportRecords with the actual Blox API response. NULL/0 until verification. Renamed from FinanceReportRecords.BloxValue. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `LevelId` COMMENT 'FK to Dictionary.FinanceReportLevel classifying the reconciliation outcome. Initially set to 100 (InitialDiscrepancy) if balance exceeds threshold, NULL otherwise. Refined by UpdateReportRecords: 1=EventualyConsolidated, 2=AllDiff, 3=EtoroDiffBoth, 5-11=API errors, 12=InternalError. Distribution: NULL=96.9%, 3=1.5%, 2=0.35%, 1=0.24%. (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ReportOccurred` COMMENT 'UTC timestamp when the reconciliation record was created by WalletBalancesReportDB.Wallet.CreateNewReportRun. Renamed from FinanceReportRecords.Created (aliased as Occurred in SP). (Tier 1 - WalletBalancesReportDB.Wallet.FinanceReportRecords)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Balance` COMMENT 'Best available crypto balance for this wallet-crypto pair, selected by LevelId-based priority: LevelId IS NULL -> WalletDBBalance; LevelId set but only BloxValue available -> WalletTrackerValue; LevelId set but both providers NULL -> WalletDBBalance; ELSE -> ProviderValue (BitGo preferred). 80% of rows = 0 (inactive wallets). (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `BalanceUSD` COMMENT 'Balance converted to USD using daily average price. Computed as Balance × Rate (EXW_Wallet.EXW_PriceDaily.AvgPrice). 0 when Balance = 0 or Rate is NULL (price unavailable). Used by SP_EXW_DimUser_Enriched as the canonical TotalBalanceUSD source. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `RegulationID` COMMENT 'Regulatory entity classification at the time of the snapshot. Sourced from DWH_dbo.Fact_SnapshotCustomer. Distribution (latest date): CySEC=1 (46%), FCA=2 (27%), FinCEN+FINRA=8 (7%), FSA SEY=9 (5%), BVI=5 (5%), ASIC & GAML=10 (4%), eToroUS=6 (3%), others. (Tier 2 - SP_EXW_FinanceReportsBalancesNew via Fact_SnapshotCustomer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Regulation` COMMENT 'Human-readable name of the regulatory entity. Lookup from DWH_dbo.Dim_Regulation.Name by RegulationID (DWHRegulationID). (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `CountryID` COMMENT 'Country of the wallet user at snapshot date. Sourced from DWH_dbo.Fact_SnapshotCustomer.CountryID. FK to DWH_dbo.Dim_Country. (Tier 2 - SP_EXW_FinanceReportsBalancesNew via Fact_SnapshotCustomer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Country` COMMENT 'Human-readable country name. Lookup from DWH_dbo.Dim_Country.Name by CountryID. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `IsTestAccount` COMMENT '1 = user is a known test account (matched from EXW_TestUsers by username pattern or Beta criteria). 0 = real customer. Sourced from EXW_DimUser via LEFT JOIN on GCID. NULL if GCID not found in EXW_DimUser (pre-scope users). (Tier 2 - SP_EXW_FinanceReportsBalancesNew via EXW_DimUser)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `IsValidCustomer` COMMENT '1 = user passes standard eToro customer validity checks at snapshot date. Sourced from DWH_dbo.Fact_SnapshotCustomer.IsValidCustomer. (Tier 2 - SP_EXW_FinanceReportsBalancesNew via Fact_SnapshotCustomer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `VerificationLevelID` COMMENT 'KYC verification tier at snapshot date. Sourced from DWH_dbo.Fact_SnapshotCustomer. FK to Dim_VerificationLevel (1=Registered, 2=Phone verified, 3=KYC approved). (Tier 2 - SP_EXW_FinanceReportsBalancesNew via Fact_SnapshotCustomer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `PlayerLevelID` COMMENT 'Club tier of the user at snapshot date. Sourced from DWH_dbo.Fact_SnapshotCustomer. FK to Dim_PlayerLevel (1=Bronze, 2=Silver, 3=Gold, 4=Platinum, 5=Diamond). (Tier 2 - SP_EXW_FinanceReportsBalancesNew via Fact_SnapshotCustomer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Club` COMMENT 'Human-readable club tier name. Lookup from DWH_dbo.Dim_PlayerLevel.Name by PlayerLevelID. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ComplianceClosureEvent` COMMENT 'Always 0. Column was intended to flag country-closure-affected users but is hardcoded to 0 in SP_EXW_FinanceReportsBalancesNew. Retained for schema backward compatibility. Do not use in analysis. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `AMLClosureEvent` COMMENT '1 = user is wallet-blocked due to AML/compliance conditions; 0 = normal. Set to 1 if any of 4 conditions: (1) PlayerStatus Blocked/BlockedUponRequest AND wallet not allowed; (2) wallet not allowed AND TotalBalance <= 0; (3) wallet not allowed AND TotalBalanceUSD <= 0; (4) compensated user AND wallet not allowed. 12.5% of rows in latest snapshot. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `UserWalletAllowance` COMMENT 'Resolved wallet access decision for the user. Sourced from EXW_UserSettingsWalletAllowance via LEFT JOIN on GCID. Values: Allowed, NotAllowed, ReadOnly. (Tier 2 - SP_EXW_FinanceReportsBalancesNew via EXW_UserSettingsWalletAllowance)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `UpdateDate` COMMENT 'Timestamp of when this row was inserted into EXW_FinanceReportsBalancesNew. Set to GETDATE() at insert time by the SP. (Tier 2 - SP_EXW_FinanceReportsBalancesNew)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletEntity` COMMENT 'Legal entity under which the wallet operates (e.g., eToro Europe Ltd, eToro USA LLC). Sourced from EXW_dbo.EXW_WalletEntity via LEFT JOIN on GCID + BalanceDateID. NULL for dates before WalletEntity data was backfilled or users not in EXW_WalletEntity. (Tier 2 - SP_EXW_FinanceReportsBalancesNew via EXW_WalletEntity)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `PlayerStatus` COMMENT 'Human-readable player/account status at snapshot date. Lookup from DWH_dbo.Dim_PlayerStatus.Name by PlayerStatusID. (Tier 2 - SP_EXW_FinanceReportsBalancesNew via Dim_PlayerStatus)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Reserved` COMMENT 'XRP on-chain activation reserve locked in this wallet. For XRP wallets (CryptoID=4): ISNULL(WalletPool.WalletPoolAttributes.ReservedAmount, 0). For all other cryptos: 0. Added 2026-04-06. The 10-XRP minimum reserve is required to activate an XRP wallet on-chain and cannot be withdrawn. (Tier 2 - SP_EXW_FinanceReportsBalancesNew via EXW_Wallet.WalletPool)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `GCID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `RealCID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `PublicAddress` SET TAGS ('pii' = 'direct');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `CryptoID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `CryptoName` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `BalanceDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `BalanceDateID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Price_Date` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Rate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ReportID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `TotalReceive` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `TotalSend` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletDBBalance` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ComputedAmount` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ProviderValue` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletTrackerValue` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `LevelId` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ReportOccurred` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Balance` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `BalanceUSD` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `RegulationID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Regulation` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `CountryID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Country` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `IsTestAccount` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `IsValidCustomer` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `VerificationLevelID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `PlayerLevelID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Club` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `ComplianceClosureEvent` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `AMLClosureEvent` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `UserWalletAllowance` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `UpdateDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `WalletEntity` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `PlayerStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_financereportsbalancesnew ALTER COLUMN `Reserved` SET TAGS ('pii' = 'none');
