-- =============================================================================
-- Databricks ALTER Script: bronze etoro.Customer.CustomerStatic
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Customer/Tables/Customer.CustomerStatic.md
-- Layer: bronze
-- UC Targets (2):
--   main.pii_data.bronze_etoro_customer_customerstatic
--   main.general.bronze_etoro_customer_customerstatic_masked
-- =============================================================================

-- ---- UC Target: main.pii_data.bronze_etoro_customer_customerstatic (business_group=pii_data) ----
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic SET TBLPROPERTIES (
    'comment' = 'The central customer master record table for all 18.7M eToro customers: stores identity, registration, demographics, status, trading configuration, and PII fields. All changes are versioned into History.Customer via three triggers. PII columns are protected by Dynamic Data Masking. Source: etoro.Customer.CustomerStatic on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Customer/Tables/Customer.CustomerStatic.md).'
);

ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'Customer',
    'source_table' = 'CustomerStatic',
    'business_group' = 'pii_data',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN CID COMMENT 'Customer ID - platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN OriginalProviderID COMMENT 'The provider ID from which this account was originally migrated or registered. Together with OriginalCID, forms the original identity key (indexed via CCST_ORIGINAL). Used for data migration tracing. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN OriginalCID COMMENT 'Original customer ID from the source provider. Together with OriginalProviderID, enables tracing of migrated accounts. Default=0 (CCST_NULLORIGINAL constraint). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN ProviderID COMMENT 'Current active provider ID. FK to Trade.Provider. Determines the trading provider/broker for this customer''s account. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN RealProviderID COMMENT 'The real (underlying) provider ID, as opposed to any UI-facing provider abstraction. Nullable. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN CountryID COMMENT 'Country of residence. FK to Dictionary.Country. Determines regulatory framework, available instruments, and leverage limits. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN CountryIDByIP COMMENT 'Country detected from the customer''s IP address at registration. Used for fraud detection and geo-comparison (CountryID vs CountryIDByIP mismatch flagging). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN StateID COMMENT 'US state ID for US customers, or 0 for others. FK to Dictionary.State. Required for certain regulatory and tax purposes. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN LanguageID COMMENT 'Customer''s preferred platform language. FK to Dictionary.Language. Controls UI language. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN CommunicationLanguageID COMMENT 'Language for customer communications (emails, notifications). May differ from LanguageID if customer has different communication preferences. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN CurrencyID COMMENT 'Customer''s account base currency. FK to Dictionary.Currency (1=USD, 2=EUR, etc.). Currently all USD in practice; central to the multi-currency migration roadmap. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN TimeZoneID COMMENT 'Customer''s time zone. FK to Dictionary.TimeZone. Used for time-aware notifications and report generation. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PlayerStatusID COMMENT 'Compliance and trading account status. FK to Dictionary.PlayerStatus. 1=Active/Registered (97.5% of accounts); other values indicate restricted, closed, banned, or special states. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN CampaignID COMMENT 'Marketing campaign ID under which the customer was acquired. FK to BackOffice.Campaign. NULL for organically acquired customers. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PlayerLevelID COMMENT 'Customer experience/permission level. FK to Dictionary.PlayerLevel. 1=Standard (94%); 4=Popular Investor (triggers IsHedged=0 in Customer.Customer); 7=VIP. Determines available features and risk limits. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN TradeLevelID COMMENT 'Trading knowledge/experience classification. FK to Dictionary.TradeLevel. Used for MiFID suitability assessment and leverage tier assignment. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN SpreadGroupID COMMENT 'Spread/pricing group. FK to Trade.SpreadGroup. Determines which pricing table the customer uses (retail, professional, institutional). Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN LabelID COMMENT 'Internal segment label. FK to Dictionary.Label. LabelID=26 = BonusOnly customer (triggers IsHedged=0 in Customer.Customer). Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN FunnelID COMMENT 'Registration funnel ID. FK to Dictionary.Funnel. Tracks which user journey/funnel variant the customer came through. NULL when not tracked. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN UserName COMMENT 'Customer''s login username. Unique (case-insensitive, enforced via UserName_LOWER computed column index). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Password COMMENT 'Hashed password. varchar(20) but stores a hash. Password changes are NOT versioned in History.Customer (per the hash implementation decision). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Registered COMMENT 'Account registration date. Default=getdate(). Indexed via Idx_Customer_Customer_Registered with INCLUDE on key contact fields. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN IsReal COMMENT 'Whether this is a real-money account (1) or demo (0). All rows in this environment are IsReal=1. Demo accounts may be in separate DB or schema. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN IP COMMENT 'Registration IP address. Dynamic Data Masking: default(). Indexed via IX_CustomerStatic_IP. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN BirthDate COMMENT 'Customer date of birth. Dynamic Data Masking: default(). Used in LinkedAccountHash1 for duplicate detection and in KYC age verification. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Gender COMMENT 'Gender: ''M'', ''F'', or ''U'' (Unknown). CHECK constraint CCST_GENDER enforces these three values only. Used in LinkedAccountHash1. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN FirstName COMMENT 'Legal first name in Unicode. Dynamic Data Masking: default(). nvarchar supports non-Latin scripts (Cyrillic, Arabic, etc.). Used in LinkedAccountHash1. See Customer.CustomerLatinName for Latin transliterations. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN LastName COMMENT 'Legal last name in Unicode. Dynamic Data Masking: default(). nvarchar. Used in LinkedAccountHash1. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Address COMMENT 'Street address in Unicode. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN City COMMENT 'City in Unicode. NOT masked (unlike Address/Zip). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Zip COMMENT 'Postal code. Dynamic Data Masking: default(). Used in LinkedAccountHash1. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN SerialID COMMENT 'Affiliate (partner) ID under which the customer was acquired. FK to BackOffice.Affiliate. NULL for direct/organic registrations. Indexed via CCST_SerialID. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN ReferralID COMMENT 'Referral CID - the customer who referred this customer (for RAF program tracking). Filtered index IXFiltered_CustomerStatic_ReferralID covers only ReferralID > 0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN SubSerialID COMMENT 'Sub-affiliate identifier string. Can be up to 1024 chars for complex affiliate tracking paths. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Email COMMENT 'Customer email address. Dynamic Data Masking: default(). Unique (case-insensitive via LowerEmail computed column). Email changes trigger Customer.LastChanges update via trigger. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN IsEmailVerified COMMENT 'Whether the email address has been verified by clicking a confirmation link. NULL for older accounts predating this flag. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Phone COMMENT 'Phone number. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Fax COMMENT 'Fax number. Legacy field; rarely populated in modern registrations. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Mobile COMMENT 'Mobile number. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN Comments COMMENT 'Internal comment field. BackOffice operators can add notes. Indexed via Idx_Customer_Customer_AccountStatusID INCLUDE. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN DownloadID COMMENT 'Platform download source ID. Legacy tracking for which platform installer the customer used. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN BannerID COMMENT 'Advertising banner ID that led to registration. Legacy acquisition tracking. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN ClientVersion COMMENT 'Client application version at registration. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PersonID COMMENT 'External person identifier. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN DownloadCounter COMMENT 'Number of times the customer has downloaded the platform client. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN AccountExpirationDate COMMENT 'Expiration date for demo or time-limited accounts. NULL for standard real-money accounts. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN HelpDeskType COMMENT 'Customer service tier assignment (VIP helpdesk, standard, etc.). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN LotCountGroupID COMMENT 'Lot/quantity group. FK to Dictionary.LotCountGroup. Controls minimum/maximum lot sizes for trading. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PrivacyPolicyID COMMENT 'Version of the privacy policy the customer has accepted. FK to Dictionary.PrivacyPolicy. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN GCID COMMENT 'Group Customer ID - cross-product identity key linking the same person across eToro products/entities. Indexed via IDX_Customer_Customer_GCID with wide INCLUDE for lookup performance. NULL for older accounts predating GCID introduction. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN WeekendFeePrecentage COMMENT 'Weekend swap fee percentage. Default=100 (full fee). Values below 100 indicate discounted weekend fees for select customers. Note: column name has typo "Precentage" instead of "Percentage". (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN IsEmailActivated COMMENT 'Email activation status flag. Default=0 (not activated). Separate from IsEmailVerified - tracks whether the account email activation step was completed. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN UserName_LOWER COMMENT 'Computed: lower(UserName). PERSISTED implicitly via unique index. Used for case-insensitive username uniqueness enforcement across 18.7M customers. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN AccountStatusID COMMENT 'Account operational status. Default=1 (Active/Normal). 2=Closed or Restricted. 5.6% NULL (pre-AccountStatusID era accounts). Indexed via Idx_Customer_Customer_AccountStatusID. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PendingClosureStatusID COMMENT 'Status in the pending closure workflow. Default=1 (no pending closure). Updated when customer requests account closure. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN ClientTypeID COMMENT 'Client classification type. FK to Dictionary.ClientType. Default=0. Used for MiFID2 client categorization (retail, professional, etc.). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN IsRequestedCall COMMENT 'Whether the customer has requested a callback from sales/support. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN FunnelFromID COMMENT 'Source funnel variant ID tracking where the customer came from within the acquisition funnel. Indexed via Idx_Customer_CustomerStatic_CID INCLUDE. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN LeverageType COMMENT 'Leverage setting type. Default=1. Determines the leverage scheme applied to this customer''s account. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN IsHedged COMMENT 'Whether the customer''s trades are hedged on the brokerage side. Default=1 (hedged). Set to 0 by CustomerVersionInsert/Update triggers when LabelID=26 or PlayerLevelID=4 (Popular Investors), or when in CEP.ListCIDMappings(NamedListID=3) or BackOffice.BonusOnlyCustomers. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN ID COMMENT 'System GUID for REST API identity. Default=newsequentialid() (sequential for index performance). Unique index Idx_CustomerCustomerStaticID. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN VerificationTitle COMMENT 'KYC verification title/level text. Default from Customer.VerificationTitle_Default() function. Changes are versioned in History.Customer. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN VerificationTitleVersion COMMENT 'Version GUID for optimistic concurrency on verification title updates. Default=newid(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN BuildingNumber COMMENT 'Building/apartment number. Dynamic Data Masking: default(). Separate from Address for structured address storage. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PhonePrefix COMMENT 'International dialing prefix (e.g., +1, +44). Stored separately from PhoneBody for structured phone number handling. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PhoneBody COMMENT 'Local phone number without country prefix. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN ExternalID COMMENT 'APEX broker external ID. Unique index Idx_CustomerCustomerStatic_ExternalID. Decimal(38,0) to accommodate APEX''s very large numeric ID format. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN RegionID COMMENT 'Geographic region ID (GeoIP-derived or set). Used alongside CountryID for more granular regional regulation. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN RegionByIP_ID COMMENT 'Region detected from IP address. Separate from RegionID (profile-based) to allow mismatch detection. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PlatformID COMMENT 'Platform/product identifier (web, mobile, etc.). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN OptOutReasonID COMMENT 'Reason for GDPR/marketing opt-out. Set when customer opts out of communications. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PlayerStatusReasonID COMMENT 'Reason code for current PlayerStatusID. Provides the "why" behind a non-Active status. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN MiddleName COMMENT 'Middle name in Unicode. Dynamic Data Masking: default(). Added 2018 (changelog: 50094). Included in CustomerVersionUpdate history tracking. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN CitizenshipCountryID COMMENT 'Country of citizenship (may differ from CountryID/residence). FK to Dictionary.Country. Added 2018 (changelog: 50308) for enhanced KYC. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN LinkedAccountHash1 COMMENT 'PERSISTED computed column: MD5(lower(FirstName) (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN LowerEmail COMMENT 'Computed: lower(Email). Used in unique index IX_CustomerCustomer_LowerEmail_Cover for case-insensitive email uniqueness. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PlayerStatusSubReasonID COMMENT 'Sub-reason code for PlayerStatus (hierarchical). FK to Dictionary.PlayerStatusSubReasons. Added 2022 (COINF-1989). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN PlayerStatusSubReasonComment COMMENT 'Free-text comment accompanying the PlayerStatusSubReasonID. Max 64 chars. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN POBCountryID COMMENT 'Place of birth country. FK to Dictionary.Country. Added for KYC (HLD: RD-4436 Add Place of Birth to KYC, Confluence CR). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN SubRegionID COMMENT 'Sub-region (province/state for non-US countries). FK to Dictionary.SubRegion. Added 2019 (RD-5830 Add province to Italy, used for EU state/province for address and regulatory purposes). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN EmailVerificationProviderID COMMENT 'External email verification provider used to verify this customer''s email. FK to Dictionary.EmailVerificationProvider. Added 2020. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN ApexID COMMENT 'APEX US stocks broker account ID. Indexed via Apexid (NC) index. Only populated for US-regulated customers at Level >= 2 who have APEX accounts (see APEX Confluence page). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN DltID COMMENT 'Distributed Ledger Technology integration ID. Added per HLD: COAKVU-2880 DLT Integration (Confluence CR). Links customer to DLT/blockchain system. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customerstatic ALTER COLUMN TradeLevelID COMMENT 'Trading knowledge level for MiFID suitability. FK to Dictionary.TradeLevel. Default=0. Used in regulatory suitability assessment for leverage and product access. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';

-- ---- UC Target: main.general.bronze_etoro_customer_customerstatic_masked (business_group=general) ----
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked SET TBLPROPERTIES (
    'comment' = 'The central customer master record table for all 18.7M eToro customers: stores identity, registration, demographics, status, trading configuration, and PII fields. All changes are versioned into History.Customer via three triggers. PII columns are protected by Dynamic Data Masking. Source: etoro.Customer.CustomerStatic on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Customer/Tables/Customer.CustomerStatic.md).'
);

ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'Customer',
    'source_table' = 'CustomerStatic',
    'business_group' = 'general',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN CID COMMENT 'Customer ID - platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN OriginalProviderID COMMENT 'The provider ID from which this account was originally migrated or registered. Together with OriginalCID, forms the original identity key (indexed via CCST_ORIGINAL). Used for data migration tracing. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN OriginalCID COMMENT 'Original customer ID from the source provider. Together with OriginalProviderID, enables tracing of migrated accounts. Default=0 (CCST_NULLORIGINAL constraint). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN ProviderID COMMENT 'Current active provider ID. FK to Trade.Provider. Determines the trading provider/broker for this customer''s account. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN RealProviderID COMMENT 'The real (underlying) provider ID, as opposed to any UI-facing provider abstraction. Nullable. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN CountryID COMMENT 'Country of residence. FK to Dictionary.Country. Determines regulatory framework, available instruments, and leverage limits. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN CountryIDByIP COMMENT 'Country detected from the customer''s IP address at registration. Used for fraud detection and geo-comparison (CountryID vs CountryIDByIP mismatch flagging). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN StateID COMMENT 'US state ID for US customers, or 0 for others. FK to Dictionary.State. Required for certain regulatory and tax purposes. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN LanguageID COMMENT 'Customer''s preferred platform language. FK to Dictionary.Language. Controls UI language. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN CommunicationLanguageID COMMENT 'Language for customer communications (emails, notifications). May differ from LanguageID if customer has different communication preferences. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN CurrencyID COMMENT 'Customer''s account base currency. FK to Dictionary.Currency (1=USD, 2=EUR, etc.). Currently all USD in practice; central to the multi-currency migration roadmap. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN TimeZoneID COMMENT 'Customer''s time zone. FK to Dictionary.TimeZone. Used for time-aware notifications and report generation. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PlayerStatusID COMMENT 'Compliance and trading account status. FK to Dictionary.PlayerStatus. 1=Active/Registered (97.5% of accounts); other values indicate restricted, closed, banned, or special states. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN CampaignID COMMENT 'Marketing campaign ID under which the customer was acquired. FK to BackOffice.Campaign. NULL for organically acquired customers. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PlayerLevelID COMMENT 'Customer experience/permission level. FK to Dictionary.PlayerLevel. 1=Standard (94%); 4=Popular Investor (triggers IsHedged=0 in Customer.Customer); 7=VIP. Determines available features and risk limits. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN TradeLevelID COMMENT 'Trading knowledge/experience classification. FK to Dictionary.TradeLevel. Used for MiFID suitability assessment and leverage tier assignment. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN SpreadGroupID COMMENT 'Spread/pricing group. FK to Trade.SpreadGroup. Determines which pricing table the customer uses (retail, professional, institutional). Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN LabelID COMMENT 'Internal segment label. FK to Dictionary.Label. LabelID=26 = BonusOnly customer (triggers IsHedged=0 in Customer.Customer). Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN FunnelID COMMENT 'Registration funnel ID. FK to Dictionary.Funnel. Tracks which user journey/funnel variant the customer came through. NULL when not tracked. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN UserName COMMENT 'Customer''s login username. Unique (case-insensitive, enforced via UserName_LOWER computed column index). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Password COMMENT 'Hashed password. varchar(20) but stores a hash. Password changes are NOT versioned in History.Customer (per the hash implementation decision). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Registered COMMENT 'Account registration date. Default=getdate(). Indexed via Idx_Customer_Customer_Registered with INCLUDE on key contact fields. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN IsReal COMMENT 'Whether this is a real-money account (1) or demo (0). All rows in this environment are IsReal=1. Demo accounts may be in separate DB or schema. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN IP COMMENT 'Registration IP address. Dynamic Data Masking: default(). Indexed via IX_CustomerStatic_IP. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN BirthDate COMMENT 'Customer date of birth. Dynamic Data Masking: default(). Used in LinkedAccountHash1 for duplicate detection and in KYC age verification. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Gender COMMENT 'Gender: ''M'', ''F'', or ''U'' (Unknown). CHECK constraint CCST_GENDER enforces these three values only. Used in LinkedAccountHash1. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN FirstName COMMENT 'Legal first name in Unicode. Dynamic Data Masking: default(). nvarchar supports non-Latin scripts (Cyrillic, Arabic, etc.). Used in LinkedAccountHash1. See Customer.CustomerLatinName for Latin transliterations. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN LastName COMMENT 'Legal last name in Unicode. Dynamic Data Masking: default(). nvarchar. Used in LinkedAccountHash1. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Address COMMENT 'Street address in Unicode. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN City COMMENT 'City in Unicode. NOT masked (unlike Address/Zip). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Zip COMMENT 'Postal code. Dynamic Data Masking: default(). Used in LinkedAccountHash1. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN SerialID COMMENT 'Affiliate (partner) ID under which the customer was acquired. FK to BackOffice.Affiliate. NULL for direct/organic registrations. Indexed via CCST_SerialID. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN ReferralID COMMENT 'Referral CID - the customer who referred this customer (for RAF program tracking). Filtered index IXFiltered_CustomerStatic_ReferralID covers only ReferralID > 0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN SubSerialID COMMENT 'Sub-affiliate identifier string. Can be up to 1024 chars for complex affiliate tracking paths. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Email COMMENT 'Customer email address. Dynamic Data Masking: default(). Unique (case-insensitive via LowerEmail computed column). Email changes trigger Customer.LastChanges update via trigger. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN IsEmailVerified COMMENT 'Whether the email address has been verified by clicking a confirmation link. NULL for older accounts predating this flag. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Phone COMMENT 'Phone number. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Fax COMMENT 'Fax number. Legacy field; rarely populated in modern registrations. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Mobile COMMENT 'Mobile number. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN Comments COMMENT 'Internal comment field. BackOffice operators can add notes. Indexed via Idx_Customer_Customer_AccountStatusID INCLUDE. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN DownloadID COMMENT 'Platform download source ID. Legacy tracking for which platform installer the customer used. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN BannerID COMMENT 'Advertising banner ID that led to registration. Legacy acquisition tracking. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN ClientVersion COMMENT 'Client application version at registration. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PersonID COMMENT 'External person identifier. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN DownloadCounter COMMENT 'Number of times the customer has downloaded the platform client. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN AccountExpirationDate COMMENT 'Expiration date for demo or time-limited accounts. NULL for standard real-money accounts. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN HelpDeskType COMMENT 'Customer service tier assignment (VIP helpdesk, standard, etc.). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN LotCountGroupID COMMENT 'Lot/quantity group. FK to Dictionary.LotCountGroup. Controls minimum/maximum lot sizes for trading. Default=0. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PrivacyPolicyID COMMENT 'Version of the privacy policy the customer has accepted. FK to Dictionary.PrivacyPolicy. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN GCID COMMENT 'Group Customer ID - cross-product identity key linking the same person across eToro products/entities. Indexed via IDX_Customer_Customer_GCID with wide INCLUDE for lookup performance. NULL for older accounts predating GCID introduction. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN WeekendFeePrecentage COMMENT 'Weekend swap fee percentage. Default=100 (full fee). Values below 100 indicate discounted weekend fees for select customers. Note: column name has typo "Precentage" instead of "Percentage". (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN IsEmailActivated COMMENT 'Email activation status flag. Default=0 (not activated). Separate from IsEmailVerified - tracks whether the account email activation step was completed. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN UserName_LOWER COMMENT 'Computed: lower(UserName). PERSISTED implicitly via unique index. Used for case-insensitive username uniqueness enforcement across 18.7M customers. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN AccountStatusID COMMENT 'Account operational status. Default=1 (Active/Normal). 2=Closed or Restricted. 5.6% NULL (pre-AccountStatusID era accounts). Indexed via Idx_Customer_Customer_AccountStatusID. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PendingClosureStatusID COMMENT 'Status in the pending closure workflow. Default=1 (no pending closure). Updated when customer requests account closure. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN ClientTypeID COMMENT 'Client classification type. FK to Dictionary.ClientType. Default=0. Used for MiFID2 client categorization (retail, professional, etc.). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN IsRequestedCall COMMENT 'Whether the customer has requested a callback from sales/support. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN FunnelFromID COMMENT 'Source funnel variant ID tracking where the customer came from within the acquisition funnel. Indexed via Idx_Customer_CustomerStatic_CID INCLUDE. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN LeverageType COMMENT 'Leverage setting type. Default=1. Determines the leverage scheme applied to this customer''s account. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN IsHedged COMMENT 'Whether the customer''s trades are hedged on the brokerage side. Default=1 (hedged). Set to 0 by CustomerVersionInsert/Update triggers when LabelID=26 or PlayerLevelID=4 (Popular Investors), or when in CEP.ListCIDMappings(NamedListID=3) or BackOffice.BonusOnlyCustomers. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN ID COMMENT 'System GUID for REST API identity. Default=newsequentialid() (sequential for index performance). Unique index Idx_CustomerCustomerStaticID. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN VerificationTitle COMMENT 'KYC verification title/level text. Default from Customer.VerificationTitle_Default() function. Changes are versioned in History.Customer. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN VerificationTitleVersion COMMENT 'Version GUID for optimistic concurrency on verification title updates. Default=newid(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN BuildingNumber COMMENT 'Building/apartment number. Dynamic Data Masking: default(). Separate from Address for structured address storage. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PhonePrefix COMMENT 'International dialing prefix (e.g., +1, +44). Stored separately from PhoneBody for structured phone number handling. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PhoneBody COMMENT 'Local phone number without country prefix. Dynamic Data Masking: default(). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN ExternalID COMMENT 'APEX broker external ID. Unique index Idx_CustomerCustomerStatic_ExternalID. Decimal(38,0) to accommodate APEX''s very large numeric ID format. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN RegionID COMMENT 'Geographic region ID (GeoIP-derived or set). Used alongside CountryID for more granular regional regulation. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN RegionByIP_ID COMMENT 'Region detected from IP address. Separate from RegionID (profile-based) to allow mismatch detection. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PlatformID COMMENT 'Platform/product identifier (web, mobile, etc.). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN OptOutReasonID COMMENT 'Reason for GDPR/marketing opt-out. Set when customer opts out of communications. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PlayerStatusReasonID COMMENT 'Reason code for current PlayerStatusID. Provides the "why" behind a non-Active status. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN MiddleName COMMENT 'Middle name in Unicode. Dynamic Data Masking: default(). Added 2018 (changelog: 50094). Included in CustomerVersionUpdate history tracking. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN CitizenshipCountryID COMMENT 'Country of citizenship (may differ from CountryID/residence). FK to Dictionary.Country. Added 2018 (changelog: 50308) for enhanced KYC. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN LinkedAccountHash1 COMMENT 'PERSISTED computed column: MD5(lower(FirstName) (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN LowerEmail COMMENT 'Computed: lower(Email). Used in unique index IX_CustomerCustomer_LowerEmail_Cover for case-insensitive email uniqueness. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PlayerStatusSubReasonID COMMENT 'Sub-reason code for PlayerStatus (hierarchical). FK to Dictionary.PlayerStatusSubReasons. Added 2022 (COINF-1989). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN PlayerStatusSubReasonComment COMMENT 'Free-text comment accompanying the PlayerStatusSubReasonID. Max 64 chars. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN POBCountryID COMMENT 'Place of birth country. FK to Dictionary.Country. Added for KYC (HLD: RD-4436 Add Place of Birth to KYC, Confluence CR). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN SubRegionID COMMENT 'Sub-region (province/state for non-US countries). FK to Dictionary.SubRegion. Added 2019 (RD-5830 Add province to Italy, used for EU state/province for address and regulatory purposes). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN EmailVerificationProviderID COMMENT 'External email verification provider used to verify this customer''s email. FK to Dictionary.EmailVerificationProvider. Added 2020. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN ApexID COMMENT 'APEX US stocks broker account ID. Indexed via Apexid (NC) index. Only populated for US-regulated customers at Level >= 2 who have APEX accounts (see APEX Confluence page). (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN DltID COMMENT 'Distributed Ledger Technology integration ID. Added per HLD: COAKVU-2880 DLT Integration (Confluence CR). Links customer to DLT/blockchain system. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
ALTER TABLE main.general.bronze_etoro_customer_customerstatic_masked ALTER COLUMN TradeLevelID COMMENT 'Trading knowledge level for MiFID suitability. FK to Dictionary.TradeLevel. Default=0. Used in regulatory suitability assessment for leverage and product access. (Tier 1 - upstream wiki, etoro.Customer.CustomerStatic)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:35:25 UTC
-- Bronze deploy: etoro batch 1
-- ====================
