-- =============================================================================
-- Databricks ALTER Script: bronze etoro.BackOffice.Customer
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/BackOffice/Tables/BackOffice.Customer.md
-- Layer: bronze
-- UC Target: main.general.bronze_etoro_backoffice_customer
-- =============================================================================

-- ---- UC Target: main.general.bronze_etoro_backoffice_customer (business_group=general) ----
ALTER TABLE main.general.bronze_etoro_backoffice_customer SET TBLPROPERTIES (
    'comment' = 'BackOffice-specific customer profile extending Customer.CustomerStatic with operational state: regulatory assignment, KYC verification level, sales agent assignment, account classification, MiFID/ASIC/Seychelles categorization, AML flags, trading risk status, and SalesForce CRM identifiers. Fully audit-trailed via INSERT/UPDATE/DELETE triggers to History.BackOfficeCustomer. Source: etoro.BackOffice.Customer on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/BackOffice/Tables/BackOffice.Customer.md).'
);

ALTER TABLE main.general.bronze_etoro_backoffice_customer SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'BackOffice',
    'source_table' = 'Customer',
    'business_group' = 'general',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN CID COMMENT 'Customer account ID. Clustered PK. FK (WITH CHECK) to Customer.CustomerStatic(CID). One row per account. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN SalesStatusID COMMENT 'Stage in the sales pipeline. FK (WITH CHECK) to Dictionary.SalesStatus. DEFAULT=0. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN ManagerID COMMENT 'Currently assigned BackOffice sales/service agent. FK (WITH CHECK) to BackOffice.Manager. NULL = unassigned. Indexed with CID for agent-level customer queries. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN IsAffiliate COMMENT '1 if this customer account is also an affiliate (partner who refers other customers). Only 22 affiliate-customers exist on the platform. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN Cleared COMMENT 'Financial clearance flag indicating the customer''s account has been reviewed and cleared for specific operations (e.g., withdrawal processing). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN Verified COMMENT 'Identity verification flag. 1 = customer has passed KYC identity check. 46.9% of accounts verified. May differ from VerificationLevelID (legacy field). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN FTDPoolManagerID COMMENT 'BackOffice agent credited with this customer''s first-time deposit (FTD) for sales attribution and compensation calculations. FK (WITH CHECK) to BackOffice.Manager. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN PreviousManagerID COMMENT 'The agent assigned before the most recent reassignment. FK (WITH CHECK) to BackOffice.Manager. Preserved for audit. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN FXEligibilityDate COMMENT 'Date when the customer became eligible for FX/leveraged product trading. NULL if not yet eligible or not applicable. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN AffiliateManagerID COMMENT 'FK to Dictionary.UserGroup - the affiliate user group this customer was referred by. Despite the name, references UserGroup not Manager. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN CashoutFeeGroupID COMMENT 'FK (WITH CHECK) to Dictionary.CashoutFeeGroup. Determines which withdrawal fee schedule applies to this customer. NULL = default fee group. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN ChangePassword COMMENT 'Flag prompting the customer to change their password on next login. NULL treated as false. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN RiskStatusID COMMENT 'Legacy single-value risk status. Distinct from the multi-row BackOffice.CustomerRisk (which allows multiple simultaneous risk flags). May reflect a legacy consolidated risk status code. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN isEmployeeAccount COMMENT '1 if this is an eToro employee''s personal trading account. Flags employee accounts for special monitoring and compliance checks. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN AccountTypeID COMMENT 'Customer account classification. DEFAULT=1 (real retail account). Distribution: 1=18.614M, 0=44K, 2=37K, 6=17K, others <6K. The filtered NC index on AccountTypeID=9 suggests type 9 is a frequently-queried special account type. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN MasterAccountCID COMMENT 'For sub-accounts: the CID of the master/parent account. NULL for standalone accounts. Supports multi-account hierarchies. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN ManagerPermitID COMMENT 'Permission level governing what the assigned manager can do with this customer account. DEFAULT=1. Distinct from ManagerToPermission (which is agent-wide). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN ThirdPartyManagerComment COMMENT 'Free-text note about the customer''s third-party management relationship (e.g., managed account arrangement). Visible in the BackOffice customer header (via GetCustomerHeader). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN GuruStatusID COMMENT 'FK (WITH CHECK) to Dictionary.GuruStatus. eToro''s Popular Investor/Guru program status - whether the customer is an active copy trading strategy provider. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN RiskClassificationID COMMENT 'FK (WITH CHECK) to Dictionary.RiskClassification. Operational risk tier assigned by risk management. Tracked in UPDATE trigger audit. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN AcceptanceStatusID COMMENT 'FK (WITH CHECK) to Dictionary.AcceptanceStatus. Customer onboarding acceptance state (e.g., pending review, accepted, rejected). DEFAULT=0. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN VerificationLevelID COMMENT 'KYC verification level. FK (WITH CHECK) to Dictionary.VerificationLevel. Values: 0=unverified (34.2%), 1=partial (12.4%), 2=intermediate (6.2%), 3=fully verified (47.1%). DEFAULT=0. Indexed for compliance reporting. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN RegulationID COMMENT 'Regulatory entity governing this account. FK (WITH CHECK) to Dictionary.Regulation. Top values: CySEC=7.39M, BVI=7.30M, FCA=1.17M. Changes trigger RegulationChangeDate update and RegulationChangeLog insert. DEFAULT=0. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN DocumentStatusID COMMENT 'Current state of the customer''s KYC document submission and review queue. NULL if no documents submitted. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN PhoneVerifiedID COMMENT 'Result code of phone number verification process. NULL if not yet attempted. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN AcceptanceStatusChanginManagerID COMMENT 'ManagerID of the BackOffice agent who last changed the AcceptanceStatus. Note: column name has a typo ("Changin" instead of "Changing"). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN GDCCheckID COMMENT 'FK (WITH CHECK) to Dictionary.GDCCheck. Gambling/debt counselling check status. Required under some regulatory frameworks (e.g., South African FAIS). DEFAULT=0. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN RegulationChangeDate COMMENT 'Timestamp when RegulationID was last changed. Updated automatically by the CustomerHistoryUpdate trigger on RegulationID changes. NULL if never changed since account creation. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN IsCopyBlocked COMMENT '1 if the customer is blocked from copy trading (copying other traders). 0 in all 18.744M current rows - feature exists but currently unused/not enforced. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN SuitabilityTestStatusID COMMENT 'MiFID II appropriateness/suitability test result. NULL if test not completed. FK to Dictionary (implied). Required for complex product access under MiFID II. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN WorldCheckID COMMENT 'FK (WITH CHECK) to Dictionary.WorldCheck. Refinitiv/LSEG World-Check sanctions and PEP (Politically Exposed Person) screening result. DEFAULT=0. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN KycState COMMENT 'KYC process state machine value. DEFAULT=0 (initial state). Application-side enum drives the states. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN VerifiedBy COMMENT 'System or vendor ID that performed the identity verification (e.g., 1=manual BackOffice, 2=Onfido, 3=Au10tix). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN VerifiedByProvider COMMENT 'Provider/entity under which the verification was performed. Distinguishes verification done under different regulatory entities. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN IsEDD COMMENT 'Enhanced Due Diligence required flag. 1 = customer requires deeper AML/KYC investigation (e.g., PEP, high-risk country, large transactions). 23,944 customers (0.13%) flagged. DEFAULT=0. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN EvMatchStatus COMMENT 'Electronic verification match result. Score or decision from automated identity verification vendors (Onfido, Au10tix). NULL if not yet processed. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN Lei COMMENT 'Legal Entity Identifier for corporate accounts. ISO 17442 standard 20-character identifier. NULL for retail (natural person) accounts. Added 2017-11-15 for corporate account support (ticket 49513_OPS0351). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN AMLComment COMMENT 'AML team free-text notes about this customer. Automatically date-prefixed by CustomerHistoryUpdate trigger when updated (prepends YYYYMMDD ). Contains investigation findings, source of funds notes, PEP status explanations. Up to 8,000 chars. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN RiskComment COMMENT 'Risk team free-text notes. Similar to AMLComment but for risk (not AML) observations. NOT tracked by the UPDATE trigger (excluded from History). Up to 8,000 chars. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN MifidCategorizationID COMMENT 'MiFID II investor classification. FK (WITH CHECK) to Dictionary.MifidCategorization. Values: 1=Retail (97.3%), 4=Eligible Counterparty (2.6%), 5=Professional (0.03%), 2/3=sub-categories. DEFAULT=1 (Retail). Key input to TradingRiskStatusID computation. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN DesignatedRegulationID COMMENT 'FK (WITH CHECK) to Dictionary.Regulation. Secondary/override regulation for accounts subject to multiple jurisdictions. Used in TradingRiskStatusID computation (e.g., Australian residents under CySEC with DesignatedRegulationID=ASIC). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN HasWallet COMMENT '1 if the customer has an active eToro Money wallet linked to their trading account. DEFAULT=0. 3,554 customers (0.019%) have a wallet. Filtered NC index for wallet-holder queries. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN SalesForceContactID COMMENT 'Salesforce CRM Contact record ID (18-char Salesforce ID). Links the trading account to the SF Contact. NULL if not yet synced to SF. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN SalesForceAccountID COMMENT 'Salesforce CRM Account record ID (18-char Salesforce ID). Links the trading account to the SF Account (company/household). NULL if not yet synced. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN AsicClassificationID COMMENT 'ASIC (Australian Securities & Investments Commission) customer classification. NULL for non-ASIC regulated accounts. Used in TradingRiskStatusID computation for Australian customers. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN SeychellesCategorizationID COMMENT 'Customer classification under Seychelles FSA regulation. NULL for non-Seychelles accounts. Used in TradingRiskStatusID computation: 0=standard, 1=protected/retail, 2=non-protected. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN TradingRiskStatusID COMMENT 'Computed (NEVER store directly). Derives effective trading risk tier from regulation + categorization. Values: 1=Eligible Counterparty/Elite (highest leverage, least protection), 2=Professional (reduced protection), 3=Standard Retail (88.3%), 4=Default/QA. Formula depends on DB name, SeychellesCategorizationID, DesignatedRegulationID, RegulationID, MifidCategorizationID, AsicClassificationID. Added 2022-08-11 (COINF-1394). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN EIDStatusID COMMENT 'FK (WITH CHECK) to Dictionary.EIDStatus. Electronic ID verification status from identity document scanning vendors. NULL if not yet processed. (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN OnboardingRiskClassificationID COMMENT 'Risk classification assigned at the time of customer onboarding (initial risk assessment). May differ from RiskClassificationID (ongoing risk). (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
ALTER TABLE main.general.bronze_etoro_backoffice_customer ALTER COLUMN `AcceptanceStatusID (tinyint)` COMMENT '(see #21 above) (Tier 1 - upstream wiki, etoro.BackOffice.Customer)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:35:25 UTC
-- Bronze deploy: etoro batch 1
-- ====================
