-- =============================================================================
-- Databricks ALTER Script: bronze etoro.BackOffice.Manager
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/BackOffice/Tables/BackOffice.Manager.md
-- Layer: bronze
-- UC Target: main.billing.bronze_etoro_backoffice_manager
-- =============================================================================

-- ---- UC Target: main.billing.bronze_etoro_backoffice_manager (business_group=billing) ----
ALTER TABLE main.billing.bronze_etoro_backoffice_manager SET TBLPROPERTIES (
    'comment' = 'Registry of all internal eToro staff who access the BackOffice system, including their department assignment, authentication credentials, role flags, and customer management relationships. Source: etoro.BackOffice.Manager on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/BackOffice/Tables/BackOffice.Manager.md).'
);

ALTER TABLE main.billing.bronze_etoro_backoffice_manager SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'BackOffice',
    'source_table' = 'Manager',
    'business_group' = 'billing',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN ManagerID COMMENT 'Auto-generated unique integer identifier for each BackOffice staff member. PK for the entire BackOffice authorization system. ManagerID=0 is the reserved System account; ManagerID=1 is the bootstrap Admin. All BackOffice action tables (BackOffice.Customer, Task, Downtime, etc.) store ManagerID as the "acting staff" reference. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN UserGroupID COMMENT 'Department/team assignment. FK to Dictionary.UserGroup. Determines access scope and team membership. Values: 1=Administrators, 2=Operations, 3=Risk, 4=Marketing, 5=Accounting, 6=Trading, 7=Sales/Support, 8=Account Management, 9=Sales 1, 10=Sales 2, 11-13=Account Management 1-3, 16=Local Offices (IBs), 17-30=Regional IB offices (Singapore, Brazil, Australia, etc.), 20=Support, 31=BackOffice, 32=Training, 33=Turkey, 34=MimoOps, 35=MimoApps, 36=AML. See UserGroup for hierarchy. Largest groups: Administrators (431), Account Management (112), MimoOps (98). (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN FirstName COMMENT 'Staff member''s first name. Combined with LastName in views and procedures to produce display names (e.g., BackOffice.GetMyCustomers sets [Manager] = FirstName + '' '' + LastName). (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN LastName COMMENT 'Staff member''s last name. Combined with FirstName for display. LastName=''*'' indicates a functional/shared account (e.g., the generic ''support'' account). (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN Login COMMENT 'Unique username for BackOffice authentication. Used as the primary lookup key in BackOffice.LogIn (case-insensitive match via LOWER()). Has unique index BMNG_LOGIN enforcing uniqueness. Maximum 20 characters. Exposed as UserName in LoadManagers and LoadManagerByUsername procedures. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN Password COMMENT 'Authentication credential. Masked in application layer with partial(0, "XXXXXXXX", 0) - all characters replaced with X when queried by non-privileged users. BackOffice.GetManager view exposes this column (legacy view used by older BackOffice app versions). NULL values indicate SSO-authenticated managers or deactivated accounts. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN Email COMMENT 'Staff member''s eToro corporate email address. Used by the email notification subsystem when IsEmailNotified=1. Exposed in LoadManagers, GetManagers, and related procedures for manager roster APIs. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN IsEmailNotified COMMENT 'Controls whether this manager receives automated email notifications from BackOffice system events (e.g., deposit alerts, escalation triggers). 1=email notifications enabled, 0=email silent. Exposed in LoadManagers procedure for application-side notification routing. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN IsActive COMMENT 'Logical soft-delete flag controlling login access and visibility. 1=active (staff currently employed, can authenticate). 0=deactivated (former staff or suspended; LOGIN is blocked by BackOffice.LogIn which checks IsActive=1). BackOffice.GetManager view filters WHERE IsActive=1, hiding deactivated managers from most application queries. Do NOT physically delete manager rows - use IsActive=0 to preserve audit history. 505 active, 455 inactive in production. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN IsTeamLeader COMMENT 'Marks this manager as a team leader within their department. 1=team leader role. 0=individual contributor. Used in LoadManagers/LoadManagerByUsername responses for role-based UI rendering. 30 active team leaders in production. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN ForceChangePassword COMMENT 'When set to 1, forces this manager to change their password at the next login session. Default 0 (no forced change). Used by administrators after password resets or security policy enforcement. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN OverrideReplicaSettings COMMENT 'When 1, bypasses read-replica routing for this manager''s BackOffice queries, directing all reads to the primary database. Used for managers requiring real-time data accuracy (e.g., risk managers monitoring live positions). Exposed in LoadManagers and LoadManagerByUsername for application-layer routing decisions. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN IsCustomerManager COMMENT 'Indicates this manager directly manages and is responsible for a portfolio of customers. 1=customer-facing manager who appears in GetMyCustomers results. 0=back-office operations role without direct customer assignment. BackOffice.GetMyCustomers filters BackOffice.Customer WHERE ManagerID IN (@ManagerIds) - the ManagerIds parameter is the set of IsCustomerManager=1 managers. 31 active customer managers in production. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN RegionalManagerID COMMENT 'Self-referential FK (no constraint defined) pointing to another Manager''s ManagerID. Represents the regional manager responsible for this staff member, primarily used for IB (Introducing Broker) local offices. 951 of 960 managers have NULL (flat org structure internally). Only populated for regional office managers (UserGroupID 16-30 range) where a parent regional coordinator exists. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN ManagerGroupID COMMENT 'FK to BackOffice.T_GroupsDictionary (no explicit constraint). Assigns this manager to a database connection group for multi-environment routing. When set, LoadManagerByUsername and LoadManagers also return ManagerGroupType from T_ManagerAccessGroupToConnectionStrings, which the application uses to select the appropriate connection string. 346 managers have this set (primarily MimoOps/MimoApps groups). NULL = default connection routing. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN CalendlyID COMMENT 'Calendly scheduling identifier for this manager. Exposed via GetManagers procedure for the customer-facing scheduler that lets customers book calls with their account manager. 958 of 960 managers have this populated (default value "etoro-club" used as placeholder for system/generic accounts). (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN ManagerTitleID COMMENT 'Job title classification FK to Dictionary.ManagerTitle. Values: 1=Sales Team, 2=Sales Representative, 3=Account Management Team, 4=Account Manager (note: DDL typo "Account Manger"), 5=Customer Success Agent. Exposed via GetManagers procedure. 293 managers have NULL (non-customer-facing roles: Administrators, Risk, Operations, Trading teams). Most populated: 4=Account Manager (176), 1=Sales Team (164), 3=Account Management Team (163), 2=Sales Representative (163). (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';
ALTER TABLE main.billing.bronze_etoro_backoffice_manager ALTER COLUMN eToroCID COMMENT 'The manager''s own eToro customer account CID (Customer ID). Links to Customer.CustomerStatic. Many staff members are also eToro customers themselves. Exposed as CID in GetManagers procedure. 659 of 960 managers have this populated. NULL for system accounts and staff who do not have personal eToro accounts. (Tier 1 - upstream wiki, etoro.BackOffice.Manager)';

