-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_DDR_Fact_MIMO_Options_Platform
-- Generated: 2026-05-14 14:29:17 UTC | _tmp_create_missing_alters.py
-- Target: Unity Catalog column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform
-- =============================================================================

-- ---- Table Comment ----
-- (table-level comment intentionally omitted; regen tool only manages column comments)

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN DateID COMMENT 'Business calendar key mirrored from Apex **`External_Sodreconciliation_apex_EXT869_CashActivity.ProcessDate`** via TVF **`CONVERT(nvarchar(8), … ,112)`**. Full **`TRUNCATE` reload** rewinds historical partitions daily (not **`DELETE WHERE DateID=@dt`** semantics). (Tier 2 - Sodreconciliation.apex.EXT869_CashActivity)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN Date COMMENT 'Calendar **`ProcessDate`** from same **`External_Sodreconciliation_apex_EXT869_CashActivity`** payload surfaced through **`Function_MIMO_Options_Platform`**. (Tier 2 - Sodreconciliation.apex.EXT869_CashActivity)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN RealCID COMMENT 'Global Real Customer Identifier on the ledger row (`fca.RealCID`). (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN MIMOAction COMMENT 'Stable label `''Deposit''` or `''Withdraw''` from UNION halves. Options path swaps TP UNION halves for Apex `CASE` on **`PayTypeCode`** **`C`**/**`D`** inside **`Function_MIMO_Options_Platform`**, emitting the same DDR-facing literals. (Tier 2 - Function_MIMO_Options_Platform)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN OrigIdentifier COMMENT 'Hardcoded `''ApexTxID''` in source facts (coerced Transactions may null out downstream AllPlatforms merges). **`BI_DB_ddr…AllPlatforms`** quotes this verbatim in consolidated Element glossary. (Tier 2 - SP_DDR_Fact_MIMO_Options_Platform)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN TransactionID COMMENT 'Apex cash **`ACATSControlNumber`** carried as alphanumeric **`varchar`**. Consolidated ingest applies **`SP_DDR_Fact_Fact_MIMO_AllPlatforms` literal `0 AS TransactionID`** with comment *cannot use the varchar it will break current schemas on move to lake.* - reconcile broker keys **only while still in this CCI fact.** (Tier 2 - Sodreconciliation.apex.EXT869_CashActivity)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN AmountUSD COMMENT '**`ABS(Amount)`** from Apex **`EXT869`** cash postings after ACH/withdraw/journal filter stack - **deposit & withdraw retain positive magnitude** (**sign semantics differ from **`BI_DB_DDR_Fact_MIMO_eMoney_Platform`** negatives** - filter on **`MIMOAction`**). (Tier 2 - Sodreconciliation.apex.EXT869_CashActivity`)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN AmountOrigCurrency COMMENT 'Loader duplicates **`AmountUSD`** (`AmountOrigCurrency = AmountUSD`) enforcing **USD bookkeeping** symmetry for DDR UNION schema - **no multi-ccy fidelity** persisted. (Tier 2 - SP_DDR_Fact_MIMO_Options_Platform`)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN FundingTypeID COMMENT '**`0` literal on INSERT (`0 AS FundingTypeID`) despite TVF-coded rail hints (`42`=Omni journal, `29`=ACH, `2`=wire per CASE). Function emits richer codes but loader zeroes **for UNION compatibility** (**100% persisted zero** MCP 2026-05-14). Analyst decode requires TVF/external, not CCI column. (Tier 2 - SP_DDR_Fact_MIMO_Options_Platform`)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN CurrencyID COMMENT 'Primary key. Universal instrument identifier. 0=NULL placeholder, 1-8=major forex currencies, ~1000+=stocks (AAPL, GOOG, etc.), ~100000+=crypto (BTC, ETH). Referenced by virtually all DWH fact tables. Legacy name: eToro originated as forex-only. DDR loader forces literal **`CurrencyID = 1`** (USD Apex book; no **`Dim_Currency` join**) matching the **`Dictionary.Currency` major-key semantics** for **`1 = USD/EUR majors bucket`**. (Tier 1 - Dictionary.Currency)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN Currency COMMENT '**`''USD''` constant** injected by `SP_DDR_Fact_MIMO_Options_Platform` (no runtime `Dim_Currency` join) - aligns with Dictionary/Currency shorthand for **`CurrencyID = 1`**. Parallels `Dim_Currency.Abbreviation` usage on sibling MIMO tables but materialized SP-side. (Tier 2 - SP_DDR_Fact_MIMO_Options_Platform)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN IsFTD COMMENT 'Platform Options **FINRA-assisted first deposit** flag from **`CASE WHEN FinalFTD.TransactionID IS NOT NULL THEN 1 ELSE 0 END`** (see **`FINRAONLY_FTD_records`/`FTDSingle`/`FTDMultiple` CTEs**). Distribution snapshot: **`1 189`** flagged rows MCP 2026-05-14. (Tier 2 - Function_MIMO_Options_Platform`)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN IsGlobalFTD COMMENT 'Outputs **`ISNULL(gftd.IsGlobalFTD, 0)`** after **`GLOBAL_FTD` LEFT JOIN`: deposit tuple must match **`Dim_Customer`** `FirstDepositAmount` / `CAST(FirstDepositDate AS date)` while **`FirstDepositDate  >=  20250901`** and **`FTDPlatformID = 2`** (**`DEPOSIT_UNIQUE_FOR_FTDJOIN`** supplies candidate deposits). MCP snapshot (**2026-05-14**): **`699`** rows with **`IsGlobalFTD = 1`**. (Tier 2 - Function_MIMO_Options_Platform`)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN IsInternalTransfer COMMENT 'Omni/internal journal discriminator `CASE WHEN ca.TerminalID = ''OMJNL'' THEN 1 ELSE 0` inside **`Function_MIMO_Options_Platform`** (**~63%** of rows MCP 2026-05-14). **Not** TP `FundingTypeID = 33` billing semantics - persists alongside loader-zeroed **`FundingTypeID`** (section 2.3). (Tier 2 - Function_MIMO_Options_Platform)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN UpdateDate COMMENT 'ETL watermark `GETDATE()` on INSERT. (Tier 2 - SP_DDR_Fact_MIMO_Options_Platform)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN DateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN RealCID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN MIMOAction SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN OrigIdentifier SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN TransactionID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN AmountUSD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN AmountOrigCurrency SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN FundingTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN CurrencyID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN Currency SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN IsFTD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN IsGlobalFTD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN IsInternalTransfer SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_options_platform ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');

