-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_CID_MonthlyPanel_FullData
-- Generated: 2026-05-03 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_CID_MonthlyPanel_FullData > Monthly per-depositor customer panel - the broadest monthly CRM fact table in BI_DB_dbo. 189 columns covering registration, trading activity, revenue, PnL, equity, copy trading, lifetime accumulators, life-stage classification, and LTV predictions. One row per depositor (IsFunded) per calendar month. 353.8M rows total; 5.87M distinct CIDs; date range 2007-08 to present (oldest data in BI_DB_dbo). | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Production Source** | Multi-source ETL (see Section 4) | | **Refresh** | Daily - DELETE WHERE ActiveDate = @BeginOfMonth + INSERT, then 4× POST-INSERT UPDATEs (SP_CID_MonthlyPanel_FullData, SB_Daily, Priority 0) | | | | | **Synapse Distribution** | HASH(CID) | | **Synapse Index** | CLUSTERED INDEX (ActiveDate ASC, CID ASC) | | **Row Count** | ~353.8M to'
);

-- ---- Table Tags ----
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CID COMMENT 'Customer ID - platform-internal primary key. Identifies the depositor. HASH distribution key. Equivalent to DWH_dbo.Dim_Customer.RealCID. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Month COMMENT 'Calendar month this row represents, in YYYY-MM format with trailing space pad to 7 chars (e.g., ''202604 ''). Grain identifier alongside ActiveDate. Always use ActiveDate (DATE) for filtering; char comparisons on Active_Month can fail due to trailing space. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveDate COMMENT 'First day of the calendar month (e.g., 2026-04-01). Primary grain column and leading CLUSTERED INDEX key. Always filter on this column for month slices. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN UpdateDate COMMENT 'ETL metadata: timestamp when this row was last inserted by SP_CID_MonthlyPanel_FullData. Refreshed daily during the current open month. (Tier 2 - ETL metadata)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Seniority COMMENT 'Months since first deposit: DATEDIFF(MONTH, FTDdate, ActiveDate). 0 = FTD month. NULL for customers without a deposit. Observed range: 0 - 225 months (2007 - 2026). (Tier 2 - SP_CID_MonthlyPanel_FullData, BI_DB_CIDFirstDates)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN RegMonth COMMENT 'Month of customer registration in YYYY-MM format. (Tier 2 - Dim_Customer via #CIDs)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN RegDate COMMENT 'Exact date of customer registration. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsReg_ThisM COMMENT '1 if the customer registered during this calendar month; 0 otherwise. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FTD_Month COMMENT 'Month of first time deposit (FTD) in YYYY-MM format. NULL before FTD. (Tier 2 - BI_DB_CIDFirstDates)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FTDdate COMMENT 'Exact date of first deposit. NULL before FTD. (Tier 2 - BI_DB_CIDFirstDates)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsFTD_ThisM COMMENT '1 if the customer made their first deposit this calendar month; 0 otherwise. (Tier 2 - BI_DB_CIDFirstDates)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FTDA COMMENT 'First time deposit amount (USD). Amount of the initial deposit event. (Tier 2 - BI_DB_CIDFirstDates)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Region COMMENT 'Marketing region name as of ETL run (e.g., ''ROW'', ''UK'', ''CEE'', ''Latam''). Denormalized from Dim_Customer. May differ from NewMarketingRegion for some countries. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Country COMMENT 'Customer''s country name (e.g., ''United Kingdom'', ''Israel''). Denormalized from Dim_Customer. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Channel COMMENT 'Acquisition channel (e.g., ''Affiliate'', ''SEM'', ''Media Performance''). (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN SubChannel COMMENT 'Acquisition sub-channel. More granular than Channel. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AffiliateID COMMENT 'Affiliate partner identifier. FK -> DWH_dbo.Dim_Affiliate. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FirstAction COMMENT 'Instrument type of the customer''s first-ever trade (e.g., ''FX/Commodities/Indices'', ''Crypto''). From BI_DB_First5Actions. (Tier 2 - BI_DB_First5Actions)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FirstInstrument COMMENT 'Name of the specific instrument in the customer''s first trade (e.g., ''EUR/USD'', ''BTC''). From BI_DB_First5Actions. (Tier 2 - BI_DB_First5Actions)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN V2_Complete COMMENT '1 if KYC level 2 (identity verification) was completed before this month. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN V3_Complete COMMENT '1 if KYC level 3 (enhanced due diligence / proof of address) was completed before this month. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastPosOpenDate COMMENT 'Date of the customer''s last position open event (any instrument) up to and including this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastLoggedIn COMMENT 'Date of the customer''s last login before end of this month. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsPro COMMENT '1 if the customer has professional client status (from External_BI_OUTPUT_Customer_ProfessionalCustomers). (Tier 2 - External table)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsOTD COMMENT '1 if the customer is classified as OTD (Over-the-Desk / client service tier). (Tier 2 - Fact_SnapshotCustomer)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AccountManager COMMENT 'Name of the assigned account manager at ETL run time. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsIslamic COMMENT '1 if the customer''s account is Islamic (swap-free). Islamic accounts incur AdminFee and SpotAdjustFee instead of overnight swaps. (Tier 1 - DWH_dbo.Dim_Customer wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsContacted COMMENT '1 if the customer was contacted by sales/CRM this month. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsContactedAmount COMMENT 'Amount associated with the CRM contact event this month (if applicable). (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastApplicationProAccountDate COMMENT 'Date of the customer''s most recent professional account application. 1900-01-01 if no application. (Tier 2 - Fact_SnapshotCustomer)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastAMLTicketDate COMMENT 'Most recent AML-related Salesforce case date for this customer (POST-INSERT UPDATE from BI_DB_SF_Cases_Panel). NULL if no AML case history. (Tier 2 - BI_DB_SF_Cases_Panel)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Club COMMENT 'eToro Club loyalty tier at end of month: LowBronze (equity < $1,000), HighBronze (equity $1,000 - Bronze threshold), Silver, Gold, Platinum, Platinum Plus, Diamond. Bronze is split at $1,000; Silver+ use Dim_PlayerLevel.Name directly. (Tier 1 - DWH_dbo.Dim_PlayerLevel wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Regulation COMMENT 'Regulatory jurisdiction at end of month (e.g., CySEC, FCA, FinCEN+FINRA, ASIC & GAML). Sourced from Dim_Regulation.Name via Fact_SnapshotCustomer.RegulationID. 15 distinct values observed. (Tier 2 - Fact_SnapshotCustomer / Dim_Regulation)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity COMMENT 'Total account equity (USD) at end of month from V_Liabilities. Includes all open position unrealised PnL + cash balance. (Tier 2 - DWH_dbo.V_Liabilities)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Balance COMMENT 'Cash balance (USD) at end of month - equity minus unrealised PnL. (Tier 2 - DWH_dbo.V_Liabilities)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Segment COMMENT 'Reserved classification field. Always NULL in practice - never populated by current ETL. (Tier 2 - Reserved)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveUser COMMENT '1 if EOM_Equity > 0 (customer has any portfolio value at month end). Broader than Active or ActiveOpen. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_IsFunded COMMENT 'Legacy funded flag at end of month from Fact_SnapshotCustomer snapshot. Differs from IsEOM_Funded_NEW / IsFunded_New in calculation. Use IsFunded_New or IsEOM_Funded_NEW for current analysis. (Tier 2 - Fact_SnapshotCustomer)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsFunded_New COMMENT 'Current funding flag (new definition). Used as the base for IsChurn_ThisM and IsWB_ThisM churn detection. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Seniority_FundedNew COMMENT 'Months since customer''s "new funded" date: DATEDIFF(MONTH, MAX(FTDMonth, FirstActionMonth, V3Month), ActiveDate). NULL for unfunded customers. (Tier 2 - BI_DB_CIDFirstDates + BI_DB_First5Actions, POST-INSERT UPDATE)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewMarketingRegion COMMENT 'Marketing region label (newer vintage than Region). Values: ROW, UK, CEE, Nordics, Latam, SEA, Australia, etc. (Tier 2 - Fact_SnapshotCustomer / Dim_Customer)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ClusterDetail COMMENT 'Customer behaviour cluster name from BI_DB_CID_DailyCluster (e.g., ''Equities Crypto''). NULL for unclustered customers. (Tier 2 - BI_DB_CID_DailyCluster)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsEOM_Funded_NEW COMMENT 'End-of-month funded flag under the new funded definition. Closely related to IsFunded_New; reflects EOM state. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CountryID COMMENT 'FK -> DWH_dbo.Dim_Country.CountryID. Use for country attribute lookups (regulation, AML risk, EU membership). CountryID=0 = Not available. (Tier 1 - DWH_dbo.Dim_Country wiki)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsChurn_ThisM COMMENT '1 if customer was funded last month (IsFunded_New=1) but not this month (IsFunded_New=0). Churn event indicator. POST-INSERT UPDATE. (Tier 2 - SP_CID_MonthlyPanel_FullData self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsWB_ThisM COMMENT '1 if customer was not funded last month but is funded this month. Win-back event indicator. POST-INSERT UPDATE. (Tier 2 - SP_CID_MonthlyPanel_FullData self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_LSD COMMENT 'Life Stage Description at end of month from BI_DB_CID_LifeStageDefinition. 17 possible values: e.g., ''Dump Churn'', ''Holder'', ''Active Open Club'', ''New Funded'', ''Win Back Active Open''. (Tier 2 - BI_DB_CID_LifeStageDefinition)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active COMMENT '1 if customer closed  >= 1 position this month (any asset class). (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen COMMENT '1 if customer has open positions at month end. Composite: 1 when ActiveOpen_Manual=1 OR ActiveOpen_NewMirror=1 OR ActiveOpen_AddMirror=1. (Tier 2 - SP_CID_MonthlyPanel_FullData, Or Filizer 2025-01-06)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpenManual COMMENT 'Count of open manual (non-copy) positions at month end. Stored as count, not a binary flag. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpenWOAirdrop COMMENT 'Count of open positions at month end, excluding airdrop-type positions. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpenWOAirdropManual COMMENT 'Count of open manual positions at month end excluding airdrop positions. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Copy COMMENT '1 if customer had active copy trades closed this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Stocks COMMENT '1 if customer closed  >= 1 real (settled) stock/ETF position this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Stocks COMMENT '1 if customer closed  >= 1 CFD (leveraged) stock position this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Crypto COMMENT '1 if customer closed  >= 1 settled crypto position this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Crypto COMMENT '1 if customer closed  >= 1 CFD crypto position this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Copy COMMENT '1 if customer has open copy trades at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks COMMENT '1 if customer has open real stock positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks COMMENT '1 if customer has open CFD stock positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto COMMENT '1 if customer has open settled crypto positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto COMMENT '1 if customer has open CFD crypto positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_AirDrop COMMENT '1 if customer has open airdrop-type positions at month end. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Mirror COMMENT '1 if customer has open mirror/add-mirror copy positions at month end. CASE WHEN NewMirror=1 OR AddMirror=1. (Tier 2 - Dim_Mirror via #mrr/#addmrr)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Manual COMMENT '1 if customer has open manually-executed positions at month end (non-copy). (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_IncludeCopy COMMENT '1 if customer has open positions including copy trades at month end. Superset of ActiveOpen. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Stocks_Lev1 COMMENT 'Flag (stored as money: 0.0 or 1.0) - customer traded real stocks with 1:1 leverage (un-leveraged long) this month. (Tier 2 - Fact_CustomerAction Lev sub-split)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Stocks_LevCFD COMMENT 'Flag - customer traded leveraged/short CFD stock positions this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Crypto_Lev1 COMMENT 'Flag - customer traded un-leveraged real crypto positions this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Crypto_LevCFD COMMENT 'Flag - customer traded leveraged/short CFD crypto positions this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks_Lev1 COMMENT 'Flag - customer has open un-leveraged real stock positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks_LevCFD COMMENT 'Flag - customer has open leveraged CFD stock positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto_Lev1 COMMENT 'Flag - customer has open un-leveraged real crypto positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto_LevCFD COMMENT 'Flag - customer has open leveraged CFD crypto positions at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsOpen_Copy COMMENT '1 if customer has an open copy trade relationship at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Opened_Copy COMMENT 'Number of new copy trade relationships opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Closed_Copy COMMENT 'Number of copy trade relationships closed this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyIn_Copy COMMENT 'USD amount allocated to new copy trades this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyOut_Copy COMMENT 'USD amount withdrawn from copy trades this month (stop-copy events). (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsOpen_CopyPortfolio COMMENT '1 if customer has an open copy-portfolio (SmartPortfolio) position at month end. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Opened_CopyPortfolio COMMENT 'Number of new copy-portfolio positions opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Closed_CopyPortfolio COMMENT 'Number of copy-portfolio positions closed this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyIn_CopyPortfolio COMMENT 'USD amount allocated to new copy-portfolio positions this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyOut_CopyPortfolio COMMENT 'USD amount withdrawn from copy-portfolio positions this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Copy COMMENT 'Count of new copy positions opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks COMMENT 'Count of new settled stock/ETF positions opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks COMMENT 'Count of new CFD stock positions opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto COMMENT 'Count of new settled crypto positions opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto COMMENT 'Count of new CFD crypto positions opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Total COMMENT 'Total count of new positions opened this month (all asset classes combined). (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Copy COMMENT 'USD amount allocated to new copy positions opened this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks COMMENT 'USD amount allocated to new real stock positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks COMMENT 'USD amount allocated to new CFD stock positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto COMMENT 'USD amount allocated to new settled crypto positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto COMMENT 'USD amount allocated to new CFD crypto positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Total COMMENT 'Total USD amount allocated to all new positions this month. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks_Lev1 COMMENT 'Count of new un-leveraged real stock positions (Lev1) opened this month. Stored as money type. (Tier 2 - Fact_CustomerAction Lev sub-split)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks_LevCFD COMMENT 'Count of new leveraged/short CFD stock positions opened this month. Stored as money type. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto_Lev1 COMMENT 'Count of new un-leveraged real crypto positions opened this month. Stored as money type. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto_LevCFD COMMENT 'Count of new leveraged/short CFD crypto positions opened this month. Stored as money type. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks_Lev1 COMMENT 'USD amount allocated to new Lev1 real stock positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks_LevCFD COMMENT 'USD amount allocated to new LevCFD CFD stock positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto_Lev1 COMMENT 'USD amount allocated to new Lev1 real crypto positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto_LevCFD COMMENT 'USD amount allocated to new LevCFD CFD crypto positions. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Copy COMMENT 'Monthly commission from copy trading (FullCommissions). (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Stocks COMMENT 'Monthly commission from settled stock/ETF trading. (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks COMMENT 'Monthly commission from CFD stock trading. (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Crypto COMMENT 'Monthly commission from settled crypto trading. (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto COMMENT 'Monthly commission from CFD crypto trading. (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Total COMMENT 'LEGACY total revenue: sum of FullCommissions only (Revenue_Copy + Real_Stocks + CFD_Stocks + Real_Crypto + CFD_Crypto + FX_Comm_Ind + Other). Excludes function fees (AdminFee, TicketFees, ConversionFees, etc.). Use Revenue_Total_New for current analysis. (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Stocks_Lev1 COMMENT 'Revenue from un-leveraged real stock positions + Revenue_TicketFees component. (Tier 2 - BI_DB_DailyCommisionReport + Function_Revenue_TicketFee)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks_LevCFD COMMENT 'Revenue from leveraged CFD stock positions + TicketFeeByPercent_Stocks_CFD_Lev. (Tier 2 - BI_DB_DailyCommisionReport + Function_Revenue_TicketFeeByPercent)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Crypto_Lev1 COMMENT 'Revenue from un-leveraged real crypto positions + TicketFeeByPercent_Crypto_Real. (Tier 2 - BI_DB_DailyCommisionReport + Function_Revenue_TicketFeeByPercent)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto_LevCFD COMMENT 'Revenue from leveraged CFD crypto positions + TicketFeeByPercent_Crypto_CFD_Lev. (Tier 2 - BI_DB_DailyCommisionReport + Function_Revenue_TicketFeeByPercent)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Currencies COMMENT 'Revenue from currency CFD instruments (Currencies sub-class of FX). (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Commodities COMMENT 'Revenue from commodity CFD instruments. (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Crypto COMMENT 'Revenue from all crypto subtypes combined (CFD Crypto + Real Crypto, all leverage tiers). (Tier 2 - BI_DB_DailyCommisionReport + Function_Revenue_TicketFeeByPercent)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Equities COMMENT 'Revenue from equity instruments (stocks, ETFs). (Tier 2 - BI_DB_DailyCommisionReport)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_IslamicFees COMMENT 'Islamic account fee revenue this month: AdminFee + SpotAdjustFee (swap replacement fees for Islamic/swap-free accounts). (Tier 2 - Function_Revenue_AdminFee + Function_Revenue_SpotAdjustFee)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_TicketFees COMMENT 'Ticket fee revenue this month from Function_Revenue_TicketFee. Per-position fees. (Tier 2 - Function_Revenue_TicketFee)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_ConversionFees COMMENT 'Currency conversion fee revenue this month from Function_Revenue_ConversionFee. Charged when trading instruments denominated in non-USD currencies. (Tier 2 - Function_Revenue_ConversionFee)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Total_New COMMENT 'CURRENT total revenue formula (Or Filizer 2025): FullCommissions + AdminFee + TicketFees + ConversionFees + SpotAdjustFee + TicketFeeByPercent. Use this column for all current revenue analysis. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Transactional_Revenue_Total COMMENT 'Revenue_Total_New minus Revenue_ConversionFees. Measures pure trading/transactional revenue, excluding currency conversion costs. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_TicketFeeByPercent COMMENT 'Percent-based ticket fee revenue from Function_Revenue_TicketFeeByPercent. Applies to crypto and leveraged stock CFD positions. (Tier 2 - Function_Revenue_TicketFeeByPercent)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Copy COMMENT 'Customer-side realised PnL from copy trades closed this month (USD). Negative = customer lost money. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Stocks COMMENT 'Realised PnL from settled stock/ETF positions closed this month. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Stocks COMMENT 'Realised PnL from CFD stock positions closed this month. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Crypto COMMENT 'Realised PnL from settled crypto positions closed this month. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Crypto COMMENT 'Realised PnL from CFD crypto positions closed this month. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Total COMMENT 'Total realised PnL across all asset classes this month. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Stocks_Lev1 COMMENT 'Realised PnL from Lev1 (un-leveraged) real stock positions. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Stocks_LevCFD COMMENT 'Realised PnL from LevCFD (leveraged) CFD stock positions. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Crypto_Lev1 COMMENT 'Realised PnL from Lev1 real crypto positions. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Crypto_LevCFD COMMENT 'Realised PnL from LevCFD CFD crypto positions. (Tier 2 - BI_DB_PositionPnL)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN TotalDeposits COMMENT 'Total USD deposited by the customer this calendar month. (Tier 2 - #Cashier from billing tables)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CountDeposits COMMENT 'Number of deposit transactions this month. (Tier 2 - #Cashier)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN TotalCashouts COMMENT 'Total USD withdrawn by the customer this month. (Tier 2 - #Cashier)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN TotalCoFee COMMENT 'Total copy-out fees charged this month (fees incurred when exiting a copy relationship). (Tier 2 - #Cashier)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NetDeposits COMMENT 'TotalDeposits - TotalCashouts for this month. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN WithdrawalToWallet COMMENT 'USD amount withdrawn to the eToro Wallet (crypto wallet) this month. (Tier 2 - SP_CID_MonthlyPanel_FullData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CashoutsAdjusted COMMENT 'Cashout amount adjusted per DDR methodology (from BI_DB_V_DDR_Daily_Panel). May differ from TotalCashouts due to DDR cashout adjustment rules. (Tier 2 - BI_DB_V_DDR_Daily_Panel)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Copy COMMENT 'End-of-month equity in copy trades (USD). (Tier 2 - Fact_SnapshotCustomer / V_Liabilities breakdown)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Crypto COMMENT 'End-of-month equity in settled crypto positions. (Tier 2 - Fact_SnapshotCustomer breakdown)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Stocks COMMENT 'End-of-month equity in settled stock/ETF positions. (Tier 2 - Fact_SnapshotCustomer breakdown)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Crypto COMMENT 'End-of-month equity in CFD crypto positions (unrealised value). (Tier 2 - Fact_SnapshotCustomer breakdown)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Stocks COMMENT 'End-of-month equity in CFD stock positions. (Tier 2 - Fact_SnapshotCustomer breakdown)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Crypto_Lev1 COMMENT 'EOM equity in un-leveraged (Lev1) real crypto positions. (Tier 2 - Fact_SnapshotCustomer Lev sub-split)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Stocks_LevCFD COMMENT 'EOM equity in leveraged-equivalent (LevCFD) real stock positions. (Tier 2 - Fact_SnapshotCustomer)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Crypto_Lev1 COMMENT 'EOM equity in Lev1 CFD crypto positions. (Tier 2 - Fact_SnapshotCustomer)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Stocks_LevCFD COMMENT 'EOM equity in LevCFD CFD stock positions. (Tier 2 - Fact_SnapshotCustomer)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Copy COMMENT 'Lifetime accumulated copy trading commission. Current month Revenue_Copy + prior month ACC_Revenue_Copy. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Stocks COMMENT 'Lifetime accumulated real stock commission. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Stocks COMMENT 'Lifetime accumulated CFD stock commission. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Crypto COMMENT 'Lifetime accumulated settled crypto commission. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Crypto COMMENT 'Lifetime accumulated CFD crypto commission. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Total COMMENT 'Lifetime accumulated total commission - accumulates LEGACY Revenue_Total. For lifetime analysis use ACC_Revenue_Total_New. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Copy COMMENT 'Lifetime accumulated copy trading PnL. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Real_Stocks COMMENT 'Lifetime accumulated real stock PnL. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Stocks COMMENT 'Lifetime accumulated CFD stock PnL. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Real_Crypto COMMENT 'Lifetime accumulated settled crypto PnL. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Crypto COMMENT 'Lifetime accumulated CFD crypto PnL. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Total COMMENT 'Lifetime accumulated total PnL across all asset classes. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_TotalDeposits COMMENT 'Lifetime accumulated total deposits. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_CountDeposits COMMENT 'Lifetime accumulated deposit transaction count. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_TotalCashouts COMMENT 'Lifetime accumulated total cashouts. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_TotalCoFee COMMENT 'Lifetime accumulated copy-out fees. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_NetDeposits COMMENT 'Lifetime accumulated net deposits (deposits minus cashouts). (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_WithdrawalToWallet COMMENT 'Lifetime accumulated withdrawals to eToro Wallet. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Currencies COMMENT 'Lifetime accumulated revenue from currency CFD instruments. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Commodities COMMENT 'Lifetime accumulated revenue from commodity CFD instruments. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Crypto COMMENT 'Lifetime accumulated revenue from all crypto subtypes. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Equities COMMENT 'Lifetime accumulated revenue from equity instruments. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Total_New COMMENT 'Lifetime accumulated Revenue_Total_New (current formula including all fee components). Use this for lifetime revenue analysis from 2025 onward. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Transactional_Revenue_Total COMMENT 'Lifetime accumulated Transactional_Revenue_Total. (Tier 2 - Self-reference)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_1Y COMMENT '1-year lifetime value prediction (USD). Inserted as 0 by SP_CID_MonthlyPanel_FullData; updated by SP_LTV_BI_Actual. Will be 0 if LTV SP has not run for this month. (Tier 2 - SP_LTV_BI_Actual)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_3Y COMMENT '3-year lifetime value prediction. Same caveats as LTV_1Y. (Tier 2 - SP_LTV_BI_Actual)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_8Y_NoExtreme COMMENT '8-year LTV prediction excluding extreme outlier customers. (Tier 2 - SP_LTV_BI_Actual)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_Expected_bySeniority COMMENT 'Expected LTV based on the customer''s seniority cohort model. (Tier 2 - SP_LTV_BI_Actual)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NoExtremeLTV_Expected_bySeniority COMMENT 'No-extreme LTV by seniority cohort. Removes outlier customers from the seniority-based expectation. (Tier 2 - SP_LTV_BI_Actual)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_8Y COMMENT '8-year lifetime value prediction (full, including extremes). (Tier 2 - SP_LTV_BI_Actual)';

-- ---- Column PII Tags ----
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Month SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Seniority SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN RegMonth SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN RegDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsReg_ThisM SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FTD_Month SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FTDdate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsFTD_ThisM SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FTDA SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Region SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Country SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Channel SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN SubChannel SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AffiliateID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FirstAction SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN FirstInstrument SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN V2_Complete SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN V3_Complete SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastPosOpenDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastLoggedIn SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsPro SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsOTD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AccountManager SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsIslamic SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsContacted SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsContactedAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastApplicationProAccountDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LastAMLTicketDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Club SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Regulation SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Balance SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Segment SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveUser SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_IsFunded SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsFunded_New SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Seniority_FundedNew SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewMarketingRegion SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ClusterDetail SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsEOM_Funded_NEW SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CountryID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsChurn_ThisM SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsWB_ThisM SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_LSD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpenManual SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpenWOAirdrop SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpenWOAirdropManual SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_AirDrop SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Mirror SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Manual SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_IncludeCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Active_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsOpen_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Opened_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Closed_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyIn_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyOut_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN IsOpen_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Opened_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Count_Closed_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyIn_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN MoneyOut_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Currencies SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Commodities SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_Revenue_Equities SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_IslamicFees SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_TicketFees SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_ConversionFees SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_Total_New SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Transactional_Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN Revenue_TicketFeeByPercent SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN PnL_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN TotalDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CountDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN TotalCashouts SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN TotalCoFee SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NetDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN WithdrawalToWallet SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN CashoutsAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_Real_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN EOM_Equity_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_PnL_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_TotalDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_CountDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_TotalCashouts SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_TotalCoFee SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_NetDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_WithdrawalToWallet SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Currencies SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Commodities SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN A_ACC_Revenue_Equities SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Revenue_Total_New SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN ACC_Transactional_Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_1Y SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_3Y SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_8Y_NoExtreme SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_Expected_bySeniority SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN NoExtremeLTV_Expected_bySeniority SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_monthlypanel_fulldata ALTER COLUMN LTV_8Y SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 12:31:52 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 9
-- Statements: 362/362 succeeded
-- ====================
