-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_DDR_Fact_Revenue_Generating_Actions
-- Generated: 2026-03-29 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_DDR_Fact_Revenue_Generating_Actions > 3.1B-row comprehensive revenue fact table capturing 18 distinct revenue streams (spreads, rollovers, ticket fees, conversion fees, dormant fees, dividends, staking, options PFOF, and more) per customer per day, broken down by instrument type, position flags, and trade characteristics. Sourced from 16+ `Function_Revenue_*` TVFs, enriched with IBAN/recurring/CopyFund/C2P position attributes, assembled by `SP_DDR_Fact_Revenue_Generating_Actions` with daily DELETE/INSERT plus special reload strategies for Options (full history) and Staking (monthly lag). | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Production Source** | Multiple - 16+ `Function_Revenue_*` TVFs + `Dim_Revenue_Metrics` + enrichment tables | | **Refresh** | Daily (DELETE/INSERT by DateID) + Options full reload + Staking'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN DateID COMMENT 'Business date key (**YYYYMMDD**) driving partition swaps; staking branch shifts Month+1 versus TVF-derived activity date; Options reload obeys TVF-supplied horizon. **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN Date COMMENT 'Calendar `DATE` mirrored from `@date` parameter on primary insert, TVF timestamps for Options, or derived calendar date when staking rewinds partitions. **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN RealCID COMMENT 'Customer ID - platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. **(Tier 1 - Customer.CustomerStatic)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN ActionTypeID COMMENT 'Event classifier - join `Dim_ActionType` for `Name` / `Category`. Drives sparse column population. Derived from **`CreditTypeID`** & branch router in loader + positional feeds. **DDR note:** aggregated revenue streams coerce NULL -> `ISNULL(...,-1)` at insert; `-1` marks non-trade metrics. **(Tier 1 - History.Credit / Trade snapshots / STS / Customer payloads)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN ActionType COMMENT 'Verb text for streams - either `Dim_ActionType.Name` (commissions path) **or** literal identifiers (`Rollover`, `SDRT`, `''Redeem''` for TransferCoin aggregates, staking/options labels). **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN InstrumentTypeID COMMENT 'From IMD (InstrumentMetaData). Asset class: 1=Currencies, 2=Commodities, 3=CFD, 4=Indices, 5=Stocks, 6=ETF, 7=Bonds, 8=TrustFunds, 9=Options, 10=Crypto. FK to Dictionary.CurrencyType. **`ISNULL(...,-1)`** masks NULL account-level feeds. **(Tier 1 - Trade.GetInstrument)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsSettled COMMENT '1 = real asset, 0 = CFD asset. **DDR note:** `ISNULL(...,-1)` sentinel for streams lacking instruments. **(Tier 5 - Expert Review)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsCopy COMMENT '`CASE WHEN MirrorID > 0 THEN 1 ELSE 0 END` from revenue TVFs, then `ISNULL(...,-1)`; crypto-to-fiat branch forces `-1` post UPDATE. Indicates copy-trading linkage on applicable metrics. **(Tier 2 - Fact_CustomerAction.MirrorID logic via Function_Revenue_*)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN Metric COMMENT 'Canonical revenue column label (`FullCommission`, `RollOverFee`, `TransferCoinFee`, `StakingLagOneMonth`, …) - enumerated in **`Dim_Revenue_Metrics.Metric`**. **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN Amount COMMENT 'USD revenue amount aggregated per UNION/GROUP grain - sign reflects economic direction (negative dividend payouts retained). Populated strictly from enumerated TVF monetary columns summarized in **`section 2.1`**. **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN CountTransactions COMMENT '`COUNT`/`SUM` amalgamation counting instrumented actions per grain; `ISNULL(...,0)` enforced on insert (`ShareLending`/`Staking` may collapse NULL counts). **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IncludedInTotalRevenue COMMENT 'True if this metric contributes to the canonical "Total Revenue" rollup; False for raw/pass-through entries (`Commission`, `Dividends`, `SDRT`). Filter on this when computing top-line revenue to avoid double-counting. **`SP_DDR`** post-processing forces `Metric=''SDRT''` rows to **`0`** even if dictionary flipped historically. Stored as **`int` mirror** of **`Dim_Revenue_Metrics`** bit semantics. **(Tier 1 - UC sample)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN CountAsActiveTrade COMMENT '**`CASE WHEN ActionTypeID IN (1,39) AND ISNULL(IsAirDrop,0) = 0 THEN 1 ELSE 0 END`** on commission feeders; flattened to **`0`** elsewhere before insert coercion. **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN UpdateDate COMMENT 'ETL stamp `GETDATE()` captured at each INSERT pass (main, options purge, staking window). **(Tier 2 - SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsBuy COMMENT '**`1`** Long **`0`** Short; NULL ⇒ non-trade row sentinel - widened/truncated via `ISNULL(...,-1)` with dividend amount-based overrides (**`Metric=''Dividends''`**) and **`CryptoToFiatFee`** sentinel `-1` path. **(Tier 1 - Trade.PositionTbl)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsLeveraged COMMENT 'Derived `CASE WHEN Leverage > 1 THEN 1 ELSE 0 END` sourced from BI_DB TVFs feeding position-level revenue; `ISNULL` packaging for lake merges. Admin fee branch aliases `Leverage` as `IsLeverage` inside grouping (typo tolerated). **(Tier 2 - Function_Revenue_FullCommissions / AdminFee lineage)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsFuture COMMENT 'Combination of TVF payloads and `Dim_Instrument.IsFuture` for admin/spot adjust branches (with `CryptoToFiatFee` forced `-1`). `ISNULL` packaging standard. **(Tier 2 - Dim_Instrument / Function_Revenue_TVF)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsCopyFund COMMENT '**`CASE WHEN BI_DB_CopyFund_Positions.PositionID IS NOT NULL THEN 1 ELSE 0 END`** seeded via sequential updates on commission temps; `ISNULL` packaging. **(Tier 2 - BI_DB_CopyFund_Positions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsOpenedFromIBAN COMMENT 'Indicator set via staged parquet + `Dim_Position`-aligned `UPDATE` overlays for eligible overnight/ticket/dividends positions (`1` once matched else `-1` sentinel via `ISNULL`). **(Tier 2 - External_bi_output_finance_bi_db_positions_opened_from_iban_parquet)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsClosedToIBAN COMMENT 'Same IBAN close-table overlay pattern as `IsOpenedFromIBAN`. **(Tier 2 - External_bi_output_finance_bi_db_positions_closed_to_iban_parquet)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsRecurring COMMENT 'Recurring investment overlay using `External_bi_db_recurringinvestment_positions_parquet`; `ConversionFee` branch also carries TVF `IsRecurring`. **(Tier 2 - External_bi_db_recurringinvestment_positions_parquet)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsAirDrop COMMENT 'Free-share flag sourced from BI_DB TVFs describing AirDrop exclusions for active-trade tallies (`ISNULL` packaging plus metric-specific coercion). **(Tier 2 - Function_Revenue_FullCommissions / Function_Revenue_Commissions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsSQF COMMENT '**`IsSQF` (SpotQuotedFuture flag) - 1 = instrument is a SpotQuotedFuture (a smaller-contract variant of eToro RealFutures, traded on the CME / Chicago Mercantile Exchange). 0 = not an SQF instrument. Source: `Function_Instrument_Snapshot_Enriched(@dateInt)` via membership in `Trade.InstrumentGroups` with `GroupID = 59`. ISNULL coalesces to -1 for streams where SQF classification doesn''t apply (Dividends, SDRT, staking, deposit/withdraw fees). (Tier 5 - user expert correction; previously mis-described as "Sustainable & Quality-Focused")**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN RevenueMetricID COMMENT 'Surrogate key. Stable integer 1-18 (with new entries appended). FK target from DDR fact tables when revenue is stored long-form. Seeds via `JOIN Dim_Revenue_Metrics`; staking (`12`) and options (`18`) forcibly seeded in dedicated branches prior to dictionary refresh. **(Tier 1 - UC sample)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN RevenueMetricCategoryID COMMENT 'Category surrogate key 1-5. 1=TradeTransactional, 2=Overnight, 3=MIMO, 4=RevShare, 5=Other - inherited from **`Dim_Revenue_Metrics`** (plus staking/options seeded pairs). **(Tier 1 - UC sample)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsMarginTrade COMMENT 'Mirrors TVF-supplied flag with SP-level overrides (`Metric=''SDRT''` ⇒ `IsMarginTrade=0`; `Metric=''Options_PFOF''` margin adjustments). **(Tier 2 - Function_Revenue_* / SP_DDR_Fact_Revenue_Generating_Actions)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsC2P COMMENT '**`CASE WHEN V_C2P_Positions.PositionID IS NOT NULL THEN 1 ELSE 0 END`** on position-backed paths; `ISNULL` packaging for non-position metrics. **(Tier 2 - BI_DB_dbo.V_C2P_Positions)**';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN DateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN RealCID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN ActionTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN ActionType SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN InstrumentTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsSettled SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN Metric SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN Amount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN CountTransactions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IncludedInTotalRevenue SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN CountAsActiveTrade SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsBuy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsLeveraged SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsFuture SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsCopyFund SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsOpenedFromIBAN SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsClosedToIBAN SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsRecurring SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsAirDrop SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsSQF SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN RevenueMetricID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN RevenueMetricCategoryID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsMarginTrade SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_revenue_generating_actions ALTER COLUMN IsC2P SET TAGS ('pii' = 'none');

