-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_OPS_Fraud_Alert_Analysis
-- Generated: 2026-05-03 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_OPS_Fraud_Alert_Analysis > 1.47M-row fraud detection scoring table covering customers registered in the last 3 months (2026-01-01 to 2026-04-11). Computes 15+ suspicious-registration signals (fake names, disposable emails, IP clustering, geographic mismatches, fast verification speed) and a weighted composite score per customer. Sourced from DWH_dbo.Dim_Customer + 9 dimension JOINs + BackOffice documents + History verification dates + billing deposits. Daily TRUNCATE+INSERT via SP_OPS_Fraud_Alert_Analysis. | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Key Identifier** | RealCID (not enforced - no PK in DDL) | | **Production Source** | SP_OPS_Fraud_Alert_Analysis (Michail Vryoni, 2025-06-25) | | **Refresh** | Daily (1440 min), TRUNCATE+INSERT, 3-month rolling window | | **Synapse Distribution** | ROUND_ROBIN | | **Syna'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN RealCID COMMENT 'Customer ID -- platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN RegisteredReal COMMENT 'Account registration date (renamed from Registered). Default=getdate(). Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FirstName COMMENT 'Legal first name in Unicode. nvarchar supports non-Latin scripts (Cyrillic, Arabic, etc.). Used in LinkedAccountHash1. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN LastName COMMENT 'Legal last name in Unicode. Used in LinkedAccountHash1. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Email COMMENT 'Customer email address. Unique (case-insensitive via LowerEmail computed column). Email changes trigger Customer.LastChanges update via trigger. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN BirthDate COMMENT 'Customer date of birth. Used in LinkedAccountHash1 for duplicate detection and in KYC age verification. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevelID COMMENT 'KYC verification level. FK to Dictionary.VerificationLevel. Values: 0=unverified, 1=partial, 2=intermediate, 3=fully verified. Default=0. Passthrough from Dim_Customer. (Tier 1 -- BackOffice.Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN ClientLanguage COMMENT 'Language display name. Used in back-office language selectors and reporting. Dim-lookup passthrough from Dim_Language.Name via Dim_Customer.LanguageID. (Tier 1 -- Dictionary.Language)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN ClientCommunicationLanguage COMMENT 'Language display name. Used in back-office language selectors and reporting. Dim-lookup passthrough from Dim_Language.Name via Dim_Customer.CommunicationLanguageID. (Tier 1 -- Dictionary.Language)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Country COMMENT 'Full country name in English. Unique per row. Used in UI dropdowns, compliance documents, and analytical reports. Dim-lookup passthrough from Dim_Country.Name via Dim_Customer.CountryID. (Tier 1 -- Dictionary.Country)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN CountryByIP COMMENT 'Full country name in English. Dim-lookup passthrough from Dim_Country.Name via Dim_Customer.CountryIDByIP. Used for geographic mismatch detection. (Tier 1 -- Dictionary.Country)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN EvMatchStatusName COMMENT 'Human-readable label for the EV match status. Values: None, PartiallyVerified, Verified, NotVerified. Dim-lookup passthrough from Dim_EvMatchStatus.EvMatchStatusName via Dim_Customer.EvMatchStatus. (Tier 2 -- SP_Dictionaries_DL_To_Synapse)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PlayerStatus COMMENT 'Human-readable restriction state label. Used in BackOffice UI, compliance reports, and monitoring dashboards. Note: some values have trailing spaces in live data -- apply RTRIM() for string comparisons. Dim-lookup passthrough from Dim_PlayerStatus.Name via Dim_Customer.PlayerStatusID. (Tier 1 -- Dictionary.PlayerStatus)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN IP COMMENT 'Registration IP address. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FakeFirstNameFlag COMMENT '1 when FirstName matches 50+ suspicious patterns: gibberish (aaa-zzz triple repeats, all 26 letters), keyboard walks (qwert, asdf, bvbv, zxzx), sequential letters (abc-xyz, all 23 pairs), digits, non-alphabetic characters, test/fake/demo/sample keywords, length < 2, or FirstName = LastName. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FakeLastNameFlag COMMENT '1 when LastName matches 40+ suspicious patterns: same logic as FakeFirstNameFlag (triple repeats, keyboard walks, digits, non-alpha, test/fake keywords, length < 2). 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FakeEmailPatternFlag COMMENT '1 when Email matches disposable domain patterns (mailinator, tempmail, yopmail, guerrillamail, sharklasers, etc.), keyboard walks, @hotmail.co typosquat, short local parts (<=4 chars), numeric-prefix local parts, or test/autobot keywords. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN InvalidDOBFlag COMMENT '1 when customer is under 18 (DATEDIFF(YEAR, BirthDate, GETDATE()) < 18) OR BirthDate equals registration date (CAST(RegisteredReal AS DATE)). 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN LanguageCountryMismatchFlag COMMENT '1 when LanguageID or CommunicationLanguageID does not match the expected language IDs for the customer''s country. 18-country matrix: Germany (2,11,1,25), France (7,1,25), Spain (6,1,25), Italy (8,1,25), UK (1,25), Russia (5,1,25), Turkey (1,11,25), Ukraine (5,1,25), Poland (17,1,25), Brazil (10,1,25), Mexico (7,1,25), China (4,1,18,25), India (11,1,25), Pakistan (121,25,1), Iran (13,1,25), Egypt (3,1,25), US (1,6,7,25), Vietnam (1,25,26). 0 for unlisted countries. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN CountryMismatchFlag COMMENT '1 when Country (registration) differs from CountryByIP (IP-detected). 0 when they match. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PhoneVerifiedName COMMENT 'Human-readable verification state label. Note: ID=2 has value "ManualyVerified" -- a production typo (single ''l'') preserved verbatim from etoro.Dictionary.PhoneVerified. Displayed in customer cards, verification reports, and compliance dashboards. Dim-lookup passthrough from Dim_PhoneVerified.PhoneVerifiedName via Dim_Customer.PhoneVerifiedID. (Tier 1 -- Dictionary.PhoneVerified)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN `2FA` COMMENT 'Two-factor authentication status. 0=disabled, 1=enabled. Derived from STS_Audit_UserOperationsData login type events. Preserves previous value when no new 2FA event exists. Passthrough from Dim_Customer. (Tier 2 -- SP_Dim_Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FailedEVMatchFlag COMMENT '1 when EvMatchStatusName = ''NotVerified''. 0 otherwise. Derived from Dim_EvMatchStatus lookup. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevel3Date COMMENT 'Earliest timestamp when the customer reached VerificationLevelID=3 (fully verified). From MIN(ValidFrom) in History.BackOfficeCustomer. NULL if never reached VL3. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevel2Date COMMENT 'Earliest timestamp when the customer reached VerificationLevelID=2 (intermediate). From MIN(ValidFrom) in History.BackOfficeCustomer. NULL if never reached VL2. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevel1Date COMMENT 'Earliest timestamp when the customer reached VerificationLevelID=1 (partial). From MIN(ValidFrom) in History.BackOfficeCustomer. NULL if never reached VL1. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLeveL0Date COMMENT 'Earliest timestamp when the customer reached VerificationLevelID=0 (unverified). From MIN(ValidFrom) in History.BackOfficeCustomer. Note: column name has uppercase ''L'' typo. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN EVMatchStatusDate COMMENT 'Earliest timestamp when the customer reached EvMatchStatus=2 (Verified). From MIN(ValidFrom) in History.BackOfficeCustomer. NULL if never reached EV verified status. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Time_L0To_L1_Min COMMENT 'Minutes between VL0 and VL1 verification dates. DATEDIFF(MINUTE, VerificationLeveL0Date, VerificationLevel1Date). NULL if either date is missing. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Time_L1To_L2_Min COMMENT 'Minutes between VL1 and VL2 verification dates. DATEDIFF(MINUTE, VerificationLevel1Date, VerificationLevel2Date). NULL if either date is missing. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Time_L2To_L3_Min COMMENT 'Minutes between VL2 and VL3 verification dates. DATEDIFF(MINUTE, VerificationLevel2Date, VerificationLevel3Date). NULL if either date is missing. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastLOL1Flag COMMENT '1 when VL0-to-VL1 transition took less than 1 minute (Time_L0To_L1_Min < 1). Indicates suspiciously fast initial verification. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastL1L2Flag COMMENT '1 when VL1-to-VL2 transition took less than 1 minute (Time_L1To_L2_Min < 1). 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastL2L3Flag COMMENT '1 when VL2-to-VL3 transition took less than 1 minute (Time_L2To_L3_Min < 1). 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastEVMatchFlag COMMENT '1 when EV match verification completed within 5 minutes of registration (DATEDIFF(MINUTE, RegisteredReal, EVMatchStatusDate) <= 5). 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN RepeatedIPAddressFlag COMMENT '1 when the customer''s registration IP has >= 20 distinct RealCIDs in the 3-month window. Indicates shared VPN/proxy or botnet origin. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN WeightedSuspiciousScore COMMENT 'Composite fraud risk score (0--15 scale). Sum of 15 binary signals: both-names-fake, fake-email+unverified-phone, country-time-cluster>10, InvalidDOB, LanguageMismatch, CountryMismatch, FastL0L1, FastL1L2, FastEVMatch, RepeatedIP, plus 5 combo flags. Higher = more suspicious. Distribution: 50% score=0, 28% score=1, 20% score=2, <2% score>=3. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_FastRegistration_FakeEmail COMMENT '1 when FastL0L1Flag=1 AND FakeEmailPatternFlag=1. Combined signal: suspiciously fast verification with disposable email. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_SuspiciousDomain_FakeName COMMENT '1 when FakeEmailPatternFlag=1 AND (FakeFirstNameFlag=1 OR FakeLastNameFlag=1). Combined signal: disposable email with fake name. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_IPRepeat_FakeEmail COMMENT '1 when IP has >= 20 users AND FakeEmailPatternFlag=1. Combined signal: shared IP with disposable email. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_FastVerification_GeoMismatch COMMENT '1 when CountryMismatchFlag=1 AND FastL0L1Flag=1 AND FastL1L2Flag=1. Combined signal: geographic mismatch with rapid verification. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN ClusteredIP_RegistrationFlag COMMENT '1 when the same IP has >= 20 registrations within the same second (DATETIME2(0) rounded). Indicates bot-driven mass registration. Currently all 0 in production (threshold may be too strict). (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN GCID COMMENT 'Group Customer ID -- cross-product identity key linking the same person across eToro products/entities. NULL for older accounts predating GCID introduction. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN CountryTimeClustersFlag COMMENT '1 when the customer''s Country + CountryByIP + registration minute combination has > 10 registrations. Detects coordinated geographic registration bursts. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PlayerStatusReason COMMENT 'Human-readable reason label. Key values: None (0), Failed Verification (1), Chargeback (5), AML-Account Closed (6), HRC (7), AML (10), AML review (11), WCH match (18), Right to be forgotten (20), Self-Service (21), eToro Money Restriction (33), Abusive Trading (34), Hacked Account (35), Tax (41). Dim-lookup passthrough from Dim_PlayerStatusReasons.Name via Dim_Customer.PlayerStatusReasonID. (Tier 1 -- Dictionary.PlayerStatusReasons)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PlayerStatusSubReason COMMENT 'Human-readable sub-reason label (renamed from production Name). Key abbreviations: CHBK=Chargeback, POI=Proof of Identity, POA=Proof of Address, FTD=First Time Deposit, MOP=Method of Payment, PWMB=eToro Money, SAR=Suspicious Activity Report, WCH=World Check. Key values: Fraud (1), Fake docs (2), ACH CHBK (35), Credit Card CHBK (36), PayPal CHBK (37), SAR filed (73), FATCA (66), W-8BEN (76), Vulnerable Client (75). Dim-lookup passthrough from Dim_PlayerStatusSubReasons.PlayerStatusSubReasonName via Dim_Customer.PlayerStatusSubReasonID. (Tier 1 -- Dictionary.PlayerStatusSubReasons)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Club COMMENT 'Tier display name: Bronze, Silver, Gold, Platinum, Platinum Plus, Diamond, Internal, N/A. Used in BackOffice reporting JOINs and customer-facing UI. Dim-lookup passthrough from Dim_PlayerLevel.Name via Dim_Customer.PlayerLevelID. (Tier 1 -- Dictionary.PlayerLevel)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN TotalDeposits COMMENT 'Sum of approved deposit amounts in USD (PaymentStatusID=2) from Fact_BillingDeposit. NULL if no approved deposits exist (LEFT JOIN). (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN AffiliateID COMMENT 'Affiliate (partner) ID under which the customer was acquired (renamed from SerialID). FK to BackOffice.Affiliate. NULL for direct/organic registrations. Passthrough from Dim_Customer. (Tier 1 -- Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN IsDepositor COMMENT 'Whether the customer has ever deposited. DEFAULT=0. Updated post-load from FTD data. Passthrough from Dim_Customer. (Tier 2 -- SP_Dim_Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN IsValidCustomer COMMENT 'DWH-computed: 1 when not Internal (PlayerLevelID!=4), not label 30/26, and not CountryID=250. Used in reporting to filter out non-standard customers. Passthrough from Dim_Customer. (Tier 2 -- SP_Dim_Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POIUploaded COMMENT '1 when at least one document with SuggestedDocumentTypeID=2 (Proof of Identity) exists in BackOffice.CustomerDocument for this customer. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POIDefined COMMENT '1 when at least one document with DocumentTypeID=2 (Proof of Identity) exists in BackOffice.CustomerDocumentToDocumentType for this customer. Defined = reviewer-confirmed type (vs Uploaded = AI/user-suggested). 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POAUploaded COMMENT '1 when at least one document with SuggestedDocumentTypeID=1 (Proof of Address) exists in BackOffice.CustomerDocument. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POADefined COMMENT '1 when at least one document with DocumentTypeID=1 (Proof of Address) exists in BackOffice.CustomerDocumentToDocumentType. 0 otherwise. (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN UpdateDate COMMENT 'ETL load timestamp. GETDATE() at SP execution time. Uniform across all rows (TRUNCATE+INSERT). (Tier 2 -- SP_OPS_Fraud_Alert_Analysis)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN RealCID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN RegisteredReal SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FirstName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN LastName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Email SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN BirthDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevelID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN ClientLanguage SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN ClientCommunicationLanguage SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Country SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN CountryByIP SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN EvMatchStatusName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PlayerStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN IP SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FakeFirstNameFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FakeLastNameFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FakeEmailPatternFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN InvalidDOBFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN LanguageCountryMismatchFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN CountryMismatchFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PhoneVerifiedName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN `2FA` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FailedEVMatchFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevel3Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevel2Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLevel1Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN VerificationLeveL0Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN EVMatchStatusDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Time_L0To_L1_Min SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Time_L1To_L2_Min SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Time_L2To_L3_Min SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastLOL1Flag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastL1L2Flag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastL2L3Flag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN FastEVMatchFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN RepeatedIPAddressFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN WeightedSuspiciousScore SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_FastRegistration_FakeEmail SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_SuspiciousDomain_FakeName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_IPRepeat_FakeEmail SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Combo_FastVerification_GeoMismatch SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN ClusteredIP_RegistrationFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN GCID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN CountryTimeClustersFlag SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PlayerStatusReason SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN PlayerStatusSubReason SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN Club SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN TotalDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN AffiliateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN IsDepositor SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN IsValidCustomer SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POIUploaded SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POIDefined SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POAUploaded SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN POADefined SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ops_fraud_alert_analysis ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 13:09:40 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 9
-- Statements: 114/114 succeeded
-- ====================
