-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_Operations_Onboarding_Flow_UserKPIs
-- Generated: 2026-05-03 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_Operations_Onboarding_Flow_UserKPIs > 9.9M-row operational onboarding analytics table tracking every customer''s KYC verification journey (VL0-VL3), AML screening, electronic verification, document processing (POI/POA), and straight-through processing outcomes over a 24-month rolling window. Produced daily by `SP_Operations_Onboarding_Flow_UserKPIs` via full TRUNCATE+INSERT. | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Production Source** | BI_DB_dbo.SP_Operations_Onboarding_Flow_UserKPIs | | **Refresh** | Daily TRUNCATE+INSERT (full refresh, 24-month window) | | **Synapse Distribution** | HASH(CID) | | **Synapse Index** | CI(CID) | | **UC Target** | `_Not_Migrated` | | **UC Format** | N/A | | **UC Partitioned By** | N/A | | **UC Table Type** | N/A | ---'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CID COMMENT 'Customer ID - platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. Distribution key and clustered index. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN GCID COMMENT 'Group Customer ID - cross-product identity key linking the same person across eToro products/entities. NULL for older accounts predating GCID introduction. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN KYCFlowID COMMENT 'KYC flow type identifier from ComplianceStateDB. Resolved from current Compliance_KycFlow table, falling back to History_KycFlow if current = 0. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN KYCFlow COMMENT 'KYC flow name (e.g., Normal, Verify Before Deposit, Verify Before Trade). Resolved from Dictionary_KYCFlowType via KYCFlowID. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CountryID COMMENT 'Country of residence. Determines regulatory framework, available instruments, and leverage limits. Default=0. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CountryName COMMENT 'Full country name in English. Unique per country. (Tier 1 - Dictionary.Country)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN RiskGroupID COMMENT 'Granular country risk classification. 0=None, 1=High risk country, 2=High risk for new clients, 3=High risk FATF country, 4=Verified before deposit. (Tier 1 - Dictionary.Country)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN Region COMMENT 'Marketing region label for this country. Loaded from etoro.Dictionary.MarketingRegion.Name via JOIN on MarketingRegionID. NOT the geographic region. 22 distinct values. (Tier 2 - SP_Dictionaries_Country_DL_To_Synapse)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN MarketingRegion COMMENT 'Manual override name for the marketing region. May differ from Region (e.g., Albania: Region=ROE, MarketingRegion=CEE). (Tier 3 - Ext_Dim_Country)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DesignatedRegulation COMMENT 'Regulatory entity name governing users from this country (via Dim_Country.RegulationID -> Dim_Regulation.Name). Values: CySEC, FCA, FSA Seychelles, FinCEN+FINRA, ASIC, FSRA, MAS, etc. (Tier 1 - Dictionary.Regulation)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsRegAndVL3SameDay COMMENT '1 if customer registration (VL0) and VL3 completion occurred on the same calendar day. 0 otherwise. NULL if VL3 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL3In24HRsFromReg COMMENT '1 if customer reached VL3 within 24 hours of registration. 0 otherwise. NULL if VL3 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CountVLChangesCount COMMENT 'Total count of verification level changes recorded in BackOffice customer history for this customer. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVLChangesCountOkay COMMENT 'Flag indicating whether the count of VL changes is within the expected/acceptable range. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDCategoryVL0toVL3 COMMENT 'Categorical bucket for total VL0-to-VL3 duration: ''<=1Hour'', ''1Hour-24Hours'', ''1Day-7Days'', ''7Days-14Days'', ''14Days-30Days'', ''>30Days'', ''NotCompleted''. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL0 COMMENT '1 if customer has reached VL0 (registered). Effectively always 1 since all rows are registered customers. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL1 COMMENT '1 if customer has reached verification level 1 or above. 0 if still at VL0. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL2 COMMENT '1 if customer has reached verification level 2 or above. 0 if below VL2. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL3 COMMENT '1 if customer has reached verification level 3 (fully verified). 0 otherwise. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsFTD COMMENT 'Whether the customer has ever deposited. Mapped from Dim_Customer.IsDepositor. 1=depositor, 0=non-depositor. (Tier 2 - SP_Dim_Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL0 COMMENT 'Registration timestamp (mapped from Dim_Customer.RegisteredReal). Represents the start of the onboarding journey. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL1 COMMENT 'Timestamp when customer first reached verification level 1. Derived from the earliest History_BackOfficeCustomer record with VerificationLevelID >= 1. NULL if VL1 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL2 COMMENT 'Timestamp when customer first reached verification level 2. Derived from History_BackOfficeCustomer. NULL if VL2 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL3 COMMENT 'Timestamp when customer first reached verification level 3 (fully verified). Derived from History_BackOfficeCustomer. NULL if VL3 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_FTD COMMENT 'Date of first deposit. Mapped from Dim_Customer.FirstDepositDate. DEFAULT=''19000101'' in Dim_Customer when no deposit exists. (Tier 2 - SP_Dim_Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL0toVL1 COMMENT 'Duration in minutes from registration (VL0) to reaching VL1. DATEDIFF(MINUTE, DateTime_VL0, DateTime_VL1). NULL if VL1 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL1toVL2 COMMENT 'Duration in minutes from VL1 to VL2. DATEDIFF(MINUTE, DateTime_VL1, DateTime_VL2). NULL if VL2 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL2toVL3 COMMENT 'Duration in minutes from VL2 to VL3. DATEDIFF(MINUTE, DateTime_VL2, DateTime_VL3). NULL if VL3 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL0toVL3 COMMENT 'Duration in minutes from registration (VL0) to full verification (VL3). DATEDIFF(MINUTE, DateTime_VL0, DateTime_VL3). NULL if VL3 not reached. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_TotalHits COMMENT 'Total number of AML screening hits returned by the screening provider for this customer. NULL if no screening record exists. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_UnresolvedHits COMMENT 'Number of screening hits still unresolved (pending manual review). NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ProviderName COMMENT 'Name of the AML screening provider (e.g., WorldCheck). NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ProviderStatus COMMENT 'Provider-level screening status. NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ScreeningStatus COMMENT 'User-level screening outcome: NoMatch (clean), UnderInvestigation, Match (positive hit). NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ScreeningProcess COMMENT 'Type of screening process applied. NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ScreeningPriority COMMENT 'Priority level of the screening case. NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_UpdatedBy COMMENT 'Identifier of the person or system that last updated the screening record. NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_IsCaseResolved COMMENT '1 if the screening case has been resolved (closed). 0 if still open. NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_StartTime COMMENT 'Timestamp when the screening case was opened. NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_EndTime COMMENT 'Timestamp when the screening case was closed/resolved. NULL if case still open or no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_SLAMinutes COMMENT 'SLA duration in minutes for screening case resolution. DATEDIFF(MINUTE, US_StartTime, US_EndTime). NULL if case not resolved or no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_IsAutomatic COMMENT '1 if the screening case was resolved automatically without manual analyst intervention. 0 if manually resolved. NULL if no screening record. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_IsCountryEligible COMMENT '1 if the customer''s country is in the hardcoded list of 25 countries eligible for electronic verification. 0 otherwise. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_MatchStatusDateTime COMMENT 'Timestamp when the EV match status was recorded in BackOffice customer history. NULL if no EV process occurred. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_MatchStatusID COMMENT 'EV match status code. 0=None, 1=PartiallyVerified, 2=Verified, 3=NotVerified. Derived from History_BackOfficeCustomer. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_MatchStatus COMMENT 'Human-readable EV match status label (None, PartiallyVerified, Verified, NotVerified). Resolved via Dim_EvMatchStatus. (Tier 2 - SP_Dictionaries_DL_To_Synapse)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_DDMinutes_VL2toEVMatch COMMENT 'Duration in minutes from VL2 to EV match completion. DATEDIFF(MINUTE, DateTime_VL2, EV_MatchStatusDateTime). NULL if VL2 not reached or no EV process. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VD_HasDocuments COMMENT '1 if the customer has any uploaded verification documents (POI or POA). 0 if no documents on file. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_IsApproved COMMENT '1 if a Proof of Identity document has been approved for this customer. 0 if no approved POI. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_UploadDateTime COMMENT 'Timestamp when the POI document was uploaded by the customer. NULL if no POI document exists. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_ResponseDateTime COMMENT 'Timestamp when the POI document review response was given (approved/rejected). NULL if not yet reviewed. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_SLAMinutes COMMENT 'SLA duration in minutes for POI document review. DATEDIFF(MINUTE, POI_UploadDateTime, POI_ResponseDateTime). NULL if not yet reviewed. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_IsResponseAutomatic COMMENT '1 if the POI document was reviewed by an automated vendor (Onfido, Au10tix, Sumsub). 0 if manually reviewed by a BackOffice agent. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_HasOnlyDeclines COMMENT '1 if all POI document submissions for this customer have been declined. 0 if at least one was approved or is pending. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_CountDeclines COMMENT 'Total number of declined POI document submissions for this customer. 0 if no declines. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_IsApproved COMMENT '1 if a Proof of Address document has been approved for this customer. 0 if no approved POA. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_UploadDateTime COMMENT 'Timestamp when the POA document was uploaded by the customer. NULL if no POA document exists. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_ResponseDateTime COMMENT 'Timestamp when the POA document review response was given. NULL if not yet reviewed. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_SLAMinutes COMMENT 'SLA duration in minutes for POA document review. DATEDIFF(MINUTE, POA_UploadDateTime, POA_ResponseDateTime). NULL if not yet reviewed. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_IsResponseAutomatic COMMENT '1 if the POA document was reviewed by an automated vendor (Onfido, Au10tix, Sumsub). 0 if manually reviewed. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_HasOnlyDeclines COMMENT '1 if all POA document submissions for this customer have been declined. 0 otherwise. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_CountDeclines COMMENT 'Total number of declined POA document submissions for this customer. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EmailVerification COMMENT 'Whether the email address has been verified by clicking a confirmation link. NULL for older accounts predating this flag. Mapped from Dim_Customer.IsEmailVerified. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PhoneVerification COMMENT 'Phone verification status label: NotVerified, AutomaticallyVerified, ManualyVerified (production typo preserved), Initiated, Rejected, AbuseFlag. Resolved via Dim_PhoneVerified.PhoneVerifiedName. (Tier 1 - Dictionary.PhoneVerified)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VerificationLevelID COMMENT 'KYC verification level. Values: 0=unverified, 1=partial, 2=intermediate, 3=fully verified. Default=0. (Tier 1 - BackOffice.Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsSTP_eToro COMMENT 'Platform straight-through processing flag. 1 when ALL of: IsVL3=1, US_IsAutomatic=1, EV matched, POI_IsResponseAutomatic=1, POA_IsResponseAutomatic=1. Measures full automation of onboarding. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsSTP_User COMMENT 'User-experience straight-through processing flag. 1 when ALL of: IsVL3=1, no documents uploaded, no declines. Measures frictionless onboarding from the user perspective. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN UpdateDate COMMENT 'ETL execution timestamp. Set to GETDATE() at SP run time. Not a business date. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstAction COMMENT 'Customer''s first platform action type code. Sourced from BI_DB_First5Actions. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstDepositAmount COMMENT 'Amount of first deposit (in USD). Updated from CustomerFinanceDB FTD data with FTDRecoveryDate logic. (Tier 2 - SP_Dim_Customer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN NonVerificationReason COMMENT 'Reason why a VL2 customer has not reached VL3. CASE logic: ''Docs not Approved'', ''Missing Docs'', ''User Screening Issue'', ''Phone Not Verified'', ''Others'', ''Not Relevant''. Only meaningful for VL2 customers. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VendorPOA COMMENT 'Name of the vendor that processed the Proof of Address document (e.g., Onfido, Au10tix, Sumsub). NULL if no POA processing. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN RejectionReasonPOA COMMENT 'Rejection reason text for the POA document. NULL if POA was approved or not submitted. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VendorPOI COMMENT 'Name of the vendor that processed the Proof of Identity document. NULL if no POI processing. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN RejectionReasonPOI COMMENT 'Rejection reason text for the POI document. NULL if POI was approved or not submitted. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CurrentRegulation COMMENT 'Current regulation name for the customer (via Dim_Customer.RegulationID -> Dim_Regulation.Name). May differ from DesignatedRegulation if customer''s regulation changed after registration. (Tier 1 - Dictionary.Regulation)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PlayerStatusID COMMENT 'Compliance and trading account status. 1=Normal (97.5% of accounts); other values indicate restricted, closed, banned, or special states. Default=0. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PlayerStatusReasonID COMMENT 'Reason code for current PlayerStatusID. Provides the why behind a non-Active status. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_Manager COMMENT 'ManagerID of the BackOffice agent who reviewed the POA document. 0 or NULL if automated. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_Manager COMMENT 'ManagerID of the BackOffice agent who reviewed the POI document. 0 or NULL if automated. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN LTV COMMENT 'Customer lifetime value (Revenue8Y_LTV_New from BI_DB_LTV_BI_Actual). NULL if customer has no LTV model coverage. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DepositAttempt COMMENT '1 if the customer has attempted at least one deposit (any payment status, including declined). 0 if no deposit attempted. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstDepositAttemptDate COMMENT 'Timestamp of the customer''s first deposit attempt (MIN PaymentDate from Fact_BillingDeposit, any status). NULL if no deposit attempted. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PlayerStatusSubReasonID COMMENT 'Sub-reason code for PlayerStatus (hierarchical). Added 2022 (COINF-1989). (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstActionDate COMMENT 'Timestamp of the customer''s first platform action. Sourced from BI_DB_First5Actions. (Tier 2 - SP_Operations_Onboarding_Flow_UserKPIs)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN GCID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN KYCFlowID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN KYCFlow SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CountryID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CountryName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN RiskGroupID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN Region SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN MarketingRegion SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DesignatedRegulation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsRegAndVL3SameDay SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL3In24HRsFromReg SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CountVLChangesCount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVLChangesCountOkay SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDCategoryVL0toVL3 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL0 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL2 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsVL3 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsFTD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL0 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL2 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_VL3 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DateTime_FTD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL0toVL1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL1toVL2 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL2toVL3 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DDMinutes_VL0toVL3 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_TotalHits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_UnresolvedHits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ProviderName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ProviderStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ScreeningStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ScreeningProcess SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_ScreeningPriority SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_UpdatedBy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_IsCaseResolved SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_StartTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_EndTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_SLAMinutes SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN US_IsAutomatic SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_IsCountryEligible SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_MatchStatusDateTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_MatchStatusID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_MatchStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EV_DDMinutes_VL2toEVMatch SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VD_HasDocuments SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_IsApproved SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_UploadDateTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_ResponseDateTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_SLAMinutes SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_IsResponseAutomatic SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_HasOnlyDeclines SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_CountDeclines SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_IsApproved SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_UploadDateTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_ResponseDateTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_SLAMinutes SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_IsResponseAutomatic SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_HasOnlyDeclines SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_CountDeclines SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN EmailVerification SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PhoneVerification SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VerificationLevelID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsSTP_eToro SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN IsSTP_User SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstAction SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstDepositAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN NonVerificationReason SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VendorPOA SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN RejectionReasonPOA SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN VendorPOI SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN RejectionReasonPOI SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN CurrentRegulation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PlayerStatusID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PlayerStatusReasonID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POA_Manager SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN POI_Manager SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN LTV SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN DepositAttempt SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstDepositAttemptDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN PlayerStatusSubReasonID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_operations_onboarding_flow_userkpis ALTER COLUMN FirstActionDate SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 13:08:58 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 9
-- Statements: 172/172 succeeded
-- ====================
