-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_DDR_CID_Level
-- Generated: 2026-05-03 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_DDR_CID_Level > 174-column daily CID-level reporting table - the primary DDR (Daily Dashboard Reporting) fact table. One row per customer per day, aggregating all transaction activity, financial metrics, P&L, NOP, regulatory attributes, and lifecycle flags for every active eToro customer. Driven by SP_DDR; ~6.81M rows/day across ~1563 dates (DateID 20220101 - 20260412). The foundational source for all DDR aggregate and time-range reporting tables. | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Production Source** | DWH_dbo.Fact_SnapshotCustomer + Fact_CustomerAction + Fact_SnapshotEquity + Fact_CustomerUnrealized_PnL + BI_DB_Client_Balance_CID_Level_New + V_Liabilities + V_GermanBaFin + Function_Population_First_Time_Funded via SP_DDR | | **Refresh** | Daily (SB_Daily); DELETE+INSERT per DateID - idempotent rerun | | **S'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CID COMMENT 'Customer identifier - the universal customer key. Sourced from the UNION of Fact_CustomerAction CIDs and BI_DB_Client_Balance_CID_Level_New CIDs for @date. (Tier 2 - SP_DDR #allUsers)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DateID COMMENT 'YYYYMMDD integer representing the data date. Computed as CONVERT(int, CONVERT(varchar(8), @date, 112)). FK to DWH_dbo.Dim_Date.DateKey. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ReportDate COMMENT 'Calendar date the report is delivered - always DateID + 1 day. DATEADD(DAY,1,@date). Reports are generated for yesterday''s data, delivered today. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ReportDateID COMMENT 'YYYYMMDD int of ReportDate. CONVERT(int, CONVERT(varchar(8), DATEADD(DAY,1,@date), 112)). (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UpdateDate COMMENT 'GETDATE() captured at SP_DDR execution time. ETL run timestamp - not a business date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Regulation COMMENT 'Regulatory regime name (e.g., ''ASIC'', ''FCA'', ''CySEC''). Resolved from Fact_SnapshotCustomer.RegulationID via Dim_Regulation. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsBlocked COMMENT '1 if the customer''s account is in a blocked state, else 0. CASE WHEN PlayerStatusID NOT IN (1,3,5,7). (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsCreditReportValidCB COMMENT 'Flag indicating whether the customer''s credit report is valid in the CB system. Passthrough from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsGermanBaFin COMMENT '1 if the customer falls under German BaFin regulatory reporting scope. Derived from V_GermanBaFin LEFT JOIN. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsValidCustomer COMMENT '1 if the customer is considered valid per DWH criteria. Passthrough from Fact_SnapshotCustomer.IsValidCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN AccountType COMMENT 'Account type name (e.g., ''Real'', ''Demo''). Resolved via Dim_AccountType from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Country COMMENT 'Customer''s registered country name. Resolved via Dim_Country from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Label COMMENT 'Customer label/tier name (e.g., ''Platinum'', ''Gold''). Resolved via Dim_Label from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MifidCategory COMMENT 'MiFID II customer category (e.g., ''Retail'', ''Professional''). Resolved via Dim_MifidCategory from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PlayerLevel COMMENT 'Customer experience level (e.g., ''Beginner'', ''Advanced''). Resolved via Dim_PlayerLevel from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PlayerStatus COMMENT 'Customer account status name (e.g., ''Active'', ''Blocked''). Resolved via Dim_PlayerStatus from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Region COMMENT 'Geographic region name (e.g., ''Europe'', ''Asia Pacific''). Resolved via Dim_Region from Fact_SnapshotCustomer. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsDepositor COMMENT '1 if the customer has ever made a deposit as of @date. Passthrough from Fact_SnapshotCustomer.IsDepositor. (Tier 2 - SP_DDR #fsc2days)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Deposits COMMENT 'Total deposit amount received from the customer on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Bonus COMMENT 'Total bonus amount credited to the customer on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Compensation COMMENT 'Total compensation amount paid to/from the customer on @date across all types. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Cashouts COMMENT 'Total cashout (withdrawal) amount processed for the customer on @date (excluding redemptions). SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutsIncludingRedeem COMMENT 'Total withdrawals including redemptions on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutFee COMMENT 'Cashout/withdrawal fee charged on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN OvernightFee COMMENT 'Overnight (rollover) fee charged for holding CFD positions overnight on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationPnLAdjustments COMMENT 'Compensation classified as P&L adjustment on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TransferCoins COMMENT 'Coin transfer amount on @date (internal eToro coin movements). SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TransferCoinFees COMMENT 'Fee charged on coin transfers on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN realizedEquity COMMENT 'Realized equity movements (closed position proceeds) on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DividendsPaid COMMENT 'Dividend payments credited to the customer on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DepositsCount COMMENT 'Number of deposit transactions by the customer on @date. COUNT from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Deposited COMMENT 'FLAG: 1 if the customer made any deposit on @date, else 0. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutsCount COMMENT 'Number of cashout transactions by the customer on @date. COUNT from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositors COMMENT 'FLAG: 1 if this is the customer''s first-ever deposit (FTD event on @date), else 0. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositAmounts COMMENT 'Amount of the customer''s first-ever deposit (FTD), if the FTD occurred on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashedOut COMMENT 'FLAG: 1 if the customer made any cashout on @date, else 0. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Redeemed COMMENT 'FLAG: 1 if the customer redeemed eToro coins or balance on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetDeposit COMMENT 'Net deposit = Deposits - Cashouts for @date. (Tier 2 - SP_DDR #CIDAgg)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FTDAmountEver COMMENT 'Customer''s lifetime first time deposit amount (not necessarily on @date). SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutsAdjusted COMMENT 'Cashout amount adjusted for reversals and redemptions. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN AdjustedNetDeposit COMMENT 'NetDeposit adjusted for cashout reversals and redemptions. Deposits - CashoutsAdjusted. (Tier 2 - SP_DDR #CIDAgg)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Redeposit COMMENT 'FLAG or amount for subsequent deposits (non-FTD deposits). Customer already deposited before @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashedOutDefinition2 COMMENT 'FLAG: alternative cashout definition used for specific regulatory or reporting requirements. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DormantFee COMMENT 'Dormant account maintenance fee charged on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationRAFInvited COMMENT 'RAF (Refer-a-Friend) compensation received by invited customer on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationRAFInviting COMMENT 'RAF compensation paid to the inviting customer on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationOther COMMENT 'Compensation not classified under RAF, PI, or affiliate categories on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationPIWithCO COMMENT 'Popular Investor program compensation paid with a cashout event on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationPINoCO COMMENT 'Popular Investor program compensation paid without cashout on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationToAffiliateWithCO COMMENT 'Affiliate compensation paid with a cashout event on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationToAffiliateNoCO COMMENT 'Affiliate compensation paid without cashout on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationRAFInvitedInviting COMMENT 'Combined RAF invited + inviting compensation total on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN OtherCompensationAmount COMMENT 'Misc compensation amounts not captured in standard sub-categories. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalLiability COMMENT 'Total liability owed to the customer per V_Liabilities. LEFT JOIN from #liabilities. (Tier 2 - SP_DDR #liabilities)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InProcessCashout COMMENT 'Pending cashout amount not yet settled, from BI_DB_Client_Balance_CID_Level_New. Included in Equity computation. (Tier 2 - SP_DDR #ClientBalance)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Equity COMMENT 'Total customer equity snapshot: PositionPNL + InProcessCashout + PositionAmount + TotalCash + StockOrders. (Tier 2 - SP_DDR #CIDAgg)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN RealizedEquityCalculated COMMENT 'Realized equity computed from equity movements, distinct from the raw realizedEquity passthrough. (Tier 2 - SP_DDR #CIDAgg)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Credit COMMENT 'Non-withdrawable credit balance from BI_DB_Client_Balance_CID_Level_New. (Tier 2 - SP_DDR #ClientBalance)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstTimeFunded COMMENT '1 if the customer has completed the 5-criteria FTF milestone (FTD + Verified + Trade/IOB/Options) as of @date, else 0. Sourced from Function_Population_First_Time_Funded(). (Tier 2 - SP_DDR #FTF)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Funded_New_Def COMMENT '1 if Equity > 0 AND VerificationLevelID = 3 AND FirstActionType != ''NoAction'', else 0. Alternative funded-customer definition. (Tier 2 - SP_DDR #CIDAgg)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FTDCurrentYear COMMENT '1 if the customer''s first time deposit occurred in the current calendar year (YEAR(FirstDepositDate) = YEAR(@date)), else 0. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPCrypto COMMENT 'Net Open Position value in real crypto assets on @dateID snapshot. SUM from Fact_SnapshotEquity via #fse2days. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPCryptoCFD COMMENT 'Net Open Position value in crypto CFD positions on @dateID. SUM from Fact_SnapshotEquity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPStocks COMMENT 'Net Open Position value in real stocks on @dateID. SUM from Fact_SnapshotEquity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPStocksCFD COMMENT 'Net Open Position value in CFD stock positions on @dateID. SUM from Fact_SnapshotEquity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalRealCryptoLoan COMMENT 'Total loan value against real crypto holdings on @dateID. SUM from Fact_SnapshotEquity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PositionPNL COMMENT 'Total unrealized P&L across all open positions on @dateID. SUM from Fact_SnapshotEquity. Component of Equity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOP COMMENT 'Total Net Open Position value (all asset types combined) on @dateID. SUM from Fact_SnapshotEquity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PositionAmount COMMENT 'Total amount invested in open positions on @dateID. SUM from Fact_SnapshotEquity. Component of Equity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StockOrders COMMENT 'Value of pending/in-flight stock orders on @date. From BI_DB_Client_Balance_CID_Level_New. Component of Equity. (Tier 2 - SP_DDR #ClientBalance)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN actualNWA COMMENT 'Net Worth Adjustment - regulatory capital adjustment on @dateID. SUM from Fact_SnapshotEquity. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnL COMMENT 'Total unrealized P&L snapshot for @dateID from Fact_CustomerUnrealized_PnL. (Tier 2 - SP_DDR #customerUnrealizedNewMetrics)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChange COMMENT 'Daily change in total unrealized P&L (@dateID minus @datePrevID) from Fact_CustomerUnrealized_PnL. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChangeCFD COMMENT 'Daily change in CFD unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChangeCryptoReal COMMENT 'Daily change in real crypto unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChangeStocksReal COMMENT 'Daily change in real stocks unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PnlChange COMMENT 'Day-over-day change in total unrealized P&L per CID (all positions). (Tier 2 - SP_DDR #customerUnrealizedNewMetrics)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyPnlChange COMMENT 'Day-over-day change in copy-trading unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksPnlChange COMMENT 'Day-over-day change in CFD stocks unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoPnLChange COMMENT 'Day-over-day change in crypto unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ManualsPnlChange COMMENT 'Day-over-day change in manual-trading unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksRealPnlChange COMMENT 'Day-over-day change in real stocks unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoRealPnlChange COMMENT 'Day-over-day change in real crypto unrealized P&L. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalCommission COMMENT 'Total close-side spread/commission charged across all position types on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullTotalCommission COMMENT 'Full commission including both open and close sides across all position types. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ManualCommission COMMENT 'Close-side commission from manually opened positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyCommission COMMENT 'Commission from copy-traded positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CurrenciesCommission COMMENT 'Commission from FX/currency positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CommoditiesCommission COMMENT 'Commission from commodity positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IndicesCommission COMMENT 'Commission from index CFD positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksOnlyCommission COMMENT 'Commission from CFD stock positions only. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ETFCommission COMMENT 'Commission from ETF positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksAndETFsCommission COMMENT 'Combined commission from CFD stocks + ETFs. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN RealStocksCommission COMMENT 'Commission from real (non-CFD) stock trades. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoCommission COMMENT 'Commission from crypto positions (CFD + real). (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PnLAdjustment COMMENT 'P&L adjustment actions applied to the customer on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullManualCommission COMMENT 'Full open+close commission from manual positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullCopyCommission COMMENT 'Full open+close commission from copy positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullStocksCommission COMMENT 'Full commission from stocks positions (open+close). (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullCryptoCommission COMMENT 'Full commission from crypto positions (open+close). (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Revenue COMMENT 'Total company revenue from this customer: FullTotalCommissionOnOpen + OvernightFee + CashoutFee + FullCommissionCloseAdjustment + TransferCoinFees. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullTotalCommissionFromBreakdown COMMENT 'FullTotalCommission cross-validated from position-level breakdown tables. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalCommissionFromBreakdown COMMENT 'TotalCommission cross-validated from position-level breakdown tables. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalNetProfit COMMENT 'Total net profit from closed positions on @date across all types. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ManualNetProfit COMMENT 'Net profit from manually opened positions closed on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyNetProfit COMMENT 'Net profit from copy-traded positions closed on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksNetProfit COMMENT 'Net profit from CFD stock positions closed on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksRealNetProfit COMMENT 'Net profit from real (non-CFD) stock positions closed on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoNetProfit COMMENT 'Net profit from CFD crypto positions closed on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoRealNetProfit COMMENT 'Net profit from real (non-CFD) crypto positions closed on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnL COMMENT 'Total customer net profit from closed positions (all types). SUM from Fact_CustomerAction. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLStocks COMMENT 'Customer net profit from stocks positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLCopy COMMENT 'Customer net profit from copy-traded positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLManual COMMENT 'Customer net profit from manual positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLCrypto COMMENT 'Customer net profit from crypto positions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLStocksReal COMMENT 'Customer net profit from real stocks. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLCryptoReal COMMENT 'Customer net profit from real crypto. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerZeroPnL COMMENT 'FLAG: 1 if CustomerPnL = 0 (customer broke even exactly). (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerZeroPnLAdjusted COMMENT 'FLAG: 1 if CustomerPnLAdjusted = 0. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerCopyZeroPnL COMMENT 'FLAG: 1 if CustomerPnLCopy = 0. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerStocksZeroPnL COMMENT 'FLAG: 1 if CustomerPnLStocks = 0. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLAdjusted COMMENT 'CustomerPnL adjusted for P&L adjustment actions. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StockTraderWithProfit COMMENT 'FLAG: 1 if the customer is a stock trader with positive net profit on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StockTraderWithLoss COMMENT 'FLAG: 1 if the customer is a stock trader with negative net profit on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyTraderWithProfit COMMENT 'FLAG: 1 if the customer is a copy trader with positive net profit on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyTraderWithLoss COMMENT 'FLAG: 1 if the customer is a copy trader with negative net profit on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TraderWithProfit COMMENT 'FLAG: 1 if the customer (any type) had positive net profit on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TraderWithLoss COMMENT 'FLAG: 1 if the customer (any type) had negative net profit on @date. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewTrades COMMENT 'Count of new position opens by the customer on @date. From Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NumberOfClosedPositions COMMENT 'Count of positions closed by the customer on @date. From Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN EditStoplossAmounts COMMENT 'Sum of stop-loss edit amounts on @date. From Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalInvestmentAmountInNewTrades COMMENT 'Total amount invested in new positions opened on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN LoggedIn COMMENT 'FLAG: 1 if the customer logged in on @date. From Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DepositorsLoggedIn COMMENT 'FLAG: 1 if the customer is a depositor who also logged in on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Registrations COMMENT 'FLAG: 1 if the customer registered on @date (new registration event). (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN EngagedInFeed COMMENT 'FLAG: 1 if the customer had any social news feed engagement (post, comment, like) on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveCopy COMMENT 'FLAG: 1 if the customer had active copy relationships on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveManualStocksETFs COMMENT 'FLAG: 1 if the customer had open manual stocks/ETF positions on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveManualFXCommoditiesIndices COMMENT 'FLAG: 1 if the customer had open manual FX, commodities, or indices positions on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveManualCrypto COMMENT 'FLAG: 1 if the customer had open manual crypto positions on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveOpen COMMENT 'FLAG: 1 if the customer had any open position (manual or copy) on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveOpenManual COMMENT 'FLAG: 1 if the customer had any open manual position on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveFunded COMMENT 'FLAG: 1 if the customer had positive account balance on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveTrader COMMENT 'FLAG: 1 if the customer opened or closed any position on @date. (Tier 2 - SP_DDR #tradersActive)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetNewTrades COMMENT 'Net trades = NewTrades - NumberOfClosedPositions on @date. (Tier 2 - SP_DDR #CIDAgg)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInManualTradeing COMMENT 'Amount invested in manually opened trades on @date (note: column name has typo "Tradeing"). (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInStocksManual COMMENT 'Amount invested in manual stocks positions on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInCryptoManual COMMENT 'Amount invested in manual crypto positions on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInCryptoTRS COMMENT 'Amount invested in crypto TRS (Total Return Swap) positions on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN AccountBalanceToMirrorAmount COMMENT 'Amount moved from account balance into a copy (mirror) relationship on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MirrorAmountToAccountBalance COMMENT 'Amount returned from a copy relationship back to account balance on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyAmount COMMENT 'Total capital allocated to new copy relationships started on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StopCopyAmount COMMENT 'Total capital withdrawn from copy relationships stopped on @date. SUM from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyActions COMMENT 'Count of new copy relationships initiated on @date. COUNT from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StopCopyActions COMMENT 'Count of copy relationships terminated on @date. COUNT from Fact_CustomerAction. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyNetActions COMMENT 'Net copy actions = NewCopyActions - StopCopyActions on @date. (Tier 2 - SP_DDR #CIDAgg)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInCopyIncludingCash COMMENT 'Total amount allocated to copy trading including idle cash held in copy portfolios. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyUniqueUsers COMMENT 'Count of distinct popular investors this customer started copying on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetMoneyIntoExistingCopy COMMENT 'Net money added to or removed from already-existing copy relationships on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MoneyIntoExistingCopy COMMENT 'Gross money added to existing copy relationships on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetMoneyIntoCopy COMMENT 'Net total money flow into all copy relationships (new + existing) on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PublishPost COMMENT 'Count of news feed posts published by the customer on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PublishComment COMMENT 'Count of comments published by the customer on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PublishLike COMMENT 'Count of likes given by the customer on @date. (Tier 2 - SP_DDR #fca)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositDate COMMENT 'Calendar date of the customer''s first-ever deposit. From #FirstActionsFinal. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositDateID COMMENT 'YYYYMMDD int of the customer''s first-ever deposit date. From #FirstActionsFinal. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PositionID COMMENT 'Position ID of the customer''s first trade action. From #FirstActionsFinal. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActionTypeID COMMENT 'ActionTypeID of the customer''s first ever recorded action. From #FirstActionsFinal. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstActionDateID COMMENT 'YYYYMMDD int of the customer''s first-ever action date. From #FirstActionsFinal. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InstrumentTypeID COMMENT 'InstrumentTypeID of the customer''s first position (NULL if first action was not a trade). From #FirstActionsFinal. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MirrorID COMMENT 'MirrorID of the customer''s first copy relationship (NULL if first action was manual). From #FirstActionsFinal. (Tier 2 - SP_DDR)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstActionType COMMENT 'Label for the customer''s first-ever action type: ''Copy'', ''Manual'', ''NoAction'', etc. From #FirstActionsFinal. (Tier 2 - SP_DDR)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ReportDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ReportDateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Regulation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsBlocked SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsCreditReportValidCB SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsGermanBaFin SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsValidCustomer SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN AccountType SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Country SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Label SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MifidCategory SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PlayerLevel SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PlayerStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Region SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IsDepositor SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Deposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Bonus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Compensation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Cashouts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutsIncludingRedeem SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN OvernightFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationPnLAdjustments SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TransferCoins SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TransferCoinFees SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN realizedEquity SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DividendsPaid SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DepositsCount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Deposited SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutsCount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositors SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositAmounts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashedOut SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Redeemed SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetDeposit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FTDAmountEver SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashoutsAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN AdjustedNetDeposit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Redeposit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CashedOutDefinition2 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DormantFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationRAFInvited SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationRAFInviting SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationOther SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationPIWithCO SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationPINoCO SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationToAffiliateWithCO SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationToAffiliateNoCO SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CompensationRAFInvitedInviting SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN OtherCompensationAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalLiability SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InProcessCashout SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Equity SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN RealizedEquityCalculated SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Credit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstTimeFunded SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Funded_New_Def SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FTDCurrentYear SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPCrypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPCryptoCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPStocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOPStocksCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalRealCryptoLoan SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PositionPNL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NOP SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PositionAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StockOrders SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN actualNWA SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChangeCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChangeCryptoReal SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN UnrealizedPnLChangeStocksReal SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoPnLChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ManualsPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksRealPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoRealPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullTotalCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ManualCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CurrenciesCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CommoditiesCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN IndicesCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksOnlyCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ETFCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksAndETFsCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN RealStocksCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PnLAdjustment SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullManualCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullCopyCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullStocksCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullCryptoCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Revenue SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FullTotalCommissionFromBreakdown SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalCommissionFromBreakdown SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalNetProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ManualNetProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyNetProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksNetProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StocksRealNetProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoNetProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CryptoRealNetProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLStocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLCrypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLStocksReal SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLCryptoReal SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerZeroPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerZeroPnLAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerCopyZeroPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerStocksZeroPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CustomerPnLAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StockTraderWithProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StockTraderWithLoss SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyTraderWithProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN CopyTraderWithLoss SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TraderWithProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TraderWithLoss SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewTrades SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NumberOfClosedPositions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN EditStoplossAmounts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN TotalInvestmentAmountInNewTrades SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN LoggedIn SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN DepositorsLoggedIn SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN Registrations SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN EngagedInFeed SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveManualStocksETFs SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveManualFXCommoditiesIndices SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveManualCrypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveOpen SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveOpenManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveFunded SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActiveTrader SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetNewTrades SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInManualTradeing SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInStocksManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInCryptoManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInCryptoTRS SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN AccountBalanceToMirrorAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MirrorAmountToAccountBalance SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StopCopyAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyActions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN StopCopyActions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyNetActions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InvestedInCopyIncludingCash SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NewCopyUniqueUsers SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetMoneyIntoExistingCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MoneyIntoExistingCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN NetMoneyIntoCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PublishPost SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PublishComment SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PublishLike SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstDepositDateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN PositionID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN ActionTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstActionDateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN InstrumentTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN MirrorID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_cid_level ALTER COLUMN FirstActionType SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 12:44:51 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 9
-- Statements: 346/346 succeeded
-- ====================
