-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_DDR_Daily_Aggregated
-- Generated: 2026-05-07 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_DDR_Daily_Aggregated > 137-column daily DDR rollup. One row per (DateID × dimension-tuple) - `SP_DDR_Aggregated @date` runs after `SP_DDR` and aggregates `BI_DB_DDR_CID_Level` along **last-day-of-period attributes** (Regulation, Country, MifidCategory, PlayerLevel, PlayerStatus, FirstActionType, Region, Label, plus 4 IsX flags). Designed for Tableau real-time slicing-and-dicing without losing unique-user counts. Author: Guy Manova (2020-12-09). Refresh contains rolling week / month / quarter / year FTD flags; trades small accuracy in slice-and-dice unique counts for query performance (CID-level table is too wide for Tableau direct). | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table - daily DDR aggregate | | **Production Source** | `BI_DB_dbo.BI_DB_DDR_CID_Level` (per-CID per-day) + `Dim_Customer` (FirstDepositAmount). Writer SP'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DateID COMMENT 'Date encoded as YYYYMMDD - the data date (joins to `Dim_Date.DateKey`). (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Regulation COMMENT 'Regulatory entity at the customer''s last-day attribute (`''CySEC''`, `''FCA''`, `''ASIC & GAML''`, ...). Pinned per section 2.1. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsBlocked COMMENT '1 if the customer''s account was in a blocked state on @date (PlayerStatusID NOT IN (1,3,5,7)). Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsCreditReportValidCB COMMENT 'Financial-customer flag for Client_Balance reports (CB = Client_Balance, NOT CreditBureau). Last-day attribute, used for FCA RTS24 / regulatory eligibility filters. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsGermanBaFin COMMENT '1 if the customer falls under German BaFin regulation. Pinned per section 2.1. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsValidCustomer COMMENT '1 if the customer is in valid (KYC-approved, not test/internal) state. Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN MifidCategory COMMENT 'MiFID II categorisation (`''Retail''`, `''Professional''`, `''Eligible Counterparty''`). Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PlayerLevel COMMENT 'Customer tier label (`''Silver''`, `''Gold''`, `''Platinum''`, `''Platinum+''`, `''Diamond''`, `''Club''`, ...). Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PlayerStatus COMMENT 'Account-status label (`''Active''`, `''Frozen''`, `''Suspended''`, `''Closed''`, ...). Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstActionType COMMENT 'Customer''s first-action type label across history (`''Trade''`, `''Deposit''`, `''Login''`, ...). Repaired by `SP_DDR_Fix_FirstAction`. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Region COMMENT 'eToro marketing region label. Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Country COMMENT 'Customer country (registration). Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Label COMMENT 'Marketing/label segment (`''eToro''`, `''partner-X''`, ...). Last-day attribute. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CountUsers COMMENT 'Distinct CID count for this dimension tuple on @date. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Deposits COMMENT 'Total deposit amount (USD) for the tuple on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Bonus COMMENT 'Total bonus amount credited to customers in the tuple on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Compensation COMMENT 'Total compensation amount credited (sum of all 11 compensation sub-categories - see CID_Level wiki). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Cashouts COMMENT 'Total cashout amount (USD) requested/processed on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutsIncludingRedeem COMMENT 'Total cashout amount **including** redeem-flagged cashouts. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutFee COMMENT 'Cashout fee revenue charged on the tuple on @date (excludes redeem). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN OvernightFee COMMENT 'Overnight (rollover) fee revenue from open-position holding. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CompensationPnLAdjustments COMMENT 'Compensation entries that affect customer P&L (vs. credits that don''t). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TransferCoins COMMENT 'Total transfer-coin / redeem amounts. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TransferCoinFees COMMENT 'Transfer-coin / redeem fee revenue. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN realizedEquity COMMENT 'Realized equity component (lowercase = legacy naming). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DividendsPaid COMMENT 'Dividend payouts to customers (pass-through, not eToro revenue). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalLiability COMMENT 'Total customer-side liability (eToro''s obligation to customers). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InProcessCashout COMMENT 'Cashouts in-flight (requested but not yet settled). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPCrypto COMMENT 'NOP (Net Open Position) - direct crypto holdings. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPCryptoCFD COMMENT 'NOP - crypto CFD positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPStocks COMMENT 'NOP - direct stock holdings. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPStocksCFD COMMENT 'NOP - stock CFD positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalRealCryptoLoan COMMENT 'Total real-crypto loan amount across the tuple. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PositionPNL COMMENT 'Open-position P&L (mark-to-market). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOP COMMENT 'Total NOP (sum across asset classes). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActualNWA COMMENT 'Actual Net Withdrawable Amount - funds the customer can actually cash out. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN UnrealizedPnLChange COMMENT 'Day-over-day diff of unrealized P&L from `Fact_CustomerUnrealized_PnL`. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DepositsCount COMMENT 'Number of deposit transactions on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Deposited COMMENT 'Number of customers who deposited on @date (unique). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutsCount COMMENT 'Number of cashout transactions on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutsAdjusted COMMENT 'Cashouts adjusted for accounting reconciliation. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewTrades COMMENT 'Number of new trades opened on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NumberOfClosedPositions COMMENT 'Number of positions closed on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN EditStoplossAmounts COMMENT 'Total stop-loss-edit amount (sum). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalInvestmentAmountInNewTrades COMMENT 'Total invested capital across NewTrades. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstDepositors COMMENT 'Number of FTD customers on @date (= number of unique CIDs whose first deposit fell on @date). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN LoggedIn COMMENT 'Number of customers who logged in on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstDepositAmounts COMMENT 'Total amount across all FTDs on @date (joined from `Dim_Customer.FirstDepositAmount`). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Registrations COMMENT 'Number of new customer registrations on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashedOut COMMENT 'Number of customers who cashed out on @date (unique). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CompensationRAFInvitedInviting COMMENT 'Refer-A-Friend compensation paid (combined invited + inviting). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN AccountBalanceToMirrorAmount COMMENT 'Sum of customer account-balance amounts that flowed into Copy/Mirror trades. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyAmount COMMENT 'Total amount allocated to new Copy/Mirror positions on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyActions COMMENT 'Number of new Copy/Mirror open actions on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PublishPost COMMENT 'Number of social posts published on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PublishComment COMMENT 'Number of social comments. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PublishLike COMMENT 'Number of social likes. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN EngagedInFeed COMMENT 'Customers who engaged in the social feed (unique). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalCommission COMMENT 'Total commission revenue (post-discount, the canonical KPI). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullTotalCommission COMMENT 'Total commission revenue (pre-discount, gross). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ManualCommission COMMENT 'Commission from manually-opened trades (post-discount). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyCommission COMMENT 'Commission from Copy/Mirror trades (post-discount). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StocksOnlyCommission COMMENT 'Commission on stocks (excluding ETFs). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ETFCommission COMMENT 'Commission on ETFs. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StocksAndETFsCommission COMMENT 'Commission on stocks + ETFs combined. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CurrenciesCommission COMMENT 'Commission on currency (FX) positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CommoditiesCommission COMMENT 'Commission on commodity positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IndicesCommission COMMENT 'Commission on index positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CryptoCommission COMMENT 'Commission on crypto positions (post-discount). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PnLAdjustment COMMENT 'P&L adjustment entries (post-trade reconciliation). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullManualCommission COMMENT 'Manual-trade commission (pre-discount, gross). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullCopyCommission COMMENT 'Copy/Mirror commission (pre-discount, gross). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullStocksCommission COMMENT 'Stocks commission (pre-discount, gross). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullCryptoCommission COMMENT 'Crypto commission (pre-discount, gross). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PnlChange COMMENT 'Total day-over-day P&L change across all customers in the tuple. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyPnlChange COMMENT 'Day-over-day P&L change attributable to Copy/Mirror trades. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StocksPnlChange COMMENT 'Day-over-day P&L change on stock positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CryptoPnlChange COMMENT 'Day-over-day P&L change on crypto positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ManualsPnlChange COMMENT 'Day-over-day P&L change on manual (non-Copy) trades. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveCopy COMMENT 'Customers active in Copy/Mirror on @date (unique count). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveManualStocksETFs COMMENT 'Customers active in manual stocks/ETF trades. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveManualFXCommoditiesIndices COMMENT 'Customers active in manual FX/commodities/indices. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveManualCrypto COMMENT 'Customers active in manual crypto trades. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveOpen COMMENT 'Customers with any open position on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveOpenManual COMMENT 'Customers with an open manual (non-Copy) position. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveFunded COMMENT 'Active **and** funded customers. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveTrader COMMENT 'Active trader customers (any new trade today). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Revenue COMMENT 'Composite revenue = TotalCommission + OvernightFee + CashoutFee + TransferCoinFees (canonical Revenue formula in SP_DDR_Aggregated). (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Equity COMMENT 'Composite Equity figure (5-component sum - see CID_Level wiki section 2.X). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetNewTrades COMMENT 'NewTrades net of partial-close split duplication. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetDeposit COMMENT 'Deposits - Cashouts. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN AdjustedNetDeposit COMMENT 'NetDeposit adjusted for compensation/PnL adjustments. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN OtherCompensationAmount COMMENT 'Compensation outside of `Compensation` category bucket. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInManualTradeing COMMENT 'Total invested capital in manual trades (typo `Tradeing` is in the source). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN RealizedEquityCalculated COMMENT 'Computed realized-equity value (vs the snapshot-derived `realizedEquity`). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyNetActions COMMENT 'NewCopyActions net of stop-copy actions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyUniqueUsers COMMENT 'Distinct customers performing a new Copy action on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInStocksManual COMMENT 'Capital invested in stock manual positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInCryptoManual COMMENT 'Capital invested in crypto manual positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInCopyIncludingCash COMMENT 'Capital invested in Copy/Mirror including cash component. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetMoneyIntoCopy COMMENT 'Net money flow into Copy (NewCopyAmount - exits). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetMoneyIntoExistingCopy COMMENT 'Net money flow into already-existing Copy positions (top-ups - exits). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Redeposit COMMENT 'Repeat-deposit amount from already-funded customers. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DepositorsLoggedIn COMMENT 'Depositor customers who logged in on @date (unique). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnL COMMENT 'Customer-side P&L total (negative for eToro losses, positive for eToro revenue from CFD spread). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLStocks COMMENT 'Customer P&L on stock positions. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLCopy COMMENT 'Customer P&L on Copy/Mirror. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLManual COMMENT 'Customer P&L on manual (non-Copy) trades. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLCrypto COMMENT 'Customer P&L on crypto. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLStocksReal COMMENT 'Customer P&L on direct (real) stock holdings (vs CFD). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLCryptoReal COMMENT 'Customer P&L on direct (real) crypto holdings. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullTotalCommissionFromBreakdown COMMENT 'Total gross commission re-summed from the sub-category breakdowns (sanity check vs FullTotalCommission). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalCommissionFromBreakdown COMMENT 'Total post-discount commission re-summed from the sub-category breakdowns. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN UnrealizedPnL COMMENT 'Unrealized P&L total from open positions on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerZeroPnL COMMENT 'Number of customers with zero P&L (unique flag). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerZeroPnLAdjusted COMMENT 'Zero-P&L customer count adjusted for rounding bands. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerCopyZeroPnL COMMENT 'Customers with zero P&L on Copy. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerStocksZeroPnL COMMENT 'Customers with zero P&L on stocks. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLAdjusted COMMENT 'Customer P&L adjusted for compensation/PnL-adjustment entries. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Redeemed COMMENT 'Total redemption amount on @date. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashedOutDefinition2 COMMENT 'Alternate "Cashed Out" definition (definition-2 - typically excludes a class of cashouts). (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StockTradersWithProfit COMMENT 'Unique stock traders with positive P&L on @date. (Tier 1 - profitable-traders framework, 2021-02-15)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StockTradersWithLoss COMMENT 'Unique stock traders with negative P&L. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyTradersWithProfit COMMENT 'Unique Copy traders with positive P&L. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyTradersWithLoss COMMENT 'Unique Copy traders with negative P&L. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TradersWithProfit COMMENT 'Unique traders (any asset class) with positive P&L. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TradersWithLoss COMMENT 'Unique traders with negative P&L. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN MoneyIntoExistingCopy COMMENT 'Total amount added to already-existing Copy positions (top-ups). Counterpart to NewCopyAmount. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Credit COMMENT 'Customer-credit-account credit amounts. (Tier 2)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN UpdateDate COMMENT 'ETL load timestamp (`GETDATE()` at SP_DDR_Aggregated run). (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstTimeFunded COMMENT '1 if customer''s FTD fell on @date - see section 2.2. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Funded_New_Def COMMENT '1 per new 5-criteria funded definition (2025-02-09) - see CID_Level wiki section 2.4. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FTDCurrentYear COMMENT '1 if customer''s FTD falls within the year-to-date window of @date. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ReportDate COMMENT 'Report **delivery** date = @date + 1 day (reports delivered next morning for prior-day data). (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ReportDateID COMMENT 'YYYYMMDD form of `ReportDate`. CLUSTERED-index participant. (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DormantFee COMMENT 'Dormant-fee revenue charged to inactive accounts on @date (added late - see `revenue-and-fees` skill). (Tier 1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInCryptoTRS COMMENT 'Capital invested in crypto via TRS (Total Return Swap) contracts. Added 2022-01-24. (Tier 1)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Regulation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsBlocked SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsCreditReportValidCB SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsGermanBaFin SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IsValidCustomer SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN MifidCategory SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PlayerLevel SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PlayerStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstActionType SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Region SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Country SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Label SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CountUsers SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Deposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Bonus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Compensation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Cashouts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutsIncludingRedeem SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN OvernightFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CompensationPnLAdjustments SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TransferCoins SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TransferCoinFees SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN realizedEquity SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DividendsPaid SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalLiability SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InProcessCashout SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPCrypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPCryptoCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPStocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOPStocksCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalRealCryptoLoan SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PositionPNL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NOP SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActualNWA SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN UnrealizedPnLChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DepositsCount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Deposited SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutsCount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashoutsAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewTrades SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NumberOfClosedPositions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN EditStoplossAmounts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalInvestmentAmountInNewTrades SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstDepositors SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN LoggedIn SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstDepositAmounts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Registrations SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashedOut SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CompensationRAFInvitedInviting SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN AccountBalanceToMirrorAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyActions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PublishPost SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PublishComment SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PublishLike SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN EngagedInFeed SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullTotalCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ManualCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StocksOnlyCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ETFCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StocksAndETFsCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CurrenciesCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CommoditiesCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN IndicesCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CryptoCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PnLAdjustment SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullManualCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullCopyCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullStocksCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullCryptoCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN PnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StocksPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CryptoPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ManualsPnlChange SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveManualStocksETFs SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveManualFXCommoditiesIndices SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveManualCrypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveOpen SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveOpenManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveFunded SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ActiveTrader SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Revenue SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Equity SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetNewTrades SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetDeposit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN AdjustedNetDeposit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN OtherCompensationAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInManualTradeing SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN RealizedEquityCalculated SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyNetActions SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NewCopyUniqueUsers SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInStocksManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInCryptoManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInCopyIncludingCash SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetMoneyIntoCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN NetMoneyIntoExistingCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Redeposit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DepositorsLoggedIn SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLStocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLManual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLCrypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLStocksReal SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLCryptoReal SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FullTotalCommissionFromBreakdown SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TotalCommissionFromBreakdown SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN UnrealizedPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerZeroPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerZeroPnLAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerCopyZeroPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerStocksZeroPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CustomerPnLAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Redeemed SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CashedOutDefinition2 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StockTradersWithProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN StockTradersWithLoss SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyTradersWithProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN CopyTradersWithLoss SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TradersWithProfit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN TradersWithLoss SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN MoneyIntoExistingCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Credit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FirstTimeFunded SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN Funded_New_Def SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN FTDCurrentYear SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ReportDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN ReportDateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN DormantFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_daily_aggregated ALTER COLUMN InvestedInCryptoTRS SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-07 10:46:06 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 13
-- Statements: 276/276 succeeded
-- ====================
