-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_CID_DailyPanel_FullData
-- Generated: 2026-05-07 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_CID_DailyPanel_FullData > Daily per-depositor customer panel - the broadest customer panel in BI_DB_dbo, covering all eToro depositors with 183 columns of daily activity, revenue, PnL, equity, copy trading, running accumulators, and demographic attributes. One row per depositor per day. 64.5M rows per daily date as of April 2026; data from 2018-01-01 to present. | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Production Source** | Multi-source ETL (see Section 4) | | **Refresh** | Daily - DELETE WHERE DateID = @startDateINT + INSERT (SP_CID_DailyPanel_FullData, SB_Daily, Priority 0) | | | | | **Synapse Distribution** | HASH(CID) | | **Synapse Index** | CLUSTERED INDEX (DateID ASC) | | **Partition** | RANGE LEFT on DateID, daily partitions 20180101 - 20260531 | | | | | **UC Target** | `_Not_Migrated` | | **UC Format** | N/'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN CID COMMENT 'eToro customer ID (Real CID). Only depositors (IsDepositor=1) present. FK to DWH_dbo.Dim_Customer.RealCID';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN DateID COMMENT 'Partition key: date in YYYYMMDD format. One row per CID per day';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Month COMMENT 'YYYYMM of this row''s date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveDate COMMENT 'Calendar date of this row';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Seniority COMMENT 'Months since customer''s first deposit (FTDdate) as of start of the current month';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Seniority_Seg COMMENT 'Seniority bucket label: ''<1month'', ''1-2month'', ''<2-3month'', ... ''<11-12month'', ''12+month''';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Reg_Month COMMENT 'YYYYMM of customer registration';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN RegDate COMMENT 'Customer registration date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsReg_ThisD COMMENT '1 if customer registered on this specific date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FTD_Month COMMENT 'YYYYMM of customer''s first-time deposit (FTD)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FTDdate COMMENT 'Customer''s first-time deposit date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsFTD_ThisD COMMENT '1 if customer made their first deposit on this specific date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FTDA COMMENT 'First-time deposit amount (USD)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Region COMMENT 'Geographic region label (e.g., ''French'', ''Arabic GCC'', ''Australia'', ''North Europe'')';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewMarketingRegion COMMENT 'Marketing team region classification (e.g., ''Arabic'', ''French'', ''Norway'', ''ROW'')';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Country COMMENT 'Customer''s country name at snapshot date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Channel COMMENT 'Acquisition channel (e.g., ''Direct'', ''Affiliate'', ''SEM'', ''SEO'', ''Friend Referral'', ''Mobile Acquisition'')';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN SubChannel COMMENT 'Acquisition sub-channel detail';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AffiliateID COMMENT 'Affiliate serial ID for affiliate-acquired customers; NULL for direct/organic';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FirstAction COMMENT 'Deprecated - always NULL. Originally planned first action type';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FirstInstrument COMMENT 'Deprecated - always NULL. Originally planned first instrument traded';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN V2_Complete COMMENT '1 if customer has completed verification level 2 as of this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN V3_Complete COMMENT '1 if customer has completed full KYC (verification level 3) as of this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN LastPosOpenDate COMMENT 'Most recent date customer opened a position (ActionTypeID IN 1,2), max of today vs. yesterday''s carry-forward';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN LastLoggedIn COMMENT 'Most recent login date (ActionTypeID=14), max of today vs. yesterday''s carry-forward';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsPro COMMENT '1 if customer is classified as professional client (MifidCategorizationID IN 2,3 in Fact_SnapshotCustomer)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsOTD COMMENT '1 if customer has made exactly one prior deposit (One Trade Done)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Daily_Classification COMMENT 'Customer segment label (e.g., ''Traders'', ''Crypto''). Set by separate SP_CID_DailyPanel_UpdateCluster SP. As of 2026 all rows are empty string - appears non-operational post-Synapse migration';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Club COMMENT 'Loyalty tier at EOD: ''LowBronze'', ''HighBronze'', ''Silver'', ''Gold'', ''Platinum'', ''Platinum Plus'', ''Diamond''';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Regulation COMMENT 'Regulatory jurisdiction name at EOD (e.g., ''CySEC'', ''FCA'', ''ASIC & GAML'', ''FinCEN+FINRA'')';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN LastApplicationProAccountDate COMMENT 'Date of most recent professional account application; ''1900-01-01'' sentinel if never applied';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Equity COMMENT 'Total EOD equity (USD): NWA (net worth of assets) + Liabilities from DWH_dbo.V_Liabilities. Includes all open positions at market value';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN RealizedEquity COMMENT 'Realized equity component (cash + closed positions only), excluding open unrealized positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AUM COMMENT 'Assets Under Management: value of assets the customer holds in copy-trading and portfolio products';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Credit COMMENT 'Credit/margin balance: funds provided as credit (e.g., bonus credits). V_Liabilities.EOD_Balance';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Copy COMMENT 'EOD equity in active copy/mirror positions (Amount + PositionPnL for MirrorID>0)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Stocks COMMENT 'EOD equity in settled stock/ETF positions (IsSettled=1, InstrumentTypeID IN 5,6)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Stocks COMMENT 'EOD equity in leveraged stock/ETF CFD positions (IsSettled=0, InstrumentTypeID IN 5,6)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Crypto COMMENT 'EOD equity in settled cryptocurrency positions (IsSettled=1, InstrumentTypeID=10)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Crypto COMMENT 'EOD equity in leveraged crypto CFD positions (IsSettled=0, InstrumentTypeID=10)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `EOD_Equity_FX/Comm/Ind` COMMENT 'EOD equity in FX, commodities, and indices positions (InstrumentTypeID IN 1,2,4)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Crypto_Lev1 COMMENT 'EOD equity in crypto positions where Leverage=1 AND IsBuy=1 (unlevered long)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Stocks_LevCFD COMMENT 'EOD equity in stock positions where Leverage>1 OR IsBuy=0 (levered or short)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Crypto_Lev1 COMMENT 'EOD equity in CFD-Crypto positions where Leverage=1 AND IsBuy=1';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Stocks_LevCFD COMMENT 'EOD equity in CFD-Stocks positions where Leverage>1 OR IsBuy=0';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_IsFunded COMMENT '1 if EOD_Equity >= $25 (original funded customer threshold)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsFunded_New COMMENT '1 if EOD_Equity > 0 AND VerificationLevelID=3 AND FirstActionDate < tomorrow (stricter funded definition)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_LSD COMMENT 'Life Stage Definition segment label at EOD (e.g., lifecycle stage name). Source: BI_DB_CID_LifeStageDefinition';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveUser COMMENT '1 if customer logged in (ActionTypeID=14) on this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active COMMENT '1 if customer had any position open or closed on this date (any instrument, including partial close children excluded)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen COMMENT '1 if customer opened a new position today - manual trade OR started/added a mirror (AirDrop excluded). See section 2.3';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Copy COMMENT '1 if customer has an open copy position on this date (MirrorID>0)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Stocks COMMENT '1 if customer has an open settled stock position (IsSettled=1, InstrumentTypeID IN 5,6, non-AirDrop)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Stocks COMMENT '1 if customer has an open CFD stock position (IsSettled=0, InstrumentTypeID IN 5,6)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Crypto COMMENT '1 if customer has an open settled crypto position (IsSettled=1, InstrumentTypeID=10, non-AirDrop)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Crypto COMMENT '1 if customer has an open CFD crypto position (IsSettled=0, InstrumentTypeID=10)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `Active_FX/Comm/Ind` COMMENT '1 if customer has an open FX/commodities/indices position (InstrumentTypeID IN 1,2,4)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_FX COMMENT '1 if customer has an open FX (Currencies, InstrumentTypeID=1) position';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Comm COMMENT '1 if customer has an open Commodities (InstrumentTypeID=2) position';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Ind COMMENT '1 if customer has an open Indices (InstrumentTypeID=4) position';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Stocks_Lev1 COMMENT '1 if customer has an open stock position with Leverage=1 AND IsBuy=1';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Stocks_LevCFD COMMENT '1 if customer has an open stock position with Leverage>1 OR IsBuy=0';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Crypto_Lev1 COMMENT '1 if customer has an open crypto position with Leverage=1 AND IsBuy=1';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Crypto_LevCFD COMMENT '1 if customer has an open crypto position with Leverage>1 OR IsBuy=0';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Manual COMMENT '1 if opened a non-AirDrop, non-copy position today (MirrorID=0, IsAirDrop=0)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Mirror COMMENT '1 if started a new copy relationship OR added mirror allocation today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_AirDrop COMMENT '1 if received an AirDrop position today (IsAirDrop=1)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_IncludeCopy COMMENT '1 if opened any position today including copy but excluding AirDrop';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Copy COMMENT '1 if opened a copy position today (MirrorID>0, non-portfolio, OpenDateID=today)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks COMMENT '1 if opened a settled stock position today (non-AirDrop)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks COMMENT '1 if opened a CFD stock position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto COMMENT '1 if opened a settled crypto position today (non-AirDrop)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto COMMENT '1 if opened a CFD crypto position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `ActiveOpen_FX/Comm/Ind` COMMENT '1 if opened a FX/Comm/Ind position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_FX COMMENT '1 if opened a FX position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Comm COMMENT '1 if opened a Commodities position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Ind COMMENT '1 if opened an Indices position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks_Lev1 COMMENT '1 if opened a stock position (Leverage=1, IsBuy=1) today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks_LevCFD COMMENT '1 if opened a leveraged/short stock position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto_Lev1 COMMENT '1 if opened a crypto position (Leverage=1, IsBuy=1) today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto_LevCFD COMMENT '1 if opened a leveraged/short crypto position today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsOpen_Copy COMMENT '1 if customer opened a new copy relationship (started copying a trader) today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Opened_Copy COMMENT 'Number of distinct copy relationships opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Closed_Copy COMMENT 'Number of distinct copy relationships closed today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyIn_Copy COMMENT 'Total funds allocated into copy positions today (negative Amount from AT=17,15)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyOut_Copy COMMENT 'Total funds returned from closed copy positions today (Amount from AT=18,16)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsOpen_CopyPortfolio COMMENT '1 if customer opened a CopyPortfolio (managed portfolio product) today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Opened_CopyPortfolio COMMENT 'Number of CopyPortfolio relationships opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Closed_CopyPortfolio COMMENT 'Number of CopyPortfolio relationships closed today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyIn_CopyPortfolio COMMENT 'Total funds into CopyPortfolio positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyOut_CopyPortfolio COMMENT 'Total funds returned from CopyPortfolio positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Copy COMMENT 'Count of new copy positions opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks COMMENT 'Count of new settled stock positions opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks COMMENT 'Count of new CFD stock positions opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto COMMENT 'Count of new settled crypto positions opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto COMMENT 'Count of new CFD crypto positions opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `NewTrades_FX/Comm/Ind` COMMENT 'Count of new FX/Comm/Ind positions opened today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Total COMMENT 'Total count of all new positions opened today across all instrument types';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Copy COMMENT 'Total USD invested in new copy positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks COMMENT 'Total USD in new settled stock positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks COMMENT 'Total USD in new CFD stock positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto COMMENT 'Total USD in new settled crypto positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto COMMENT 'Total USD in new CFD crypto positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `AmountIn_NewTrades_FX/Comm/Ind` COMMENT 'Total USD in new FX/Comm/Ind positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Total COMMENT 'Total USD invested in all new positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks_Lev1 COMMENT 'Count of new Lev1 stock positions (Leverage=1, IsBuy=1) today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks_LevCFD COMMENT 'Count of new leveraged/short stock positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto_Lev1 COMMENT 'Count of new Lev1 crypto positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto_LevCFD COMMENT 'Count of new leveraged/short crypto positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks_Lev1 COMMENT 'USD in new Lev1 stock positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks_LevCFD COMMENT 'USD in new leveraged/short stock positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto_Lev1 COMMENT 'USD in new Lev1 crypto positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto_LevCFD COMMENT 'USD in new leveraged/short crypto positions today';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Copy COMMENT 'Daily revenue from copy positions (FullCommissions + RollOverFee) + TicketFeeByPercent_Copy';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Stocks COMMENT 'Revenue from settled stock positions + flat ticket fees';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks COMMENT 'Revenue from CFD stock positions + ticket fee by percent (Stocks CFD)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Crypto COMMENT 'Revenue from settled crypto positions + ticket fee by percent (Crypto Real)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto COMMENT 'Revenue from CFD crypto positions + ticket fee by percent (Crypto CFD)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `Revenue_FX/Comm/Ind` COMMENT 'Revenue from FX/Commodities/Indices positions + ticket fee by percent';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_FX COMMENT 'Revenue from FX (Currencies) positions + Currencies CFD ticket fee by percent';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Comm COMMENT 'Revenue from Commodities positions + Commodities CFD ticket fee by percent';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Ind COMMENT 'Revenue from Indices positions + Indices CFD ticket fee by percent';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Total COMMENT 'Total daily revenue across all instruments + all fee types (commissions + rollover + ticket + conversion + Islamic). See section 2.6';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_IslamicFees COMMENT 'Islamic account fees only: AdminFee + SpotAdjustFee (swap-free surcharge). 0 for non-Islamic accounts';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_TicketFees COMMENT 'Flat per-trade ticket fees on stock trades (Function_Revenue_TicketFee)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_ConversionFees COMMENT 'Currency conversion fees on deposits/cashouts (Function_Revenue_ConversionFee)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_TicketFeeByPercent COMMENT 'Total percentage-based ticket fees across all instrument types and copy';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Transactional_Revenue_Total COMMENT 'Revenue_Total minus Islamic fees - the pure transaction-driven revenue portion. See section 2.6';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Stocks_Lev1 COMMENT 'Revenue from Lev1 stock positions + flat ticket fees';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks_LevCFD COMMENT 'Revenue from leveraged/short stock positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Crypto_Lev1 COMMENT 'Revenue from Lev1 crypto positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto_LevCFD COMMENT 'Revenue from leveraged/short crypto positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Copy COMMENT 'Customer-side PnL on copy positions on this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Stocks COMMENT 'Customer-side PnL on settled stock positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Stocks COMMENT 'Customer-side PnL on CFD stock positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Crypto COMMENT 'Customer-side PnL on settled crypto positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Crypto COMMENT 'Customer-side PnL on CFD crypto positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `PnL_FX/Comm/Ind` COMMENT 'Customer-side PnL on FX/Comm/Ind positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_FX COMMENT 'Customer-side PnL on FX (Currencies) positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Comm COMMENT 'Customer-side PnL on Commodities positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Ind COMMENT 'Customer-side PnL on Indices positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Total COMMENT 'Total customer-side PnL across all instruments (sum of Copy + Real_Stocks + CFD_Stocks + Real_Crypto + CFD_Crypto + FX/Comm/Ind)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Stocks_Lev1 COMMENT 'PnL on Lev1 stock positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Stocks_LevCFD COMMENT 'PnL on leveraged/short stock positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Crypto_Lev1 COMMENT 'PnL on Lev1 crypto positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Crypto_LevCFD COMMENT 'PnL on leveraged/short crypto positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN TotalDeposits COMMENT 'Total deposit amount (USD) on this date (Fact_CustomerAction ActionTypeID=7)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN CountDeposits COMMENT 'Number of deposits on this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN TotalCashouts COMMENT 'Total cashout amount (USD) on this date (ActionTypeID=8)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN TotalCoFee COMMENT 'Copy-out fee charged on copy position closure (ActionTypeID=30, Commission field)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NetDeposits COMMENT 'TotalDeposits minus TotalCashouts for this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN WithdrawalToWallet COMMENT 'Cashout amount directed to eToro Money wallet (FundingTypeID=27)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN CashoutsAdjusted COMMENT 'Adjusted cashout: TPCashoutsOldDef - CashoutAdjustment - TransferCoins. Used for DDR/finance normalisation';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Copy COMMENT 'Lifetime accumulated revenue from copy positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Stocks COMMENT 'Lifetime accumulated revenue from settled stocks';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Stocks COMMENT 'Lifetime accumulated revenue from CFD stocks';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Crypto COMMENT 'Lifetime accumulated revenue from settled crypto';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Crypto COMMENT 'Lifetime accumulated revenue from CFD crypto';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `ACC_Revenue_FX/Comm/Ind` COMMENT 'Lifetime accumulated revenue from FX/Comm/Ind';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Total COMMENT 'Lifetime accumulated total revenue (all instruments + all fee types)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Transactional_Revenue_Total COMMENT 'Lifetime accumulated transactional-only revenue (excludes Islamic fees)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Copy COMMENT 'Lifetime accumulated customer PnL on copy positions';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Real_Stocks COMMENT 'Lifetime accumulated customer PnL on settled stocks';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Stocks COMMENT 'Lifetime accumulated customer PnL on CFD stocks';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Real_Crypto COMMENT 'Lifetime accumulated customer PnL on settled crypto';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Crypto COMMENT 'Lifetime accumulated customer PnL on CFD crypto';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `ACC_PnL_FX/Comm/Ind` COMMENT 'Lifetime accumulated customer PnL on FX/Comm/Ind';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Total COMMENT 'Lifetime accumulated total customer PnL';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_TotalDeposits COMMENT 'Lifetime total deposits (USD)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_CountDeposits COMMENT 'Lifetime total deposit count';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_TotalCashouts COMMENT 'Lifetime total cashouts (USD)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_TotalCoFee COMMENT 'Lifetime total copy-out fees paid';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_NetDeposits COMMENT 'Lifetime net deposits (TotalDeposits - TotalCashouts cumulative)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_WithdrawalToWallet COMMENT 'Lifetime total withdrawals to eToro Money wallet';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_ChurnDays COMMENT 'Consecutive days since first funded date where customer was not in IsFunded_New state. Resets to 0 when IsFunded_New=1. See section 2.5';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AccountManager COMMENT 'Account manager full name (FirstName + '' '' + LastName) from Dim_Manager';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsIslamic COMMENT '1 if customer has a swap-free/Islamic account (WeekendFeePrecentage=0). See section 2.11';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsContacted COMMENT '1 if customer was contacted through bonus/CRM channel on this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsContactedAmount COMMENT 'Total deposit amount from contacted periods on this date';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN UpdateDate COMMENT 'ETL timestamp: GETDATE() at time of SP execution. Reflects the most recent daily ETL run for this partition';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FirstNewFundedDate COMMENT 'Date when customer first satisfied the IsFunded_New criteria (first VL3-verified funded day). NULL if never funded under new definition';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN CID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN DateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Month SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Seniority SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Seniority_Seg SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Reg_Month SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN RegDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsReg_ThisD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FTD_Month SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FTDdate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsFTD_ThisD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FTDA SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Region SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewMarketingRegion SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Country SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Channel SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN SubChannel SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AffiliateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FirstAction SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FirstInstrument SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN V2_Complete SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN V3_Complete SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN LastPosOpenDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN LastLoggedIn SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsPro SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsOTD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Daily_Classification SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Club SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Regulation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN LastApplicationProAccountDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Equity SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN RealizedEquity SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AUM SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Credit SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `EOD_Equity_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_Real_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_Equity_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_IsFunded SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsFunded_New SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN EOD_LSD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveUser SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `Active_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_FX SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Comm SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Ind SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Active_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Manual SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Mirror SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_AirDrop SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_IncludeCopy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `ActiveOpen_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_FX SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Comm SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Ind SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ActiveOpen_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsOpen_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Opened_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Closed_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyIn_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyOut_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsOpen_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Opened_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Count_Closed_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyIn_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN MoneyOut_CopyPortfolio SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `NewTrades_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `AmountIn_NewTrades_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NewTrades_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AmountIn_NewTrades_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `Revenue_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_FX SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Comm SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Ind SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_IslamicFees SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_TicketFees SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_ConversionFees SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_TicketFeeByPercent SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Transactional_Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN Revenue_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `PnL_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_FX SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Comm SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Ind SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Stocks_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Stocks_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_Real_Crypto_Lev1 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN PnL_CFD_Crypto_LevCFD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN TotalDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN CountDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN TotalCashouts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN TotalCoFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN NetDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN WithdrawalToWallet SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN CashoutsAdjusted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `ACC_Revenue_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_Transactional_Revenue_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Copy SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Real_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Stocks SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Real_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_CFD_Crypto SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN `ACC_PnL_FX/Comm/Ind` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_PnL_Total SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_TotalDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_CountDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_TotalCashouts SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_TotalCoFee SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_NetDeposits SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_WithdrawalToWallet SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN ACC_ChurnDays SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN AccountManager SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsIslamic SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsContacted SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN IsContactedAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata ALTER COLUMN FirstNewFundedDate SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-07 09:06:39 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 12
-- Statements: 364/366 succeeded
-- Error: [COLUMN_NOT_FOUND_IN_TABLE] Column 'V3_CompleteDate' not found in table 'main'.'bi_db'.'gold_sql_dp_prod_we_bi_db_dbo_bi_db_cid_dailypanel_fulldata''. SQLSTATE: 42703
-- ====================