-- =============================================================================
-- Databricks Deep Lineage Column Comment Propagation: BI_DB_dbo.BI_DB_Client_Balance_CID_Level_New
-- Generated: 2026-05-07 | dwh-semantic-doc pipeline (deep lineage)
--
-- Source (UC): main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new
-- Source (Synapse): BI_DB_dbo.BI_DB_Client_Balance_CID_Level_New
--
-- Target tables (7):
--   main.bi_output.fca_cb_pop  (TABLE, 34 cols)
--   main.bi_output.cb  (TABLE, 35 cols)
--   main.bi_output.fca_cb_pop1  (TABLE, 34 cols)
--   main.bi_output.cb_ind  (TABLE, 40 cols)
--   main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum  (TABLE, 20 cols)
--   main.bi_output.cbr_ind  (TABLE, 31 cols)
--   main.bi_output.final  (TABLE, 7 cols)
-- Target views (4):
--   main.etoro_kpi_prep.v_population_balance_only_accounts  (VIEW, 4 cols)
--   main.etoro_kpi_prep.v_population_funded  (VIEW, 4 cols)
--   main.etoro_kpi_prep.v_population_portfolio_only  (VIEW, 1 cols)
--   main.etoro_kpi_prep.v_ddr_fact_aum  (VIEW, 22 cols)
-- =============================================================================

-- main.etoro_kpi_prep.v_population_balance_only_accounts (VIEW, 4 columns)
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_balance_only_accounts.`RealCID` IS 'Same as CID: Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: CID -> RealCID)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_balance_only_accounts.`MaxAnyEquity` IS 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> MaxAnyEquity)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_balance_only_accounts.`MaxAnyEquity` IS 'Same as actualNWA: Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: actualNWA -> MaxAnyEquity)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_balance_only_accounts.`DateID` IS 'Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New)';

-- main.etoro_kpi_prep.v_population_funded (VIEW, 4 columns)
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_funded.`RealCID` IS 'Same as CID: Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: CID -> RealCID)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_funded.`DateID` IS 'Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_funded.`Equity` IS 'Same as actualNWA: Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: actualNWA -> Equity)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_funded.`Equity` IS 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> Equity)';

-- main.bi_output.fca_cb_pop (TABLE, 34 columns)
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionAmount: Total position amount (sum of all open position values). From Fact_SnapshotEquity.TotalPositionsAmount. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionAmount -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityRealStocks` COMMENT 'Same as PositionPNLStocksReal: Position PnL for real (settled) stock positions. Unrealized profit/loss on owned shares. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLStocksReal -> EquityRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `CashInCopy` COMMENT 'Cash allocated to copy-trading relationships. From V_Liabilities.CashInCopy. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `IsCreditReportValidCB` COMMENT 'Credit Bureau reporting eligibility flag. 1 = eligible for credit reporting. Inherited from Fact_SnapshotCustomer. Excludes demo non-real accounts, internal labels (26,30), and blocked countries (250). Used by finance for regulatory balance reconciliation. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotCustomer)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealStocks` COMMENT 'Same as NOPStocks: Net Open Position for stock instruments. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocks -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `AvailableCash` COMMENT 'Cash available for trading. From V_Liabilities.AvailableCash. Free cash not locked in positions or pending cashouts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealStocks` COMMENT 'Same as TotalRealStocks: Total real stock position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID IN (5,6) AND NOT futures. Customer owns the underlying shares. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealStocks -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityCFD` COMMENT 'Same as TotalRealCrypto: Total real crypto position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID=10. Customer owns the underlying crypto asset. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealCrypto -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionPNLStocksReal: Position PnL for real (settled) stock positions. Unrealized profit/loss on owned shares. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLStocksReal -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityRealCrypto` COMMENT 'Same as TotalRealCrypto: Total real crypto position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID=10. Customer owns the underlying crypto asset. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealCrypto -> EquityRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityCFD` COMMENT 'Same as TotalRealStocks: Total real stock position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID IN (5,6) AND NOT futures. Customer owns the underlying shares. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealStocks -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `NOPRealStocks` COMMENT 'Same as NOPStocksCFD: NOP for stock CFDs specifically. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocksCFD -> NOPRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionPNL: Total position PnL across all asset classes. From V_Liabilities.PositionPnL. Unrealized profit/loss on all open positions. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNL -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionPNLCryptoReal: Position PnL for real (settled) crypto positions. Unrealized profit/loss on owned crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLCryptoReal -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `InProcessCashout` COMMENT 'Pending cashout amount not yet finalized. From Fact_SnapshotEquity.InProcessCashouts. Excludes statuses 3=Processed, 4=Cancelled, 5, 6. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityRealCrypto` COMMENT 'Same as PositionPNLCryptoReal: Position PnL for real (settled) crypto positions. Unrealized profit/loss on owned crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLCryptoReal -> EquityRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealStocks` COMMENT 'Same as PositionPNLStocksReal: Position PnL for real (settled) stock positions. Unrealized profit/loss on owned shares. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLStocksReal -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `NOPRealStocks` COMMENT 'Same as NOPStocks: Net Open Position for stock instruments. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocks -> NOPRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealCrypto` COMMENT 'Same as NOPCrypto: Net Open Position for crypto instruments. From V_Liabilities. Represents the net market exposure in crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCrypto -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealCrypto` COMMENT 'Same as NOPCryptoCFD: NOP for crypto CFDs specifically (not settled/real crypto). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCryptoCFD -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealCrypto` COMMENT 'Same as PositionPNLCryptoReal: Position PnL for real (settled) crypto positions. Unrealized profit/loss on owned crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLCryptoReal -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `TotalRealCryptoLoan` COMMENT 'Total leveraged real crypto loan amount. InitialAmount where IsSettled=1 AND InstrumentTypeID=10 AND Leverage=2. Represents the initial investment in 2x leveraged crypto. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `actualNWA` COMMENT 'Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `TotalCash` COMMENT 'Same as AvailableCash: Cash available for trading. From V_Liabilities.AvailableCash. Free cash not locked in positions or pending cashouts. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: AvailableCash -> TotalCash)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `NOPRealCrypto` COMMENT 'Same as NOPCrypto: Net Open Position for crypto instruments. From V_Liabilities. Represents the net market exposure in crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCrypto -> NOPRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `NOPRealCrypto` COMMENT 'Same as NOPCryptoCFD: NOP for crypto CFDs specifically (not settled/real crypto). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCryptoCFD -> NOPRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `Regulation` COMMENT 'Name of the regulatory entity governing this customer row. Values: FCA, CySEC, ASIC, SIBA, SFSA, FSA, etc. Resolved from Dim_Regulation.Name via Fact_SnapshotCustomer.RegulationID. For transfer CIDs, the -1 row shows the previous regulation. (Tier 1 - Dictionary.Regulation)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `Date` COMMENT 'The business date as a DATE type. Equivalent to DateID but in date format. Computed from @date SP parameter. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealStocks` COMMENT 'Same as NOPStocksCFD: NOP for stock CFDs specifically. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocksCFD -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `CID` COMMENT 'Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `TotalNegativeLiability` COMMENT 'Negative portion of total liability. Used in regulatory reporting to isolate client obligations. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `GapRealCrypto` COMMENT 'Same as TotalRealCrypto: Total real crypto position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID=10. Customer owns the underlying crypto asset. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealCrypto -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `EquityRealStocks` COMMENT 'Same as TotalRealStocks: Total real stock position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID IN (5,6) AND NOT futures. Customer owns the underlying shares. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealStocks -> EquityRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop ALTER COLUMN `TotalCash` COMMENT 'Same as CashInCopy: Cash allocated to copy-trading relationships. From V_Liabilities.CashInCopy. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: CashInCopy -> TotalCash)';

-- main.bi_output.cb (TABLE, 35 columns)
ALTER TABLE main.bi_output.cb ALTER COLUMN `OpeningBalance` COMMENT 'Same as DateID: Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: DateID -> OpeningBalance)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CompensationDormantFee` COMMENT 'Dormant fee compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (30). Refunds of inactivity fees charged to dormant accounts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `TransferCoins` COMMENT 'Crypto coin transfers. -SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=8 AND IsRedeem=1. Blockchain wallet-to-wallet movements (sign-inverted). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `OpeningBalance` COMMENT 'Customer''s balance at the start of the business day (in USD). Equals the previous day''s ClosingBalance for this CID. Source: V_Liabilities (previous day). For the first row per CID, this is the initial deposit amount. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `NetTransfersUnrealizedPnL` COMMENT 'Unrealized PnL component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `ClientBalanceRealizedPnL` COMMENT 'Total realized PnL. SUM(NetProfit) from Fact_CustomerAction WHERE ActionTypeID IN (4,5,6,28,40). All closed positions across all asset classes. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CompensationToAffiliate` COMMENT 'Affiliate compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (8,51,52). Payouts to affiliate/partner accounts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `TransferCoinFees` COMMENT 'Crypto transfer fees. -SUM(Commission) from Fact_CustomerAction WHERE ActionTypeID=30 AND IsRedeem=1. Blockchain network + eToro transfer fees. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `Cashouts` COMMENT 'Cashout withdrawals. SUM(Amount) from Fact_CustomerAction WHERE (ActionTypeID=8 AND IsRedeem!=1) OR ActionTypeID=45. Excludes crypto redemptions (IsRedeem=1). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `UnrealizedPnLChange` COMMENT 'Day-over-day change in total unrealized PnL across all asset classes. Key metric for equity volatility tracking. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CID` COMMENT 'Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `OvernightFee` COMMENT 'Overnight/rollover fees. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35. CFD swap fees charged for holding positions overnight/weekend. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `ClosingBalance` COMMENT 'Customer''s balance at end of business day (USD). From V_Liabilities. Tomorrow''s OpeningBalance = today''s ClosingBalance. The cycle equation must hold: OpeningBalance + all flows = ClosingBalance. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `Deposits` COMMENT 'Total deposits. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID IN (7,44). Includes both external deposits (7) and internal transfers (44). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `Refund` COMMENT 'Refund amounts. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=12. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `Foreclosure` COMMENT 'Foreclosure amounts. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (32). Forced position closures due to margin calls or regulatory requirements. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `ChargebackLoss` COMMENT 'Loss from chargebacks that could not be recovered. Split by TransferDirection for regulation transfer CIDs. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `Chargeback` COMMENT 'Chargeback amounts. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID IN (11,13). Disputed deposit reversals. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `LostDebt` COMMENT 'Lost debt write-off. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (31). Uncollectable amounts written off. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CashoutFee` COMMENT 'Cashout fee. -SUM(Commission) + SUM(CASE WHEN IsRedeem=1 THEN Commission END) from Fact_CustomerAction WHERE ActionTypeID=30. Excludes crypto redemption commissions. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `NetTransfersNWA` COMMENT 'NWA (Net Withdrawable Amount) component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CompensationPnLAdjustments` COMMENT 'PnL adjustment compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (22). Corrections to realized PnL via compensation mechanism. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `UnrealizedCommissionChange` COMMENT 'Day-over-day change in total unrealized commission. Commission accrued but not yet realized (positions still open). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CompensationDeposit` COMMENT 'Deposit-type compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID = 7. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `UsedBonus` COMMENT 'Bonus credit amount currently used in open positions. Change metric (day-over-day). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `ClosingBalance` COMMENT 'Same as DateID: Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: DateID -> ClosingBalance)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CompensationCashouts` COMMENT 'Cashout-type compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (33). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `Regulation` COMMENT 'Name of the regulatory entity governing this customer row. Values: FCA, CySEC, ASIC, SIBA, SFSA, FSA, etc. Resolved from Dim_Regulation.Name via Fact_SnapshotCustomer.RegulationID. For transfer CIDs, the -1 row shows the previous regulation. (Tier 1 - Dictionary.Regulation)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `NetTransfersLiability` COMMENT 'Liability component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `Compensation` COMMENT 'General compensation. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=36 AND CompensationReasonID NOT IN (7,8,11,18,19,22,30,31,32,33,34,36,37,38,40,41,50,51,52). Excluded IDs are captured in dedicated columns (7=CompDeposit, 8/51/52=Affiliate, 11=NegRefill, 19=NWAAdj, 22=PnLAdj, 30=DormantFee, 31=LostDebt, 32=Foreclosure, 33=CompCashout, 41/50=PI). Reason 17 re-included per SR-280376 (Nov 2024). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `OtherNegatives` COMMENT 'Other negative balance adjustments not captured in specific columns. Split by TransferDirection for regulation transfer CIDs. Catch-all for miscellaneous balance reductions. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `NegativeRefill` COMMENT 'Negative balance protection refill. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (11). Platform refills retail client balance to zero after CFD/futures losses exceed available funds. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `CompensationPI` COMMENT 'PI compensation. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=36 AND CompensationReasonID IN (41,50). Performance Incentive payouts to popular investors. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `NWAAdjustment` COMMENT 'NWA adjustment compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (19). Adjustments to Net Withdrawable Amount. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb ALTER COLUMN `IsCreditReportValidCB` COMMENT 'Credit Bureau reporting eligibility flag. 1 = eligible for credit reporting. Inherited from Fact_SnapshotCustomer. Excludes demo non-real accounts, internal labels (26,30), and blocked countries (250). Used by finance for regulatory balance reconciliation. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotCustomer)';

-- main.bi_output.fca_cb_pop1 (TABLE, 34 columns)
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `actualNWA` COMMENT 'Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `Regulation` COMMENT 'Name of the regulatory entity governing this customer row. Values: FCA, CySEC, ASIC, SIBA, SFSA, FSA, etc. Resolved from Dim_Regulation.Name via Fact_SnapshotCustomer.RegulationID. For transfer CIDs, the -1 row shows the previous regulation. (Tier 1 - Dictionary.Regulation)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityCFD` COMMENT 'Same as TotalRealStocks: Total real stock position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID IN (5,6) AND NOT futures. Customer owns the underlying shares. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealStocks -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `NOPRealCrypto` COMMENT 'Same as NOPCryptoCFD: NOP for crypto CFDs specifically (not settled/real crypto). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCryptoCFD -> NOPRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityRealCrypto` COMMENT 'Same as PositionPNLCryptoReal: Position PnL for real (settled) crypto positions. Unrealized profit/loss on owned crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLCryptoReal -> EquityRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionAmount: Total position amount (sum of all open position values). From Fact_SnapshotEquity.TotalPositionsAmount. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionAmount -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `TotalNegativeLiability` COMMENT 'Negative portion of total liability. Used in regulatory reporting to isolate client obligations. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionPNLCryptoReal: Position PnL for real (settled) crypto positions. Unrealized profit/loss on owned crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLCryptoReal -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityRealStocks` COMMENT 'Same as PositionPNLStocksReal: Position PnL for real (settled) stock positions. Unrealized profit/loss on owned shares. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLStocksReal -> EquityRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `NOPRealStocks` COMMENT 'Same as NOPStocks: Net Open Position for stock instruments. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocks -> NOPRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `CID` COMMENT 'Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityRealCrypto` COMMENT 'Same as TotalRealCrypto: Total real crypto position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID=10. Customer owns the underlying crypto asset. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealCrypto -> EquityRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealCrypto` COMMENT 'Same as NOPCrypto: Net Open Position for crypto instruments. From V_Liabilities. Represents the net market exposure in crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCrypto -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `InProcessCashout` COMMENT 'Pending cashout amount not yet finalized. From Fact_SnapshotEquity.InProcessCashouts. Excludes statuses 3=Processed, 4=Cancelled, 5, 6. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `TotalCash` COMMENT 'Same as AvailableCash: Cash available for trading. From V_Liabilities.AvailableCash. Free cash not locked in positions or pending cashouts. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: AvailableCash -> TotalCash)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `TotalRealCryptoLoan` COMMENT 'Total leveraged real crypto loan amount. InitialAmount where IsSettled=1 AND InstrumentTypeID=10 AND Leverage=2. Represents the initial investment in 2x leveraged crypto. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `CashInCopy` COMMENT 'Cash allocated to copy-trading relationships. From V_Liabilities.CashInCopy. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealStocks` COMMENT 'Same as TotalRealStocks: Total real stock position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID IN (5,6) AND NOT futures. Customer owns the underlying shares. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealStocks -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealStocks` COMMENT 'Same as NOPStocks: Net Open Position for stock instruments. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocks -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealStocks` COMMENT 'Same as PositionPNLStocksReal: Position PnL for real (settled) stock positions. Unrealized profit/loss on owned shares. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLStocksReal -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealCrypto` COMMENT 'Same as PositionPNLCryptoReal: Position PnL for real (settled) crypto positions. Unrealized profit/loss on owned crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLCryptoReal -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `Date` COMMENT 'The business date as a DATE type. Equivalent to DateID but in date format. Computed from @date SP parameter. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionPNL: Total position PnL across all asset classes. From V_Liabilities.PositionPnL. Unrealized profit/loss on all open positions. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNL -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealCrypto` COMMENT 'Same as TotalRealCrypto: Total real crypto position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID=10. Customer owns the underlying crypto asset. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealCrypto -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `TotalCash` COMMENT 'Same as CashInCopy: Cash allocated to copy-trading relationships. From V_Liabilities.CashInCopy. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: CashInCopy -> TotalCash)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityCFD` COMMENT 'Same as PositionPNLStocksReal: Position PnL for real (settled) stock positions. Unrealized profit/loss on owned shares. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNLStocksReal -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealCrypto` COMMENT 'Same as NOPCryptoCFD: NOP for crypto CFDs specifically (not settled/real crypto). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCryptoCFD -> GapRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `IsCreditReportValidCB` COMMENT 'Credit Bureau reporting eligibility flag. 1 = eligible for credit reporting. Inherited from Fact_SnapshotCustomer. Excludes demo non-real accounts, internal labels (26,30), and blocked countries (250). Used by finance for regulatory balance reconciliation. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotCustomer)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityRealStocks` COMMENT 'Same as TotalRealStocks: Total real stock position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID IN (5,6) AND NOT futures. Customer owns the underlying shares. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealStocks -> EquityRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `AvailableCash` COMMENT 'Cash available for trading. From V_Liabilities.AvailableCash. Free cash not locked in positions or pending cashouts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `NOPRealCrypto` COMMENT 'Same as NOPCrypto: Net Open Position for crypto instruments. From V_Liabilities. Represents the net market exposure in crypto. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPCrypto -> NOPRealCrypto)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `GapRealStocks` COMMENT 'Same as NOPStocksCFD: NOP for stock CFDs specifically. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocksCFD -> GapRealStocks)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `EquityCFD` COMMENT 'Same as TotalRealCrypto: Total real crypto position value. Sum of position amounts where IsSettled=1 AND InstrumentTypeID=10. Customer owns the underlying crypto asset. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalRealCrypto -> EquityCFD)';
ALTER TABLE main.bi_output.fca_cb_pop1 ALTER COLUMN `NOPRealStocks` COMMENT 'Same as NOPStocksCFD: NOP for stock CFDs specifically. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: NOPStocksCFD -> NOPRealStocks)';

-- main.bi_output.cb_ind (TABLE, 40 columns)
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CompensationDeposit` COMMENT 'Deposit-type compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID = 7. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `LostDebt` COMMENT 'Lost debt write-off. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (31). Uncollectable amounts written off. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `OpeningBalance` COMMENT 'Same as DateID: Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: DateID -> OpeningBalance)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `UnrealizedCommissionChange` COMMENT 'Day-over-day change in total unrealized commission. Commission accrued but not yet realized (positions still open). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CompensationPnLAdjustments` COMMENT 'PnL adjustment compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (22). Corrections to realized PnL via compensation mechanism. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `TransferCoins` COMMENT 'Crypto coin transfers. -SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=8 AND IsRedeem=1. Blockchain wallet-to-wallet movements (sign-inverted). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `TransferCoinFees` COMMENT 'Crypto transfer fees. -SUM(Commission) from Fact_CustomerAction WHERE ActionTypeID=30 AND IsRedeem=1. Blockchain network + eToro transfer fees. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `DividendsPaid` COMMENT 'Dividend payments. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35 AND IsFeeDividend=1. Real stock and ETF holders receive dividends. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CompensationDormantFee` COMMENT 'Dormant fee compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (30). Refunds of inactivity fees charged to dormant accounts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `NetTransfersUnrealizedPnL` COMMENT 'Unrealized PnL component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `Cashouts` COMMENT 'Cashout withdrawals. SUM(Amount) from Fact_CustomerAction WHERE (ActionTypeID=8 AND IsRedeem!=1) OR ActionTypeID=45. Excludes crypto redemptions (IsRedeem=1). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `Refund` COMMENT 'Refund amounts. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=12. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CompensationCashouts` COMMENT 'Cashout-type compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (33). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `ClosingBalance` COMMENT 'Customer''s balance at end of business day (USD). From V_Liabilities. Tomorrow''s OpeningBalance = today''s ClosingBalance. The cycle equation must hold: OpeningBalance + all flows = ClosingBalance. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `Deposits` COMMENT 'Total deposits. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID IN (7,44). Includes both external deposits (7) and internal transfers (44). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `Compensation` COMMENT 'General compensation. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=36 AND CompensationReasonID NOT IN (7,8,11,18,19,22,30,31,32,33,34,36,37,38,40,41,50,51,52). Excluded IDs are captured in dedicated columns (7=CompDeposit, 8/51/52=Affiliate, 11=NegRefill, 19=NWAAdj, 22=PnLAdj, 30=DormantFee, 31=LostDebt, 32=Foreclosure, 33=CompCashout, 41/50=PI). Reason 17 re-included per SR-280376 (Nov 2024). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `TicketFee` COMMENT 'Fixed ticket fee. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=1000 (synthetic type for fixed-amount ticket fees). Separated from TradingFees per SR-262975 (Jul 2024). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `ClosingBalance` COMMENT 'Same as DateID: Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: DateID -> ClosingBalance)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `SDRT` COMMENT 'Stamp Duty Reserve Tax (UK). SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35 AND IsFeeDividend=3. Tax on UK stock purchases. Added Oct 2023. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `NetTransfersLiability` COMMENT 'Liability component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `Chargeback` COMMENT 'Chargeback amounts. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID IN (11,13). Disputed deposit reversals. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CashoutFee` COMMENT 'Cashout fee. -SUM(Commission) + SUM(CASE WHEN IsRedeem=1 THEN Commission END) from Fact_CustomerAction WHERE ActionTypeID=30. Excludes crypto redemption commissions. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `ClientBalanceRealizedPnL` COMMENT 'Total realized PnL. SUM(NetProfit) from Fact_CustomerAction WHERE ActionTypeID IN (4,5,6,28,40). All closed positions across all asset classes. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `NegativeRefill` COMMENT 'Negative balance protection refill. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (11). Platform refills retail client balance to zero after CFD/futures losses exceed available funds. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CompensationToAffiliate` COMMENT 'Affiliate compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (8,51,52). Payouts to affiliate/partner accounts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `NWAAdjustment` COMMENT 'NWA adjustment compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (19). Adjustments to Net Withdrawable Amount. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `OtherNegatives` COMMENT 'Other negative balance adjustments not captured in specific columns. Split by TransferDirection for regulation transfer CIDs. Catch-all for miscellaneous balance reductions. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `OpeningBalance` COMMENT 'Customer''s balance at the start of the business day (in USD). Equals the previous day''s ClosingBalance for this CID. Source: V_Liabilities (previous day). For the first row per CID, this is the initial deposit amount. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `NetTransfersNWA` COMMENT 'NWA (Net Withdrawable Amount) component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `OvernightFee` COMMENT 'Overnight/rollover fees. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35. CFD swap fees charged for holding positions overnight/weekend. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `Regulation` COMMENT 'Name of the regulatory entity governing this customer row. Values: FCA, CySEC, ASIC, SIBA, SFSA, FSA, etc. Resolved from Dim_Regulation.Name via Fact_SnapshotCustomer.RegulationID. For transfer CIDs, the -1 row shows the previous regulation. (Tier 1 - Dictionary.Regulation)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CID` COMMENT 'Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `IsValidCustomer` COMMENT 'Segment flag from Fact_SnapshotCustomer. 1 = valid retail customer (not demo, not internal label, not blocked country). Use `WHERE IsValidCustomer = 1` for most analytics. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotCustomer)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `CompensationPI` COMMENT 'PI compensation. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=36 AND CompensationReasonID IN (41,50). Performance Incentive payouts to popular investors. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `ChargebackLoss` COMMENT 'Loss from chargebacks that could not be recovered. Split by TransferDirection for regulation transfer CIDs. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `UnrealizedPnLChange` COMMENT 'Day-over-day change in total unrealized PnL across all asset classes. Key metric for equity volatility tracking. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `UsedBonus` COMMENT 'Bonus credit amount currently used in open positions. Change metric (day-over-day). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `IsCreditReportValidCB` COMMENT 'Credit Bureau reporting eligibility flag. 1 = eligible for credit reporting. Inherited from Fact_SnapshotCustomer. Excludes demo non-real accounts, internal labels (26,30), and blocked countries (250). Used by finance for regulatory balance reconciliation. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotCustomer)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `Foreclosure` COMMENT 'Foreclosure amounts. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (32). Forced position closures due to margin calls or regulatory requirements. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cb_ind ALTER COLUMN `club` COMMENT 'eToro Club tier from Dim_PlayerLevel. Values: Bronze, Silver, Gold, Platinum, Platinum Plus, Diamond. Determines benefits such as interest on balance eligibility. (Tier 1 - Dictionary.PlayerLevel)';

-- main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum (TABLE, 20 columns)
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `Bonus` COMMENT 'Bonus credits. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=9. Credit bonus amounts applied to account. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `TotalInvestedAmount` COMMENT 'Same as PositionAmount: Total position amount (sum of all open position values). From Fact_SnapshotEquity.TotalPositionsAmount. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionAmount -> TotalInvestedAmount)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `TotalPositionPNL` COMMENT 'Same as PositionPNL: Total position PnL across all asset classes. From V_Liabilities.PositionPnL. Unrealized profit/loss on all open positions. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNL -> TotalPositionPNL)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `RealizedEquityGlobal` COMMENT 'Same as realizedEquity: Customer settled (realized) equity — the realized portion of customer balance, excluding unrealized PnL on open positions (the unrealized component lives in Fact_CustomerUnrealized_PnL.PositionPnL). From DWH_dbo.Fact_SnapshotEquity.RealizedEquity. Together with PositionPnL it sums to Balance per V_Liabilities (Balance = RealizedEquity + PositionPnL). (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: realizedEquity -> RealizedEquityGlobal)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `TotalLiabilityGlobal` COMMENT 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> TotalLiabilityGlobal)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `NOPStocks` COMMENT 'Net Open Position for stock instruments. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `NOPCryptoCFD` COMMENT 'NOP for crypto CFDs specifically (not settled/real crypto). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `RealizedEquityTP` COMMENT 'Same as realizedEquity: Customer settled (realized) equity — the realized portion of customer balance, excluding unrealized PnL on open positions (the unrealized component lives in Fact_CustomerUnrealized_PnL.PositionPnL). From DWH_dbo.Fact_SnapshotEquity.RealizedEquity. Together with PositionPnL it sums to Balance per V_Liabilities (Balance = RealizedEquity + PositionPnL). (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: realizedEquity -> RealizedEquityTP)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `TotalEquityTP` COMMENT 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> TotalEquityTP)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `NOPStocksCFD` COMMENT 'NOP for stock CFDs specifically. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `InProcessCashout` COMMENT 'Pending cashout amount not yet finalized. From Fact_SnapshotEquity.InProcessCashouts. Excludes statuses 3=Processed, 4=Cancelled, 5, 6. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `EquityGlobal` COMMENT 'Same as actualNWA: Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: actualNWA -> EquityGlobal)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `TotalLiabilityTP` COMMENT 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> TotalLiabilityTP)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `NOP` COMMENT 'Total Net Open Position across all asset classes. From V_Liabilities.NOP. Net market exposure. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `DateID` COMMENT 'Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `RealCID` COMMENT 'Same as CID: Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: CID -> RealCID)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `EquityGlobal` COMMENT 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> EquityGlobal)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `TotalRealCryptoLoan` COMMENT 'Total leveraged real crypto loan amount. InitialAmount where IsSettled=1 AND InstrumentTypeID=10 AND Leverage=2. Represents the initial investment in 2x leveraged crypto. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `NOPCrypto` COMMENT 'Net Open Position for crypto instruments. From V_Liabilities. Represents the net market exposure in crypto. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_aum ALTER COLUMN `TotalEquityTP` COMMENT 'Same as actualNWA: Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: actualNWA -> TotalEquityTP)';

-- main.etoro_kpi_prep.v_population_portfolio_only (VIEW, 1 columns)
COMMENT ON COLUMN main.etoro_kpi_prep.v_population_portfolio_only.`DateID` IS 'Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New)';

-- main.etoro_kpi_prep.v_ddr_fact_aum (VIEW, 22 columns)
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`NOP` IS 'Total Net Open Position across all asset classes. From V_Liabilities.NOP. Net market exposure. (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`RealizedEquityGlobal` IS 'Same as realizedEquity: Customer settled (realized) equity — the realized portion of customer balance, excluding unrealized PnL on open positions (the unrealized component lives in Fact_CustomerUnrealized_PnL.PositionPnL). From DWH_dbo.Fact_SnapshotEquity.RealizedEquity. Together with PositionPnL it sums to Balance per V_Liabilities (Balance = RealizedEquity + PositionPnL). (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: realizedEquity -> RealizedEquityGlobal)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`EquityAllPlatforms` IS 'Same as actualNWA: Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: actualNWA -> EquityAllPlatforms)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`NOPStocksCFD` IS 'NOP for stock CFDs specifically. (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`RealizedEquityTP` IS 'Same as realizedEquity: Customer settled (realized) equity — the realized portion of customer balance, excluding unrealized PnL on open positions (the unrealized component lives in Fact_CustomerUnrealized_PnL.PositionPnL). From DWH_dbo.Fact_SnapshotEquity.RealizedEquity. Together with PositionPnL it sums to Balance per V_Liabilities (Balance = RealizedEquity + PositionPnL). (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: realizedEquity -> RealizedEquityTP)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`TotalEquityTP` IS 'Same as actualNWA: Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: actualNWA -> TotalEquityTP)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`EquityAllPlatforms` IS 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> EquityAllPlatforms)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`Bonus` IS 'Bonus credits. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=9. Credit bonus amounts applied to account. (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`TotalPositionPNL` IS 'Same as PositionPNL: Total position PnL across all asset classes. From V_Liabilities.PositionPnL. Unrealized profit/loss on all open positions. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionPNL -> TotalPositionPNL)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`RealCID` IS 'Same as CID: Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: CID -> RealCID)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`NOPCrypto` IS 'Net Open Position for crypto instruments. From V_Liabilities. Represents the net market exposure in crypto. (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`NOPStocks` IS 'Net Open Position for stock instruments. (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`EquityGlobal` IS 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> EquityGlobal)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`TotalEquityTP` IS 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> TotalEquityTP)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`TotalLiabilityGlobal` IS 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> TotalLiabilityGlobal)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`TotalRealCryptoLoan` IS 'Total leveraged real crypto loan amount. InitialAmount where IsSettled=1 AND InstrumentTypeID=10 AND Leverage=2. Represents the initial investment in 2x leveraged crypto. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`NOPCryptoCFD` IS 'NOP for crypto CFDs specifically (not settled/real crypto). (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`InProcessCashout` IS 'Pending cashout amount not yet finalized. From Fact_SnapshotEquity.InProcessCashouts. Excludes statuses 3=Processed, 4=Cancelled, 5, 6. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`EquityGlobal` IS 'Same as actualNWA: Actual Net Withdrawable Amount. From V_Liabilities.ActualNWA. The amount the customer could withdraw right now. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: actualNWA -> EquityGlobal)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`TotalLiabilityTP` IS 'Same as TotalLiability: Total liability from open positions. From V_Liabilities.Liabilities. Represents the unrealized obligation (positive = amount owed to customer; negative = customer owes). (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: TotalLiability -> TotalLiabilityTP)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`DateID` IS 'Date identifier in YYYYMMDD integer format. Clustered index column. The date this balance snapshot represents. Filter on this column for efficient date-range queries. (Tier 2 - SP_Client_Balance_New)';
COMMENT ON COLUMN main.etoro_kpi_prep.v_ddr_fact_aum.`TotalInvestedAmount` IS 'Same as PositionAmount: Total position amount (sum of all open position values). From Fact_SnapshotEquity.TotalPositionsAmount. (Tier 2 - SP_Client_Balance_New, from DWH_dbo.Fact_SnapshotEquity). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: PositionAmount -> TotalInvestedAmount)';

-- main.bi_output.cbr_ind (TABLE, 31 columns)
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `NetTransfersUnrealizedPnL` COMMENT 'Unrealized PnL component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `OvernightFee` COMMENT 'Overnight/rollover fees. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35. CFD swap fees charged for holding positions overnight/weekend. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `LostDebt` COMMENT 'Lost debt write-off. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (31). Uncollectable amounts written off. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `UsedBonus` COMMENT 'Bonus credit amount currently used in open positions. Change metric (day-over-day). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `TicketFee` COMMENT 'Fixed ticket fee. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=1000 (synthetic type for fixed-amount ticket fees). Separated from TradingFees per SR-262975 (Jul 2024). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `NWAAdjustment` COMMENT 'NWA adjustment compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (19). Adjustments to Net Withdrawable Amount. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `TransferCoins` COMMENT 'Crypto coin transfers. -SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=8 AND IsRedeem=1. Blockchain wallet-to-wallet movements (sign-inverted). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `UnrealizedCommissionChange` COMMENT 'Day-over-day change in total unrealized commission. Commission accrued but not yet realized (positions still open). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `CompensationDeposit` COMMENT 'Deposit-type compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID = 7. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `Foreclosure` COMMENT 'Foreclosure amounts. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (32). Forced position closures due to margin calls or regulatory requirements. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `CompensationPnLAdjustments` COMMENT 'PnL adjustment compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (22). Corrections to realized PnL via compensation mechanism. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `Cashouts` COMMENT 'Cashout withdrawals. SUM(Amount) from Fact_CustomerAction WHERE (ActionTypeID=8 AND IsRedeem!=1) OR ActionTypeID=45. Excludes crypto redemptions (IsRedeem=1). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `Refund` COMMENT 'Refund amounts. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=12. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `NetTransfersLiability` COMMENT 'Liability component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `UnrealizedPnLChange` COMMENT 'Day-over-day change in total unrealized PnL across all asset classes. Key metric for equity volatility tracking. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `CompensationToAffiliate` COMMENT 'Affiliate compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (8,51,52). Payouts to affiliate/partner accounts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `CompensationCashouts` COMMENT 'Cashout-type compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (33). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `Compensation` COMMENT 'General compensation. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=36 AND CompensationReasonID NOT IN (7,8,11,18,19,22,30,31,32,33,34,36,37,38,40,41,50,51,52). Excluded IDs are captured in dedicated columns (7=CompDeposit, 8/51/52=Affiliate, 11=NegRefill, 19=NWAAdj, 22=PnLAdj, 30=DormantFee, 31=LostDebt, 32=Foreclosure, 33=CompCashout, 41/50=PI). Reason 17 re-included per SR-280376 (Nov 2024). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `CompensationDormantFee` COMMENT 'Dormant fee compensation. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (30). Refunds of inactivity fees charged to dormant accounts. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `Chargeback` COMMENT 'Chargeback amounts. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID IN (11,13). Disputed deposit reversals. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `NetTransfersNWA` COMMENT 'NWA (Net Withdrawable Amount) component of regulation transfers. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `ClientBalanceRealizedPnL` COMMENT 'Total realized PnL. SUM(NetProfit) from Fact_CustomerAction WHERE ActionTypeID IN (4,5,6,28,40). All closed positions across all asset classes. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `SDRT` COMMENT 'Stamp Duty Reserve Tax (UK). SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35 AND IsFeeDividend=3. Tax on UK stock purchases. Added Oct 2023. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `Deposits` COMMENT 'Total deposits. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID IN (7,44). Includes both external deposits (7) and internal transfers (44). (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `CompensationPI` COMMENT 'PI compensation. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=36 AND CompensationReasonID IN (41,50). Performance Incentive payouts to popular investors. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `CashoutFee` COMMENT 'Cashout fee. -SUM(Commission) + SUM(CASE WHEN IsRedeem=1 THEN Commission END) from Fact_CustomerAction WHERE ActionTypeID=30. Excludes crypto redemption commissions. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `ChargebackLoss` COMMENT 'Loss from chargebacks that could not be recovered. Split by TransferDirection for regulation transfer CIDs. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `TransferCoinFees` COMMENT 'Crypto transfer fees. -SUM(Commission) from Fact_CustomerAction WHERE ActionTypeID=30 AND IsRedeem=1. Blockchain network + eToro transfer fees. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `NegativeRefill` COMMENT 'Negative balance protection refill. SUM(Amount) from Fact_CustomerAction WHERE CompensationReasonID IN (11). Platform refills retail client balance to zero after CFD/futures losses exceed available funds. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `DividendsPaid` COMMENT 'Dividend payments. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35 AND IsFeeDividend=1. Real stock and ETF holders receive dividends. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.cbr_ind ALTER COLUMN `OtherNegatives` COMMENT 'Other negative balance adjustments not captured in specific columns. Split by TransferDirection for regulation transfer CIDs. Catch-all for miscellaneous balance reductions. (Tier 2 - SP_Client_Balance_New)';

-- main.bi_output.final (TABLE, 7 columns)
ALTER TABLE main.bi_output.final ALTER COLUMN `RollOverFee` COMMENT 'Same as DividendsPaid: Dividend payments. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35 AND IsFeeDividend=1. Real stock and ETF holders receive dividends. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: DividendsPaid -> RollOverFee)';
ALTER TABLE main.bi_output.final ALTER COLUMN `RollOver_and_Divivdends` COMMENT 'Same as OvernightFee: Overnight/rollover fees. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35. CFD swap fees charged for holding positions overnight/weekend. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: OvernightFee -> RollOver_and_Divivdends)';
ALTER TABLE main.bi_output.final ALTER COLUMN `rn` COMMENT 'Same as CID: Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: CID -> rn)';
ALTER TABLE main.bi_output.final ALTER COLUMN `Regulation` COMMENT 'Name of the regulatory entity governing this customer row. Values: FCA, CySEC, ASIC, SIBA, SFSA, FSA, etc. Resolved from Dim_Regulation.Name via Fact_SnapshotCustomer.RegulationID. For transfer CIDs, the -1 row shows the previous regulation. (Tier 1 - Dictionary.Regulation)';
ALTER TABLE main.bi_output.final ALTER COLUMN `CID` COMMENT 'Customer ID. The eToro platform''s primary customer identifier (RealCID from Fact_SnapshotCustomer). HASH distribution key. One or two rows per CID per DateID depending on transfer status. (Tier 2 - SP_Client_Balance_New)';
ALTER TABLE main.bi_output.final ALTER COLUMN `Divivdends` COMMENT 'Same as DividendsPaid: Dividend payments. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35 AND IsFeeDividend=1. Real stock and ETF holders receive dividends. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: DividendsPaid -> Divivdends)';
ALTER TABLE main.bi_output.final ALTER COLUMN `RollOverFee` COMMENT 'Same as OvernightFee: Overnight/rollover fees. SUM(Amount) from Fact_CustomerAction WHERE ActionTypeID=35. CFD swap fees charged for holding positions overnight/weekend. (Tier 2 - SP_Client_Balance_New). (Propagated from main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_client_balance_cid_level_new, rename chain: OvernightFee -> RollOverFee)';
