-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.BI_DB_DDR_Fact_MIMO_AllPlatforms
-- Generated: 2026-03-29 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.BI_DB_DDR_Fact_MIMO_AllPlatforms > 91.5M-row transaction-level MIMO (Money In / Money Out) fact table unifying deposits and withdrawals across all four platforms - TradingPlatform, eMoney, Options (Apex), and MoneyFarm - with first-time deposit flags at both platform and global levels. Sourced from three sub-platform MIMO tables plus `Function_MIMO_First_Deposit_All_Platforms` for cross-platform FTD reconciliation, assembled by `SP_DDR_Fact_Fact_MIMO_AllPlatforms` with daily DELETE/INSERT by DateID for TP+eMoney and full DELETE/re-INSERT for Options and MoneyFarm. | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Production Source** | Multiple - `BI_DB_DDR_Fact_MIMO_Trading_Platform`, `BI_DB_DDR_Fact_MIMO_eMoney_Platform`, `BI_DB_DDR_Fact_MIMO_Options_Platform`, `Function_MIMO_First_Deposit_All_Platforms` | | **Refresh** | Dail'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN DateID COMMENT 'Ledger business date partition key duplicated from `@date`. `CAST(CONVERT(varchar(8),@date,112) AS int)` seeded into `#depositsTP`/`#cashoutTP`, carried through UNION. DELETE partition uses same `@dateID`. **AllPlatforms transforms:** `#globalMIMO` passes sibling `DateID`; MoneyFarm uses `CAST(FORMAT(gf.FirstDepositDate,''yyyyMMdd'') AS int)` from **`#moneyfarmFTDs`**. (Tier 2 - SP_DDR_Fact_Fact_MIMO_AllPlatforms)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN Date COMMENT 'Calendar counterpart to `DateID`; **`INSERT`** uses `@date AS [Date]` for **`#final` rows**; **`MoneyFarm`** uses `CAST(gf.FirstDepositDate AS date)`. (Tier 2 - SP_DDR_Fact_Fact_MIMO_AllPlatforms)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN RealCID COMMENT 'Global Real Customer Identifier on the ledger row (`fca.RealCID`). (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN MIMOAction COMMENT 'Stable label `''Deposit''` or `''Withdraw''` from UNION halves. (Tier 2 - SP_DDR_Fact_MIMO_Trading_Platform)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN OrigIdentifier COMMENT '**Trading Platform (verbatim Element #5 `BI_DB_DDR_Fact_MIMO_Trading_Platform.md`):** Literal discriminator `''DepositID''` vs `''WithdrawPaymentID''` aligning `TransactionID` grain. **eMoney (verbatim Element #5 `BI_DB_DDR_Fact_MIMO_eMoney_Platform.md`):** Source ID type label - Always `''TransactionID''` for all eMoney transactions. **Options (verbatim Element #5 `BI_DB_DDR_Fact_MIMO_Options_Platform.md`):** Hardcoded `''ApexTxID''` in source facts (coerced Transactions may null out). **MoneyFarm (SP literals):** `''DepositID''` inside `#moneyfarmFTDs`. (Tier 2 - SP_DDR_Fact_Fact_MIMO_AllPlatforms)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN TransactionID COMMENT '`DepositID` for deposits (`ActionTypeID` 7/44) OR `WithdrawPaymentID` for withdraw rows (`ActionTypeID` 8/45). ROW_NUMBER dedupe trims duplicate `(MIMOAction, TransactionID)` pairs (`BI_DB_DDR_Fact_MIMO_Trading_Platform` lineage baseline). **AllPlatforms transforms:** `CAST(f.TransactionID AS varchar(50))` persisted into `INT` from `#final`; `UPDATE #final SET TransactionID=NULL WHERE MIMOPlatform=''Options''`; Options **`INSERT`** uses literal `0 AS TransactionID`; MoneyFarm literals `0` with outer **`isnull(TransactionID,-1)`** guard. **Not all platforms joinable naïvely.** (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN AmountUSD COMMENT '`fca.Amount` from `Fact_CustomerAction WHERE ActionTypeID IN (7,44)` (deposits) or `IN (8,45)` (withdrawals) at `@dateID`. **AllPlatforms:** passthrough **`#final`** (see sibling facts); **`MoneyFarm`** uses `gf.FirstDepositAmount` (**`#moneyfarmFTDs`**). **eMoney negatives** retained from sibling negatives for withdrawals (**see **`BI_DB_DDR_Fact_MIMO_eMoney_Platform.md section 2.5`**)**. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN AmountOrigCurrency COMMENT 'Deposit: `fbd.Amount`. Withdraw: `COALESCE(bddwf.Amount, ROUND( ROUND(fbw.Amount_WithdrawToFunding,6) / NULLIF(ROUND(fbw.ExchangeRate,6),0), 6))` with joins defined in `#cashoutTP`. **MoneyFarm sentinel `-1`** (no original-ccy fidelity in synthetic FTD stitch). Options equals USD per sibling fact. **(Tier 2 - Fact_BillingDeposit / Fact_BillingWithdraw)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN FundingTypeID COMMENT 'Deposit: `fbd.FundingTypeID`. Withdraw: `fbw.FundingTypeID_Funding`. Type of funding instrument powering the payout leg. Deposit description reference: Fact_BillingDeposit column #17 semantics. Withdraw description reference: `FundingTypeID_Funding` semantics in `Fact_BillingWithdraw`. **`MoneyFarm` sentinel `-1`**. **`Options`** generally `0`. **Tier attribution preserved from TP wiki mix.** **(Tier 2 - Fact_BillingDeposit / Billing.Funding)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN CurrencyID COMMENT 'Deposit: `fbd.CurrencyID` - “Currency of the deposit amount…” (Billing upstream). Withdraw: `fbw.ProcessCurrencyID` - “Currency used for the actual payment processing…” (Billing.WithdrawToFunding upstream). Same column merges both semantics via SP branch. **`MoneyFarm` literal `3`**. **`Options`** **`1`** (USD). **(Tier 1 - upstream wiki, Billing.Deposit / Billing.WithdrawToFunding)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN Currency COMMENT 'Ticker symbol (`dc.Abbreviation`) joined on `CurrencyID`/`ProcessCurrencyID`. `"USD","EUR"` forex; equities/crypto codes per dictionary. Passthrough from `Dim_Currency`. **`MoneyFarm` literal `''GBP''`**. **(Tier 1 - Dictionary.Currency)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsPlatformFTD COMMENT '**`IsFTD` relay from sibling facts surfaced as **`IsPlatformFTD` in **`#final` (`m.IsFTD AS IsPlatformFTD`) with `INSERT ISNULL(IsPlatformFTD,0)`.** Recoveries per SP blocks **JOIN `Dim_Customer` / `eMoney_Fact_Transaction_Status` when `DateID>=20250901`.** Interpret per-platform using sibling docs (**`TradingPlatform`** vs **`eMoney`** **`FTDPlatformID` expectations** vs **`MoneyFarm` synthetic **`1`**). **(Tier 2 - SP_DDR_Fact_Fact_MIMO_AllPlatforms)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsInternalTransfer COMMENT '`CASE WHEN FundingTypeID = 33 THEN 1 ELSE 0` (deposit branch on `fbd.FundingTypeID`; withdraw branch on `fbw.FundingTypeID_Funding`). Mirrors IBAN/quick-transfer interplay described in changelog. **`INSERT ISNULL`; Options inherits `bddfmop.IsInternalTransfer`; MoneyFarm literal `0`.** **(Tier 2 - SP_DDR_Fact_MIMO_Trading_Platform)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsRedeem COMMENT '**Transfer-to-coin / transfercoin flag on Money-Out.** Withdraw leg reads `fca.IsRedeem` with `WHERE fca.ActionTypeID IN (8,45)`. Deposit UNION hard-codes literal `0` after `#depositsTP` seeded `NULL`. INSERT applies `ISNULL(IsRedeem,0)`. Interpret `1` as customer movement from TP fiat wallet into on-chain/crypto custody - not “redeem to bank.” Cross-surface: revenue TVF **`Function_Revenue_TransferCoinFee`** documents `Fact_CustomerAction` rows **`ActionTypeID = 30` AND `IsRedeem = 1`** for TransferCoinFee commissions tied to transfercoin redemption. (Tier 2 - Fact_CustomerAction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsTradeFromIBAN COMMENT 'Deposit: `CASE WHEN fca.ActionTypeID = 44 THEN 1 ELSE 0`; Withdraw: `CASE WHEN fca.ActionTypeID = 45 THEN 1 ELSE 0`. Flags sweep-style IBAN internal deposit/withdraw events. **AllPlatforms mapping:** **`f.IsIBANTrade` from **`#final`** (`tm.IsIBANTrade` ∪ `im.IsTradeFromIBAN`) with **`INSERT ISNULL(f.IsIBANTrade,0)` targeting column `IsTradeFromIBAN`.** **Options / MoneyFarm literal `0`.** **(Tier 2 - SP_DDR_Fact_MIMO_Trading_Platform)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN MIMOPlatform COMMENT '**ETL literals** `''TradingPlatform''`, `''eMoney''`, `''Options''`, `''MoneyFarm''` (see section 2.1). Jan‑2026 sample distribution on single day partition enumerated in section 1. **(Tier 2 - SP_DDR_Fact_Fact_MIMO_AllPlatforms)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsGlobalFTD COMMENT '**Primary path (#final INSERT):** `CASE WHEN f.RealCID IS NOT NULL THEN 1 ELSE 0` after `LEFT JOIN #globalFTDs f` on **`m.MIMOAction=''Deposit'' AND m.RealCID=f.RealCID AND m.IsFTD=1 AND m.FTDPlatformID=f.FTDPlatformID`** where **`f` originates from **`BI_DB_dbo.Function_MIMO_First_Deposit_All_Platforms(0)`** ( **`#globalFTDs`** ). **MoneyFarm synthetic rows forced `1`.** **`INSERT ISNULL` + recovery UPDATE overlays.** **`Options`** second INSERT **`SELECT bddfmop.IsGlobalFTD` (no `#globalFTDs` JOIN in that block). Interpret per **`Function_MIMO_First_Deposit_All_Platforms` section 1 business meaning**: date‑routed spine across IBAN / TP extracts with **`REMOVE_BAD_FTDS`** handling. **(Tier 2 - Function_MIMO_First_Deposit_All_Platforms / SP_DDR_Fact_Fact_MIMO_AllPlatforms)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN UpdateDate COMMENT 'ETL watermark `GETDATE()` on INSERT. (Tier 2 - SP_DDR_Fact_MIMO_Trading_Platform)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsCryptoToFiat COMMENT 'Explicit literal `0` - reserved column (C2F captured on other DDR MIMO siblings). `INSERT SELECT … , 0 AS IsCryptoToFiat`. **PLUS `UPDATE`** sets **`1`** for **`FundingTypeID=27` TP deposits `DateID>=20250701` (see section 2.5). **eMoney** uses **`TxTypeID=14`** per sibling (**`BI_DB_ddr…eMoney`**). **`Options`/MoneyFarm forced `0` on insert.** **(Tier 2 - SP_DDR_Fact_MIMO_Trading_Platform)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsRecurring COMMENT '`1=deposit is part of a recurring schedule (OUTER APPLY on Billing.RecurringDeposit). 0=one-time deposit.` carries only on deposit UNION; `''Withdraw''` half injects literal `0`. Final `INSERT` uses `ISNULL(t.IsRecurring,0)`. **`Options`/MoneyFarm insert literal `0`.** **eMoney sibling remains placeholder zeros.** **(Tier 2 - SP_Fact_BillingDeposit_DL_To_Synapse)**';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsIBANQuickTransfer COMMENT 'Internal transfer discriminator `CASE WHEN fca.MoveMoneyReasonID = 6 THEN 1 ELSE 0` on both halves (SP changelog `20250611`). **AllPlatforms** `INSERT` applies `ISNULL`; **Options** / **MoneyFarm** literals `0`. **eMoney** wiring caveat: sibling fact still hard‑codes **`0`** - enrichment may occur only downstream - cross‑check **`BI_DB_DDR_Fact_MIMO_eMoney_Platform.md` section 3.4**. **(Tier 2 - SP_DDR_Fact_MIMO_Trading_Platform)**';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN DateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN RealCID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN MIMOAction SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN OrigIdentifier SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN TransactionID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN AmountUSD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN AmountOrigCurrency SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN FundingTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN CurrencyID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN Currency SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsPlatformFTD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsInternalTransfer SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsRedeem SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsTradeFromIBAN SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN MIMOPlatform SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsGlobalFTD SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsCryptoToFiat SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsRecurring SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_ddr_fact_mimo_allplatforms ALTER COLUMN IsIBANQuickTransfer SET TAGS ('pii' = 'none');

