-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.Client_Balance_Breakdown_Instrument_Level
-- Generated: 2026-05-03 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.Client_Balance_Breakdown_Instrument_Level > Daily PnL and commission breakdown at the (customer × instrument × segmentation) grain - decomposed into realized/unrealized components across 53 dimensions. Designed as a robust replacement for raw PositionPnL + DimPosition queries in financial reporting. --- | Attribute | Value | |-----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | Table | | **Production Source** | Computed (aggregated from Fact_CustomerAction, BI_DB_PositionPnL, Dim_Position, Dim_SnapshotCustomer) | | **Author** | Guy Manova (2023-04-20) | | **Refresh** | Daily (P20 - runs after position and customer snapshot data is available) | | | | | **Synapse Distribution** | ROUND_ROBIN | | **Synapse Index** | CLUSTERED COLUMNSTORE INDEX (optimized for aggregation) | | **Rows** | ~5M per day; >2B total (INT overflow on COUNT) | | **Date Range** | 2023-04-20 (S'
);

-- ---- Table Tags ----
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN DateID COMMENT 'Date of the record in YYYYMMDD integer format. ETL key: the SP deletes and reloads all rows for this DateID on each run. E.g., 20260412 = April 12, 2026. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Date COMMENT 'Full date value corresponding to DateID. Set from `@Date` SP parameter. Redundant with DateID; use DateID for joins, Date for display. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsSettled COMMENT '1 if the position has settled (crypto: real crypto ownership transferred); 0 if CFD/unsettled. Sourced from `Dim_Position.IsSettled` with override logic for positions that changed settlement status during the day (via `#IsSettledIsMirror`). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsMirror COMMENT '1 if the position is a copy-trading (CopyTrade/Mirror) position; 0 if manually placed. Derived: `CASE WHEN MirrorID > 0 THEN 1 ELSE 0`. Override applied via `#IsSettledIsMirror` for settlement-day edge cases. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN InstrumentID COMMENT 'Instrument identifier. FK to `DWH_dbo.Dim_Instrument`. Grain dimension: one row per unique instrument active for the CID-group on this date. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN InstrumentTypeID COMMENT 'Numeric instrument type code. FK to `DWH_dbo.Dim_Instrument`. Values: 5=Stocks, 10=Crypto Currencies, 6=ETF, etc. From SP: `di.InstrumentTypeID`. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN InstrumentType COMMENT 'Instrument type name: "Stocks" (78.5%), "ETF" (11.4%), "Crypto Currencies" (9.1%), "Commodities" (0.4%), "Indices" (0.4%), "Currencies" (0.2%). Sourced from `DWH_dbo.Dim_Instrument.InstrumentType`. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsLeverage COMMENT '1 if the position uses leverage > 1x; 0 for non-leveraged (Leverage=1, typical for stocks/crypto). Derived: `CASE WHEN Leverage > 1 THEN 1 ELSE 0`. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsLeverageMoreThen20 COMMENT '1 if position leverage exceeds 20x; 0 otherwise. Derived: `CASE WHEN Leverage > 20 THEN 1 ELSE 0`. Used for high-leverage exposure reporting and regulatory risk filters. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsAirDrop COMMENT '1 if position originated from a crypto airdrop event; 0 otherwise. Sourced from `Dim_Position.IsAirDrop`. Relevant for eToro crypto airdrop distribution events. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN SettlementTypeID COMMENT 'Settlement type identifier from `Dim_Position.SettlementTypeID`. Distinguishes settlement methods (e.g., real crypto vs CFD). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsBuy COMMENT '1 if the position is a long (buy) position; 0 if short (sell). Sourced from `Dim_Position.IsBuy`. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Regulation COMMENT 'Customer''s regulatory jurisdiction on this date from `Dim_Regulation.Name`. For regulation-transfer days, this column holds EITHER the old (RegTransferDirection=-1) or new (RegTransferDirection=+1) regulation. See section 2.3. Top values: CySEC (59%), FCA (20%), FSA Seychelles (13%), ASIC & GAML (2.9%), FSRA (2.2%). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RegTransferDirection COMMENT 'Direction of regulation transfer for customers who changed regulation on this date. Values: 1=standard row (all customers), -1=old-regulation reversal row (only regulation-transfer customers). April 12, 2026: 4.94M rows at +1, 142 rows at -1. Filter: `WHERE RegTransferDirection = 1` for standard analysis. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsCreditReportValidCB COMMENT '1 if the customer is eligible for credit bureau reporting at this date''s snapshot. ETL-computed flag from `Fact_SnapshotCustomer`. See DWH_dbo.Fact_SnapshotCustomer section 2.3 for logic. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsValidCustomer COMMENT '1 if the customer is a valid retail customer for analytics (excludes demo/internal/blocked). From `Fact_SnapshotCustomer.IsValidCustomer`. Nearly all active trading rows = 1. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN AccountStatusName COMMENT 'Customer account status name from `Dim_AccountStatus.AccountStatusName`. Values include: "Open" (active), "Closed", "Blocked", etc. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN AccountType COMMENT 'Account type name from `Dim_AccountType.Name`. Values: "Private" (retail), "Professional", "Employee", etc. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Country COMMENT 'Customer''s registered country name from `Dim_Country.Name`. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN US_State COMMENT 'US state short name (e.g., "CA", "NY") from `Dim_State_and_Province.ShortName`, populated only for US customers (CountryID=219). Empty string for non-US customers. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Region COMMENT 'Customer''s marketing region from `Dim_Country.MarketingRegionManualName`. Groups countries into business regions (e.g., "Spain", "CEE", "North Europe"). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN MiFiDCategorization COMMENT 'Customer''s MiFID II categorization from `Dim_MifidCategorization.Name`. Values: "Retail", "Retail Pending", "Professional", "Eligible Counterparty". (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Club COMMENT 'eToro Club loyalty tier name from `Dim_PlayerLevel.Name`. Values: Bronze, Silver, Gold, Platinum, Platinum Plus, Diamond, N/A. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN PlayerStatus COMMENT 'Customer account lifecycle status from `Dim_PlayerStatus.Name`. Values: "Normal", "Closed", "Blocked", etc. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Label COMMENT 'eToro brand/label from `Dim_Label.Name`. Values: "eToro", "eToro UK", "eToro Australia", etc. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsOutlier COMMENT '1 if the customer is flagged as a statistical outlier on this date by `BI_DB_Outliers_New`; 0 otherwise. Used to exclude atypical customers from aggregate PnL analysis. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Transition COMMENT 'Outlier transition type from `BI_DB_Outliers_New.Transition`. "NoTransition" for non-outliers. Describes the nature of outlier status (e.g., new outlier, exiting outlier). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsGermanBaFIN COMMENT '1 if the customer is a German BaFin-regulated customer with crypto holdings; 0 otherwise. ETL-computed: `CASE WHEN HoldsCrypto=1 AND CountryID=79 THEN 1 ELSE 0`. Relevant for BaFin regulatory reporting. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsEtoroTradingCID COMMENT '1 if the CID is an internal eToro trading account (hardcoded list of 7 CIDs: 2244852, 2283663, 2283668, 5969868, 5969870, 5969875, 5969866). Used to filter out eToro''s own positions in customer-facing metrics. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsGlenEagleAccount COMMENT '1 if the CID is the Glen Eagle account (CID = 14155290); 0 otherwise. Glen Eagle is a specific institutional counterparty account. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UnrealizedPnLChange COMMENT 'Daily change in unrealized PnL for positions still open at end of day. Aggregates: new position''s end-of-day PnL (OpenDuringNotClosed), daily mark-to-market change for existing open positions (OpenBeforeNotClosed), and reversal of prior-day PnL for positions closed today (OpenBeforeClosedDuring). USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RealizedPnL COMMENT 'Realized profit/loss for positions closed on this date. `Dim_Position.NetProfit` summed for OpenBeforeClosedDuring and OpenDuringClosedDuring types. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalPnL COMMENT '`UnrealizedPnLChange + RealizedPnL`. Total daily PnL contribution including both realized and mark-to-market changes. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UnrealizedCommissionChange COMMENT 'Daily change in the unrealized commission component. Captures opening spread costs for new open positions and partial close adjustments. Standard commission scale (customer-facing). USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RealizedCommission COMMENT 'Commission realized on positions closed today. Standard commission (customer-facing). Sourced from `CommissionOnClose` for closed positions. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UnrealizedFullCommissionChange COMMENT 'Daily change in unrealized full commission. "Full" = accounting/revenue commission including all spread components. For non-leveraged positions, equals UnrealizedCommissionChange. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RealizedFullCommission COMMENT 'Full commission realized on closed positions. "Full" = accounting/revenue commission. For leveraged positions, FullCommission > Commission. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN CommissionOnOpen COMMENT 'Commission charged at the time of position opening for positions opened on this date. From `Dim_Position.Commission` for OpenDuringNotClosed and OpenDuringClosedDuring types. Zero for positions opened before this date. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN FullCommissionOnOpen COMMENT 'Full (accounting) commission charged at open for positions opened today. Parallel to CommissionOnOpen but using FullCommission scale. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN CommissionCloseAdjustment COMMENT 'Adjustment to commission at position close: `CommissionOnClose - CommissionByUnits`. Captures the difference between the actual close commission and the original by-units commission. Used in partially-closed position accounting. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN FullCommissionCloseAdjustment COMMENT 'Full commission close adjustment: `FullCommissionOnClose - FullCommissionByUnits`. Parallel to CommissionCloseAdjustment using FullCommission scale. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalCommission COMMENT '`RealizedCommission + UnrealizedCommissionChange`. Total daily commission in standard (customer-facing) scale. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalFullCommission COMMENT '`RealizedFullCommission + UnrealizedFullCommissionChange`. Total daily full (accounting/revenue) commission. eToro''s primary revenue metric from position activity. USD. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalZero COMMENT 'Reconciliation metric: `UnrealizedFullCommissionChange + UnrealizedPnLChange + RealizedFullCommission + RealizedPnL`. Should approximately equal zero over time as revenue (commission) offsets customer PnL. Non-zero values indicate timing differences. Not a PnL metric. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UpdateDate COMMENT 'ETL metadata: timestamp when this row was written. Set to `GETDATE()` on insert. (Tier 5 - propagation)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TanganyStatus COMMENT 'Customer''s Tangany digital wallet status, sourced from `BI_DB_Client_Balance_CID_Level_New` (MAX per CID per day). Values: NULL (88.7% - no Tangany), "Inactive" (6.2%), "MicaCustomer" (2.9%), "Internal" (1.1%), "Customer" (0.8%), "ConsentCustomer" (0.04%), "Pending" (0.0001%). Added 2024-02-08 (Adi Meidan). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsDLTUser COMMENT '1 if the customer uses the DLT (Distributed Ledger Technology) platform (`DltStatusID=4` in Fact_SnapshotCustomer). Sourced via `#realTanganystatus` from `BI_DB_Client_Balance_CID_Level_New`. Added 2024-07-30. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN CommissionVersion COMMENT 'Version of the commission calculation schema applied to the positions in this row. Value 2 = current commission model as of 2025-06. Used to distinguish historical (pre-restructuring) vs current commission calculations. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TicketFeeByPercentOnClose COMMENT 'USD ticket fee charged as a percentage at position close for qualifying instruments/positions. Zero for standard-commission positions. Only populated for positions where `TicketFeeByPercentAction = ''Close''` via `Function_Revenue_TicketFeeByPercent`. Added 2025-06-02. Bugfix 2026-01-01: excluded when RegTransferDirection=-1. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsSQF COMMENT '1 if the position uses the SQF (Small Quantity Fee) pricing model. Instruments flagged via `Function_Instrument_Snapshot_Enriched.IsSQF=1` for positions opened from 2025-06-01 onward. 0 otherwise. Added 2025-06-18. (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TicketFeeByPercentPositionType COMMENT 'Classification of the position''s ticket-fee pricing: "New" (instrument uses percent-fee AND position opened after 2025-06-01 threshold), "Legacy" (instrument qualifies but position predates new model), "NotRelevantToTicketFeeByPercent" (standard commission - the vast majority). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TicketFeeByPercentOnOpen COMMENT 'USD ticket fee charged as a percentage at position open. Zero for standard-commission positions. Populated from `Function_Revenue_TicketFeeByPercent` where `TicketFeeByPercentAction=''Open''`. Added 2025-09-14. Very high precision (38,18). (Tier 2 - SP_Client_Balance_Breakdown)';
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsC2P COMMENT '1 if the position is a C2P (Commission to Position) compensation position - identified from `External_Bronze_etoro_Trade_AdminPositionLog` with `CompensationReasonID=134`. These are admin-created positions used for compensation payouts. Added 2025-11-25. (Tier 2 - SP_Client_Balance_Breakdown)';

-- ---- Column PII Tags ----
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN DateID SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Date SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsSettled SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsMirror SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN InstrumentID SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN InstrumentTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN InstrumentType SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsLeverage SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsLeverageMoreThen20 SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsAirDrop SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN SettlementTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsBuy SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Regulation SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RegTransferDirection SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsCreditReportValidCB SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsValidCustomer SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN AccountStatusName SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN AccountType SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Country SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN US_State SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Region SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN MiFiDCategorization SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Club SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN PlayerStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Label SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsOutlier SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN Transition SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsGermanBaFIN SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsEtoroTradingCID SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsGlenEagleAccount SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UnrealizedPnLChange SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RealizedPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalPnL SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UnrealizedCommissionChange SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RealizedCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UnrealizedFullCommissionChange SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN RealizedFullCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN CommissionOnOpen SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN FullCommissionOnOpen SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN CommissionCloseAdjustment SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN FullCommissionCloseAdjustment SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalFullCommission SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TotalZero SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TanganyStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsDLTUser SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN CommissionVersion SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TicketFeeByPercentOnClose SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsSQF SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TicketFeeByPercentPositionType SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN TicketFeeByPercentOnOpen SET TAGS ('pii' = 'none');
ALTER TABLE main.finance.gold_sql_dp_prod_we_bi_db_dbo_client_balance_breakdown_instrument_level ALTER COLUMN IsC2P SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 13:17:36 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 9
-- Statements: 108/108 succeeded
-- ====================
