"""Complete entity-level inventory of Tableau Custom SQLs and Calculated Fields.

The existing on-disk extract in `knowledge/tableau/_index/` is keyed by Synapse
*table* — each Custom SQL or Calculated Field appears once per table it touches,
and only the LENGTH of the SQL/formula is recorded. That doesn't give a clean
"what does this SQL do? where is it used?" view.

This script writes the inverted view by walking the Tableau Metadata GraphQL API
directly:

  CustomSQLTablesConnection  ->  knowledge/tableau/_index/custom_sql_inventory.csv
                                  knowledge/tableau/_index/custom_sql_edges.csv
                                  knowledge/tableau/_index/custom_sql_bodies/<id>.sql
                                  (full SQL text written one file per query)

  CalculatedFieldsConnection ->  knowledge/tableau/_index/calc_field_inventory.csv
                                  knowledge/tableau/_index/calc_field_edges.csv

CSVs are sorted deterministically. Re-runs overwrite. The legacy table-keyed
`custom_sql.csv` and `calc_fields.csv` are left untouched for compatibility.

Run from repo root:
    python tools/tableau/extract_custom_logic.py
    python tools/tableau/extract_custom_logic.py --skip-calc      # SQLs only
    python tools/tableau/extract_custom_logic.py --skip-sql       # calc fields only
    python tools/tableau/extract_custom_logic.py --page-size 25   # smaller pages
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import sys
from pathlib import Path

from _lib import iter_paginated, signin

OUT_DIR = Path("knowledge/tableau/_index")
SQL_BODIES_DIR = OUT_DIR / "custom_sql_bodies"

# ----------------------------- GraphQL queries ----------------------------- #

CUSTOM_SQL_QUERY = """
query customSQL($first: Int!, $after: String) {
  customSQLTablesConnection(first: $first, after: $after) {
    pageInfo { hasNextPage endCursor }
    nodes {
      id
      name
      isEmbedded
      isUnsupportedCustomSql
      connectionType
      query
      database { name connectionType }
      tables {
        id
        name
        schema
        fullName
        connectionType
        database { name }
      }
      upstreamTables {
        id
        name
        schema
        fullName
        connectionType
        database { name }
      }
      downstreamDatasources {
        id
        luid
        name
        projectName
        hasExtracts
      }
      downstreamWorkbooks {
        id
        luid
        name
        projectName
        owner { name email }
      }
      downstreamSheets { id name }
      downstreamDashboards { id name }
    }
  }
}
"""

# calculatedFieldsConnection requires admin or a name filter, so we walk via
# parent datasources (published + embedded-inside-workbook), which are
# unrestricted. The CalculatedField fragment lets us pull all fields we need.
CALC_FIELD_FRAGMENT = """
fragment CalcCore on CalculatedField {
  id
  name
  fullyQualifiedName
  isHidden
  isAutoGenerated
  hasUserReference
  folderName
  formula
  dataType
  role
  aggregation
  fields { id name }
  upstreamTables {
    id
    name
    schema
    fullName
    connectionType
    database { name }
  }
  downstreamSheets { id name }
  downstreamDashboards { id name }
  downstreamWorkbooks { id luid name projectName }
  downstreamFields { id name }
}
"""

PUBLISHED_DS_CALC_QUERY = CALC_FIELD_FRAGMENT + """
query pdsCalc($first: Int!, $after: String) {
  publishedDatasourcesConnection(first: $first, after: $after) {
    pageInfo { hasNextPage endCursor }
    nodes {
      id
      luid
      name
      projectName
      fields {
        __typename
        ... on CalculatedField { ...CalcCore }
      }
    }
  }
}
"""

EMBEDDED_DS_CALC_QUERY = CALC_FIELD_FRAGMENT + """
query embCalc($first: Int!, $after: String) {
  embeddedDatasourcesConnection(first: $first, after: $after) {
    pageInfo { hasNextPage endCursor }
    nodes {
      id
      name
      workbook { id luid name projectName }
      fields {
        __typename
        ... on CalculatedField { ...CalcCore }
      }
    }
  }
}
"""

# ------------------------------- helpers ------------------------------- #


def _table_full(t: dict) -> str:
    full = t.get("fullName")
    if full:
        return full
    db = (t.get("database") or {}).get("name") or ""
    schema = t.get("schema") or ""
    name = t.get("name") or ""
    parts = [p for p in (db, schema, name) if p]
    return ".".join(parts) if parts else (name or "?")


def _sql_filename(query_id: str) -> str:
    """Make a filesystem-safe filename for the SQL body."""
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in (query_id or "unknown"))
    return f"{safe}.sql"


def _trunc_join(items: list[str], n: int = 10, sep: str = " | ") -> str:
    if len(items) <= n:
        return sep.join(items)
    return sep.join(items[:n]) + f" | ... +{len(items) - n} more"


# ----------------------------- Custom SQLs ----------------------------- #


def extract_custom_sqls(server, page_size: int) -> tuple[list[dict], list[dict]]:
    SQL_BODIES_DIR.mkdir(parents=True, exist_ok=True)

    inv_rows: list[dict] = []
    edge_rows: list[dict] = []

    print("Walking customSQLTablesConnection ...", flush=True)
    for node in iter_paginated(
        server,
        CUSTOM_SQL_QUERY,
        connection_path="customSQLTablesConnection",
        page_size=page_size,
        progress_label="custom SQL nodes",
    ):
        qid = node.get("id") or ""
        qname = node.get("name") or ""
        sql = node.get("query") or ""
        sql_hash = hashlib.sha1(sql.encode("utf-8", "replace")).hexdigest()[:12] if sql else ""
        if sql:
            (SQL_BODIES_DIR / _sql_filename(qid)).write_text(sql, encoding="utf-8")

        upstream = node.get("upstreamTables") or node.get("tables") or []
        upstream_full = sorted({_table_full(t) for t in upstream})

        ds_down = node.get("downstreamDatasources") or []
        wb_down = node.get("downstreamWorkbooks") or []
        sh_down = node.get("downstreamSheets") or []
        db_down = node.get("downstreamDashboards") or []

        ds_names = sorted({d.get("name") or "" for d in ds_down if d.get("name")})
        wb_names = sorted({w.get("name") or "" for w in wb_down if w.get("name")})

        inv_rows.append({
            "query_id": qid,
            "query_name": qname,
            "connection_type": (node.get("connectionType") or "").lower(),
            "database_name": (node.get("database") or {}).get("name") or "",
            "is_embedded": node.get("isEmbedded"),
            "is_unsupported": node.get("isUnsupportedCustomSql"),
            "sql_chars": len(sql),
            "sql_sha1_short": sql_hash,
            "sql_body_path": str((SQL_BODIES_DIR / _sql_filename(qid)).as_posix()) if sql else "",
            "n_upstream_tables": len(upstream_full),
            "n_downstream_datasources": len(ds_down),
            "n_downstream_workbooks": len(wb_down),
            "n_downstream_sheets": len(sh_down),
            "n_downstream_dashboards": len(db_down),
            "upstream_tables_sample": _trunc_join(upstream_full, n=10),
            "downstream_workbooks_sample": _trunc_join(wb_names, n=10),
            "downstream_datasources_sample": _trunc_join(ds_names, n=10),
        })

        for t in upstream:
            edge_rows.append({
                "query_id": qid,
                "query_name": qname,
                "direction": "upstream",
                "target_kind": "table",
                "target_id": t.get("id") or "",
                "target_name": _table_full(t),
                "target_extra": (t.get("connectionType") or "").lower(),
            })
        for d in ds_down:
            edge_rows.append({
                "query_id": qid,
                "query_name": qname,
                "direction": "downstream",
                "target_kind": "datasource",
                "target_id": d.get("luid") or d.get("id") or "",
                "target_name": d.get("name") or "",
                "target_extra": d.get("projectName") or "",
            })
        for w in wb_down:
            edge_rows.append({
                "query_id": qid,
                "query_name": qname,
                "direction": "downstream",
                "target_kind": "workbook",
                "target_id": w.get("luid") or w.get("id") or "",
                "target_name": w.get("name") or "",
                "target_extra": w.get("projectName") or "",
            })
        for s in sh_down:
            edge_rows.append({
                "query_id": qid,
                "query_name": qname,
                "direction": "downstream",
                "target_kind": "sheet",
                "target_id": s.get("id") or "",
                "target_name": s.get("name") or "",
                "target_extra": "",
            })
        for d in db_down:
            edge_rows.append({
                "query_id": qid,
                "query_name": qname,
                "direction": "downstream",
                "target_kind": "dashboard",
                "target_id": d.get("id") or "",
                "target_name": d.get("name") or "",
                "target_extra": "",
            })

    return inv_rows, edge_rows


# ----------------------------- Calc Fields ----------------------------- #


def _consume_calc_field(
    cf: dict,
    *,
    ds_kind: str,
    ds_id: str,
    ds_name: str,
    project_name: str,
    workbook_luid: str,
    workbook_name: str,
    inv_rows: list[dict],
    edge_rows: list[dict],
    seen_ids: set[str],
) -> None:
    """Append inventory + edge rows for one calc field, deduplicated by id."""
    fid = cf.get("id") or ""
    if fid in seen_ids:
        return
    seen_ids.add(fid)

    fname = cf.get("name") or ""
    formula = cf.get("formula") or ""

    upstream_fields = cf.get("fields") or []
    upstream_tables = cf.get("upstreamTables") or []
    upstream_table_full = sorted({_table_full(t) for t in upstream_tables})
    upstream_field_names = sorted({f.get("name") or "" for f in upstream_fields if f.get("name")})

    sh_down = cf.get("downstreamSheets") or []
    db_down = cf.get("downstreamDashboards") or []
    wb_down = cf.get("downstreamWorkbooks") or []
    fld_down = cf.get("downstreamFields") or []

    inv_rows.append({
        "field_id": fid,
        "field_name": fname,
        "fully_qualified_name": cf.get("fullyQualifiedName") or "",
        "datasource_kind": ds_kind,
        "datasource_id": ds_id,
        "datasource_name": ds_name,
        "workbook_luid": workbook_luid,
        "workbook_name": workbook_name,
        "project_name": project_name,
        "folder_name": cf.get("folderName") or "",
        "data_type": cf.get("dataType") or "",
        "role": cf.get("role") or "",
        "aggregation": cf.get("aggregation") or "",
        "is_hidden": cf.get("isHidden"),
        "is_auto_generated": cf.get("isAutoGenerated"),
        "has_user_reference": cf.get("hasUserReference"),
        "formula_chars": len(formula),
        "formula": formula,
        "n_upstream_fields": len(upstream_fields),
        "n_upstream_tables": len(upstream_table_full),
        "n_downstream_sheets": len(sh_down),
        "n_downstream_dashboards": len(db_down),
        "n_downstream_workbooks": len(wb_down),
        "n_downstream_fields": len(fld_down),
        "upstream_fields_sample": _trunc_join(upstream_field_names, n=10),
        "upstream_tables_sample": _trunc_join(upstream_table_full, n=10),
    })

    for f in upstream_fields:
        edge_rows.append({
            "field_id": fid, "field_name": fname,
            "direction": "upstream", "target_kind": "field",
            "target_id": f.get("id") or "", "target_name": f.get("name") or "",
            "target_extra": "",
        })
    for t in upstream_tables:
        edge_rows.append({
            "field_id": fid, "field_name": fname,
            "direction": "upstream", "target_kind": "table",
            "target_id": t.get("id") or "", "target_name": _table_full(t),
            "target_extra": (t.get("connectionType") or "").lower(),
        })
    for s in sh_down:
        edge_rows.append({
            "field_id": fid, "field_name": fname,
            "direction": "downstream", "target_kind": "sheet",
            "target_id": s.get("id") or "", "target_name": s.get("name") or "",
            "target_extra": "",
        })
    for d in db_down:
        edge_rows.append({
            "field_id": fid, "field_name": fname,
            "direction": "downstream", "target_kind": "dashboard",
            "target_id": d.get("id") or "", "target_name": d.get("name") or "",
            "target_extra": "",
        })
    for w in wb_down:
        edge_rows.append({
            "field_id": fid, "field_name": fname,
            "direction": "downstream", "target_kind": "workbook",
            "target_id": w.get("luid") or w.get("id") or "",
            "target_name": w.get("name") or "",
            "target_extra": w.get("projectName") or "",
        })
    for f in fld_down:
        edge_rows.append({
            "field_id": fid, "field_name": fname,
            "direction": "downstream", "target_kind": "field",
            "target_id": f.get("id") or "", "target_name": f.get("name") or "",
            "target_extra": "",
        })


def extract_calc_fields(server, page_size: int) -> tuple[list[dict], list[dict]]:
    inv_rows: list[dict] = []
    edge_rows: list[dict] = []
    seen_ids: set[str] = set()

    print("Walking publishedDatasourcesConnection (calc fields) ...", flush=True)
    for pds in iter_paginated(
        server,
        PUBLISHED_DS_CALC_QUERY,
        connection_path="publishedDatasourcesConnection",
        page_size=page_size,
        progress_label="published datasources",
    ):
        ds_id = pds.get("luid") or pds.get("id") or ""
        ds_name = pds.get("name") or ""
        proj = pds.get("projectName") or ""
        for f in pds.get("fields") or []:
            if f.get("__typename") != "CalculatedField":
                continue
            _consume_calc_field(
                f,
                ds_kind="published",
                ds_id=ds_id,
                ds_name=ds_name,
                project_name=proj,
                workbook_luid="",
                workbook_name="",
                inv_rows=inv_rows,
                edge_rows=edge_rows,
                seen_ids=seen_ids,
            )

    print("Walking embeddedDatasourcesConnection (calc fields) ...", flush=True)
    for ed in iter_paginated(
        server,
        EMBEDDED_DS_CALC_QUERY,
        connection_path="embeddedDatasourcesConnection",
        page_size=max(1, min(page_size, 10)),
        progress_label="embedded datasources",
    ):
        wb = ed.get("workbook") or {}
        ds_id = ed.get("id") or ""
        ds_name = ed.get("name") or ""
        for f in ed.get("fields") or []:
            if f.get("__typename") != "CalculatedField":
                continue
            _consume_calc_field(
                f,
                ds_kind="embedded",
                ds_id=ds_id,
                ds_name=ds_name,
                project_name=wb.get("projectName") or "",
                workbook_luid=wb.get("luid") or "",
                workbook_name=wb.get("name") or "",
                inv_rows=inv_rows,
                edge_rows=edge_rows,
                seen_ids=seen_ids,
            )

    return inv_rows, edge_rows


# ------------------------------ writers ------------------------------ #


def _write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    print(f"  wrote {path}  ({len(rows)} rows)", flush=True)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--page-size", type=int, default=50)
    p.add_argument("--skip-sql", action="store_true", help="Skip Custom SQL extraction")
    p.add_argument("--skip-calc", action="store_true", help="Skip Calculated Field extraction")
    args = p.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Signing in to Tableau ...", flush=True)
    server = signin()
    print(f"  site_id = {server.site_id}", flush=True)

    try:
        if not args.skip_sql:
            inv, edges = extract_custom_sqls(server, args.page_size)
            inv.sort(key=lambda r: (r["connection_type"], r["query_name"], r["query_id"]))
            edges.sort(key=lambda r: (r["query_id"], r["direction"], r["target_kind"], r["target_name"]))
            _write_csv(
                OUT_DIR / "custom_sql_inventory.csv",
                inv,
                fieldnames=[
                    "query_id", "query_name", "connection_type", "database_name",
                    "is_embedded", "is_unsupported",
                    "sql_chars", "sql_sha1_short", "sql_body_path",
                    "n_upstream_tables", "n_downstream_datasources", "n_downstream_workbooks",
                    "n_downstream_sheets", "n_downstream_dashboards",
                    "upstream_tables_sample", "downstream_workbooks_sample", "downstream_datasources_sample",
                ],
            )
            _write_csv(
                OUT_DIR / "custom_sql_edges.csv",
                edges,
                fieldnames=[
                    "query_id", "query_name", "direction", "target_kind",
                    "target_id", "target_name", "target_extra",
                ],
            )
            print(f"  wrote {len(inv)} SQL bodies under {SQL_BODIES_DIR.as_posix()}", flush=True)

        if not args.skip_calc:
            inv, edges = extract_calc_fields(server, args.page_size)
            inv.sort(key=lambda r: (r["datasource_name"].lower(), r["field_name"].lower(), r["field_id"]))
            edges.sort(key=lambda r: (r["field_id"], r["direction"], r["target_kind"], r["target_name"]))
            _write_csv(
                OUT_DIR / "calc_field_inventory.csv",
                inv,
                fieldnames=[
                    "field_id", "field_name", "fully_qualified_name",
                    "datasource_kind", "datasource_id", "datasource_name",
                    "workbook_luid", "workbook_name", "project_name", "folder_name",
                    "data_type", "role", "aggregation",
                    "is_hidden", "is_auto_generated", "has_user_reference",
                    "formula_chars", "formula",
                    "n_upstream_fields", "n_upstream_tables",
                    "n_downstream_sheets", "n_downstream_dashboards",
                    "n_downstream_workbooks", "n_downstream_fields",
                    "upstream_fields_sample", "upstream_tables_sample",
                ],
            )
            _write_csv(
                OUT_DIR / "calc_field_edges.csv",
                edges,
                fieldnames=[
                    "field_id", "field_name", "direction", "target_kind",
                    "target_id", "target_name", "target_extra",
                ],
            )
    finally:
        try:
            server.auth.sign_out()
        except Exception:  # noqa: BLE001
            pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
