-- =============================================================================
-- Databricks ALTER Script: bronze WalletDB.Wallet.Requests
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/CryptoDBs/WalletDB/Wiki/Wallet/Tables/Wallet.Requests.md
-- Layer: bronze
-- UC Target: main.wallet.bronze_walletdb_wallet_requests
-- =============================================================================

-- ---- UC Target: main.wallet.bronze_walletdb_wallet_requests (business_group=Wallet) ----
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests SET TBLPROPERTIES (
    'comment' = 'Central request tracking table recording every wallet operation initiated by users or the system - the primary unit of work orchestrating wallet creation, transactions, conversions, payments, and redemptions. Source: WalletDB.Wallet.Requests on the WalletDB production database, ingested via the Generic Pipeline (Append strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/CryptoDBs/WalletDB/Wiki/Wallet/Tables/Wallet.Requests.md).'
);

ALTER TABLE main.wallet.bronze_walletdb_wallet_requests SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'WalletDB',
    'source_schema' = 'Wallet',
    'source_table' = 'Requests',
    'business_group' = 'Wallet',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Append',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN Id COMMENT 'Auto-incrementing primary key and the primary identifier for a request across the entire wallet system. Referenced by Wallet.RequestStatuses.RequestId as FK. Also used as lookup key by numerous stored procedures. (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN CorrelationId COMMENT 'GUID serving as idempotency key and cross-service correlation identifier. Unique index enforced. Generated by the calling service before insertion. Propagates to SentTransactions, ReceivedTransactions, Conversions, and Payments for end-to-end traceability. NULL only for legacy records. (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN Gcid COMMENT 'Global Customer ID identifying the user who initiated the request. Used for filtering requests by customer and for authorization checks. High-cardinality column indexed for efficient per-user lookups. (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN CryptoId COMMENT 'Identifier of the cryptocurrency this request operates on. Implicit reference to Wallet.CryptoTypes.CryptoID. For conversions, this is the source crypto. Combined with Gcid for per-user per-crypto request lookups. (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN RequestTypeId COMMENT 'Type of wallet operation: 0=CreateWallet, 1=SendTransaction, 2=InitiatePayment, 3=Redeem, 4=Conversion, 5=Funding, 6=Staking, 7=ConversionToFiat, 8=ReceiveTransaction, 9=ConversionToPosition. See Request Type. FK to Dictionary.RequestTypes. (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN Timestamp COMMENT 'When the request was created. No default - explicitly set by the calling code. Used for chronological ordering, SLA monitoring, and date-range queries. Indexed descending for recent-request lookups. (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN DetailsJson COMMENT 'JSON payload containing type-specific request parameters. For SendTransaction: destination address, amount, original address. For ReceiveTransaction: batch correlation ID, receiver list. For CreateWallet: typically NULL (no extra params needed). Schema varies by RequestTypeId. (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';
ALTER TABLE main.wallet.bronze_walletdb_wallet_requests ALTER COLUMN DeviceId COMMENT 'Identifier of the device or client that initiated the request. Used for fraud detection and audit purposes. NULL for system-initiated requests (Funding, ReceiveTransaction). (Tier 1 - upstream wiki, WalletDB.Wallet.Requests)';

