-- =============================================================================
-- Databricks ALTER Script: bronze fiktivo.dbo.tblaff_Affiliates
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/ExperianceDBs/fiktivo/Wiki/dbo/Tables/dbo.tblaff_Affiliates.md
-- Layer: bronze
-- UC Targets (2):
--   main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates
--   main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked
-- =============================================================================

-- ---- UC Target: main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates (business_group=BI_DB) ----
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates SET TBLPROPERTIES (
    'comment' = 'Central entity table for the affiliate management platform, storing all affiliate partner accounts with their profile, credentials, configuration, compliance data, and commission settings. Source: fiktivo.dbo.tblaff_Affiliates on the fiktivo production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/ExperianceDBs/fiktivo/Wiki/dbo/Tables/dbo.tblaff_Affiliates.md).'
);

ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'fiktivo',
    'source_schema' = 'dbo',
    'source_table' = 'tblaff_Affiliates',
    'business_group' = 'BI_DB',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliateID COMMENT 'Primary key. The unique identifier for each affiliate in the system. Referenced by virtually every other table via AffiliateID columns. NOT FOR REPLICATION identity. NC PK (clustered index is multi-column). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN UserID COMMENT 'Links to dbo.tblaff_User for admin portal user management. Default 0 indicates no linked admin user. Used by triggers and management procedures. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliatesGroupsID COMMENT 'Organizational group assignment. References dbo.tblaff_AffiliatesGroups.AffiliatesGroupsID [done]. Default 2 is the standard/default group. Groups control manager assignments and reporting segmentation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN LoginName COMMENT 'Affiliate portal login username. MASKED with default() for dynamic data masking. Has dedicated NC index for login lookups. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN LoginPassword COMMENT 'Affiliate portal password. MASKED with default() for dynamic data masking. Stored as plaintext/hash depending on era of creation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Phrase COMMENT 'Security phrase for account recovery or verification. Legacy field from original affiliate system. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Contact COMMENT 'Primary contact person name for the affiliate. For corporate affiliates, this is the business contact. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Email COMMENT 'Affiliate''s email address. Has dedicated NC index. Used for notifications, password resets, and communication. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN TaxID COMMENT 'Tax identification number for the affiliate. Required for payment processing and regulatory reporting in some jurisdictions. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN SocialSecurity COMMENT 'Social security or national insurance number. Required for US-based affiliates for IRS W-9 reporting. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CompanyName COMMENT 'Legal company name for corporate affiliates. MASKED with default(). Used in payment processing and compliance documentation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CompanyAddress COMMENT 'Business address of the affiliate. MASKED with default(). Required for payment and compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Country COMMENT 'Country name as free text. Legacy field - CountryID (column 54) is the normalized version used by newer code. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN City COMMENT 'City of the affiliate''s business address. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN State COMMENT 'State/province of the affiliate''s business address. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Zip COMMENT 'Postal/ZIP code of the affiliate''s business address. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Telephone COMMENT 'Primary telephone number. Legacy field - PhoneCountryID + PhoneNumber are the structured replacement. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Fax COMMENT 'Fax number. Legacy communication field. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN WebSiteURL COMMENT 'URL of the affiliate''s website. Used for compliance review and traffic source verification. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN WebSiteTitle COMMENT 'Title/name of the affiliate''s website. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Comments COMMENT 'Free-text notes about the affiliate. Used by admins for internal annotations. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AccountStatus COMMENT 'Affiliate account lifecycle state: 0=Inactive/Pending (default), 1=Active, 2=Suspended, 4=Under Review, 5=Rejected. Controls portal access and commission eligibility. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN SendEmailNotification COMMENT 'Controls whether the affiliate receives automated email notifications (commission reports, announcements). 1=receive emails, 0=no emails. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN DateCreated COMMENT 'Timestamp of affiliate account creation. Set automatically on INSERT. Oldest records date to 2007-07-01. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AcceptedAgreement COMMENT 'Whether the affiliate has accepted the affiliate program terms and conditions. 1=accepted, 0=not yet accepted. Required before commissions can be paid. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliateTypeID COMMENT 'Commission plan type. References dbo.tblaff_AffiliateTypes.AffiliateTypeID [done]. Determines commission rates, CPA slabs, and payment terms. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN VATNumber COMMENT 'EU VAT registration number. Required for European affiliates for proper invoicing and tax compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliateCustom1 COMMENT 'Custom field 1. Configurable per deployment for additional affiliate metadata. Sometimes used for last name or additional contact info. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliateCustom2 COMMENT 'Custom field 2. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliateCustom3 COMMENT 'Custom field 3. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliateCustom4 COMMENT 'Custom field 4. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AffiliateCustom5 COMMENT 'Custom field 5. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN PaymentDetailsID COMMENT 'Primary payment method. References dbo.tblaff_PaymentDetails [done]. Links to banking/payment info for commission disbursement. Has NC index. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IBAffiliate COMMENT 'Introducing Broker flag/parent ID. 0=not an IB, >0=this affiliate is an IB (value may indicate parent IB structure). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Reports_Tiers_Summary COMMENT 'Controls whether the affiliate can see tier summary reports in the portal. 1=visible, 0=hidden. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Reports_Tiers_Details COMMENT 'Controls whether the affiliate can see detailed tier reports in the portal. 1=visible, 0=hidden. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IBCountries COMMENT 'Comma-separated or JSON list of country IDs where this IB affiliate can operate. NULL means no geographic restriction. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN ManagerID_Demo COMMENT 'Demo account manager ID assigned to this affiliate. Default 36. Used for demo/sandbox environment tracking. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN ManagerID_Real COMMENT 'Real/production account manager ID assigned to this affiliate. Default 45. Determines which manager oversees this affiliate relationship. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN MarketingExpenseID COMMENT 'Marketing expense category. References dbo.tblaff_MarketingExpense [done]. Default 1. Categorizes the affiliate''s marketing cost allocation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IBProviderID COMMENT 'The provider/partner ID within the IB hierarchy. Default 1. For IB sub-affiliates, identifies their parent IB. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IBLabelID COMMENT 'Label/brand identifier within the IB structure. Default 0. Supports white-label IB configurations. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN HideExceptIBCRM COMMENT 'Visibility flag. 1=this affiliate is hidden from standard admin views, only visible in IB CRM tools. 0=visible everywhere. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CanShowCashier COMMENT 'Controls whether the affiliate can access cashier/payment features in the portal. 1=cashier visible, 0=hidden. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CommunicationLangID COMMENT 'Preferred communication language for emails and notifications. Default 0. References a language lookup. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CountImpressions COMMENT 'Controls whether banner impressions are tracked for this affiliate. 1=track impressions, 0=clicks only. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CountClicks COMMENT 'Controls whether clicks are tracked for this affiliate. 1=track clicks (default), 0=no click tracking. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN PrefferedCurrencyID COMMENT 'Affiliate''s preferred payment currency. References Dictionary.Currency (1=USD, 2=EUR, 3=GBP, 4=CAD, 5=AUD, 38=RMB). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN PaymentDetails2ID COMMENT 'Secondary payment method. References dbo.tblaff_PaymentDetails [done]. NULL if only one payment method configured. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN PaymentDetails3ID COMMENT 'Tertiary payment method. References dbo.tblaff_PaymentDetails [done]. NULL if fewer than three payment methods configured. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN PaymentDetailsDefault COMMENT 'Indicates which payment method is active for disbursement. 1=primary (PaymentDetailsID), 2=secondary, 12=specific method (most common at 93%). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN BirthDayDate COMMENT 'Affiliate''s date of birth. Required for individual affiliates in some jurisdictions for KYC compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CountryID COMMENT 'Normalized country reference. FK to dbo.tblaff_Country.CountryID [done]. Default 0. The authoritative country field (replaces legacy Country text field). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IdentificationTypeID COMMENT 'Type of government ID submitted. FK to Dictionary.IdentificationType: 1=Passport, 2=ID Card, 3=NI Number, etc. Part of KYC compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IdentificationNumber COMMENT 'The actual ID document number corresponding to IdentificationTypeID. Stored for KYC verification records. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN NeedsResetPassword COMMENT 'Forces password change on next login. 1=must reset, NULL/0=normal login. Set by admins for security events. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN GCID COMMENT 'Global Customer ID linking this affiliate to the main trading platform''s customer system. Has filtered NC index (WHERE GCID IS NOT NULL). Enables cross-platform identity resolution. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AccountTypeID COMMENT 'Entity type classification: 0=Legacy/unclassified (181), 1=Individual (43,513), 2=Corporate (12). Determines required compliance fields. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN EntityName COMMENT 'Legal entity name for corporate affiliates (AccountTypeID=2). The registered company name for KYP documentation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IncorporationNumber COMMENT 'Company registration/incorporation number for corporate affiliates. Required for KYP compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN IncorporationDate COMMENT 'Date the corporate entity was incorporated. Part of KYP due diligence. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN LeiNumber COMMENT 'Legal Entity Identifier (LEI) - a 20-character alphanumeric code required for corporate entities under MiFID II and other financial regulations. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN ContactPersonFullName COMMENT 'Full name of the authorized contact person for corporate affiliates. MASKED with default(). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CreationSourceID COMMENT 'How the affiliate account was created. FK to Dictionary.CreationSource: 1=Local (admin), 2=Azure (AD sync), 3=Test. NULL for legacy accounts. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN AzureObjectId COMMENT 'Azure Active Directory object identifier for SSO-provisioned affiliates. Has unique filtered NC index (WHERE NOT NULL). Enables SSO login and identity sync. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN Trace COMMENT 'Computed JSON column capturing session context: HostName, AppName, SUserName, SPID, DBName, ObjectName. Audit trail for who modified the record. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN ValidFrom COMMENT 'Temporal system column. Row start time for system versioning. GENERATED ALWAYS AS ROW START HIDDEN. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN ValidTo COMMENT 'Temporal system column. Row end time for system versioning. GENERATED ALWAYS AS ROW END HIDDEN. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN PhoneCountryID COMMENT 'International dialing code/country for the affiliate''s phone number. Structured replacement for the legacy Telephone field. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN PhoneNumber COMMENT 'Affiliate''s phone number (without country code). Paired with PhoneCountryID for the full international number. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN StreetNumber COMMENT 'Street/building number component of the affiliate''s address. Added to support structured address formats. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN LoginName_LOWER COMMENT 'Computed column: lower(LoginName). Provides case-insensitive login name lookups via NC index without collation overhead. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates ALTER COLUMN CalculateCommission COMMENT 'Commission calculation method flag: 0=standard calculation (99.8%), 1=custom/override calculation (96 accounts). Controls which commission engine processes this affiliate''s earnings. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';

-- ---- UC Target: main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked (business_group=BI_DB) ----
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked SET TBLPROPERTIES (
    'comment' = 'Central entity table for the affiliate management platform, storing all affiliate partner accounts with their profile, credentials, configuration, compliance data, and commission settings. Source: fiktivo.dbo.tblaff_Affiliates on the fiktivo production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/ExperianceDBs/fiktivo/Wiki/dbo/Tables/dbo.tblaff_Affiliates.md).'
);

ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'fiktivo',
    'source_schema' = 'dbo',
    'source_table' = 'tblaff_Affiliates',
    'business_group' = 'BI_DB',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliateID COMMENT 'Primary key. The unique identifier for each affiliate in the system. Referenced by virtually every other table via AffiliateID columns. NOT FOR REPLICATION identity. NC PK (clustered index is multi-column). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN UserID COMMENT 'Links to dbo.tblaff_User for admin portal user management. Default 0 indicates no linked admin user. Used by triggers and management procedures. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliatesGroupsID COMMENT 'Organizational group assignment. References dbo.tblaff_AffiliatesGroups.AffiliatesGroupsID [done]. Default 2 is the standard/default group. Groups control manager assignments and reporting segmentation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN LoginName COMMENT 'Affiliate portal login username. MASKED with default() for dynamic data masking. Has dedicated NC index for login lookups. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN LoginPassword COMMENT 'Affiliate portal password. MASKED with default() for dynamic data masking. Stored as plaintext/hash depending on era of creation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Phrase COMMENT 'Security phrase for account recovery or verification. Legacy field from original affiliate system. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Contact COMMENT 'Primary contact person name for the affiliate. For corporate affiliates, this is the business contact. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Email COMMENT 'Affiliate''s email address. Has dedicated NC index. Used for notifications, password resets, and communication. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN TaxID COMMENT 'Tax identification number for the affiliate. Required for payment processing and regulatory reporting in some jurisdictions. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN SocialSecurity COMMENT 'Social security or national insurance number. Required for US-based affiliates for IRS W-9 reporting. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CompanyName COMMENT 'Legal company name for corporate affiliates. MASKED with default(). Used in payment processing and compliance documentation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CompanyAddress COMMENT 'Business address of the affiliate. MASKED with default(). Required for payment and compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Country COMMENT 'Country name as free text. Legacy field - CountryID (column 54) is the normalized version used by newer code. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN City COMMENT 'City of the affiliate''s business address. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN State COMMENT 'State/province of the affiliate''s business address. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Zip COMMENT 'Postal/ZIP code of the affiliate''s business address. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Telephone COMMENT 'Primary telephone number. Legacy field - PhoneCountryID + PhoneNumber are the structured replacement. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Fax COMMENT 'Fax number. Legacy communication field. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN WebSiteURL COMMENT 'URL of the affiliate''s website. Used for compliance review and traffic source verification. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN WebSiteTitle COMMENT 'Title/name of the affiliate''s website. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Comments COMMENT 'Free-text notes about the affiliate. Used by admins for internal annotations. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AccountStatus COMMENT 'Affiliate account lifecycle state: 0=Inactive/Pending (default), 1=Active, 2=Suspended, 4=Under Review, 5=Rejected. Controls portal access and commission eligibility. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN SendEmailNotification COMMENT 'Controls whether the affiliate receives automated email notifications (commission reports, announcements). 1=receive emails, 0=no emails. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN DateCreated COMMENT 'Timestamp of affiliate account creation. Set automatically on INSERT. Oldest records date to 2007-07-01. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AcceptedAgreement COMMENT 'Whether the affiliate has accepted the affiliate program terms and conditions. 1=accepted, 0=not yet accepted. Required before commissions can be paid. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliateTypeID COMMENT 'Commission plan type. References dbo.tblaff_AffiliateTypes.AffiliateTypeID [done]. Determines commission rates, CPA slabs, and payment terms. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN VATNumber COMMENT 'EU VAT registration number. Required for European affiliates for proper invoicing and tax compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliateCustom1 COMMENT 'Custom field 1. Configurable per deployment for additional affiliate metadata. Sometimes used for last name or additional contact info. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliateCustom2 COMMENT 'Custom field 2. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliateCustom3 COMMENT 'Custom field 3. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliateCustom4 COMMENT 'Custom field 4. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AffiliateCustom5 COMMENT 'Custom field 5. Configurable per deployment. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN PaymentDetailsID COMMENT 'Primary payment method. References dbo.tblaff_PaymentDetails [done]. Links to banking/payment info for commission disbursement. Has NC index. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IBAffiliate COMMENT 'Introducing Broker flag/parent ID. 0=not an IB, >0=this affiliate is an IB (value may indicate parent IB structure). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Reports_Tiers_Summary COMMENT 'Controls whether the affiliate can see tier summary reports in the portal. 1=visible, 0=hidden. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Reports_Tiers_Details COMMENT 'Controls whether the affiliate can see detailed tier reports in the portal. 1=visible, 0=hidden. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IBCountries COMMENT 'Comma-separated or JSON list of country IDs where this IB affiliate can operate. NULL means no geographic restriction. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN ManagerID_Demo COMMENT 'Demo account manager ID assigned to this affiliate. Default 36. Used for demo/sandbox environment tracking. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN ManagerID_Real COMMENT 'Real/production account manager ID assigned to this affiliate. Default 45. Determines which manager oversees this affiliate relationship. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN MarketingExpenseID COMMENT 'Marketing expense category. References dbo.tblaff_MarketingExpense [done]. Default 1. Categorizes the affiliate''s marketing cost allocation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IBProviderID COMMENT 'The provider/partner ID within the IB hierarchy. Default 1. For IB sub-affiliates, identifies their parent IB. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IBLabelID COMMENT 'Label/brand identifier within the IB structure. Default 0. Supports white-label IB configurations. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN HideExceptIBCRM COMMENT 'Visibility flag. 1=this affiliate is hidden from standard admin views, only visible in IB CRM tools. 0=visible everywhere. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CanShowCashier COMMENT 'Controls whether the affiliate can access cashier/payment features in the portal. 1=cashier visible, 0=hidden. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CommunicationLangID COMMENT 'Preferred communication language for emails and notifications. Default 0. References a language lookup. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CountImpressions COMMENT 'Controls whether banner impressions are tracked for this affiliate. 1=track impressions, 0=clicks only. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CountClicks COMMENT 'Controls whether clicks are tracked for this affiliate. 1=track clicks (default), 0=no click tracking. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN PrefferedCurrencyID COMMENT 'Affiliate''s preferred payment currency. References Dictionary.Currency (1=USD, 2=EUR, 3=GBP, 4=CAD, 5=AUD, 38=RMB). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN PaymentDetails2ID COMMENT 'Secondary payment method. References dbo.tblaff_PaymentDetails [done]. NULL if only one payment method configured. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN PaymentDetails3ID COMMENT 'Tertiary payment method. References dbo.tblaff_PaymentDetails [done]. NULL if fewer than three payment methods configured. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN PaymentDetailsDefault COMMENT 'Indicates which payment method is active for disbursement. 1=primary (PaymentDetailsID), 2=secondary, 12=specific method (most common at 93%). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN BirthDayDate COMMENT 'Affiliate''s date of birth. Required for individual affiliates in some jurisdictions for KYC compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CountryID COMMENT 'Normalized country reference. FK to dbo.tblaff_Country.CountryID [done]. Default 0. The authoritative country field (replaces legacy Country text field). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IdentificationTypeID COMMENT 'Type of government ID submitted. FK to Dictionary.IdentificationType: 1=Passport, 2=ID Card, 3=NI Number, etc. Part of KYC compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IdentificationNumber COMMENT 'The actual ID document number corresponding to IdentificationTypeID. Stored for KYC verification records. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN NeedsResetPassword COMMENT 'Forces password change on next login. 1=must reset, NULL/0=normal login. Set by admins for security events. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN GCID COMMENT 'Global Customer ID linking this affiliate to the main trading platform''s customer system. Has filtered NC index (WHERE GCID IS NOT NULL). Enables cross-platform identity resolution. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AccountTypeID COMMENT 'Entity type classification: 0=Legacy/unclassified (181), 1=Individual (43,513), 2=Corporate (12). Determines required compliance fields. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN EntityName COMMENT 'Legal entity name for corporate affiliates (AccountTypeID=2). The registered company name for KYP documentation. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IncorporationNumber COMMENT 'Company registration/incorporation number for corporate affiliates. Required for KYP compliance. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN IncorporationDate COMMENT 'Date the corporate entity was incorporated. Part of KYP due diligence. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN LeiNumber COMMENT 'Legal Entity Identifier (LEI) - a 20-character alphanumeric code required for corporate entities under MiFID II and other financial regulations. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN ContactPersonFullName COMMENT 'Full name of the authorized contact person for corporate affiliates. MASKED with default(). (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CreationSourceID COMMENT 'How the affiliate account was created. FK to Dictionary.CreationSource: 1=Local (admin), 2=Azure (AD sync), 3=Test. NULL for legacy accounts. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN AzureObjectId COMMENT 'Azure Active Directory object identifier for SSO-provisioned affiliates. Has unique filtered NC index (WHERE NOT NULL). Enables SSO login and identity sync. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN Trace COMMENT 'Computed JSON column capturing session context: HostName, AppName, SUserName, SPID, DBName, ObjectName. Audit trail for who modified the record. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN ValidFrom COMMENT 'Temporal system column. Row start time for system versioning. GENERATED ALWAYS AS ROW START HIDDEN. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN ValidTo COMMENT 'Temporal system column. Row end time for system versioning. GENERATED ALWAYS AS ROW END HIDDEN. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN PhoneCountryID COMMENT 'International dialing code/country for the affiliate''s phone number. Structured replacement for the legacy Telephone field. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN PhoneNumber COMMENT 'Affiliate''s phone number (without country code). Paired with PhoneCountryID for the full international number. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN StreetNumber COMMENT 'Street/building number component of the affiliate''s address. Added to support structured address formats. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN LoginName_LOWER COMMENT 'Computed column: lower(LoginName). Provides case-insensitive login name lookups via NC index without collation overhead. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
ALTER TABLE main.bi_db.bronze_fiktivo_dbo_tblaff_affiliates_masked ALTER COLUMN CalculateCommission COMMENT 'Commission calculation method flag: 0=standard calculation (99.8%), 1=custom/override calculation (96 accounts). Controls which commission engine processes this affiliate''s earnings. (Tier 1 - upstream wiki, fiktivo.dbo.tblaff_Affiliates)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 09:51:26 UTC
-- Bronze deploy: fiktivo batch 1
-- ====================
