-- =============================================================================
-- Databricks ALTER Script: eMoney_dbo.eMoney_Fact_Transaction_Status
-- Generated: 2026-04-21 | 15-phase pipeline
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status
-- Resolved via: information_schema bulk query
-- Classification: Non-standard
-- =============================================================================

ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status SET TBLPROPERTIES (
    'comment' = '`eMoney_Fact_Transaction_Status` is the **full status history fact table** for eToro Money (eTM) fiat transactions. Unlike `eMoney_Dim_Transaction` (which retains only the latest status per transaction), this table retains **every status event** from `FiatTransactionsStatuses` - including intermediate states such as Authorized, Reserved, or Rejected - before a transaction reaches its terminal state. The table is populated by **Step 11** of `SP_eMoney_DimFact_Transaction`, which shares the same 11-step pipeline as `eMoney_Dim_Transaction`. Both tables read from the same `#leveled_txs` staging CTE (all status events), but diverge at the final INSERT step: - `eMoney_Dim_Transaction` (Step 10): inserts `WHERE RNDesc=1` - latest status per transaction only - `eMoney_Fact_Transaction_Status` (Step 11): inserts **without RNDesc filter** - all status events The row count difference (~3.7M more rows than `eMoney_Dim_Transaction`) represents transactions that went through multiple status events (e.g., Authorized -> S...'
);

ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status SET TAGS (
    'domain' = 'general',
    'object_type' = 'table',
    'source_schema' = 'eMoney_dbo',
    'refresh_frequency' = 'daily',
    'source_system' = 'Synapse',
    'synapse_distribution' = 'HASH(CID)',
    'synapse_index' = 'CLUSTERED COLUMNSTORE INDEX (no clustering key; no NCIs)',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = '15-phase'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TransactionID` COMMENT 'Surrogate key for the fiat transaction from FiatDwhDB.dbo.FiatTransactions.Id. Each transaction appears on MULTIPLE rows in this table (one row per status event). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountID` COMMENT 'Auto-incrementing surrogate primary key. Referenced by all child entity tables as the FK to the account. Passthrough from FiatTransactions.AccountId -> FK to FiatAccount.Id. (Tier 1 - dbo.FiatAccount)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `GCID` COMMENT 'Global Customer ID. Identifies the customer across all eToro platforms (trading, crypto, fiat). Part of the unique constraint with AccountGuid. Used in Confluence queries as the primary customer lookup key. Passthrough via eMoney_Dim_Account snapshot (Step 01). (Tier 1 - dbo.FiatAccount)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CID` COMMENT 'Customer ID - platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. Renamed from RealCID in DWH_dbo.Dim_Customer. Passthrough via eMoney_Dim_Account snapshot. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CardID` COMMENT 'Auto-incrementing surrogate primary key. Referenced by FiatCardStatuses.CardId, FiatCardInstances (implicit), and CardsProvidersMapping.CardId. FK from FiatTransactions.CardId. NULL for non-card transactions. (Tier 1 - dbo.FiatCards)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderCardID` COMMENT 'Provider-side card identifier from CardsProvidersMapping, sourced from eMoney_Dim_Account snapshot (RN_Card_Desc=1 join). NULL for non-card transactions or accounts without a provider card mapping. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CurrencyBalanceID` COMMENT 'Auto-incrementing surrogate PK. Referenced by FiatTransactions, FiatCurrencyBalancesStatuses, CurrencyBalancesProvidersMapping, PaymentSpecifications, FiatBankAccount, and BalanceReports. FK from FiatTransactions.CurrencyBalanceId. (Tier 1 - dbo.FiatCurrencyBalances)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderCurrencyBalanceID` COMMENT 'Provider-side currency balance identifier from CurrencyBalancesProvidersMapping, sourced from eMoney_Dim_Account snapshot (RN_CurrencyBalance_Desc=1 join). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ExternalBankAccountID` COMMENT 'Auto-incrementing surrogate primary key for the external bank account record. FK from FiatTransactions.ExternalBankAccountId -> dbo.FiatBankAccount.Id. NULL for non-bank-transfer transactions. (Tier 1 - dbo.FiatBankAccount)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxTypeID` COMMENT 'Transaction type identifier. 1=CardPayment, 2=ContactlessPayment, 3=CardCashWithdrawal, 4=CardRefund, 5=Transfer, 6=TransferReceived, 7=PaymentReceived, 8=Payment, 9=Refund, 10=Fee, 11=CreditBankAccount, 12=DebitBankAccount, 13=OnlinePayment, 14=DirectDebit (15=CryptoToFiat via dictionary). Passthrough from FiatTransactions.TransactionTypeId. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxType` COMMENT 'Transaction type display name for TxTypeID, resolved from External_FiatDwhDB_Dictionary_TransactionTypes.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxTypeCategory` COMMENT 'Grouped transaction type bucket: Card (TxTypeID 1-4, 13), IBAN (TxTypeID 5-8), Other (all other TxTypeIDs). ETL CASE expression in Step 03. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxClientBalanceCategory` COMMENT 'Client-facing balance impact category. ETL CASE maps all 14 TxTypeID values to one of 9 labels (e.g., Payments, Refunds, TransferIn, TransferOut, CashWithdrawal, Fee, DirectDebit, CryptoToFiat, Other). Step 03. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MerchantID` COMMENT 'Merchant identifier from FiatTransactions.MerchantId. Populated for card POS and online transactions; NULL for bank transfers and internal transactions. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCreatedDate` COMMENT 'Date on which the transaction record was created in FiatDwhDB. DWH-derived: CAST(FiatTransactions.Created AS DATE). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCreatedDateID` COMMENT 'YYYYMMDD integer date key for TxCreatedDate. DWH-derived: CONVERT(VARCHAR(8), FiatTransactions.Created, 112). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLabel` COMMENT 'Free-text label from FiatTransactions.Label. Contains merchant names, IBAN references, or internal notes depending on transaction type. May contain PII. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalTime` COMMENT 'Local transaction timestamp from FiatTransactions.TransactionLocalTime. The authoritative event time for the transaction itself (same for all status event rows of the same transaction). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalDate` COMMENT 'Date portion of TxLocalTime. DWH-derived: CAST(TransactionLocalTime AS DATE). Used as the reference date for customer snapshots (Step 08) and USD approximation (Step 06). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalDateID` COMMENT 'YYYYMMDD integer date key for TxLocalDate. DWH-derived: CONVERT(VARCHAR(8), TransactionLocalTime, 112). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalCountryNumericISO` COMMENT 'ISO 3166-1 numeric country code for the country where the transaction occurred. Passthrough from FiatTransactions.TransactionCountryIso. NULL for non-card or non-localized transactions. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalCountryNameISO` COMMENT 'Country display name for TxLocalCountryNumericISO, resolved via eMoney_Country_Codes_Mapping_ISO bridge to DWH_dbo.Dim_Country.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ReferenceNumber` COMMENT 'External payment reference from FiatTransactions.ReferenceNumber. Populated for IBAN-based transactions (Faster Payments, SEPA). May contain PII. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCategoryID` COMMENT 'Transaction category from FiatTransactions.TransactionCategory. 1=CardTransaction, 2=BankingTransaction, 3=TransferTransaction, 4=BalanceAdjustmentTransaction. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCategory` COMMENT 'Transaction category display name for TxCategoryID, resolved from External_FiatDwhDB_Dictionary_TransactionCategories.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PaymentSchemaTypeID` COMMENT 'Payment scheme identifier. 0=Unknown, 1=Transfer, 2=FasterPayments, 3=Chaps, 4=Bacs, 5=SEPAstandart (note: source typo preserved), 6=SEPAinstantTransfer. IDs 8 and 10 exist in data but have no dictionary name (NULL PaymentSchemaType). Also NULL for some transactions. Passthrough from FiatTransactions.PaymentSchemeId. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PaymentSchemaType` COMMENT 'Payment scheme display name for PaymentSchemaTypeID, resolved from External_FiatDwhDB_Dictionary_PaymentSchemaType.Name. NULL for unknown/unmapped schemes. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PaymentReference` COMMENT 'Payment-specific reference from FiatTransactions.PaymentReference. Bank-side reference for SEPA/Faster Payments. May contain PII. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MoneyCorrelationID` COMMENT 'Correlation ID linking this transaction to related money movements. CAST(FiatTransactions.MoneyCorrelationId AS VARCHAR(2000)). Used for cross-transaction tracing. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderID` COMMENT 'Payment provider identifier from TransactionsProvidersMapping.ProviderId (latest mapping, RN_Desc=1 by TransactionId). Identifies which payment processor handled this transaction. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderDesc` COMMENT 'Provider display name for ProviderID, resolved from External_FiatDwhDB_Dictionary_Providers.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderTransactionID` COMMENT 'Provider-side transaction identifier from TransactionsProvidersMapping.TransactionProviderId (latest mapping, RN_Desc=1). Used for reconciliation with provider records. Type is float in DDL - cast to BIGINT for equality predicates. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountProgramID` COMMENT 'Account program type: 0=Unknown, 1=card (default), 2=iban. Determines the fundamental product type (card-based vs IBAN-based banking). DWH note: current program at ETL run time, sourced from eMoney_Dim_Account snapshot (not at transaction date). (Tier 1 - dbo.FiatAccount)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountProgram` COMMENT 'Account program display name for AccountProgramID, resolved from eMoney_Dictionary_AccountProgram. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountSubProgramID` COMMENT 'Specific sub-program variant: 1-16 (e.g., Card Premium UK, IBAN EU Green). FK to dbo.SubPrograms. NULL if not yet assigned to a specific variant. DWH note: current sub-program at ETL run time, sourced from eMoney_Dim_Account snapshot (not at transaction date). (Tier 1 - dbo.FiatAccount)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountSubProgram` COMMENT 'Sub-program display name for AccountSubProgramID, resolved from eMoney_dbo.SubPrograms (16 active programs across UK/EU/AUS regions). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `IsValidETM` COMMENT 'eToro Money validity flag (current at ETL run time from eMoney_Dim_Account snapshot). 1 when IsValidCustomer=1 AND IsTestAccount=0 AND IsCancelledAccount=0. Standard filter for eTM production analytics. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `IsValidCustomer` COMMENT 'DWH-computed validity flag at TxLocalDate (from Fact_SnapshotCustomer snapshot, Step 08). 1 when not Popular Investor, not label 30/26, and not CountryID=250 at the time of the transaction. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ClubIDTxDate` COMMENT 'PlayerLevelID from DWH_dbo.Fact_SnapshotCustomer at TxLocalDateID range. Represents the customer''s club at the time of the transaction. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ClubTxDate` COMMENT 'Club display name for ClubIDTxDate, resolved from DWH_dbo.Dim_PlayerLevel.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RegulationIDTxDate` COMMENT 'RegulationID from DWH_dbo.Fact_SnapshotCustomer at TxLocalDateID range. Represents the customer''s regulatory entity at the time of the transaction. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RegulationTxDate` COMMENT 'Regulation display name for RegulationIDTxDate, resolved from DWH_dbo.Dim_Regulation.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CountryIDTxDate` COMMENT 'CountryID from DWH_dbo.Fact_SnapshotCustomer at TxLocalDateID range. Represents the customer''s country at the time of the transaction. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CountryTxDate` COMMENT 'Country display name for CountryIDTxDate, resolved from DWH_dbo.Dim_Country.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PlayerStatusIDTxDate` COMMENT 'PlayerStatusID from DWH_dbo.Fact_SnapshotCustomer at TxLocalDateID range. Represents the customer''s compliance/trading status at the time of the transaction. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PlayerStatusTxDate` COMMENT 'Player status display name for PlayerStatusIDTxDate, resolved from DWH_dbo.Dim_PlayerStatus.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `FiatTransactionStatusRunningID` COMMENT 'Surrogate PK of this individual status event row, sourced from FiatTransactionsStatuses.Id. Uniquely identifies a single status event for a transaction. Also used as the join key to the USD approximation pipeline (#usdapprox join). KEY DIFFERENCE from eMoney_Dim_Transaction (which has IsTxSettled at this position). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusID` COMMENT 'Transaction lifecycle status for THIS event (not necessarily the latest). 0=Failed, 1=Authorized, 2=Settled, 3=Rejected, 4=Returned, 5=Expired, 6=Reserved, 7=Cancelled. Passthrough from FiatTransactionsStatuses.TransactionStatusId. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatus` COMMENT 'Transaction status display name for TxStatusID, resolved from External_FiatDwhDB_Dictionary_TransactionStatuses.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CountStatusChanges` COMMENT 'Total number of status events for this transaction (MAX(RNDesc) per TransactionID). Denormalized - same value on all rows for a given TransactionID. 1 = single-status transaction; >1 = went through multiple states. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AuthorizationTypeID` COMMENT 'Authorization method used in THIS status event from FiatTransactionsStatuses. 13 possible values (e.g., PIN, Contactless, Online, 3DS, Chargeback-related). Passthrough from FiatTransactionsStatuses.AuthorizationType. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AuthorizationType` COMMENT 'Authorization type display name for AuthorizationTypeID, resolved from External_FiatDwhDB_Dictionary_AuthorizationTypes.Name. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `IsTxStatusCBRelevant` COMMENT '1 if THIS status event is relevant for chargeback analysis: TxStatusID IN (2,3,4) AND AuthorizationTypeID NOT IN (12,13). Both conditions must hold simultaneously. ETL CASE in Step 04. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MoneyMoveDirection` COMMENT 'Direction of money flow for THIS event based on HolderAmount: HolderAmount < 0 = MoneyOut; HolderAmount > 0 = MoneyIn; HolderAmount = 0 = Error. ETL CASE in Step 04. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `HolderCurrencyISO` COMMENT 'ISO 4217 numeric currency code for the holder''s balance currency (e.g., 826=GBP, 978=EUR, 208=DKK). Passthrough from FiatTransactionsStatuses.HolderCurrency (this event). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `HolderCurrencyDesc` COMMENT 'Currency display name for HolderCurrencyISO, resolved via eMoney_Currency_Mapping_ISO.CurrencyAlphaThreeCode from the instrument mapping COALESCE(buy-side, sell-side). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `HolderAmount` COMMENT 'Amount debited/credited to the holder''s balance in HolderCurrency for THIS event. Negative = debit (MoneyOut); positive = credit (MoneyIn). Passthrough from FiatTransactionsStatuses.HolderAmount. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `LocalCurrencyISO` COMMENT 'ISO 4217 numeric currency code for the local transaction currency (e.g., the merchant''s currency for card transactions). Passthrough from FiatTransactionsStatuses.TransactionCurrency. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `LocalCurrencyDesc` COMMENT 'Currency display name for LocalCurrencyISO, resolved from eMoney_Currency_Mapping_ISO.CurrencyName. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `LocalAmount` COMMENT 'Amount in the local transaction currency for THIS event. Passthrough from FiatTransactionsStatuses.TransactionAmount. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `USDAmountApprox` COMMENT 'Approximate USD equivalent of HolderAmount at TxLocalDate for THIS status event. Joined via FiatTransactionStatusRunningID. ROUND(HolderAmount × (Ask+Bid)/2, 2). NULL for DKK. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `USDRateApprox` COMMENT 'USD mid-rate used for USDAmountApprox for THIS event. ROUND((Ask+Bid)/2, 2) from Fact_CurrencyPriceWithSplit at TxLocalDate. NULL for DKK transactions. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccumulatedAmount` COMMENT 'Running accumulated balance in HolderCurrency at THIS transaction''s status event. Passthrough from FiatTransactionsStatuses.AccumulatedAmount. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccumulatedUSDAmountApprox` COMMENT 'Approximate USD equivalent of AccumulatedAmount at TxLocalDate for THIS event. Same mid-rate logic as USDAmountApprox. NULL for DKK. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusModificationTime` COMMENT 'Timestamp of THIS status change event (FiatTransactionsStatuses.TransactionOccured). The event time for this particular row in the status history. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusModificationDate` COMMENT 'Date portion of TxStatusModificationTime. DWH-derived: CAST(TransactionOccured AS DATE). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusModificationDateID` COMMENT 'YYYYMMDD integer date key for TxStatusModificationDate. DWH-derived: CONVERT(VARCHAR(8), TransactionOccured, 112). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusCreatedDate` COMMENT 'Date on which THIS status event was created in FiatDwhDB. DWH-derived: CAST(FiatTransactionsStatuses.Created AS DATE). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusCreatedDateID` COMMENT 'YYYYMMDD integer date key for TxStatusCreatedDate. DWH-derived: CONVERT(VARCHAR(8), FiatTransactionsStatuses.Created, 112). (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TXStatusCorrelationID` COMMENT 'Correlation ID from THIS status event. CAST(FiatTransactionsStatuses.CorrelationId AS VARCHAR(2000)). Used for tracing status events across systems. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RiskRuleCodes` COMMENT 'Risk rule codes triggered for THIS status event. CAST(FiatTransactionsStatuses.RiskRuleCodes AS VARCHAR(2000)). NULL when no risk rules were triggered. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MarkTransactionAsSuspiciousRiskAction` COMMENT 'Risk action flag: 1 if the risk engine marked this status event as suspicious. Passthrough from FiatTransactionsStatuses. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ChangeCardStatusToRiskRiskAction` COMMENT 'Risk action flag: 1 if the risk engine triggered a card status change to ''Risk'' on this status event. Passthrough from FiatTransactionsStatuses. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ChangeAccountStatusToSuspendedRiskAction` COMMENT 'Risk action flag: 1 if the risk engine triggered account suspension on this status event. Passthrough from FiatTransactionsStatuses. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RejectTransactionRiskAction` COMMENT 'Risk action flag: 1 if the risk engine rejected this status event. Passthrough from FiatTransactionsStatuses. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `UpdateDate` COMMENT 'GETDATE() at INSERT time. Marks when the daily ETL refresh ran; not a business timestamp. (Tier 2 - SP_eMoney_DimFact_Transaction)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `SourceCugTransactionID` COMMENT 'Source transaction ID in the CUG (eToro Crypto-to-Fiat) system. Added 2025-09-08 (Inessa Ovadia). NULL for transactions created before this feature was deployed or for non-CUG transactions. (Tier 2 - SP_eMoney_DimFact_Transaction)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TransactionID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `GCID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CardID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderCardID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CurrencyBalanceID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderCurrencyBalanceID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ExternalBankAccountID` SET TAGS ('pii' = 'direct');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxTypeID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxType` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxTypeCategory` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxClientBalanceCategory` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MerchantID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCreatedDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCreatedDateID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLabel` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalTime` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalDateID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalCountryNumericISO` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxLocalCountryNameISO` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ReferenceNumber` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCategoryID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxCategory` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PaymentSchemaTypeID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PaymentSchemaType` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PaymentReference` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MoneyCorrelationID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderDesc` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ProviderTransactionID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountProgramID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountProgram` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountSubProgramID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccountSubProgram` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `IsValidETM` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `IsValidCustomer` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ClubIDTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ClubTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RegulationIDTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RegulationTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CountryIDTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CountryTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PlayerStatusIDTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `PlayerStatusTxDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `FiatTransactionStatusRunningID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `CountStatusChanges` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AuthorizationTypeID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AuthorizationType` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `IsTxStatusCBRelevant` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MoneyMoveDirection` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `HolderCurrencyISO` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `HolderCurrencyDesc` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `HolderAmount` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `LocalCurrencyISO` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `LocalCurrencyDesc` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `LocalAmount` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `USDAmountApprox` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `USDRateApprox` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccumulatedAmount` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `AccumulatedUSDAmountApprox` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusModificationTime` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusModificationDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusModificationDateID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusCreatedDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TxStatusCreatedDateID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `TXStatusCorrelationID` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RiskRuleCodes` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `MarkTransactionAsSuspiciousRiskAction` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ChangeCardStatusToRiskRiskAction` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `ChangeAccountStatusToSuspendedRiskAction` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `RejectTransactionRiskAction` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `UpdateDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_emoney_dbo_emoney_fact_transaction_status ALTER COLUMN `SourceCugTransactionID` SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-05 13:24:40 UTC
-- Batch deploy resume: eMoney_dbo deploy batch 10
-- Statements: 156/156 succeeded
-- ====================
