-- =============================================================================
-- Databricks ALTER Script: eMoney_dbo.eMoney_Customer_Risk_Assessment_History
-- Generated: 2026-04-21 | 15-phase pipeline
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history
-- Resolved via: information_schema bulk query
-- Classification: Non-standard
-- =============================================================================

ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history SET TBLPROPERTIES (
    'comment' = '`eMoney_Customer_Risk_Assessment_History` is the **class-change audit log** for the eToro Money AML/KYC risk engine. Where `eMoney_Customer_Risk_Assessment` holds exactly one current-state row per customer (rebuilt daily via TRUNCATE + INSERT), History accumulates one row for each time a customer''s risk class (`ClientRisk`) changes. The same 120-column schema is shared across both tables, including all parameter scores (P1 - P32) and supporting customer attributes. Each History row is a complete snapshot of the customer''s state at the moment of the class change - not just a diff. **When a History row is inserted** (Step 32 of SP_eMoney_Customer_Risk_Assessment): - First time the customer appears in CRA (no prior History row for this CID) - The customer''s `ClientRisk` class changes from the last History row (e.g., Low -> Medium) **When a History row is NOT inserted**: - The customer''s class is unchanged from the last History row (Low stays Low) - Note: even if `Risk_Final_Result` changes (score movement within...'
);

ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history SET TAGS (
    'domain' = 'customer',
    'object_type' = 'table',
    'source_schema' = 'eMoney_dbo',
    'refresh_frequency' = 'unknown',
    'source_system' = 'Synapse',
    'synapse_distribution' = 'HASH(CID)',
    'synapse_index' = 'HEAP',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = '15-phase'
);

-- ---- Column Comments ----
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CID` COMMENT 'Customer ID - platform-internal primary key. Assigned at registration. Unique within etoro DB. Used as the universal customer identifier across all tables. DWH note: column renamed from RealCID (Dim_Customer) for eMoney context; joins back via CID=RealCID. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `GCID` COMMENT 'Group Customer ID - cross-product identity key linking the same person across eToro products/entities. NULL for older accounts predating GCID introduction. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientRiskDate` COMMENT 'Date the current ClientRisk class was first assigned. Preserved across daily runs while class is unchanged; reset to @Date (today) when class changes. For PEP overrides: ISNULL(last history date, @Date). For manual overrides: ExecutedDate from override sheet. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientRisk` COMMENT 'Customer AML risk classification. Values: Low (score <= @RiskLowerCut), Medium (> LowerCut <= UpperCut), High ( >=  @RiskUpperCut), Error (unresolvable). Thresholds are dynamic (ParameterID=98/99 in Fivetran classification table). Overridden to ''High'' for PEP customers; overridden to custom value for manual override CIDs. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientRiskAssignmentType` COMMENT 'Method by which ClientRisk was assigned. Values: ''Regular'' (algorithm), ''PEP Override'' (ScreeningStatus=''PEP''), ''Manual Override'' (CID in override Google Sheet). Override types take precedence over Regular in that order. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `Risk_Final_Result` COMMENT 'Weighted risk score: SUM(P1_RiskID×P1_Weight + P2_RiskID×P2_Weight + … + P32_RiskID×P32_Weight). P10 always contributes 0 (cancelled). Missing parameters contribute 99999-code row from classification table. Used to derive ClientRisk via threshold comparison. NOT modified by override logic - a PEP-forced customer retains the algorithm score. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PreviousClientRisk` COMMENT 'ClientRisk from the most recent row in eMoney_Customer_Risk_Assessment_History (latest ClientRiskDate DESC). ISNULL -> ''None'' for customers with no history. Used in ClientRiskDate preservation logic and History insert filter. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PreviousClientRiskDate` COMMENT 'ClientRiskDate from the most recent row in eMoney_Customer_Risk_Assessment_History. NULL for customers with no history. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `VerificationLevelID` COMMENT 'KYC verification level. FK to Dictionary.VerificationLevel. Values: 0=unverified, 1=partial, 2=intermediate, 3=fully verified. Default=0. (Tier 1 - BackOffice.Customer)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsValidCustomer` COMMENT 'DWH-computed validity flag from Dim_Customer. 1 when not Internal (PlayerLevelID != 4), not label 30/26, and CountryID != 250. Used for filtering non-standard customer profiles. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsDepositor` COMMENT '1 if the customer has made at least one deposit on the eToro trading platform. Sourced from Dim_Customer. Used in certain eTM analytics filters. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `AccountType` COMMENT 'Trading platform account type display name, resolved from DWH_dbo.Dim_AccountType via AccountTypeID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `Regulation` COMMENT 'Regulatory jurisdiction display name, resolved from DWH_dbo.Dim_Regulation via RegulationID. Top values: CySEC, FCA, BVI, ASIC, GAML. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `Club` COMMENT 'eToro Club tier display name, resolved from DWH_dbo.Dim_PlayerLevel via PlayerLevelID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientAge` COMMENT 'Customer''s age in years at SP execution date, computed as DATEDIFF(YEAR, BirthDate, @Date). Sentinel 99999 used when age > 120, <= 0, or BirthDate is NULL. This integer value feeds into P1 classification. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DateOfBirth` COMMENT 'Customer date of birth. Used in LinkedAccountHash1 for duplicate detection and in KYC age verification. DWH note: CAST from datetime to date (time component removed); column renamed from BirthDate. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DateOfReg` COMMENT 'Account registration date (renamed from Registered). Default=getdate(). DWH note: CAST from datetime to date; column renamed from RegisteredReal in Dim_Customer. (Tier 1 - Customer.CustomerStatic)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DateOfFTD` COMMENT 'Date of first trading platform deposit. CAST(FirstDepositDate AS DATE) from Dim_Customer. Sentinel ''19000101'' for non-depositors. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `BusinessDuration` COMMENT 'Bucketed tenure as eToro depositor, based on years since DateOfFTD. Values: 99999 (no FTD or sentinel ''19000101''), 1 (<1 year), 2 (1 - 3 years), 3 (>3 years). Feeds into P11 classification. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryAddress` COMMENT 'KYC address country display name, resolved from #dim_country (Dim_Country) via CountryID. Reflects the customer''s declared residential country. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryCitizenship` COMMENT 'Citizenship country display name, resolved from #dim_country via CitizenshipCountryID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryPOB` COMMENT 'Place of birth country display name, resolved from #dim_country via POBCountryID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryTIN` COMMENT 'Tax identification number (TIN) country display name. Resolved via a prioritised lookup: address-matching country > HRC country > non-HRC country from BI_DB_dbo.External_UserApiDB_Customer_ExtendedUserField (FieldId=6). NULL when no TIN country is registered. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryAddress_IsHRC` COMMENT 'High-risk country flag for the KYC address country. 0=not high risk, 1=high risk, 99999=not classified in CRA mapping. Sourced from Fivetran country risk map. Feeds into P2 classification. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryCitizenship_IsHRC` COMMENT 'High-risk country flag for the citizenship country. 0=not high risk, 1=high risk, 99999=not classified. Feeds into P3 classification. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryPOB_IsHRC` COMMENT 'High-risk country flag for the place of birth country. 0=not high risk, 1=high risk, 99999=not classified. Feeds into P4 classification. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryTIN_IsHRC` COMMENT 'High-risk country flag for the TIN country. 0=not high risk, 1=high risk, 99999=not classified or no TIN. Feeds into P16 classification. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `AccountStatus` COMMENT 'Trading platform account lifecycle status display name, resolved from DWH_dbo.Dim_AccountStatus via AccountStatusID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PlayerStatus` COMMENT 'Trading platform compliance status display name, resolved from DWH_dbo.Dim_PlayerStatus via PlayerStatusID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PlayerStatusReason` COMMENT 'Reason for the PlayerStatus (e.g., account closure reason), resolved from DWH_dbo.Dim_PlayerStatusReasons via PlayerStatusReasonID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PlayerStatusSubReason` COMMENT 'Sub-reason providing further granularity below PlayerStatusReason, resolved from DWH_dbo.Dim_PlayerStatusSubReasons via PlayerStatusSubReasonID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ScreeningStatus` COMMENT 'AML/sanctions screening status display name, resolved from DWH_dbo.Dim_ScreeningStatus. Source ID is ISNULL(ScreeningStatusID, 99999) before lookup. ''PEP'' value triggers PEP Override logic. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `EVStatus` COMMENT 'Electronic verification (identity check) status display name, resolved from DWH_dbo.Dim_EvMatchStatus. Source ID is ISNULL(EvMatchStatus, 99999) before lookup. Feeds into P15 classification. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DocumentStatus` COMMENT 'KYC document verification status display name, resolved from DWH_dbo.Dim_DocumentStatus via DocumentStatusID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PhoneStatus` COMMENT 'Phone verification status display name, resolved from DWH_dbo.Dim_PhoneVerified via PhoneVerifiedID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DocsOK` COMMENT 'Composite flag from Dim_Customer indicating all required KYC documents are accepted. Business definition follows Dim_Customer logic. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsIDProof` COMMENT 'Proof of identity status from Dim_Customer. ISNULL(raw value, 99999). Feeds into P18 classification. 99999=not available/unknown. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsAddressProof` COMMENT 'Proof of address status from Dim_Customer. ISNULL(raw value, 99999). Feeds into P19 classification. 99999=not available/unknown. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsPhoneVerified` COMMENT '1 if the customer''s phone number has been verified. Sourced from Dim_Customer. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsValidETM` COMMENT 'eToro Money validity flag from eMoney_Dim_Account. 1 when IsValidCustomer=1 AND IsTestAccount=0 AND IsCancelledAccount=0. NULL when the customer has no eTM account (LEFT JOIN). (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CurrencyBalanceID` COMMENT 'eTM currency balance identifier (FiatCurrencyBalances.Id). Primary key of the customer''s eTM money account. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CurrencyBalanceCreateDate` COMMENT 'Date the eTM currency balance was created. Sourced from eMoney_Dim_Account.CurrencyBalanceCreateDate. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CurrencyBalanceStatus` COMMENT 'Current status of the eTM currency balance (e.g., Active, Suspended). Sourced from eMoney_Dim_Account.CurrencyBalanceStatus. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountID` COMMENT 'eTM fiat account identifier (FiatAccount.Id). Parent account of the currency balance. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountCreateDate` COMMENT 'Date the eTM fiat account was created. Sourced from eMoney_Dim_Account.AccountCreateDate. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountStatus` COMMENT 'Current lifecycle status of the eTM fiat account (e.g., Active, Deleted). Sourced from eMoney_Dim_Account.AccountStatus. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountProgram` COMMENT 'eTM account programme type (e.g., iban, card). Sourced from eMoney_Dim_Account.AccountProgram. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountSubProgram` COMMENT 'eTM account sub-programme variant (e.g., IBAN EU Green, IBAN Standard UK). Sourced from eMoney_Dim_Account.AccountSubProgram. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_HasCard` COMMENT '1 if the customer has an associated eTM card; 0 otherwise. Sourced from eMoney_Dim_Account.HasCard. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CardStatus` COMMENT 'Current card status (e.g., Activated, Blocked). Sourced from eMoney_Dim_Account.CardStatus. NULL if HasCard=0. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_ProviderHolderID` COMMENT 'Provider-side customer holder identifier (Tribe payment provider). Sourced from eMoney_Dim_Account.ProviderHolderID. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMI_Date` COMMENT 'Date of the customer''s first money-in (FMI) transaction on the eTM platform. Sourced from eMoney_Panel_FirstDates via AccountID JOIN. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMI_Source` COMMENT 'Transaction type (channel) of the first money-in event. Sourced from eMoney_Panel_FirstDates.FMI_Source. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMO_Date` COMMENT 'Date of the customer''s first money-out (FMO) transaction on the eTM platform. Sourced from eMoney_Panel_FirstDates.FMO_Date. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMO_Target` COMMENT 'Transaction type (channel) of the first money-out event. Sourced from eMoney_Panel_FirstDates.FMO_Target. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P1_Response` COMMENT 'Classification response description for P1 (Client Age). ResponseID = ClientAge integer. Matched from Fivetran classification table ParameterID=1. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P1_Risk` COMMENT 'Risk tier label for P1 (Client Age). Contributes P1_RiskID × P1_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P2_Response` COMMENT 'Classification response description for P2 (Address Country High Risk). ResponseID = CountryAddress_IsHRC (0/1/99999). ParameterID=2. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P2_Risk` COMMENT 'Risk tier label for P2 (Address Country High Risk). Contributes P2_RiskID × P2_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P3_Response` COMMENT 'Classification response description for P3 (Citizenship Country High Risk). ResponseID = CountryCitizenship_IsHRC. ParameterID=3. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P3_Risk` COMMENT 'Risk tier label for P3 (Citizenship Country High Risk). Contributes P3_RiskID × P3_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P4_Response` COMMENT 'Classification response description for P4 (Place of Birth Country High Risk). ResponseID = CountryPOB_IsHRC. ParameterID=4. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P4_Risk` COMMENT 'Risk tier label for P4 (Place of Birth Country High Risk). Contributes P4_RiskID × P4_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P5_Response` COMMENT 'Classification response description for P5 (Annual Income - KYC Q10). ResponseID = Q10_AnswerID. ParameterID=5. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P5_Risk` COMMENT 'Risk tier label for P5 (Annual Income). Contributes P5_RiskID × P5_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P6_Response` COMMENT 'Classification response description for P6 (Total Assets - KYC Q11). ResponseID = Q11_AnswerID. ParameterID=6. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P6_Risk` COMMENT 'Risk tier label for P6 (Total Assets). Contributes P6_RiskID × P6_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P7_Response` COMMENT 'Classification response description for P7 (Planned Investment Amount - KYC Q14). ResponseID = Q14_AnswerID. ParameterID=7. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P7_Risk` COMMENT 'Risk tier label for P7 (Planned Investment Amount). Contributes P7_RiskID × P7_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P8_Response` COMMENT 'Classification response description for P8 (Main Source of Income - KYC Q15). ResponseID = Q15_AnswerID. ParameterID=8. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P8_Risk` COMMENT 'Risk tier label for P8 (Main Source of Income). Contributes P8_RiskID × P8_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P9_Response` COMMENT 'Classification response description for P9 (Occupation Category - KYC Q18). ResponseID = Q18_AnswerID. ParameterID=9. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P9_Risk` COMMENT 'Risk tier label for P9 (Occupation Category). Contributes P9_RiskID × P9_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P10_Response` COMMENT 'ALWAYS NULL. Parameter 10 (KYC Q46 Citizenship By Investment Program) was permanently cancelled. P10_RiskID=0 and P10_Weight=0; this parameter contributes nothing to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P10_Risk` COMMENT 'ALWAYS NULL. P10 is permanently cancelled - see P10_Response. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P11_Response` COMMENT 'Classification response description for P11 (Business Duration as eToro depositor). ResponseID = BusinessDuration bucket (99999/1/2/3). ParameterID=11. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P11_Risk` COMMENT 'Risk tier label for P11 (Business Duration). Contributes P11_RiskID × P11_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P12_Response` COMMENT 'Classification response description for P12 (Source of Income Document). ResponseID: 1=document provided, 2=absent with IBAN MoneyIn  <= 50K, 3=absent with IBAN MoneyIn >50K. ParameterID=12. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P12_Risk` COMMENT 'Risk tier label for P12 (Source of Income Document). Contributes P12_RiskID × P12_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P13_Response` COMMENT 'Classification response description for P13 (Selfie Verification Document). ResponseID: 1=selfie provided (DocType 15 or 18, no rejection), 0=not provided. ParameterID=13. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P13_Risk` COMMENT 'Risk tier label for P13 (Selfie Verification). Contributes P13_RiskID × P13_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P14_Response` COMMENT 'Classification response description for P14 (AML Screening Status). ResponseID = ScreeningStatusID (ISNULL -> 99999). ParameterID=14. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P14_Risk` COMMENT 'Risk tier label for P14 (Screening Status). Contributes P14_RiskID × P14_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P15_Response` COMMENT 'Classification response description for P15 (Electronic Verification / EV Match Status). ResponseID = EvMatchStatus (ISNULL -> 99999). ParameterID=15. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P15_Risk` COMMENT 'Risk tier label for P15 (Electronic Verification). Contributes P15_RiskID × P15_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P16_Response` COMMENT 'Classification response description for P16 (TIN Country High Risk). ResponseID = CountryTIN_IsHRC (0/1/99999). ParameterID=16. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P16_Risk` COMMENT 'Risk tier label for P16 (TIN Country High Risk). Contributes P16_RiskID × P16_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P17_Response` COMMENT 'Classification response description for P17 (TIN Country matches KYC Address Country). ResponseID: 1=match, 0=mismatch, 99999=no TIN. ParameterID=17. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P17_Risk` COMMENT 'Risk tier label for P17 (TIN Country Match). Contributes P17_RiskID × P17_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P18_Response` COMMENT 'Classification response description for P18 (Proof of Identity). ResponseID = IsIDProof (ISNULL -> 99999). ParameterID=18. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P18_Risk` COMMENT 'Risk tier label for P18 (Proof of Identity). Contributes P18_RiskID × P18_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P19_Response` COMMENT 'Classification response description for P19 (Proof of Address). ResponseID = IsAddressProof (ISNULL -> 99999). ParameterID=19. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P19_Risk` COMMENT 'Risk tier label for P19 (Proof of Address). Contributes P19_RiskID × P19_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P20_Response` COMMENT 'Classification response description for P20 (IBAN Load - Number of Source Countries). ResponseID encoded: 11=no IBAN loads, 33=1 country, 44=2-3 countries, 55= >= 4 countries. ParameterID=20. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P20_Risk` COMMENT 'Risk tier label for P20 (IBAN Load Country Diversity). Contributes P20_RiskID × P20_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P21_Response` COMMENT 'Classification response description for P21 (Last IBAN Load Country matches KYC Address Country). ResponseID: 11=no loads, 22=match, 33=mismatch, 44=missing country data. ParameterID=21. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P21_Risk` COMMENT 'Risk tier label for P21 (IBAN Load Country vs KYC). Contributes P21_RiskID × P21_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P22_Response` COMMENT 'Classification response description for P22 (Last IBAN Load Country is High Risk). ResponseID: 11=no loads, 22=not HRC, 33=HRC, 44=missing HRC data. ParameterID=22. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P22_Risk` COMMENT 'Risk tier label for P22 (IBAN Load Country HRC). Contributes P22_RiskID × P22_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P23_Response` COMMENT 'Classification response description for P23 (IBAN Unload - Number of Destination Countries). Same ResponseID encoding as P20. ParameterID=23. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P23_Risk` COMMENT 'Risk tier label for P23 (IBAN Unload Country Diversity). Contributes P23_RiskID × P23_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P24_Response` COMMENT 'Classification response description for P24 (Last IBAN Unload Country matches KYC Address Country). Same encoding as P21. ParameterID=24. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P24_Risk` COMMENT 'Risk tier label for P24 (IBAN Unload Country vs KYC). Contributes P24_RiskID × P24_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P25_Response` COMMENT 'Classification response description for P25 (Last IBAN Unload Country is High Risk). Same encoding as P22. ParameterID=25. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P25_Risk` COMMENT 'Risk tier label for P25 (IBAN Unload Country HRC). Contributes P25_RiskID × P25_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P26_Response` COMMENT 'Classification response description for P26 (High Net Worth Individual). ResponseID: 11=MoneyIn_IBAN  <= 500K USD, 22=>500K USD. ParameterID=26. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P26_Risk` COMMENT 'Risk tier label for P26 (High Net Worth). Contributes P26_RiskID × P26_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P32_Response` COMMENT 'Classification response description for P32 (Total IBAN Money In Volume). ResponseID: 11= <= $10K, 22=>$10K - $200K, 33=>$200K. MoneyIn_IBAN = sum of TxTypeID=5 and TxTypeID=7 amounts. ParameterID=32. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P32_Risk` COMMENT 'Risk tier label for P32 (IBAN Total Volume). Contributes P32_RiskID × P32_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P27_Response` COMMENT 'Classification response description for P27 (VPN/TOR Usage). ResponseID: 11=VPN/TOR ratio >40% of logins, 22= <= 40%, 99999=no login history. Sourced from STS_User_Operations_Data_History (login events). ParameterID=27. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P27_Risk` COMMENT 'Risk tier label for P27 (VPN/TOR Usage). Contributes P27_RiskID × P27_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P28_Response` COMMENT 'Classification response description for P28 (Citizenship Country = Place of Birth Country). ResponseID: 1=match, 0=mismatch, 99999=missing data. ParameterID=28. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P28_Risk` COMMENT 'Risk tier label for P28 (Citizenship = POB). Contributes P28_RiskID × P28_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P29_Response` COMMENT 'Classification response description for P29 (Citizenship Country = KYC Address Country). ResponseID: 1=match, 0=mismatch, 99999=missing data. ParameterID=29. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P29_Risk` COMMENT 'Risk tier label for P29 (Citizenship = Address). Contributes P29_RiskID × P29_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P30_Response` COMMENT 'Classification response description for P30 (Source of Funds - KYC Q26). ResponseID = Q26_AnswerID. ParameterID=30. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P30_Risk` COMMENT 'Risk tier label for P30 (Source of Funds). Contributes P30_RiskID × P30_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P31_Response` COMMENT 'Classification response description for P31 (Total Ecosystem Money In vs Declared Max Income). MoneyIn_Total = TP deposits (Fact_CustomerAction) + IBAN loads. Compared against Q10_AnswerID-derived max declared income. ResponseID: 11=within/under declared, 22=up to 130% of declared, 33=exceeds 130% of declared. ParameterID=31. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P31_Risk` COMMENT 'Risk tier label for P31 (Ecosystem Money vs Declared). Contributes P31_RiskID × P31_Weight to Risk_Final_Result. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `UpdateDate` COMMENT 'SP execution timestamp (GETDATE() at INSERT time). Not a business date; marks when the class-change row was inserted. (Tier 2 - SP_eMoney_Customer_Risk_Assessment)';

-- ---- Column PII Tags ----
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CID` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `GCID` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientRiskDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientRisk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientRiskAssignmentType` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `Risk_Final_Result` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PreviousClientRisk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PreviousClientRiskDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `VerificationLevelID` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsValidCustomer` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsDepositor` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `AccountType` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `Regulation` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `Club` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ClientAge` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DateOfBirth` SET TAGS ('pii' = 'direct');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DateOfReg` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DateOfFTD` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `BusinessDuration` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryAddress` SET TAGS ('pii' = 'direct');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryCitizenship` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryPOB` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryTIN` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryAddress_IsHRC` SET TAGS ('pii' = 'direct');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryCitizenship_IsHRC` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryPOB_IsHRC` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `CountryTIN_IsHRC` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `AccountStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PlayerStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PlayerStatusReason` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PlayerStatusSubReason` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `ScreeningStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `EVStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DocumentStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `PhoneStatus` SET TAGS ('pii' = 'direct');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `DocsOK` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsIDProof` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsAddressProof` SET TAGS ('pii' = 'direct');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsPhoneVerified` SET TAGS ('pii' = 'direct');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `IsValidETM` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CurrencyBalanceID` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CurrencyBalanceCreateDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CurrencyBalanceStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountID` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountCreateDate` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountProgram` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_AccountSubProgram` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_HasCard` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_CardStatus` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_ProviderHolderID` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMI_Date` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMI_Source` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMO_Date` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `eTM_FMO_Target` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P1_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P1_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P2_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P2_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P3_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P3_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P4_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P4_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P5_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P5_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P6_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P6_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P7_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P7_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P8_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P8_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P9_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P9_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P10_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P10_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P11_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P11_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P12_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P12_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P13_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P13_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P14_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P14_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P15_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P15_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P16_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P16_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P17_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P17_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P18_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P18_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P19_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P19_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P20_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P20_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P21_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P21_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P22_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P22_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P23_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P23_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P24_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P24_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P25_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P25_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P26_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P26_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P32_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P32_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P27_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P27_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P28_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P28_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P29_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P29_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P30_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P30_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P31_Response` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `P31_Risk` SET TAGS ('pii' = 'none');
ALTER TABLE main.emoney.gold_sql_dp_prod_we_emoney_dbo_emoney_customer_risk_assessment_history ALTER COLUMN `UpdateDate` SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 06:16:09 UTC
-- Batch deploy resume: eMoney_dbo deploy batch 1
-- Statements: 242/242 succeeded
-- ====================
