-- =============================================================================
-- Databricks ALTER Script: main.etoro_kpi_prep.v_fact_customeraction_enriched
-- Generated: 2026-05-17 | uc-pipeline-doc framework, Phase 6
-- Target: Unity Catalog view comment + column comments (1024 char limit)
-- Writer kind: view_definition (no notebook / job to update)
-- Source-of-truth wiki: knowledge/UC_generated/etoro_kpi_prep/Views/v_fact_customeraction_enriched.md
-- =============================================================================

-- ---- View Comment ----
COMMENT ON VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched IS
'Enrichment view over main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction that UNION-ALLs a passive-action branch (ActionTypeID in {19,32,35} or ActionTypeID=36 with CompensationReasonID in {56,117,118}) and an active-action branch (everything else) so every row carries position-derived OpenDateID, CloseDateID, VolumeOnOpen, VolumeOnClose. Same per-event grain as the upstream fact. Adds 6 COALESCE-from-position columns (InstrumentID, Leverage, IsSettled, IsAirDrop, SettlementTypeID, IsBuy), 2 CASE rewrites (PositionID Description-parse, MirrorID post-mirror-close zero-out), 2 CAST replications (OpenDateID, CloseDateID), 2 branch-dependent volume columns, and 1 TicketFeeAction CASE classifier. Writer: view_definition (no scheduling). Refreshes on every query.';

-- ---- View Tags ----
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched SET TAGS (
    'domain' = 'customer_action',
    'object_type' = 'enrichment_view',
    'source_schema' = 'etoro_kpi_prep',
    'source_server' = 'Databricks Unity Catalog',
    'refresh_frequency' = 'on_query',
    'sla' = 'inherits_upstream',
    'source_system' = 'Databricks',
    'uc_format' = 'view',
    'pipeline' = 'uc-pipeline-doc',
    'pipeline_version' = '7-phase',
    'primary_upstream' = 'main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction',
    'semantic_grade' = '4'
);

-- ---- Column Comments (79 columns) ----
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN HistoryID COMMENT 'Intended as a unique key but contains duplicates — NOT reliable as a primary/unique identifier. Do not use for JOINs, deduplication, or row identification. Has no practical use for analysts. (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN GCID COMMENT 'Global Customer ID — the platform-wide unique customer identifier. References Dim_Customer.GCID. (Tier 1 — Customer.CustomerStatic)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN RealCID COMMENT 'Real-account Customer ID. HASH distribution key. References Dim_Customer.RealCID. Each customer has one real CID. (Tier 1 — Customer.CustomerStatic)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN DemoCID COMMENT 'Demo-account Customer ID. Always 0 in this table (real accounts only). (Tier 3 — ETL-assigned)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN Occurred COMMENT 'UTC timestamp when the action occurred. For position opens: when position was opened. For logins: login time. For credits: when the credit was recorded. (Tier 1 — source-dependent)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IPNumber COMMENT 'IP address of the customer as a numeric value. Populated for logins and registrations. (Tier 1 — STS/Billing.Login)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsReal COMMENT 'Account type flag. Always 1 in this table (real accounts only). (Tier 3 — ETL-assigned)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN ActionTypeID COMMENT 'Event classifier — join Dim_ActionType for Name / Category. Drives sparse column population. Derived from CreditTypeID & branch router in loader + positional feeds. (Tier 1 — History.Credit / Trade snapshots / STS / Customer payloads)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN PlatformTypeID COMMENT 'Legacy platform discriminator (0 default; 99 STS-heavy logins sampled 202601+). (Tier 3 — ETL-assigned)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN InstrumentID COMMENT 'FK to Trade.Instrument. Financial instrument being traded when row is instrument-bearing. In this view: COALESCE(dp.InstrumentID, fca.InstrumentID) — prefers position-derived instrument for position-bound rows, falls back to Fact''s column otherwise. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction / main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN Amount COMMENT 'Position / ledger amount discipline per branch (cash change on opens; fee/deposit sizing on ledger rows — see lineage). Must be >= 0 on trade opens historically. (Tier 1 — Trade.PositionTbl / History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN Leverage COMMENT 'Leverage multiplier (1, 5, 10, etc.). Determines margin and settlement posture. In this view: COALESCE(dp.Leverage, fca.Leverage) — prefers position''s stored leverage when row references a position. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction / main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN NetProfit COMMENT 'Realized PnL. 0 when open; populated on closes in position currency. (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN Commission COMMENT 'Open commission in dollars (/100 cents conversion on ingest per Dim_Position lineage notes). (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN PositionID COMMENT 'Surrogate bigint from Internal.GetPositionID_Bigint domain; unique trade position key. In this view, overridden via CASE for compensation rows that encode the position id inside Description: when ActionTypeID = 36 AND CompensationReasonID IN (117, 118), parses the trailing token off REVERSE(SUBSTRING(REVERSE(Description), 1, CHARINDEX('' '', REVERSE(Description)) - 1)) via TRY_CAST(... AS BIGINT) (NULL on parse failure); otherwise passes through fca.PositionID. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CampaignID COMMENT 'Marketing campaign identifier — 0 if not campaign-bound. References Dim_Campaign. (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN BonusTypeID COMMENT 'Bonus classifier on bonus credit rows (ActionTypeID=9). 0 elsewhere. References Dim_BonusType. (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN FundingTypeID COMMENT 'Ledger funding / wallet channel identifier (deposits & cash-outs). Nullable upstream coerced with ISNULL(...,0) sentinel row 0. Value 27 pairs with redeem flag derivation on cash-outs. References Dim_FundingType. (Tier 1 — History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN LoginID COMMENT 'Billing login session key (Billing.Login lineage). 0 off-login. (Tier 1 — Billing.Login)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN MirrorID COMMENT 'FK to Trade.Mirror (0/NULL => manual trading; >0 => copy-trade child). In this view (passive branch only), overridden via CASE to 0 when the row''s Occurred is AFTER the most-recent ActionTypeID=19 (Mirror Removed) snapshot for the same position; otherwise COALESCE(dp.MirrorID, fca.MirrorID). Resolves the "ex-copy" case. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction / main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN WithdrawID COMMENT 'Withdrawal request identifier for cash-out credits; 0 when absent. (Tier 1 — History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN DurationInSeconds COMMENT 'Login session dwell seconds (NULL outside login cashier events). (Tier 1 — Billing.Login)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN PostID COMMENT 'Social GUID for deprecated social action types (21-26) — stale per historical wiki audits. NULL otherwise. (Tier 1 — Social platform)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CaseID COMMENT 'CRM case (ActionTypeID=31). 0 default. (Tier 1 — CRM)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN UpdateDate COMMENT 'Last successful fact loader write (GETDATE()/GETUTCDATE() parity in ops). (Tier 2 — SP_Fact_CustomerAction)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN DateID COMMENT 'Occurred -> YYYYMMDD int (nonclustered index driver). (Tier 2 — SP_Fact_CustomerAction)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN TimeID COMMENT 'Hour bucket DATEPART(HOUR,Occurred). (Tier 2 — SP_Fact_CustomerAction)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN StatusID COMMENT 'Row vitality flag (1 almost always; rare NULL cohort). (Tier 3 — ETL-assigned)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN PreviousOccurred COMMENT 'Deprecated / unreliable historical column — analysts should ignore. (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CompensationReasonID COMMENT 'BackOffice.CompensationReason code on comps & some opens for airdrops. (Tier 1 — History.Credit, updated wiki 2025-12)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN WithdrawPaymentID COMMENT 'Payment-processing key for withdrawals; used to collapse duplicate WithdrawProcessing tuples per historical ETL memo. (Tier 1 — History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CommissionOnClose COMMENT 'Close commission dollars — reopen-adjust net-of-original per Dim_Position wiki. CommissionOnCloseOrig preserves untouched close fee. (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsPlug COMMENT 'Deprecated placeholder (NULL). (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN DepositID COMMENT 'Deposit transaction reference on inbound money rows (NULL off-deposit actions). (Tier 1 — History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN PostRootID COMMENT 'Deprecated social threading key. NULL off-social. (Tier 1 — Social platform)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN FullCommission COMMENT 'Gross commission inclusive of hidden spread uplift at open (/100 ingestion note). (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN FullCommissionOnClose COMMENT 'Gross commission on exit — symmetrical reopen-adjust story to CommissionOnClose. (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN RedeemID COMMENT 'Billing.Redeem reference when position closed via redeem. (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN RedeemStatus COMMENT 'Redemption state. Billing.Redeem integration. (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN SessionID COMMENT 'STS session BIGINT for opens/logins (NULL off those branches). (Tier 1 — STS)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsRedeem COMMENT 'Dual-semantics redeem flag. (A) Ledger / Crypto-wallet Path: Loader CASE tagging eToroCryptoWallet (FundingTypeID=27) cash-outs (ActionTypeID = 8 slice 100% FundingType 27 whenever IsRedeem=1). Revenue TVF Function_Revenue_TransferCoinFee filters Fact_CustomerAction with ActionTypeID = 30 AND IsRedeem = 1 — interpret as transfer-to-coin / fiat-wallet -> on-chain custody (not shorthand for bank cash-out). (B) CFD Billing.Redeem Path: Positional closes (ActionTypeID in {4,5,6,...}) can emit IsRedeem=1 alongside RedeemID / RedeemStatus (Billing.Redeem integration per Trade.PositionTbl) — orthogonal to transfercoin semantics. (Tier 2 — SP_Fact_CustomerAction)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN RegulationIDOnOpen COMMENT 'Regulatory jurisdiction ID at time of position open. ETL-computed via JOIN to etoro_History_BackOfficeCustomer (customer regulation history). ISNULL(..., 0) when no regulation match found. (Tier 2 — SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN PlatformID COMMENT 'Product/platform identifier — badly named, references Dim_Product.ProductID; resolve Product/Platform/SubPlatform columns via JOIN (ActionTypeID 14 / 41 focus). (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN ReopenForPositionID COMMENT 'When position reopened: erroneous prior PositionID. NULL if virgin cycle. (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsReOpen COMMENT '1=this position was reopened from ReopenForPositionID. CASE WHEN ReopenForPositionID IS NOT NULL THEN 1 ELSE 0 default. (Tier 2 — SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CommissionOnCloseOrig COMMENT 'CASE WHEN ReopenForPositionID IS NOT NULL THEN CommissionOnClose ELSE 0 — preserves naive close commission before netting. (Tier 2 — SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN FullCommissionOnCloseOrig COMMENT 'CASE WHEN ReopenForPositionID IS NOT NULL THEN FullCommissionOnClose ELSE 0 (default zeros). (Tier 2 — SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN OriginalPositionID COMMENT 'Source position BEFORE partial-split chains. (Tier 2 — SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsPartialCloseParent COMMENT 'Marks parent row around partial-close split (subject to SP_Fact_CustomerAction_IsParitalCloseParent post-job). Analyst filtering nuance persists from Dim_Position guidance. (Tier 5 — domain expert, SP_Fact_CustomerAction_IsParitalCloseParent)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsPartialCloseChild COMMENT 'Marks remainder leg after partial close — filter guidance identical to Dim_Position: avoid dropping CLOSE child rows blindly. (Tier 5 — domain expert, SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN InitialUnits COMMENT 'Opening unit count denominator for partial proration ladders. (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN PaymentStatusID COMMENT 'Payment pipeline status IDs on inbound/outbound monies — join Dim_PaymentStatus. (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsDiscounted COMMENT '1=commission discount applied at open (legacy bit widening). (Tier 1 — Trade.PositionTbl)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsSettled COMMENT '1 = real asset, 0 = CFD asset. In this view: COALESCE(dp.IsSettled, fca.IsSettled) — prefers position-derived value for position-bound rows. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction / main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CommissionByUnits COMMENT 'Prorated commission for partial close. Formula: (AmountInUnitsDecimal / InitialUnits) * Commission. Used for partial-close PnL. (Tier 1 — Trade.Position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN FullCommissionByUnits COMMENT 'Prorated full commission for partial close. Same proration formula as CommissionByUnits applied to FullCommission. (Tier 1 — Trade.Position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsFTD COMMENT 'First-Time Deposit tagging on qualifying deposit/action rows (NULL elsewhere). Derived during credit classification & snapshot merges. (Tier 2 — SP_Fact_CustomerAction)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CountryIDByIP COMMENT 'Geo-IP-derived country surrogate — join Dim_Country. (Tier 5 — domain expert)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsAnonymousIP COMMENT 'Anonymous / proxy heuristic flag STS path. NULL off relevant rows. (Tier 1 — IP geolocation service)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN ProxyType COMMENT 'Proxy taxonomy (DCH, VPN, TOR, etc.) from STS classifications. NULL if direct. (Tier 1 — STS)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsFeeDividend COMMENT 'Fee subclass for ActionTypeID=35 (1 nightly/weekend fee, 2 dividend, 3 SDRT, 4 ticket aggregates) encoded off Description heuristics (DSM-1463). NULL off-fee rows. (Tier 2 — SP_Fact_CustomerAction)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsAirDrop COMMENT 'JOIN to etoro_Trade_PositionAirdropLog path per Dim_Position — 1 denotes airdrop-sourced crypto open. In this view: COALESCE(dp.IsAirDrop, fca.IsAirDrop) — prefers position-derived flag. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction / main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN DividendID COMMENT 'Dividend event pointer for dividend-driven fee deductions. NULL off-dividend. (Tier 1 — Trade.Positions/dividends lineage)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN MoveMoneyReasonID COMMENT 'Dictionary.MoveMoneyReason code on internal sweeps (5/6/recurring enums per prior audits). References dictionary dimension. (Tier 1 — History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN SettlementTypeID COMMENT 'Dictionary.SettlementTypes modern encoding (0 CFD, 1 REAL, 2 TRS, 3 CMT, 4 REAL_FUTURES, 5 MARGIN_TRADE). Supersedes naive IsSettled reads. In this view: COALESCE(dp.SettlementTypeID, fca.SettlementTypeID). (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction / main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN etr_y COMMENT 'Year partition value injected by the gold/spaceship pipeline. Equals YEAR(etr_ts). Used as Delta partition key in UC. (Pipeline-injected metadata; not present in Synapse source DDL.) (Tier 2 — gold/spaceship pipeline)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN etr_ym COMMENT 'Year-month partition value (YYYY-MM) injected by the gold/spaceship pipeline. Used as Delta partition key for month-level pruning in UC. (Tier 2 — gold/spaceship pipeline)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN etr_ymd COMMENT 'Year-month-day partition value (YYYY-MM-DD) injected by the gold/spaceship pipeline. Used as Delta partition key for day-level pruning in UC. (Tier 2 — gold/spaceship pipeline)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN DLTOpen COMMENT 'Distributed-ledger telemetry captured at OPEN (Prod addition 2024-06-02 per dim wiki). NULL historical. (Tier 2 — SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN DLTClose COMMENT 'Ledger telemetry captured at CLOSE mirroring DLTOpen. (Tier 2 — SP_Dim_Position_DL_To_Synapse)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN OpenMarkupByUnits COMMENT 'Prorated open markup OpenMarkup * AmountInUnitsDecimal / InitialUnits for partial closes. (Tier 1 — Trade.Position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN Description COMMENT 'Operational narrative pulled from Credits / fees ("Over night fee", ticket fee tokens, Payments deposit processor strings). (Tier 1 — History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN IsBuy COMMENT '1 Long, 0 Short; NULL => non-trade row sentinel. In this view: COALESCE(dp.IsBuy, fca.IsBuy) — prefers position-derived direction. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction / main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CreditID COMMENT 'Direct pointer to History.Credit.CreditID lineage for reversible audits. Added 2025 loader wave. (Tier 1 — History.Credit)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN OpenDateID COMMENT 'Position open date as YYYYMMDD int. In this view, derived by casting dp.OpenDateID to INT (the position-side replicates the date for both UNION branches). 0 / NULL when the row does not reference a position. (Tier 2 — main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN CloseDateID COMMENT 'Position close date as YYYYMMDD int. 0 = still open. In this view, derived by casting dp.CloseDateID to INT. Key filter for open vs closed. (Tier 2 — main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN VolumeOnOpen COMMENT 'Position open volume snapshot. Branch-dependent: in the passive branch (fees / edits / airdrops / certain comps) the column is CAST(NULL AS DECIMAL(38,6)) to prevent aggregation duplication; in the active branch (everything else) it is CAST(ROUND(dp.InitialUnits * dp.InitForexRate * dp.InitConversionRate) AS DECIMAL(38,6)) — original volume in account currency, pre-partial-close. (Tier 2 — main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN VolumeOnClose COMMENT 'Position close volume snapshot. Branch-dependent: NULL in passive branch (same anti-duplication rationale); CAST(dp.VolumeOnClose AS DECIMAL(38,6)) in active branch. (Tier 2 — main.dwh.dim_position)';
ALTER VIEW main.etoro_kpi_prep.v_fact_customeraction_enriched ALTER COLUMN TicketFeeAction COMMENT 'Pre-classifier for ticket fees (ActionTypeID = 35 AND IsFeeDividend = 4): ''Open'' when Description = ''OpenTotalFees'', ''Close'' when Description = ''CloseTotalFees'', NULL otherwise. Consumed by v_fact_customeraction_w_metrics to split into TicketFeeOpen / TicketFeeClose revenue columns. (Tier 2 — main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_customeraction)';

-- ---- End ----
-- Idempotent: re-running this script is a no-op once the column comments are in sync with the wiki.
