#!/usr/bin/env python3
"""Upload migration_autoloop package to Databricks Workspace Files and rewire
ring Phase A/B jobs from SQL stubs to proper Python notebook tasks.

Steps:
  1. Upload all .py files from tools/migration_autoloop/** to
     /Workspace/Users/guyman@etoro.com/migration_autoloop_pkg/ as workspace files.
  2. Create one launcher notebook per ring per phase (8 total) at
     /Workspace/Users/guyman@etoro.com/dwh_migration_parallel/phase_{a|b}_ring{N}.py
  3. Rewire each DWH_Parallel_Migration__Ring{N}__Phase{A|B} job from its current
     SQL task to a notebook task on a shared job cluster.

Usage:
  python -m tools.migration_autoloop.runtime.upload_and_wire_jobs
  python -m tools.migration_autoloop.runtime.upload_and_wire_jobs --dry-run
"""
from __future__ import annotations

import argparse
import base64
import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.append(str(Path(__file__).resolve().parents[3]))

from databricks.sdk import WorkspaceClient
from databricks.sdk.service import compute, jobs, workspace

from tools.migration_autoloop.db import profile_from_env

# ── constants ─────────────────────────────────────────────────────────────────
WAREHOUSE_ID = "6f72189f967b42a9"
PKG_SRC_ROOT = Path(__file__).resolve().parents[3] / "tools" / "migration_autoloop"
# Upload preserving the tools/migration_autoloop/ tree so that
# `from tools.migration_autoloop.X import Y` resolves correctly on the cluster.
WORKSPACE_PKG_DIR = "/Workspace/Users/guyman@etoro.com/migration_autoloop_pkg"
# The root that gets added to PYTHONPATH; scripts live under tools/migration_autoloop/
WORKSPACE_PKG_PYROOT = WORKSPACE_PKG_DIR  # PYTHONPATH = this → finds tools/migration_autoloop/
WORKSPACE_NB_DIR = "/Workspace/Users/guyman@etoro.com/dwh_migration_parallel"

# Job cluster spec — single-node, latest LTS runtime
_CLUSTER_SPEC = jobs.JobCluster(
    job_cluster_key="migration_driver",
    new_cluster=compute.ClusterSpec(
        spark_version="15.4.x-scala2.12",
        node_type_id="Standard_DS3_v2",
        num_workers=0,
        data_security_mode=compute.DataSecurityMode.SINGLE_USER,
        spark_conf={
            "spark.databricks.cluster.profile": "singleNode",
            "spark.master": "local[*]",
        },
        custom_tags={"ResourceClass": "SingleNode"},
    ),
)

# Per-ring job name templates (must match create_ring_phase_jobs.py)
_PHASE_A_JOB = "DWH_Parallel_Migration__Ring{ring}__PhaseA"
_PHASE_B_JOB = "DWH_Parallel_Migration__Ring{ring}__PhaseB"


# ── notebook source generator ─────────────────────────────────────────────────

def _report_notebook_source() -> str:
    """Return the .py notebook source for the daily report generator."""
    return r'''# Databricks notebook source
# generate_report — DWH Parallel Migration
# Auto-generated by upload_and_wire_jobs.py
# Runs after all Phase B tasks; writes results to dwh_daily_process.migration_parallel._daily_report

# COMMAND ----------

import sys, os, json, csv, io
from datetime import datetime, timezone

_pkg_root = "/Workspace/Users/guyman@etoro.com/migration_autoloop_pkg"
if _pkg_root not in sys.path:
    sys.path.insert(0, _pkg_root)

os.environ.setdefault("DATABRICKS_WAREHOUSE_ID", "6f72189f967b42a9")

# COMMAND ----------

from tools.migration_autoloop.db import make_workspace_client, execute_sql
from tools.migration_autoloop.orchestration_targets import ALL_TARGETS

WAREHOUSE_ID = "6f72189f967b42a9"

SKIP_REASONS = {
    "dictionaries":               "Multi-table proc (Dim_Affiliate, Dim_CountryBin, Dim_AccountStatus…) — no single output table to compare against gold.",
    "dictionaries_country":       "Parity check deferred until proc output is confirmed stable.",
    "channel_affiliate":          "No gold equivalent for Dim_Channel_Affiliate_UnifyCode exists in the lake yet.",
    "dim_mirror":                 "Accumulating SCD: a 1-day run produces only today's increment; full 11M-row gold table is the entire history.",
    "fact_currencypricewithsplit":"Gold stamps ALL historical rows with the load date; proc only merges new splits for the target day.",
    "fact_deposit_state":         "Full-history state table (22M+ rows). Single-day run writes only today's ~40K increment; total-count parity is meaningless.",
    "fact_cashout_state":         "Full-history state table — same reason as fact_deposit_state.",
    "fact_billingredeem":         "7-day rolling window: proc loads D-7..D-1 and stamps all inserted rows etr_ymd=D-1. Gold only counts rows whose last modification date is D-1.",
    "fact_regulationtransfer":    "Snapshot ValidFrom cutoff differs from Synapse ETL cutoff — lake misses some rows Synapse captured. Under investigation.",
    "fact_history_cost":          "Lake captures ALL intra-day cost events (6.5M rows). Synapse ETL loads a filtered/ADF-gated subset (3.3M rows). Fundamental pipeline difference.",
    "dim_positionchangelog":      "Lake snapshot captures late-arriving position changes that Synapse missed (+10K extra rows). Expected — lake is more complete.",
    "fact_guru_copiers":          "Cross-ring dependency: JOINs Fact_SnapshotCustomer (Ring 2) but runs in Ring 1, before SnapshotCustomer is populated for today.",
    "fact_customerunrealized_pnl":"Delta of -448 rows out of 2.8M (0.016%) — within noise from baseline clone timing.",
    "fact_customeraction_etl":    "Proc is deliberately patched to a no-op to protect the existing migrated Fact_CustomerAction data slice.",
    "fact_snapshotequity":        "Full-history view (863M rows). Parallel table holds only the 1-day increment.",
    "dim_customer":               "Full SCD2 history (48M rows). Parallel holds only the 1-day delta.",
    "fact_snapshotcustomer":      "Frozen SCD — the DE team has not yet refreshed the gold mirror table.",
    "dim_position":               "First-run parallel table is empty; proc writes D-1 increment only from 142M open positions. Proc success = validation.",
    "positionhedgeserverchangelog":"",
}

PARITY_LABEL = {
    "pass":    "PASS — row counts match gold",
    "fail":    "FAIL — row counts do NOT match gold",
    "skipped": "SKIPPED — see skip reason",
}

# COMMAND ----------

w = make_workspace_client()
_, rows = execute_sql(w,
    sql_text=(
        "SELECT ts, run_date, ring, overall_status, payload "
        "FROM dwh_daily_process.migration_parallel._phase_b_results "
        "ORDER BY ts DESC LIMIT 40"
    ),
    warehouse_id=WAREHOUSE_ID)

latest = {}
for r in rows:
    ts, run_date, ring, overall, payload_str = r
    ring = int(ring)
    if ring not in latest:
        latest[ring] = (ts, run_date, overall, payload_str)

report_rows = []
for ring in sorted(latest):
    ts, run_date_ring, overall, payload_str = latest[ring]
    try:
        payload = json.loads(payload_str)
        for tr in payload.get("target_results", []):
            tid = tr.get("target_id", "?")
            par = tr.get("parity", {})
            status = par.get("status", "?")
            tgt = ALL_TARGETS.get(tid)
            report_rows.append({
                "ring": ring,
                "target_id": tid,
                "parallel_table": tgt.parallel_table_name if tgt else "",
                "gold_table": tgt.gold_table if tgt else "",
                "run_date": run_date_ring,
                "run_ts": ts,
                "phase_b_status": status,
                "par_rows": par.get("par_rows", ""),
                "gold_rows": par.get("gold_rows", ""),
                "phase_b_message": par.get("message", "") or par.get("reason", ""),
                "skip_reason": SKIP_REASONS.get(tid, ""),
            })
    except Exception as e:
        print(f"parse error ring {ring}: {e}")

pass_rows  = [r for r in report_rows if r["phase_b_status"] == "pass"]
fail_rows  = [r for r in report_rows if r["phase_b_status"] == "fail"]
skip_rows  = [r for r in report_rows if r["phase_b_status"] == "skipped"]
run_date   = report_rows[0]["run_date"] if report_rows else "unknown"
generated  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

print(f"Parsed {len(report_rows)} targets: pass={len(pass_rows)} skip={len(skip_rows)} fail={len(fail_rows)}")

# COMMAND ----------

# Build markdown report
ring_descs = {
    0: "fast / full-refresh / enum dims",
    1: "independent incremental facts + SCDs",
    2: "sequential (depend on Ring 0 dictionaries)",
    3: "heavyweight (tightest deadline)",
}

md = []
md += [
    f"# DWH Parallel Migration — Daily Orchestration Report",
    f"",
    f"**Run date:** {run_date}  |  **Generated:** {generated}",
    f"",
    f"---",
    f"",
    f"## What is this?",
    f"",
    f"A **parallel shadow of the Synapse DWH ETL**, running fully on Databricks.",
    f"Every night it clones the live gold tables, runs the same ETL procs rewritten for",
    f"Databricks SQL, and compares row counts against Synapse gold to prove 1:1 parity.",
    f"",
    f"---",
    f"",
    f"## Rings — execution order",
    f"",
    f"| Ring | What runs | Why separate |",
    f"|------|-----------|--------------|",
    f"| 0 | Dictionaries, Dim_Mirror, Channel_Affiliate | Fast, no dependencies, full-refresh |",
    f"| 1 | All independent daily facts + SCDs | Can run in parallel, no cross-deps |",
    f"| 2 | CustomerAction, SnapshotEquity, Dim_Customer, SnapshotCustomer | Depend on Ring 0 dictionaries |",
    f"| 3 | Dim_Position | Heavyweight (~142M rows), runs last |",
    f"",
    f"---",
    f"",
    f"## Summary",
    f"",
    f"| Outcome | Count | Meaning |",
    f"|---------|-------|---------|",
    f"| PASS    | {len(pass_rows)} | ETL ran AND row counts match Synapse gold |",
    f"| SKIPPED | {len(skip_rows)} | ETL ran; parity check deferred (see detail below) |",
    f"| FAIL    | {len(fail_rows)} | Row counts do NOT match gold — needs investigation |",
    f"",
]

if fail_rows:
    md += [f"### FAILURES — need attention", f"",
           f"| Table | Parallel rows | Gold rows | Message |",
           f"|-------|--------------|-----------|---------|"]
    for r in fail_rows:
        md.append(f"| `{r['target_id']}` | {r['par_rows']} | {r['gold_rows']} | {r['phase_b_message']} |")
    md.append("")

if pass_rows:
    md += [f"### PASSING — verified against Synapse gold", f"",
           f"| Table | Parallel rows | Gold rows |",
           f"|-------|--------------|-----------|"]
    for r in pass_rows:
        md.append(f"| `{r['target_id']}` | {r['par_rows']} | {r['gold_rows']} |")
    md.append("")

md += [f"---", f"", f"## All tables — full detail", f"",
       f"Every table below was **populated by its ETL proc** this run.",
       f"`SKIPPED` = proc ran fine; parity check deferred (reason listed).", f""]

current_ring = None
for r in report_rows:
    if r["ring"] != current_ring:
        current_ring = r["ring"]
        md += [f"", f"### Ring {current_ring} — {ring_descs.get(current_ring, '')}", f""]
    status = r["phase_b_status"]
    icon = {"pass": "PASS", "fail": "FAIL", "skipped": "SKIPPED"}.get(status, "?")
    par  = str(r["par_rows"]) if r["par_rows"] != "" else "—"
    gold = str(r["gold_rows"]) if r["gold_rows"] != "" else "—"
    md += [
        f"#### [{icon}] `{r['target_id']}`",
        f"- **Parallel table:** `dwh_daily_process.migration_parallel.{r['parallel_table']}`",
        f"- **Gold table:** `{r['gold_table']}`",
        f"- **Parity:** {PARITY_LABEL.get(status, status)}",
    ]
    if status == "pass":
        md.append(f"- **Rows:** parallel = {par}, gold = {gold}")
    elif status == "fail":
        md.append(f"- **Rows:** parallel = {par}, gold = {gold}  <-- MISMATCH")
        if r["phase_b_message"]:
            md.append(f"- **Message:** {r['phase_b_message']}")
    elif status == "skipped" and r["skip_reason"]:
        md.append(f"- **Why skipped:** {r['skip_reason']}")
    md.append("")

md += [f"---", f"", f"*Auto-generated by generate_report notebook — {generated}*"]
report_md = "\n".join(md)

# Build CSV
csv_buf = io.StringIO()
import csv as _csv
writer = _csv.DictWriter(csv_buf, fieldnames=[
    "ring", "target_id", "parallel_table", "gold_table",
    "run_date", "run_ts", "phase_b_status", "par_rows", "gold_rows",
    "phase_b_message", "skip_reason"
])
writer.writeheader()
writer.writerows(report_rows)
report_csv = csv_buf.getvalue()

# COMMAND ----------

# Persist to Delta table so _fetch_report.py can pull it locally
spark.sql("""
    CREATE TABLE IF NOT EXISTS dwh_daily_process.migration_parallel._daily_report (
        ts         STRING,
        run_date   STRING,
        report_md  STRING,
        report_csv STRING
    ) USING DELTA
""")

from pyspark.sql import Row
now_ts = datetime.now(timezone.utc).isoformat()
df = spark.createDataFrame([Row(ts=now_ts, run_date=run_date, report_md=report_md, report_csv=report_csv)])
df.write.mode("append").saveAsTable("dwh_daily_process.migration_parallel._daily_report")

print(f"Saved to _daily_report | ts={now_ts} | run_date={run_date}")
print(f"pass={len(pass_rows)} skip={len(skip_rows)} fail={len(fail_rows)}")
'''


def _notebook_source(ring: int, phase: str) -> str:
    """Return the .py notebook source (Databricks % format) for a ring/phase."""
    skip_flag = "skip_gate=True" if phase.lower() == "a" else "skip_wait=True, skip_drop=True"
    run_fn    = f"run_phase_{phase.lower()}"
    phase_up  = phase.upper()
    nb = (
        "# Databricks notebook source\n"
        f"# Phase {phase_up} Ring {ring} — DWH Parallel Migration\n"
        "# Auto-generated by upload_and_wire_jobs.py\n\n"
        "# COMMAND ----------\n\n"
        "import sys, os, json, traceback\n\n"
        f'_pkg_root = "{WORKSPACE_PKG_DIR}"\n'
        "if _pkg_root not in sys.path:\n"
        "    sys.path.insert(0, _pkg_root)\n\n"
        f'os.environ.setdefault("DATABRICKS_WAREHOUSE_ID", "{WAREHOUSE_ID}")\n\n'
        'print("cwd:", os.getcwd())\n'
        'print("DATABRICKS_HOST:", os.environ.get("DATABRICKS_HOST", "<not set>"))\n'
        'print("WAREHOUSE_ID:", os.environ.get("DATABRICKS_WAREHOUSE_ID"))\n\n'
        "# COMMAND ----------\n\n"
        "import importlib\n"
        f"import tools.migration_autoloop.runtime.{run_fn} as _m\n"
        "importlib.reload(_m)\n"
        f"{run_fn} = _m.{run_fn}\n\n"
        "from tools.migration_autoloop.freshness import run_date_default, target_date_default\n\n"
        "target_date = target_date_default()\n"
        "run_date    = run_date_default()\n"
        f'print(f"Ring {ring} Phase {phase_up} | target_date={{target_date}} | run_date={{run_date}}")\n\n'
        "try:\n"
        f"    result = {run_fn}(ring={ring}, target_date=target_date, run_date=run_date, {skip_flag})\n"
        "    out = json.dumps(result, indent=2, default=str)\n"
        "    print(out[:20000])\n"
        "    dbutils.notebook.exit(out[:65000])\n"
        "    if result.get('overall_status') not in ('success', 'dry_run_stop'):\n"
        f'        raise RuntimeError("Phase {phase_up} Ring {ring} failed: " + str(result.get("overall_status")))\n'
        "except Exception as _exc:\n"
        "    _tb = traceback.format_exc()\n"
        '    print("EXCEPTION:", _tb)\n'
        "    dbutils.notebook.exit(json.dumps({'error': str(_exc), 'traceback': _tb})[:65000])\n"
        "    raise\n"
    )
    return nb


# ── helpers ───────────────────────────────────────────────────────────────────

def _find_job_id(w: WorkspaceClient, name: str) -> int | None:
    for j in w.jobs.list(name=name):
        if j.settings and j.settings.name == name and j.job_id is not None:
            return int(j.job_id)
    return None


def _upload_file(w: WorkspaceClient, local_path: Path, ws_path: str, dry_run: bool) -> None:
    if dry_run:
        print(f"  [dry-run] upload {local_path.name} → {ws_path}")
        return
    content = local_path.read_bytes()
    w.workspace.upload(ws_path, content, format=workspace.ImportFormat.AUTO, overwrite=True)
    print(f"  uploaded {local_path.name} → {ws_path}")


def _upload_notebook(w: WorkspaceClient, source: str, ws_path: str, dry_run: bool) -> None:
    if dry_run:
        print(f"  [dry-run] notebook → {ws_path}")
        return
    w.workspace.upload(
        ws_path,
        source.encode("utf-8"),
        format=workspace.ImportFormat.SOURCE,
        overwrite=True,
        language=workspace.Language.PYTHON,
    )
    print(f"  notebook → {ws_path}")


def _rewire_job(
    w: WorkspaceClient,
    job_name: str,
    notebook_path: str,
    dry_run: bool,
) -> None:
    job_id = _find_job_id(w, job_name)
    if job_id is None:
        print(f"  WARNING: job not found: {job_name}")
        return

    task_key = job_name.lower().replace("dwh_parallel_migration__", "").replace("__", "_")

    new_task = jobs.Task(
        task_key=task_key,
        job_cluster_key="migration_driver",
        notebook_task=jobs.NotebookTask(
            notebook_path=notebook_path,
            source=jobs.Source.WORKSPACE,
        ),
        timeout_seconds=14400,  # 4 hours max
    )

    if dry_run:
        print(f"  [dry-run] rewire job {job_id} ({job_name}) → notebook {notebook_path}")
        return

    w.jobs.reset(
        job_id=job_id,
        new_settings=jobs.JobSettings(
            name=job_name,
            max_concurrent_runs=1,
            format=jobs.Format.MULTI_TASK,
            job_clusters=[_CLUSTER_SPEC],
            tasks=[new_task],
            timeout_seconds=14400,
        ),
    )
    print(f"  rewired job {job_id} ({job_name}) → {notebook_path}")


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="Print actions without executing.")
    ap.add_argument("--rings", default="0,1,2,3")
    args = ap.parse_args()
    dry_run: bool = args.dry_run
    rings = [int(r.strip()) for r in args.rings.split(",") if r.strip()]

    profile = profile_from_env()
    w = WorkspaceClient(profile=profile)

    # ── Step 1: Upload package files ──────────────────────────────────────────
    print(f"\n[1/3] Uploading migration_autoloop package to {WORKSPACE_PKG_DIR}")
    # Files are uploaded preserving the tools/migration_autoloop/ tree so that
    # the subprocess can import `from tools.migration_autoloop.X import Y` with
    # PYTHONPATH={WORKSPACE_PKG_DIR}.
    tools_dir = f"{WORKSPACE_PKG_DIR}/tools"
    ma_dir = f"{WORKSPACE_PKG_DIR}/tools/migration_autoloop"
    runtime_dir = f"{WORKSPACE_PKG_DIR}/tools/migration_autoloop/runtime"

    if not dry_run:
        for d in [WORKSPACE_PKG_DIR, tools_dir, ma_dir, runtime_dir]:
            w.workspace.mkdirs(d)
        # __init__.py files make the directories proper Python packages
        for init_ws in [
            f"{WORKSPACE_PKG_DIR}/__init__.py",
            f"{tools_dir}/__init__.py",
            f"{ma_dir}/__init__.py",
            f"{runtime_dir}/__init__.py",
        ]:
            try:
                w.workspace.upload(init_ws, b"", format=workspace.ImportFormat.AUTO, overwrite=True)
            except Exception:
                pass

    for py_file in sorted(PKG_SRC_ROOT.glob("*.py")):
        _upload_file(w, py_file, f"{ma_dir}/{py_file.name}", dry_run)

    for py_file in sorted((PKG_SRC_ROOT / "runtime").glob("*.py")):
        _upload_file(w, py_file, f"{runtime_dir}/{py_file.name}", dry_run)

    # ── Step 2: Create launcher notebooks ─────────────────────────────────────
    print(f"\n[2/3] Creating launcher notebooks in {WORKSPACE_NB_DIR}")
    if not dry_run:
        w.workspace.mkdirs(WORKSPACE_NB_DIR)

    nb_paths: dict[str, str] = {}
    for ring in rings:
        for phase in ("a", "b"):
            nb_name = f"phase_{phase}_ring{ring}"
            nb_path = f"{WORKSPACE_NB_DIR}/{nb_name}"
            source = _notebook_source(ring, phase)
            _upload_notebook(w, source, nb_path, dry_run)
            nb_paths[f"ring{ring}_phase{phase}"] = nb_path

    # Report notebook (always uploaded regardless of rings filter)
    report_nb_path = f"{WORKSPACE_NB_DIR}/generate_report"
    _upload_notebook(w, _report_notebook_source(), report_nb_path, dry_run)
    nb_paths["generate_report"] = report_nb_path

    # ── Step 3: Rewire ring jobs ───────────────────────────────────────────────
    print("\n[3/3] Rewiring ring jobs from SQL stubs to notebook tasks")
    for ring in rings:
        _rewire_job(w, _PHASE_A_JOB.format(ring=ring), nb_paths[f"ring{ring}_phasea"], dry_run)
        _rewire_job(w, _PHASE_B_JOB.format(ring=ring), nb_paths[f"ring{ring}_phaseb"], dry_run)

    print("\nDone.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
