-- =============================================================================
-- Databricks ALTER Script: bronze MoneyTransfer.Billing.Transfers
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/PaymentsDBs/MoneyTransfer/Wiki/Billing/Tables/Billing.Transfers.md
-- Layer: bronze
-- UC Target: main.bi_db.bronze_moneytransfer_billing_transfers
-- =============================================================================

-- ---- UC Target: main.bi_db.bronze_moneytransfer_billing_transfers (business_group=BI_DB) ----
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers SET TBLPROPERTIES (
    'comment' = 'Core transactional table storing all money transfer records between funding sources (e.g., IBAN bank accounts and eToro Trading accounts), tracking each transfer from creation through processing to final resolution. Source: MoneyTransfer.Billing.Transfers on the MoneyTransfer production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/PaymentsDBs/MoneyTransfer/Wiki/Billing/Tables/Billing.Transfers.md).'
);

ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'MoneyTransfer',
    'source_schema' = 'Billing',
    'source_table' = 'Transfers',
    'business_group' = 'BI_DB',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN TransferID COMMENT 'Auto-incrementing unique identifier for each transfer. NONCLUSTERED PK. Used as a secondary lookup key and in range-based monitoring queries (GetLastTransfersStatusesInPercentage scans by TransferID ranges). Current values in the ~4.88M range. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN ReferenceID COMMENT 'Application-generated GUID serving as the primary business key for each transfer. UNIQUE CLUSTERED index makes it the physical sort order. All UPDATE operations (SaveRoutingInfo, SaveTransferOrigin, UpdateTransferStatus, etc.) locate records by ReferenceID via WHERE clause. More reliable than TransferID for cross-service correlation. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN CID COMMENT 'Customer identifier - the user who initiated or owns the transfer. Used for customer-scoped queries: GetTransfersByCID, GetDepotIdOfLastSuccessfulTransferByCid, GetLastSuccessTransferDataByCid. Indexed for performance (IX_Billing_Transfers_CID). References an external customer system. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN CurrencyID COMMENT 'Currency of the transfer amount. No Dictionary table exists in this database; values are managed externally. Sample data shows 2 (likely EUR) and 3 (likely GBP) as common values. Part of composite index IX_Billing_Transfers_CurrencyID_TransferStatusID_TransferID. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN OriginFundingTypeID COMMENT 'Type classification for the source/origin funding instrument. No lookup table in this database; values managed by the MoneyBus/MoneyBusAdapter application layer. Sample data shows 38 as the dominant value. Paired with DestinationFundingTypeID to define the transfer direction (e.g., bank-to-trading, trading-to-bank). (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN DestinationFundingTypeID COMMENT 'Type classification for the destination funding instrument. No lookup table in this database. Sample data shows 33 as the dominant value. Together with OriginFundingTypeID defines the transfer flow direction. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN Amount COMMENT 'Transfer amount in the currency specified by CurrencyID. Set at creation time and not modified afterward. Observed range in sample: 50 to 10,000. Stored as SQL Server money type (4 decimal places). (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN OriginFundingData COMMENT 'Masked (Dynamic Data Masking: default()) JSON or structured data containing the origin funding instrument details (bank account number, card details, etc.). Contains PII - masked for non-privileged users. Set by Billing.SaveTransferOrigin. NULL until the origin funding data is captured. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN DestinationFundingData COMMENT 'Masked (Dynamic Data Masking: default()) JSON or structured data containing the destination funding instrument details. Contains PII. Set by Billing.SaveTransferDestination. NULL until destination data is captured. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN CreateDate COMMENT 'UTC timestamp of transfer creation. Set automatically on INSERT via DEFAULT constraint. Never modified after creation. Used in monitoring queries to scope transfers by time window. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN ModificationDate COMMENT 'UTC timestamp of the most recent modification. Initialized to GETUTCDATE() on INSERT, then auto-updated by trigger TR_Transfers_ModificationDate on every UPDATE operation. The gap between CreateDate and ModificationDate indicates processing duration. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN TransferStatusID COMMENT 'Current lifecycle state of the transfer. Implicit FK to Dictionary.TransferStatus: 0=New, 1=Init, 2=Pending, 4=Technical, 7=Cancel, 8=Fail, 9=Sent, 10=Received. See Transfer Status for full business definitions. Set to 0 on INSERT by CreateTransfer; updated by UpdateTransferStatus. Status 10 is a hard terminal state. Part of composite index with CurrencyID and TransferID. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN ExReferenceID COMMENT 'External reference ID - a provider-facing identifier for the transfer. Prefix pattern observed: "TZ" and "TK" followed by a GUID fragment (lowercase, no hyphens). Set at creation time and can be updated by SaveExtRefId. Covered by index IX_Transfer_ExReferenceID_Cover for lookups via GetTransferByExReference. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN Trace COMMENT 'Computed column (not persisted) generating a JSON diagnostic string containing HostName, AppName, SUserName, SPID, DBName, and ObjectName at query time. Formula: CONCAT(''{"HostName": "'',host_name(),''","AppName": "'',app_name(),...}''). Used for debugging to identify which connection/process last read the row. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN StartTime COMMENT 'System versioning row start time (HIDDEN). Automatically managed by SQL Server temporal tables. Marks when this version of the row became current. Not visible in normal SELECT queries. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN EndTime COMMENT 'System versioning row end time (HIDDEN). Automatically managed by SQL Server temporal tables. Set to 9999-12-31 for current rows; set to the modification timestamp when a row is superseded. Not visible in normal SELECT queries. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN InitFundingId COMMENT 'Initial funding instrument identifier assigned early in the transfer pipeline, before origin/destination routing is finalized. Set by SaveTransferInitFundingId. Often NULL - populated only when the initial funding instrument differs from the final origin/destination. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN OriginFundingId COMMENT 'Provider-assigned numeric identifier for the origin funding instrument (bank account, card, wallet). Set by SaveTransferOriginFundingId. NULL in most recent sample data, suggesting it may be populated only for certain transfer types or providers. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN DestinationFundingId COMMENT 'Provider-assigned numeric identifier for the destination funding instrument. Set by SaveTransferDestinationFundingId. More frequently populated than OriginFundingId in sample data. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN DepotId COMMENT 'Depot/data center identifier determining which processing infrastructure handles this transfer. Set by SaveRoutingInfo. Common values: 104 and 166. Default fallback value is 104 (used by GetDepotIdOfLastSuccessfulTransferByCid when DepotId is NULL). Determines routing for regional processing. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN CountryId COMMENT 'Country identifier for the customer or transfer jurisdiction. Set by SaveRoutingInfo alongside DepotId. Observed values: 74, 112, 143, 191, 218. References an external country lookup. Used for regional routing and compliance. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
ALTER TABLE main.bi_db.bronze_moneytransfer_billing_transfers ALTER COLUMN ExtTransactionId COMMENT 'External transaction identifier from the payment provider. Set by SaveExtTransactionId. Can be GUID-format (with hyphens removed) or shorter hex strings, depending on the provider. NULL until the provider assigns a transaction reference. Returned by GetTransferByReferenceID. (Tier 1 - upstream wiki, MoneyTransfer.Billing.Transfers)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 09:38:27 UTC
-- Bronze deploy: MoneyTransfer batch 1
-- ====================
