-- =============================================================================
-- Databricks ALTER Script: bronze fiktivo.AffiliateConfiguration.TraderFirstAssetPosition
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/ExperianceDBs/fiktivo/Wiki/AffiliateConfiguration/Tables/AffiliateConfiguration.TraderFirstAssetPosition.md
-- Layer: bronze
-- UC Target: main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition
-- =============================================================================

-- ---- UC Target: main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition (business_group=BI_DB) ----
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition SET TBLPROPERTIES (
    'comment' = 'Tracks each customer''s first trading position asset class and accumulated revenue, used to determine when CPA commission thresholds from FirstPositionAssetPlan are met and the affiliate can be paid. Source: fiktivo.AffiliateConfiguration.TraderFirstAssetPosition on the fiktivo production database, ingested via the Generic Pipeline (Append strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/ExperianceDBs/fiktivo/Wiki/AffiliateConfiguration/Tables/AffiliateConfiguration.TraderFirstAssetPosition.md).'
);

ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'fiktivo',
    'source_schema' = 'AffiliateConfiguration',
    'source_table' = 'TraderFirstAssetPosition',
    'business_group' = 'BI_DB',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Append',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN CID COMMENT 'Customer identifier. Part of composite PK. References the customer who opened a first trading position. One row per CID (guaranteed by anti-join insert logic in SetTraderFirstAssetPosition). Used with PartitionCol for partition-aligned lookups: WHERE CID = @CID AND PartitionCol = @CID % 50. (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN PartitionCol COMMENT 'Computed: CID % 50. PERSISTED. Part of composite PK. Partition alignment column for the PS_Mod50 scheme, distributing rows across 50 physical partitions. Always included in WHERE clauses alongside CID to enable partition elimination. Never set by application code - derived automatically from CID. (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN FirstPositionAssetTypeID COMMENT 'Asset class of the customer''s first trading position. Implicit FK to Dictionary.PositionAssetType: 0=All, 1=Forex, 2=Commodity, 3=CFD, 4=Indices, 5=Stocks, 6=ETF, 7=Bonds, 8=TrustFunds, 9=Options, 10=Crypto, 11=Copy. See Position Asset Type. Crypto (10) dominates at 61%, CFD (3) at 34%. Set once on INSERT and never updated. Matched against FirstPositionAssetPlan.PositionAssetTypeID to determine CPA amount. (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN TotalRevenue COMMENT 'Cumulative trading revenue generated by this customer since their first position. Updated by SetCustomerFinanceDetailsState as new revenue is reported. NULL = no revenue reported yet. Used in RevenuesPercentage calculation to determine CPA threshold progress. (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN MinimumCommission COMMENT 'CPA revenue threshold this customer must reach before the affiliate''s commission is paid. Copied from the applicable FirstPositionAssetPlan entry. NULL = threshold not yet determined. 0 = no threshold required (immediate CPA payout). Updated by SetCustomerFinanceDetailsState alongside TotalRevenue. 98.6% of rows have 0 or NULL (no threshold). (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN DateAdded COMMENT 'Timestamp when the customer opened their first position and this row was created (UTC). Set by the @DateAdded parameter in SetTraderFirstAssetPosition - represents the actual position open time, not the insert time. Used in GetCreditTriggeredEvents for commission eligibility timing calculations. Never updated after insert. (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN RevenuesPercentage COMMENT 'Computed (not persisted): progress toward CPA minimum commission threshold, rounded to 2 decimals. Formula: CASE WHEN MinimumCommission=0 THEN 100 WHEN MinimumCommission IS NULL THEN NULL WHEN MinimumCommission < TotalRevenue THEN 100 ELSE (TotalRevenue/MinimumCommission)*100 END. Returns 100 when threshold is met or no threshold exists. Used by reporting (PortalReportSummaryByAffiliate) to show conversion progress. (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';
ALTER TABLE main.bi_db.bronze_fiktivo_affiliateconfiguration_traderfirstassetposition ALTER COLUMN DateUpdated COMMENT 'Timestamp of the last revenue update (UTC). Default: GETUTCDATE(). Set to GETUTCDATE() on every SetCustomerFinanceDetailsState call. Used as the only column in IX_TraderFirstAssetPosition_DateUpdated index, likely for batch processing queries that find recently-updated customers. (Tier 1 - upstream wiki, fiktivo.AffiliateConfiguration.TraderFirstAssetPosition)';

