SELECT [Custom SQL Query].[CID] AS [CID],
  [Custom SQL Query].[UserName] AS [UserName],
  [Custom SQL Query].[Club] AS [Club],
  [Custom SQL Query].[Channel] AS [Channel],
  [Custom SQL Query].[SubChannel] AS [SubChannel],
  [Custom SQL Query].[Country] AS [Country],
  [Custom SQL Query].[Language] AS [Language],
  [Custom SQL Query].[Region] AS [Region],
  [Custom SQL Query].[Credit] AS [Credit],
  [Custom SQL Query].[RealizedEquity] AS [RealizedEquity],
  [Custom SQL Query].[Blocked] AS [Blocked],
  [Custom SQL Query].[registered] AS [registered],
  [Custom SQL Query].[FirstTimeUser] AS [FirstTimeUser],
  [Custom SQL Query].[FirstLoggedIn] AS [FirstLoggedIn],
  [Custom SQL Query].[FirstDepositAttempt] AS [FirstDepositAttempt],
  [Custom SQL Query].[FirstDepositAttemptAmount] AS [FirstDepositAttemptAmount],
  [Custom SQL Query].[FirstDepositAttemptFundingType] AS [FirstDepositAttemptFundingType],
  [Custom SQL Query].[FirstDepositDate] AS [FirstDepositDate],
  [Custom SQL Query].[FirstDepositFundingType] AS [FirstDepositFundingType],
  [Custom SQL Query].[FirstDepositAmount] AS [FirstDepositAmount],
  [Custom SQL Query].[LastLoggedIn] AS [LastLoggedIn],
  [Custom SQL Query].[LastPosOpenDate] AS [LastPosOpenDate],
  [Custom SQL Query].[Gender] AS [Gender],
  [Custom SQL Query].[CountryID] AS [CountryID],
  [Custom SQL Query].[BirthDate] AS [BirthDate],
  [Custom SQL Query].[Follow5UsersDate] AS [Follow5UsersDate],
  [Custom SQL Query].[NumberOfUsersFollowed] AS [NumberOfUsersFollowed],
  [Custom SQL Query].[LastDepositDate] AS [LastDepositDate],
  [Custom SQL Query].[LastDepositAmount] AS [LastDepositAmount],
  [Custom SQL Query].[LastDepositFundingType] AS [LastDepositFundingType],
  [Custom SQL Query].[RegulationID] AS [RegulationID],
  [Custom SQL Query].[FTDIsLessThanAWeek] AS [FTDIsLessThanAWeek],
  [Custom SQL Query].[FirstNewFundedDate] AS [FirstNewFundedDate],
  [Custom SQL Query].[LastNewFundedDate] AS [LastNewFundedDate],
  [BI_DB_CID_MonthlyPanel_FullData].[CID] AS [CID (BI_DB_CID_MonthlyPanel_FullData)],
  [BI_DB_CID_MonthlyPanel_FullData].[Active_Month] AS [Active_Month],
  [BI_DB_CID_MonthlyPanel_FullData].[ActiveDate] AS [ActiveDate],
  [BI_DB_CID_MonthlyPanel_FullData].[Seniority] AS [Seniority],
  [BI_DB_CID_MonthlyPanel_FullData].[RegDate] AS [RegDate],
  [BI_DB_CID_MonthlyPanel_FullData].[IsReg_ThisM] AS [IsReg_ThisM],
  [BI_DB_CID_MonthlyPanel_FullData].[FTD_Month] AS [FTD_Month],
  [BI_DB_CID_MonthlyPanel_FullData].[FTDdate] AS [FTDdate],
  [BI_DB_CID_MonthlyPanel_FullData].[IsFTD_ThisM] AS [IsFTD_ThisM],
  [BI_DB_CID_MonthlyPanel_FullData].[FTDA] AS [FTDA],

  [BI_DB_CID_MonthlyPanel_FullData].[SubChannel] AS [SubChannel (BI_DB_CID_MonthlyPanel_FullData)],
  [BI_DB_CID_MonthlyPanel_FullData].[AffiliateID] AS [AffiliateID],
  [BI_DB_CID_MonthlyPanel_FullData].[FirstAction] AS [FirstAction],
  [BI_DB_CID_MonthlyPanel_FullData].[FirstInstrument] AS [FirstInstrument],
  [BI_DB_CID_MonthlyPanel_FullData].[EOM_Club] AS [EOM_Club],
  [BI_DB_CID_MonthlyPanel_FullData].[ActiveUser] AS [ActiveUser],
  [BI_DB_CID_MonthlyPanel_FullData].[Active] AS [Active],
  [BI_DB_CID_MonthlyPanel_FullData].[ActiveOpen] AS [ActiveOpen],

  [BI_DB_CID_MonthlyPanel_FullData].[IsFunded_New] AS [IsFunded_New]
FROM (
  SELECT [BI_DB_CIDFirstDates].[CID] AS [CID],
    [BI_DB_CIDFirstDates].[UserName] AS [UserName],
    [BI_DB_CIDFirstDates].[Club] AS [Club],
    [BI_DB_CIDFirstDates].[Channel] AS [Channel],
    [BI_DB_CIDFirstDates].[SubChannel] AS [SubChannel],
    [BI_DB_CIDFirstDates].[Country] AS [Country],
    [BI_DB_CIDFirstDates].[Language] AS [Language],
    [BI_DB_CIDFirstDates].[Region] AS [Region],
    [BI_DB_CIDFirstDates].[Credit] AS [Credit],
    [BI_DB_CIDFirstDates].[RealizedEquity] AS [RealizedEquity],
    [BI_DB_CIDFirstDates].[Blocked] AS [Blocked],
    [BI_DB_CIDFirstDates].[registered] AS [registered],
    [BI_DB_CIDFirstDates].[FirstTimeUser] AS [FirstTimeUser],
    [BI_DB_CIDFirstDates].[FirstLoggedIn] AS [FirstLoggedIn],
    [BI_DB_CIDFirstDates].[FirstDepositAttempt] AS [FirstDepositAttempt],
    [BI_DB_CIDFirstDates].[FirstDepositAttemptAmount] AS [FirstDepositAttemptAmount],
    [BI_DB_CIDFirstDates].[FirstDepositAttemptFundingType] AS [FirstDepositAttemptFundingType],
    [BI_DB_CIDFirstDates].[FirstDepositDate] AS [FirstDepositDate],
    [BI_DB_CIDFirstDates].[FirstDepositFundingType] AS [FirstDepositFundingType],
    [BI_DB_CIDFirstDates].[FirstDepositAmount] AS [FirstDepositAmount],
    [BI_DB_CIDFirstDates].[LastLoggedIn] AS [LastLoggedIn],
    [BI_DB_CIDFirstDates].[LastPosOpenDate] AS [LastPosOpenDate],
    [BI_DB_CIDFirstDates].[Gender] AS [Gender],
    [BI_DB_CIDFirstDates].[CountryID] AS [CountryID],
    [BI_DB_CIDFirstDates].[BirthDate] AS [BirthDate],
    [BI_DB_CIDFirstDates].[Follow5UsersDate] AS [Follow5UsersDate],
    [BI_DB_CIDFirstDates].[NumberOfUsersFollowed] AS [NumberOfUsersFollowed],
    [BI_DB_CIDFirstDates].[LastDepositDate] AS [LastDepositDate],
    [BI_DB_CIDFirstDates].[LastDepositAmount] AS [LastDepositAmount],
    [BI_DB_CIDFirstDates].[LastDepositFundingType] AS [LastDepositFundingType],
    [BI_DB_CIDFirstDates].[RegulationID] AS [RegulationID],
    [BI_DB_CIDFirstDates].[FTDIsLessThanAWeek] AS [FTDIsLessThanAWeek],
    [BI_DB_CIDFirstDates].[IsFundedNew] AS [IsFundedNew],
    [BI_DB_CIDFirstDates].[FirstNewFundedDate] AS [FirstNewFundedDate],
    [BI_DB_CIDFirstDates].[LastNewFundedDate] AS [LastNewFundedDate]
  FROM [dbo].[BI_DB_CIDFirstDates] [BI_DB_CIDFirstDates]
) [Custom SQL Query]
  FULL JOIN [dbo].[BI_DB_CID_MonthlyPanel_FullData] [BI_DB_CID_MonthlyPanel_FullData] ON ([Custom SQL Query].[CID] = [BI_DB_CID_MonthlyPanel_FullData].[CID])