select DateID
	 , TimeRange
	 , Regulation
	 , IsBlocked
	 , IsCreditReportValidCB
	 , IsGermanBaFin
	 , IsValidCustomer
	 , MifidCategory
	 , PlayerLevel
	 , PlayerStatus
	 , FirstActionType
	 , Country
	 , dc.MarketingRegionManualName as Region
	 , CountUsers
	 , Deposits
	 , Bonus
	 , Compensation
	 , Cashouts
	 , CashoutsIncludingRedeem
	 , CashoutFee
	 , OvernightFee
	 , CompensationPnLAdjustments
	 , TransferCoins
	 , TransferCoinFees
	 , realizedEquity
	 , DividendsPaid
	 , TotalLiability
	 , InProcessCashout
	 , NOPCrypto
	 , NOPCryptoCFD
	 , NOPStocks
	 , NOPStocksCFD
	 , TotalRealCryptoLoan
	 , PositionPNL
	 , NOP
	 , ActualNWA
	 , UnrealizedPnLChange
	 , DepositsCount
	 , Deposited
	 , CashoutsCount
	 , CashoutsAdjusted
	 , NewTrades
	 , NumberOfClosedPositions
	 , EditStoplossAmounts
	 , TotalInvestmentAmountInNewTrades
	 , FirstDepositors
	 , LoggedIn
	 , FirstDepositAmounts
	 , Registrations
	 , CashedOut
	 , CompensationRAFInvitedInviting
	 , AccountBalanceToMirrorAmount
	 , NewCopyAmount
	 , NewCopyActions
	 , PublishPost
	 , PublishComment
	 , PublishLike
	 , EngagedInFeed
	 , TotalCommission
	 , FullTotalCommission
	 , ManualCommission
	 , CopyCommission
	 , StocksOnlyCommission
	 , ETFCommission
	 , StocksAndETFsCommission
	 , CurrenciesCommission
	 , CommoditiesCommission
	 , IndicesCommission
	 , CryptoCommission
	 , PnLAdjustment
	 , FullManualCommission
	 , FullCopyCommission
	 , FullStocksCommission
	 , FullCryptoCommission
	 , PnlChange
	 , CopyPnlChange
	 , StocksPnlChange
	 , CryptoPnlChange
	 , ManualsPnlChange
	 , ActiveCopy
	 , ActiveManualStocksETFs
	 , ActiveManualFXCommoditiesIndices
	 , ActiveManualCrypto
	 , ActiveOpen
	 , ActiveOpenManual
	 , ActiveFunded
	 , ActiveTrader
	 , Revenue
	 , Equity
	 , NetNewTrades
	 , NetDeposit
	 , AdjustedNetDeposit
	 , OtherCompensationAmount
	 , InvestedInManualTradeing
	 , RealizedEquityCalculated
	 , NewCopyNetActions
	 , NewCopyUniqueUsers
	 , InvestedInStocksManual
	 , InvestedInCryptoManual
	 , InvestedInCopyIncludingCash
	 , NetMoneyIntoCopy
	 , NetMoneyIntoExistingCopy
	 , Redeposit
	 , DepositorsLoggedIn
	 , CustomerPnL
	 , CustomerPnLStocks
	 , CustomerPnLCopy
	 , CustomerPnLManual
	 , CustomerPnLCrypto
	 , CustomerPnLStocksReal
	 , CustomerPnLCryptoReal
	 , FullTotalCommissionFromBreakdown
	 , TotalCommissionFromBreakdown
	 , UnrealizedPnL
	 , CustomerZeroPnL
	 , CustomerZeroPnLAdjusted
	 , CustomerCopyZeroPnL
	 , CustomerStocksZeroPnL
	 , CustomerPnLAdjusted
	 , Redeemed
	 , CashedOutDefinition2
	 , StockTradersWithProfit
	 , StockTradersWithLoss
	 , CopyTradersWithProfit
	 , CopyTradersWithLoss
	 , TradersWithProfit
	 , TradersWithLoss
	 , MoneyIntoExistingCopy
	 , Credit
	 , tr.UpdateDate
	 , FirstTimeFunded
	 , Funded_New_Def
	 , FTDCurrentYear
	 , ReportDate
	 , ReportDateID
	 , DormantFee
	 , ConversionFees
	 , WalletBalanceUSD
	 , InterestFees
	 , DataSource
	 , InvestedInCryptoTRS
     , -1 * SDRT as SDRT
	 ,-1*tr.TradingFees as TradingFees
        , -1 * TicketFees as TicketFees
from BI_DB_dbo.BI_DB_DDR_TimeRange_Aggregated_Country_Level tr with (nolock)
JOIN DWH_dbo.Dim_Country dc WITH (NOLOCK)
	ON dc.Name = Country
where DateID = CAST(FORMAT(CAST(<[Parameters].[Parameter 1]> AS DATE),'yyyyMMdd') as INT)