SELECT `gold_tres_staking_data_staking_data`.`Asset_Identifier` AS `asset_identifier`,
  `gold_tres_staking_data_staking_data`.`Asset_Name` AS `Asset_Name`,
  `gold_tres_staking_data_staking_data`.`Asset_Symbol` AS `Asset_Symbol`,
  `gold_tres_staking_data_staking_data`.`Claimable` AS `Claimable`,
  `gold_tres_staking_data_staking_data`.`Date` AS `Date`,
  `gold_tres_staking_data_staking_data`.`Day` AS `day`,
  `gold_tres_staking_data_staking_data`.`Fiat_Value_Per_Unit` AS `Fiat_Value_Per_Unit`,
  `gold_tres_staking_data_staking_data`.`FileName` AS `filename`,
  `gold_tres_staking_data_staking_data`.`Generated_Rewards` AS `Generated_Rewards`,
  `gold_tres_staking_data_staking_data`.`Identifier` AS `identifier`,
  `gold_tres_staking_data_staking_data`.`Internal_Account_Name` AS `Internal_Account_Name`,
  `gold_tres_staking_data_staking_data`.`Internal_Account_Tags` AS `Internal_Account_Tags`,
  `gold_tres_staking_data_staking_data`.`Locked` AS `Locked`,
  `gold_tres_staking_data_staking_data`.`Month` AS `month`,
  `gold_tres_staking_data_staking_data`.`Platform` AS `Platform`,
  `gold_tres_staking_data_staking_data`.`ReportDateID` AS `reportdateid`,
  `gold_tres_staking_data_staking_data`.`Start` AS `start`,
  `gold_tres_staking_data_staking_data`.`Total_Fiat_Value` AS `Total_Fiat_Value`,
  `gold_tres_staking_data_staking_data`.`Unlocking` AS `Unlocking`,
  `gold_tres_staking_data_staking_data`.`Validator_Identifier` AS `Validator_Identifier`,
  `gold_tres_staking_data_staking_data`.`Week_Number` AS `week_number`,
  `gold_tres_staking_data_staking_data`.`Year` AS `year`,
  `gold_tres_staking_data_staking_data`.`Yield_Type` AS `Yield_Type`,
  `gold_tres_staking_data_staking_data`.`etr_y` AS `etr_y`,
  `gold_tres_staking_data_staking_data`.`etr_ym` AS `etr_ym`,
  `gold_tres_staking_data_staking_data`.`etr_ymd` AS `etr_ymd`
FROM `main`.`general`.`gold_tres_staking_data_staking_data` `gold_tres_staking_data_staking_data`
where `gold_tres_staking_data_staking_data`.`Date` = <[Parameters].[Parameter 5]> and `gold_tres_staking_data_staking_data`.`etr_ymd` = dateadd(day,1,<[Parameters].[Parameter 5]>)