SELECT [Dim_Country].[Abbreviation] AS [Abbreviation],
  [BI_DB_CID_DailyPanel_Club].[AccountManagerID] AS [AccountManagerID],
  [BI_DB_CID_DailyPanel_Club].[AmountToRemain] AS [AmountToRemain],
  [BI_DB_CID_DailyPanel_Club].[AmountToUpgrade] AS [AmountToUpgrade],
  [Dim_Country].[CFKey] AS [CFKey],
  [BI_DB_CID_DailyPanel_Club].[CID] AS [CID],
  [Dim_Date].[CalendarQuarter] AS [CalendarQuarter],
  [Dim_Date].[CalendarSemester] AS [CalendarSemester],
  [Dim_Date].[CalendarYearMonth] AS [CalendarYearMonth],
  [Dim_Date].[CalendarYearQtr] AS [CalendarYearQtr],
  [Dim_Date].[CalendarYear] AS [CalendarYear],
  [BI_DB_CID_DailyPanel_Club].[CashoutFeeExemption] AS [CashoutFeeExemption],
  [BI_DB_CID_DailyPanel_Club].[CashoutFeePaid] AS [CashoutFeePaid],
  [LastTier].[CashoutPendingHours] AS [CashoutPendingHours (Dim_PlayerLevel)],
  [CurrentTier].[CashoutPendingHours] AS [CashoutPendingHours],
  [BI_DB_CID_DailyPanel_Club].[Classification] AS [Classification],
  [Dim_Country].[CountryID] AS [CountryID (Dim_Country)],
  [BI_DB_CID_DailyPanel_Club].[CountryID] AS [CountryID],
  [BI_DB_CID_DailyPanel_Club].[CurrentTier] AS [CurrentTier],
  [Dim_Country].[DWHCountryID] AS [DWHCountryID],
  [LastTier].[DWHPlayerLevelID] AS [DWHPlayerLevelID (Dim_PlayerLevel)],
  [CurrentTier].[DWHPlayerLevelID] AS [DWHPlayerLevelID],
  [BI_DB_CID_DailyPanel_Club].[DailyCalculationInterest] AS [DailyCalculationInterest],
  [BI_DB_CID_DailyPanel_Club].[DailyFee] AS [DailyFee],
  [BI_DB_CID_DailyPanel_Club].[DateID] AS [DateID],
  [Dim_Date].[DateKey] AS [DateKey],
  [BI_DB_CID_DailyPanel_Club].[Date] AS [Date],
  [Dim_Date].[DayNameAbbreviation] AS [DayNameAbbreviation],
  [Dim_Date].[DayName] AS [DayName],
  [Dim_Date].[DayNumberOfFiscalYear] AS [DayNumberOfFiscalYear],
  [Dim_Date].[DayNumberOfMonth] AS [DayNumberOfMonth],
  [Dim_Date].[DayNumberOfQuarter] AS [DayNumberOfQuarter],
  [Dim_Date].[DayNumberOfWeek_Sun_Start] AS [DayNumberOfWeek_Sun_Start],
  [Dim_Date].[DayNumberOfYear] AS [DayNumberOfYear],
  [BI_DB_CID_DailyPanel_Club].[DaysFromFTD] AS [DaysFromFTD],
  [BI_DB_CID_DailyPanel_Club].[DaysInClub] AS [DaysInClub],
  [BI_DB_CID_DailyPanel_Club].[DaysInCurrentClub] AS [DaysInCurrentClub],
  [Dim_Date].[DaysSince1900] AS [DaysSince1900],
  [BI_DB_CID_DailyPanel_Club].[DaysTillFTC] AS [DaysTillFTC],
  [BI_DB_CID_DailyPanel_Club].[DepositAmountWireTransfer] AS [DepositAmountWireTransfer],
  [BI_DB_CID_DailyPanel_Club].[DepositAmount] AS [DepositAmount],
  [BI_DB_CID_DailyPanel_Club].[DepositConversionFeeExemption] AS [DepositConversionFeeExemption],
  [BI_DB_CID_DailyPanel_Club].[DepositConversionFee] AS [DepositConversionFee],
  [BI_DB_CID_DailyPanel_Club].[DepositTransactions] AS [DepositTransactions],
  [BI_DB_CID_DailyPanel_Club].[DepositWireTransferTransactions] AS [DepositWireTransferTransactions],
  [Dim_Country].[Desk] AS [Desk],
  [Dim_Country].[EU] AS [EU],
  [BI_DB_CID_DailyPanel_Club].[Equity] AS [Equity],
  [BI_DB_CID_DailyPanel_Club].[ExpectedDowngradeDate] AS [ExpectedDowngradeDate],
  [BI_DB_CID_DailyPanel_Club].[ExpectedDowngradePlayerLevelID] AS [ExpectedDowngradePlayerLevelID],
  [BI_DB_CID_DailyPanel_Club].[ExpectedDowngradeStartDate] AS [ExpectedDowngradeStartDate],
  [BI_DB_CID_DailyPanel_Club].[ExpectedDowngradeTierLT] AS [ExpectedDowngradeTierLT],
  [BI_DB_CID_DailyPanel_Club].[FTCDate] AS [FTCDate],
  [BI_DB_CID_DailyPanel_Club].[FTDDate] AS [FTDDate],
  [Dim_Date].[FiscalMonth] AS [FiscalMonth],
  [Dim_Date].[FiscalQuarter] AS [FiscalQuarter],
  [Dim_Date].[FiscalYearMonth] AS [FiscalYearMonth],
  [Dim_Date].[FiscalYearQtr] AS [FiscalYearQtr],
  [Dim_Date].[FiscalYear] AS [FiscalYear],
  [LastTier].[FromSumDeposit] AS [FromSumDeposit (Dim_PlayerLevel)],
  [CurrentTier].[FromSumDeposit] AS [FromSumDeposit],
  [LastTier].[FromSumLotCount] AS [FromSumLotCount (Dim_PlayerLevel)],
  [CurrentTier].[FromSumLotCount] AS [FromSumLotCount],
  [Dim_Date].[FullDate] AS [FullDate],
  [Dim_Date].[ISOWeekNumberOfQuarter_454_Pattern] AS [ISOWeekNumberOfQuarter_454_Pattern],
  [Dim_Date].[ISOWeekNumberOfYear] AS [ISOWeekNumberOfYear],
  [Dim_Date].[ISOYearAndWeekNumber] AS [ISOYearAndWeekNumber],
  [Dim_Country].[InsertDate] AS [InsertDate (Dim_Country)],
  [LastTier].[InsertDate] AS [InsertDate (Dim_PlayerLevel)],
  [CurrentTier].[InsertDate] AS [InsertDate],
  [BI_DB_CID_DailyPanel_Club].[InvestedAmount] AS [InvestedAmount],
  [Dim_Date].[IsBankHoliday] AS [IsBankHoliday],
  [BI_DB_CID_DailyPanel_Club].[IsClosedCreditLine] AS [IsClosedCreditLine],
  [Dim_Date].[IsCompanyHoliday] AS [IsCompanyHoliday],
  [BI_DB_CID_DailyPanel_Club].[IsCreditEligible] AS [IsCreditEligible],
  [BI_DB_CID_DailyPanel_Club].[IsCreditLineCustomer] AS [IsCreditLineCustomer],
  [BI_DB_CID_DailyPanel_Club].[IsDowngrade] AS [IsDowngrade],
  [Dim_Country].[IsEligibleForRAFBonusCountry] AS [IsEligibleForRAFBonusCountry],
  [Dim_Country].[IsEuropeanCountry] AS [IsEuropeanCountry],
  [BI_DB_CID_DailyPanel_Club].[IsExpectedDowngrade] AS [IsExpectedDowngrade],
  [BI_DB_CID_DailyPanel_Club].[IsFTC] AS [IsFTC],
  [Dim_Date].[IsFederalHoliday] AS [IsFederalHoliday],
  [Dim_Date].[IsFirstDayOfMonth] AS [IsFirstDayOfMonth],
  [BI_DB_CID_DailyPanel_Club].[IsFundedCurrentTier] AS [IsFundedCurrentTier],
  [BI_DB_CID_DailyPanel_Club].[IsFunded] AS [IsFunded],
  [Dim_Country].[IsHighRiskCountry] AS [IsHighRiskCountry],
  [Dim_Date].[IsLastDayOfMonth] AS [IsLastDayOfMonth],
  [BI_DB_CID_DailyPanel_Club].[IsOpenCreditLine] AS [IsOpenCreditLine],
  [BI_DB_CID_DailyPanel_Club].[IsOptInInterest] AS [IsOptInInterest],
  [BI_DB_CID_DailyPanel_Club].[IsProCustomer] AS [IsProCustomer],
  [BI_DB_CID_DailyPanel_Club].[IsUpgrade] AS [IsUpgrade],
  [Dim_Date].[IsWeekday] AS [IsWeekday],
  [Dim_Date].[IsWeekend] AS [IsWeekend],
  [Dim_Date].[IsWorkday] AS [IsWorkday],
  [BI_DB_CID_DailyPanel_Club].[LastContacted] AS [LastContacted],
  [BI_DB_CID_DailyPanel_Club].[LastTier] AS [LastTier],
  [Dim_Country].[LongAbbreviation] AS [LongAbbreviation],
  [Dim_Date].[MM/DD/YYYY] AS [MM/DD/YYYY],
  [Dim_Country].[MarketingRegionID] AS [MarketingRegionID],
  [Dim_Country].[MarketingRegionManualName] AS [MarketingRegionManualName],
  [BI_DB_CID_DailyPanel_Club].[MaxTier] AS [MaxTier],
  [Dim_Date].[MonDDYYYY] AS [MonDDYYYY],
  [BI_DB_CID_DailyPanel_Club].[Moneyfarm] AS [Moneyfarm],
  [Dim_Date].[MonthNameAbbreviation] AS [MonthNameAbbreviation],
  [Dim_Date].[MonthName] AS [MonthName],
  [Dim_Date].[MonthNumberOfQuarter] AS [MonthNumberOfQuarter],
  [Dim_Date].[MonthNumberOfYear] AS [MonthNumberOfYear],
  [BI_DB_CID_DailyPanel_Club].[MonthlyInterestPayments] AS [MonthlyInterestPayments],
  [Dim_Country].[Name] AS [Name (Dim_Country)],
  [LastTier].[Name] AS [Name (Dim_PlayerLevel)],
  [CurrentTier].[Name] AS [Name],
  [BI_DB_CID_DailyPanel_Club].[OptInDate] AS [OptInDate],
  [Dim_Date].[PartitionID] AS [PartitionID],
  [LastTier].[PlayerLevelID] AS [PlayerLevelID (Dim_PlayerLevel)],
  [CurrentTier].[PlayerLevelID] AS [PlayerLevelID],
  [Dim_Date].[QuarterNumber] AS [QuarterNumber],
  [BI_DB_CID_DailyPanel_Club].[RealizedEquityClub] AS [RealizedEquityClub],
  [BI_DB_CID_DailyPanel_Club].[RealizedEquityNoCFD] AS [RealizedEquityNoCFD],
  [BI_DB_CID_DailyPanel_Club].[RealizedEquity] AS [RealizedEquity],
  [Dim_Country].[Region] AS [Region],
  [Dim_Country].[RegulationID] AS [RegulationID (Dim_Country)],
  [BI_DB_CID_DailyPanel_Club].[RegulationID] AS [RegulationID],
  [BI_DB_CID_DailyPanel_Club].[Revenue] AS [Revenue],
  [Dim_Country].[RiskGroupID] AS [RiskGroupID],
  [Dim_Date].[SSWeekNumberOfMonth] AS [SSWeekNumberOfMonth],
  [Dim_Date].[SSWeekNumberOfQuarter_454_Pattern] AS [SSWeekNumberOfQuarter_454_Pattern],
  [Dim_Date].[SSWeekNumberOfYear] AS [SSWeekNumberOfYear],
  [LastTier].[Sort] AS [Sort (Dim_PlayerLevel)],
  [CurrentTier].[Sort] AS [Sort],
  [Dim_Country].[StatusID] AS [StatusID (Dim_Country)],
  [LastTier].[StatusID] AS [StatusID (Dim_PlayerLevel)],
  [CurrentTier].[StatusID] AS [StatusID],
  [BI_DB_CID_DailyPanel_Club].[TierChangeDate] AS [TierChangeDate],
  [BI_DB_CID_DailyPanel_Club].[TierChangeType] AS [TierChangeType],
  [LastTier].[ToSumDeposit] AS [ToSumDeposit (Dim_PlayerLevel)],
  [CurrentTier].[ToSumDeposit] AS [ToSumDeposit],
  [LastTier].[ToSumLotCount] AS [ToSumLotCount (Dim_PlayerLevel)],
  [CurrentTier].[ToSumLotCount] AS [ToSumLotCount],
  [BI_DB_CID_DailyPanel_Club].[TotalCLAmount] AS [TotalCLAmount],
  [Dim_Country].[UpdateDate] AS [UpdateDate (Dim_Country)],
  [Dim_Date].[UpdateDate] AS [UpdateDate (Dim_Date)],
  [LastTier].[UpdateDate] AS [UpdateDate (Dim_PlayerLevel) #1],
  [CurrentTier].[UpdateDate] AS [UpdateDate (Dim_PlayerLevel)],
  [BI_DB_CID_DailyPanel_Club].[UpdateDate] AS [UpdateDate],
  [BI_DB_CID_DailyPanel_Club].[WithdrawAmountWallet] AS [WithdrawAmountWallet],
  [BI_DB_CID_DailyPanel_Club].[WithdrawAmountWireTransfer] AS [WithdrawAmountWireTransfer],
  [BI_DB_CID_DailyPanel_Club].[WithdrawAmount] AS [WithdrawAmount],
  [BI_DB_CID_DailyPanel_Club].[WithdrawConversionFeeExemption] AS [WithdrawConversionFeeExemption],
  [BI_DB_CID_DailyPanel_Club].[WithdrawConversionFee] AS [WithdrawConversionFee],
  [BI_DB_CID_DailyPanel_Club].[WithdrawTransactions] AS [WithdrawTransactions],
  [BI_DB_CID_DailyPanel_Club].[WithdrawWalletTransactions] AS [WithdrawWalletTransactions],
  [BI_DB_CID_DailyPanel_Club].[WithdrawWireTransferTransactions] AS [WithdrawWireTransferTransactions],
  [Dim_Date].[YYYY-MM-DD] AS [YYYY-MM-DD],
  [Dim_Date].[YYYY/MM/DD] AS [YYYY/MM/DD],
  [Dim_Date].[YYYYMMDD] AS [YYYYMMDD],
  [Dim_Regulation].[Name] AS [Regulation],
  [BI_DB_CID_DailyPanel_Club].[eMoneyBalance] AS [eMoneyBalance]
FROM [BI_DB_dbo].[BI_DB_CID_DailyPanel_Club] [BI_DB_CID_DailyPanel_Club]
  INNER JOIN [DWH_dbo].[Dim_Date] [Dim_Date] ON ([BI_DB_CID_DailyPanel_Club].[DateID] = [Dim_Date].[DateKey])
  INNER JOIN [DWH_dbo].[Dim_PlayerLevel] [CurrentTier] ON ([BI_DB_CID_DailyPanel_Club].[CurrentTier] = [CurrentTier].[DWHPlayerLevelID])
  INNER JOIN [DWH_dbo].[Dim_PlayerLevel] [LastTier] ON ([BI_DB_CID_DailyPanel_Club].[LastTier] = [LastTier].[PlayerLevelID])
  INNER JOIN [DWH_dbo].[Dim_Country] [Dim_Country] ON ([BI_DB_CID_DailyPanel_Club].[CountryID] = [Dim_Country].[CountryID])
  INNER JOIN [DWH_dbo].[Dim_Regulation] [Dim_Regulation] ON ([BI_DB_CID_DailyPanel_Club].[RegulationID]= [Dim_Regulation].[ID])