With cids as (
  SELECT
	c.RealCID,
  c.RegisteredReal,
	co.Name as KYC_Country,
  co1.Name as CountryIDByIP,
  case when c.CountryID <> c.CountryIDByIP then 'MISMATCH' else 'MATCH' end as CountryIDByIP_Mismatch,
	c.VerificationLevelID,
	ps.Name as PlayerStatus,
	pl.Name as PlayerLevel,
  c.IsDepositor,
  case when lower(cc.Comments) like ('%registration abuse%') then 'ABUSE' else 'NOT ABUSE' end as Abuse,
  e.EvMatchStatusName,
CASE 
    WHEN (co.Name = 'France' AND co1.Name = 'Bulgaria') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Bulgaria') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Serbia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Seychelles') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Seychelles') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Czech Republic') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Czech Republic') THEN 'Block'
    WHEN (co.Name = 'Cayman Islands' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Seychelles') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Barbados') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Thailand') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Afghanistan' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Nigeria' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'Sint Maarten (Dutch Part)' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Puerto Rico') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Guyana') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Seychelles') THEN 'Block'
    WHEN (co.Name = 'Costa Rica' AND co1.Name = 'Nicaragua') THEN 'Block'
    WHEN (co.Name = 'Nepal' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Kazakhstan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Brunei') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Moldova') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Puerto Rico') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Romania') THEN 'Block'
    WHEN (co.Name = 'American Samoa' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Nigeria' AND co1.Name = 'Not available') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'Croatia' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Myanmar') THEN 'Block'
    WHEN (co.Name = 'Albania' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'American Samoa' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Armenia' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Mexico') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'Guadeloupe' AND co1.Name = 'French Guiana') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'Thailand') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'Thailand') THEN 'Block'
    WHEN (co.Name = 'Uzbekistan' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Uzbekistan' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Bangladesh') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Afghanistan' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Uzbekistan' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'Cuba' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Sri Lanka' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'Ghana' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'Dominican Republic' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Latvia') THEN 'Block'
    WHEN (co.Name = 'Not available' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'Cameroon' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Tajikistan') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Afghanistan' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Jordan' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Cyprus') THEN 'Block'
    WHEN (co.Name = 'Cote d''Ivoire' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Uzbekistan' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'American Samoa' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Liechtenstein' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Kazakhstan') THEN 'Block'
    WHEN (co.Name = 'Armenia' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Jamaica' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Albania') THEN 'Block'
    WHEN (co.Name = 'Martinique' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Chile') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Bahrain' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'Jordan' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Bahrain') THEN 'Block'
    WHEN (co.Name = 'French Polynesia' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Guadeloupe' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'Italy') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Colombia') THEN 'Block'
    WHEN (co.Name = 'Nigeria' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Belgium') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Saint Lucia') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'Ecuador') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Cambodia') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Trinidad and Tobago') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Not available' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Barbados') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Myanmar') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Kazakhstan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Puerto Rico') THEN 'Block'
    WHEN (co.Name = 'Kyrgyzstan' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Slovenia' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Brunei') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Macedonia') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Hungary' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Chile') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Romania') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Botswana') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Algeria' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Colombia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Myanmar') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Grenada') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Slovenia') THEN 'Block'
    WHEN (co.Name = 'Romania' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Belgium') THEN 'Block'
    WHEN (co.Name = 'Azerbaijan' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Antigua and Barbuda') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Namibia') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Grenada') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Spain') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Myanmar') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Ethiopia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Laos') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Yemen') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'South Africa') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'Slovenia' AND co1.Name = 'Singapore') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Bahamas') THEN 'Block'
    WHEN (co.Name = 'Poland' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Sweden') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Saint Lucia') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Not available') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Macau') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Congo Republic') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Italy') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'Jordan' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Kazakhstan' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Poland') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Ethiopia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Reunion Island') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Ethiopia') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'Greece' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Greece' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Syria') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'South Africa') THEN 'Block'
    WHEN (co.Name = 'Switzerland' AND co1.Name = 'Latvia') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Mali') THEN 'Block'
    WHEN (co.Name = 'Saudi Arabia' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Colombia' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'Uruguay' AND co1.Name = 'Venezuela') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Poland') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Yemen') THEN 'Block'
    WHEN (co.Name = 'Ecuador' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'Italy') THEN 'Block'
    WHEN (co.Name = 'Indonesia' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Iran') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Trinidad and Tobago') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Turkey') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Belgium') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Turkey' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Singapore' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'Romania') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Argentina') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Hong Kong') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Romania') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Guyana') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Kazakhstan') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Switzerland') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Romania') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Switzerland' AND co1.Name = 'Moldova') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Belgium') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Bahamas') THEN 'Block'
    WHEN (co.Name = 'Indonesia' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'South Korea' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Poland') THEN 'Block'
    WHEN (co.Name = 'Thailand' AND co1.Name = 'Cambodia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Suriname') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Zambia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Iraq') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Congo') THEN 'Block'
    WHEN (co.Name = 'Italy' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Poland' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'China') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Russia') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Uganda') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'Malaysia') THEN 'Block'
    WHEN (co.Name = 'Colombia' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Ecuador' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Israel') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Mongolia') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Czech Republic') THEN 'Block'
    WHEN (co.Name = 'Bahrain' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Uzbekistan') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Zambia') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Poland') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Seychelles' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Argentina') THEN 'Block'
    WHEN (co.Name = 'Switzerland' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'Singapore' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Austria') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'Mexico') THEN 'Block'
    WHEN (co.Name = 'Morocco' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Sweden') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Kuwait') THEN 'Block'
    WHEN (co.Name = 'India' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Kyrgyzstan') THEN 'Block'
    WHEN (co.Name = 'Austria' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Costa Rica' AND co1.Name = 'El Salvador') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Belgium') THEN 'Block'
    WHEN (co.Name = 'Greece' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Switzerland') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Kazakhstan') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Italy') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'Netherlands' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Colombia' AND co1.Name = 'Venezuela') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Mauritius') THEN 'Block'
    WHEN (co.Name = 'Reunion Island' AND co1.Name = 'Mauritius') THEN 'Block'
    WHEN (co.Name = 'Colombia' AND co1.Name = 'El Salvador') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Kyrgyzstan') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Norway') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Ghana') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'Australia') THEN 'Block'
    WHEN (co.Name = 'Switzerland' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Austria') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Cote d''Ivoire') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Uzbekistan') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'El Salvador') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Bosnia and Herzegovina') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Botswana') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Italy' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Oman') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Kuwait') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Nepal') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'El Salvador') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Zimbabwe') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Uganda') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Guinea') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Mozambique') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Singapore') THEN 'Block'
    WHEN (co.Name = 'Martinique' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Portugal' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Bahrain' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'Cambodia') THEN 'Block'
    WHEN (co.Name = 'Egypt' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Spain' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Nigeria' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'Cyprus' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Romania' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'South Africa') THEN 'Block'
    WHEN (co.Name = 'French Guiana' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Burkina Faso') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Poland') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Guatemala') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Switzerland' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Mauritania') THEN 'Block'
    WHEN (co.Name = 'Spain' AND co1.Name = 'Cote d''Ivoire') THEN 'Block'
    WHEN (co.Name = 'Costa Rica' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'Spain' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'Bulgaria' AND co1.Name = 'Serbia') THEN 'Block'
    WHEN (co.Name = 'Bulgaria' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Nepal') THEN 'Block'
    WHEN (co.Name = 'Dominican Republic' AND co1.Name = 'Puerto Rico') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'El Salvador') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Virgin Islands') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Poland') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Tanzania') THEN 'Block'
    WHEN (co.Name = 'Martinique' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Armenia') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Togo') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Peru') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Uganda') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Guatemala') THEN 'Block'
    WHEN (co.Name = 'Costa Rica' AND co1.Name = 'Guatemala') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Thailand') THEN 'Block'
    WHEN (co.Name = 'Reunion Island' AND co1.Name = 'Madagascar') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'United Kingdom' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Uzbekistan') THEN 'Block'
    WHEN (co.Name = 'Norway' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Rwanda') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Uzbekistan') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Mauritania') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Turkey') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Azerbaijan') THEN 'Block'
    WHEN (co.Name = 'Chile' AND co1.Name = 'Haiti') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Gabon') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Gabon') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Burkina Faso') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Belgium') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Bahrain') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'Japan') THEN 'Block'
    WHEN (co.Name = 'Oman' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Sweden' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Norway' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Spain' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Romania') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Panama') THEN 'Block'
    WHEN (co.Name = 'Poland' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Laos') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Seychelles' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'South Korea' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Libya') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Paraguay') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Jamaica') THEN 'Block'
    WHEN (co.Name = 'Netherlands' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Australia') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Mongolia') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Costa Rica' AND co1.Name = 'Panama') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Saudi Arabia') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Angola') THEN 'Block'
    WHEN (co.Name = 'Portugal' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Mauritania') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'Croatia' AND co1.Name = 'Montenegro') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Uzbekistan') THEN 'Block'
    WHEN (co.Name = 'Uruguay' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Cambodia') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Libya') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Senegal') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Kyrgyzstan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Libya') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Cote d''Ivoire') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Peru') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Ghana') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Mozambique') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Madagascar') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Uganda') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'Hungary' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'United Kingdom') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Netherlands') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Nepal') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Malta' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Senegal') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Paraguay') THEN 'Block'
    WHEN (co.Name = 'Austria' AND co1.Name = 'Azerbaijan') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Costa Rica') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Armenia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Jamaica') THEN 'Block'
    WHEN (co.Name = 'Nigeria' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Togo') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'Cayman Islands' AND co1.Name = 'Jamaica') THEN 'Block'
    WHEN (co.Name = 'Pakistan' AND co1.Name = 'Netherlands') THEN 'Block'
    WHEN (co.Name = 'Iceland' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Ghana') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Guatemala') THEN 'Block'
    WHEN (co.Name = 'Cayman Islands' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Denmark' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Italy') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Uganda') THEN 'Block'
    WHEN (co.Name = 'Iceland' AND co1.Name = 'Israel') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Oman') THEN 'Block'
    WHEN (co.Name = 'Colombia' AND co1.Name = 'Curacao') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Taiwan') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Haiti') THEN 'Block'
    WHEN (co.Name = 'Austria' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Mongolia') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Azerbaijan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Malawi') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Uruguay') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Oman') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Panama') THEN 'Block'
    WHEN (co.Name = 'Bulgaria' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Angola') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Turkey') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Uzbekistan') THEN 'Block'
    WHEN (co.Name = 'Bulgaria' AND co1.Name = 'Macedonia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Angola') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Bolivia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Senegal') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Thailand') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Netherlands') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Cote d''Ivoire') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Oman' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Ghana') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Ghana') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Curacao') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'South Africa') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Swaziland') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Seychelles') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Azerbaijan') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Argentina') THEN 'Block'
    WHEN (co.Name = 'Netherlands' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'US Virgin Islands' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Uruguay') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Madagascar') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Cyprus') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Tanzania') THEN 'Block'
    WHEN (co.Name = 'Bahrain' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'Austria' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Laos') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Qatar') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Cambodia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Burundi') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Botswana') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Bolivia') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Spain' AND co1.Name = 'Guatemala') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Mexico') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Cote d''Ivoire') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Netherlands') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Libya') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Azerbaijan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Rwanda') THEN 'Block'
    WHEN (co.Name = 'Colombia' AND co1.Name = 'Aruba') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Azerbaijan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Macedonia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Belgium') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Macedonia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Togo') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Togo') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Maldives') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'New Zealand' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Puerto Rico' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Singapore') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'El Salvador') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Niger') THEN 'Block'
    WHEN (co.Name = 'Ireland' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Hong Kong' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Portugal' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Serbia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Madagascar') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Malawi') THEN 'Block'
    WHEN (co.Name = 'Belgium' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Germany') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Mozambique') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Sweden' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Iceland' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Paraguay') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Zambia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Libya') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Libya') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Chad') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Cote d''Ivoire') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Ghana') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Lesotho') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Cambodia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Mauritania') THEN 'Block'
    WHEN (co.Name = 'Denmark' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'Austria' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Luxembourg' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Saudi Arabia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Chile') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'United Arab Emirates' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Netherlands') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Guatemala') THEN 'Block'
    WHEN (co.Name = 'Dominican Republic' AND co1.Name = 'Haiti') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Ecuador') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Maldives') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Paraguay') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Slovenia' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Monaco' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Ecuador' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Cambodia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Colombia') THEN 'Block'
    WHEN (co.Name = 'Israel' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Malaysia') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Zambia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Uganda') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'El Salvador') THEN 'Block'
    WHEN (co.Name = 'Spain' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Albania') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Ecuador') THEN 'Block'
    WHEN (co.Name = 'Bahrain' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Guinea') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Paraguay') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Colombia') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Chile') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Saudi Arabia') THEN 'Block'
    WHEN (co.Name = 'Qatar' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'South Africa' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Tunisia') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Saudi Arabia') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Burkina Faso') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Jordan') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Burkina Faso') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Sri Lanka') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'Slovenia' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'Ecuador' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Tanzania') THEN 'Block'
    WHEN (co.Name = 'Kuwait' AND co1.Name = 'Saudi Arabia') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Haiti') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Thailand') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Armenia') THEN 'Block'
    WHEN (co.Name = 'Brazil' AND co1.Name = 'Angola') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Kyrgyzstan') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Serbia') THEN 'Block'
    WHEN (co.Name = 'Argentina' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Armenia') THEN 'Block'
    WHEN (co.Name = 'Australia' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Indonesia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Mauritius') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Mongolia') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'United States') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Suriname') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Jamaica') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Canada') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Togo') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Georgia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Serbia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Armenia') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'France') THEN 'Block'
    WHEN (co.Name = 'Vietnam' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Ghana') THEN 'Block'
    WHEN (co.Name = 'Poland' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Algeria') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Thailand') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Angola') THEN 'Block'
    WHEN (co.Name = 'Malaysia' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Guatemala') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Bangladesh') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Benin') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Ukraine') THEN 'Block'
    WHEN (co.Name = 'Mexico' AND co1.Name = 'Czech Republic') THEN 'Block'
    WHEN (co.Name = 'Bangladesh' AND co1.Name = 'Saudi Arabia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Madagascar') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Cameroon') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Egypt') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Philippines') THEN 'Block'
    WHEN (co.Name = 'US Minor Islands' AND co1.Name = 'India') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Moldova') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Azerbaijan') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Moldova') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Nigeria') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Bangladesh') THEN 'Block'
    WHEN (co.Name = 'Spain' AND co1.Name = 'Morocco') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Trinidad and Tobago') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Brazil') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Honduras') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Pakistan') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Kenya') THEN 'Block'
    WHEN (co.Name = 'Singapore' AND co1.Name = 'Netherlands') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'Saudi Arabia') THEN 'Block'
    WHEN (co.Name = 'France' AND co1.Name = 'Bangladesh') THEN 'Block'
    WHEN (co.Name = 'Germany' AND co1.Name = 'Bangladesh') THEN 'Block'
    WHEN (co.Name = 'United States' AND co1.Name = 'India') THEN 'Block'
    ELSE 'Should Sent to EV'
END AS BlockfromEV
FROM
	main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_customer_masked c
	LEFT JOIN main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_country co on co.CountryID = c.CountryID
  LEFT JOIN main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_country co1 on co1.CountryID = c.CountryIDByIP
	LEFT JOIN main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_playerstatus ps on ps.PlayerStatusID = c.PlayerStatusID
	LEFT JOIN main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_playerlevel pl on c.PlayerLevelID = pl.PlayerLevelID
  LEFT JOIN main.general.bronze_etoro_customer_customer_masked cc on cc.CID = c.RealCID
  LEFT JOIN main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_evmatchstatus e on e.EvMatchStatusID = c.EvMatchStatus
WHERE 
  c.RegisteredReal >= date_add(current_date(), -180)
)

,evvendor as (
SELECT DISTINCT
    cc.RealCID
    ,ev.Name as EvProvider
    ,ev1.EvMatchStatusName
FROM  
    main.compliance.bronze_userapidb_ev_customerresult  cr
JOIN 
    main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_customer_masked cc on cr.GCID = cc.GCID
LEFT JOIN 
    main.compliance.bronze_userapidb_dictionary_evprovider ev on ev.EvProviderId = cr.EvProviderId
LEFT JOIN 
    main.dwh.gold_sql_dp_prod_we_dwh_dbo_dim_evmatchstatus ev1 on cc.EvMatchStatus=ev1.EvMatchStatusId
)

,finalev as (

Select distinct 
    e.RealCID
    ,concat_ws(', ', collect_list(e.EvProvider)) as EvProviders
    ,concat_ws(', ', collect_list(e.EvMatchStatusName)) as EvMatchStatus
FROM 
    evvendor e
GROUP BY 
    e.RealCID
)

select
  count(c.realcid) as NumOfClients,
  c.KYC_Country,
  c.CountryIDByIP,
  c.CountryIDByIP_Mismatch,
  c.VerificationLevelID,
  c.PlayerStatus,
  c.PlayerLevel,
  c.IsDepositor,
  cast(c.RegisteredReal as date) as RegisteredReal,
  c.Abuse
  ,case when c.evmatchstatusname = 'None' or c.evmatchstatusname is null then 'Not Sent to EV' else 'Sent to EV' end as EV_Sent
  ,c.BlockfromEV
  ,f.evproviders
  ,f.evmatchstatus
FROM
  cids c 
LEFT JOIN 
  finalev f on f.realcid = c.realcid
GROUP BY 
  c.KYC_Country,
  c.CountryIDByIP,
  c.CountryIDByIP_Mismatch,
  c.VerificationLevelID,
  c.PlayerStatus,
  c.PlayerLevel,
  c.IsDepositor,
  cast(c.RegisteredReal as date),
  c.Abuse,
  c.evmatchstatusname,
  case when c.evmatchstatusname = 'None' or c.evmatchstatusname is null then 'Not Sent to EV' else 'Sent to EV' end,
  c.BlockfromEV 
  ,f.evproviders
  ,f.evmatchstatus