SELECT rr.RiskScore_Explanation
	  ,rr.Regulation
	  ,rr.RiskScoreName
	  ,rr.GCID
	  ,rr.CID	
	  ,dc.RealCID
	  ,dc.DemoCID
	  ,dc.OriginalCID
	  ,dc.UserName
	  ,dc.FirstName
	  ,dc.LastName
	  ,dc.Gender
	  ,dc.BirthDate
	  ,dc.ReferralID
	  ,dc.CountryID
	  ,dc.IP
	  ,dc.AffiliateID
	  ,dc.CampaignID
	  ,dc.SubChannelID
	  ,dc.LabelID
	  ,dc.LanguageID
	  ,dc.Email
	  ,dc.Phone
	  ,dc.Zip
	  ,dc.City
	  ,dc.Address
	  ,dc.AccountExpirationDate
	  ,dc.SocialConnectID
	  ,dc.VerificationLevelID
	  ,dc.DocsOK
	  ,dc.PlayerStatusID
	  ,dc.Bankruptcy
	  ,dc.FunnelID
	  ,dc.DownloadID
	  ,dc.RegisteredReal
	  ,dc.RegisteredDemo
	  ,dc.FunnelFromID
	  ,dc.RiskStatusID
	  ,dc.RiskClassificationID
	  ,dc.EmployeeAccount
	  ,dc.CommunicationLanguageID
	  ,dc.BannerID
	  ,dc.PremiumAccount
	  ,dc.Evangelist
	  ,dc.GuruStatusID
	  ,dc.NumOfGurus
	  ,dc.NumOfCopiers
	  ,dc.NumOfRAF
	  ,dc.AccountTypeID
	  ,dc.RegulationID
	  ,dc.PlayerLevelID
	  ,dc.AccountStatusID
	  ,dc.AccountManagerID
	  ,dc.HasAvatar
	  ,dc.AvatarUploadDate
	  ,dc.UpdateDate
	  ,dc.IsDepositor
	  ,dc.FirstDepositDate
	  ,dc.ID
	  ,dc.ExternalID
	  ,dc.PlayerStatusReasonID
	  ,dc.PendingClosureStatusID
	  ,dc.CountryIDByIP
	  ,dc.SubSerialID
	  ,dc.EvMatchStatus
	  ,dc.DocumentStatusID
	  ,dc.RegulationChangeDate
	  ,dc.IsCopyBlocked
	  ,dc.WorldCheckID
	  ,dc.IsEDD
	  ,dc.SuitabilityTestStatusID
	  ,dc.FirstDepositAmount
	  ,dc.PrivacyPolicyID
	  ,dc.MifidCategorizationID
	  ,dc.IsEmailVerified
	  ,dc.IsValidCustomer
	  ,dc.[2FA]
	  ,dc.DesignatedRegulationID
	  ,dc.RegionByIP_ID
	  ,dc.ScreeningStatusID
	  ,dc.RegionID
	  ,dc.WorldCheckResultsUpdated
	  ,dc.HasWallet
	  ,dc.IsAddressProof
	  ,dc.IsAddressProofExpiryDate
	  ,dc.IsIDProof
	  ,dc.IsIDProofExpiryDate
	  ,dc.PhoneVerifiedID
	  ,dc.CitizenshipCountryID
	  ,dc.PlayerStatusSubReasonID
	  ,dc.IsCreditReportValidCB
	  ,dc.CashoutFeeGroupID
	  ,dc.MiddleName
	  ,dc.BuildingNumber
	  ,dc.UserName_Lower
	  ,dc.SalesForceAccountID
	  ,dc.POBCountryID
	  ,dc.ApexID
	  ,dc.PhoneNumber
	  ,dc.IsPhoneVerified
	  ,dc.PhoneVerificationDate
	  ,dc.WeekendFeePrecentage
          ,bdasec.AMLSubEntity
	  ,bdasec.AMLEntity	
	  ,bdasec.AMLSubEntity_2
FROM [BI_DB_dbo].[External_RiskClassification_dbo_V_RiskClassificationDataLake] rr
JOIN DWH_dbo.Dim_Customer dc ON dc.RealCID = rr.CID
LEFT JOIN BI_DB_dbo.BI_DB_AML_SubEntity_Categorization bdasec ON dc.RealCID= bdasec.CID
AND dc.IsValidCustomer =1
AND dc.IsDepositor =1
AND dc.VerificationLevelID =3
AND dc.PlayerStatusID NOT IN (2,4)
WHERE rr.CID = <[Parameters].[Parameter 1]>