SELECT ecfee.C2FCorrelationID
	  ,ecfee.TargetPlatformID
	  ,ecfee.TargetPlatform
	  ,ecfee.ConversionCycle
	  ,ecfee.LastModificationDateTime
	  ,ecfee.LastModificationDate
	  ,ecfee.LastModificationDateID
	  ,ecfee.GCID
	  ,ecfee.RealCID
	  ,ecfee.RequestID
	  ,ecfee.RequestCryptoID
	  ,ecfee.RequestDateTime
	  ,ecfee.RequestLastStatusID
	  ,ecfee.RequestLastStatus
	  ,ecfee.RequestLastStatusDateTime
	  ,ecfee.SentTransactionID
	  ,ecfee.SentBlockchainTransactionID
	  ,ecfee.SentWalletID
	  ,ecfee.SentTransactionDateTime
	  ,ecfee.SentBlockchainFee
	  ,ecfee.SentCryptoID
	  ,ecfee.SentAmount
	  ,ecfee.SentEtoroFees
	  ,ecfee.SentLastStatusID
	  ,ecfee.SentLastStatus
	  ,ecfee.EstimatedFiatAmount
	  ,ecfee.EstimatedUsdAmount
	  ,ecfee.EstimatedCryptoToUsdRate
	  ,ecfee.EstimatedFiatToUsdRate
	  ,ecfee.EstimatedCryptoToFiatRate
	  ,ecfee.EstimatedDateTime
	  ,ecfee.C2FConversionID
	  ,ecfee.CryptoID
	  ,ecfee.Crypto
	  ,ecfee.FiatCurrencyID
	  ,ecfee.FiatCurrency
	  ,ecfee.CryptoAmount
	  ,ecfee.TotalFeePercentage
	  ,ecfee.TotalFeeUSD
	  ,ecfee.ConversionDateTime
	  ,ecfee.ConversionDateID
	  ,ecfee.ConversionDate
	  ,ecfee.ConversionStatusID
	  ,ecfee.ConversionStatus
	  ,ecfee.ConversionStatusDateTime
	  ,ecfee.ConversionStatusDateID
	  ,ecfee.ConversionStatusDate
	  ,ecfee.BlockchainTransactionID
	  ,ecfee.FromAddress
	  ,ecfee.ToAddress
	  ,ecfee.BlockchainFee
	  ,ecfee.CryptoTransactionDateTime
	  ,ecfee.CryptoTransactionDateID
	  ,ecfee.CryptoTransactionDate
	  ,ecfee.CryptoToFiatRate
	  ,ecfee.FiatToUsdRate
	  ,ecfee.CryptoToUsdRate
	  ,ecfee.FiatAmount
	  ,ecfee.UsdAmount
	  ,ecfee.FiatAccountID
	  ,ecfee.FiatDetails
	  ,ecfee.RateTime
	  ,ecfee.FiatTxTime
	  ,ecfee.eMoneyTransactionID
	  ,ecfee.eMoneyTxCreatedDate
	  ,ecfee.eMoneyReferenceNumber
	  ,ecfee.eMoneyLastTxStatusID
	  ,ecfee.eMoneyLastTxStatus
	  ,ecfee.eMoneyHolderAmount
	  ,ecfee.eMoneyLastStatusTime
	  ,ecfee.eMoneyProviderTransactionID
	  ,ecfee.eMoneyAccountProgram
	  ,ecfee.eMoneyAccountSubProgram
	  ,ecfee.eMoneyCurrencyBalanceID
	  ,ecfee.eMoneyProviderCurrencyBalanceID
	  ,ecfee.eMoneyHolderID
	  ,ecfee.eMoneyIsValidETM
	  ,ecfee.eMoneyEntity
	  ,ecfee.IsTestAccount
	  ,ecfee.IsRequestDone
	  ,ecfee.TribeHolderAmount
	  ,ecfee.TribeTxDateTime
	  ,ecfee.DepositID
	  ,ecfee.DepositDateTime
	  ,ecfee.DepositModificationTime
	  ,ecfee.DepositLastStatusID
	  ,ecfee.DepositLastStatus
	  ,ecfee.DepositUSD
	  ,ecfee.RegulationID
	  ,ecfee.Regulation
	  ,ecfee.CountryID
	  ,ecfee.Country
	  ,ecfee.CustomerRegionID
	  ,ecfee.State
	  ,ecfee.IsValidCustomer
	  ,ecfee.IsCreditReportValidCB
	  ,ecfee.PlayerLevelID
	  ,ecfee.Club
	  ,ecfee.PlayerStatusID
	  ,ecfee.PlayerStatus
	  ,ecfee.WalletEntity
	  ,ecfee.AccountManager
	  ,ecfee.UpdateDate 
	  
	  FROM EXW_dbo.EXW_C2F_E2E ecfee
 WHERE   
    LastModificationDate >=  <[Parameters].[Parameter 1]>
   
AND 
   LastModificationDate <= <[Parameters].[Start Date for Report (copy)_223772611717361664]>