SELECT ([TR_MIFID_EU_CySEC_TRAX_Response].[TRAX1_AACK]+ISNULL([TR_MIFID_EU_CySEC_TRAX_Response].[TRAX2_AACK],0))-
[TR_MIFID_EU_CySEC_TRAX_Response].[CySEC_RACK]+ISNULL([TR_MIFID_EU_CySEC_TRAX_Response].[CySEC_NPND],0) AS [CySEC_NPND],
  [TR_MIFID_EU_CySEC_TRAX_Response].[CySEC_RACK] AS [CySEC_RACK],
  [TR_MIFID_EU_CySEC_TRAX_Response].[CySEC_RREJ] AS [CySEC_RREJ],
  [TR_MIFID_EU_CySEC_TRAX_Response].[CySEC_Total] AS [CySEC_Total],
  [TR_MIFID_EU_CySEC_TRAX_Response].[Submission Date] AS [Submission Date],
  [TR_MIFID_EU_CySEC_TRAX_Response].[TRAX1_AACK] AS [TRAX1_AACK],
  [TR_MIFID_EU_CySEC_TRAX_Response].[TRAX1_AREJ] AS [TRAX1_AREJ],
  [TR_MIFID_EU_CySEC_TRAX_Response].[TRAX1_HELD] AS [TRAX1_HELD],
  [TR_MIFID_EU_CySEC_TRAX_Response].[TRAX2_AACK] AS [TRAX2_AACK],
  [TR_MIFID_EU_CySEC_TRAX_Response].[TRAX2_AREJ] AS [TRAX2_AREJ],
  [TR_MIFID_EU_CySEC_TRAX_Response].[TRAX_Total] AS [TRAX_Total],
  ([TR_MIFID_EU_CySEC_TRAX_Response].[TRAX1_AACK]+ISNULL([TR_MIFID_EU_CySEC_TRAX_Response].[TRAX2_AREJ],0)) AS TOTAL,
  [TR_MIFID_EU_CySEC_TRAX_Response].[UpdateDate] AS [UpdateDate]
FROM [dbo].[TR_MIFID_EU_CySEC_TRAX_Response] [TR_MIFID_EU_CySEC_TRAX_Response]