SELECT 
       bdad.CID, 
       bdad.DepositID,
       bdad.FundingType,
       bdad.[Amount In Orig Curr],
       bdad.[Amount in $],
       bdad.Currency,
       bdad.ModificationDate,
       bdad.[Deposit Time],
       bdad.Month, 
       bdad.Day,
       bdad.Year,
   bdad.PaymentStatus PaymentStatus ,
       bdad.[Country (customer)], 
       bdad.FirstDepositDate, 
       bdad.Funnel,
       bdad.FunnelFrom, 
       bdad.BINCountry, 
       bdad.Provider,
       bdad.CardType,
       bdad.CardSubType,
       bdad.IsFTD,
       bdad.[Country By Reg IP],
       bdad.[Deposit Risk Status],
       bdad.RiskStatus,
       bdad.[External Transaction ID],
       bdad.Region, bdad.[Affiliate ID],
       bdad.[Account Manager],
       bdad.BinCode,
       bdad.[Bank name by Bincode],
       bdad.Regulation,
       bdad.DesignatedRegulation,
       bdad.Category,
       bdad.MID,
       bdad.UpdateDate,
       bdad.Response,
       bdad.ModificationDateID, 
       bdad.BankCode,
       bdad.PSPCode,
       bdad.FundingID,
       bdad.AccountBalanceAsDecimal,
       bdad.AccountHolderAsString,
       bdad.AccountIDAsDecimal,
       bdad.ACHBankAccountIDAsInteger,
       bdad.Address1AsString,
       bdad.Address2AsString,
       bdad.AdviseAsString,
       bdad.AvailableBalanceAsDecimal,
       bdad.BankCodeAsString,
       bdad.BankIDAsInteger,
       bdad.BillNumberAsString, 
       bdad.BuildingNumberAsString,
       bdad.CardHolderPhoneNumberBodyAsString,
       bdad.CardHolderPhoneNumberPrefixAsString,
       bdad.CardNumberAsString, 
       bdad.CityAsString,
       bdad.CountryIDAsString,
       bdad.CountryNameAsString,
       bdad.CreatedAtAsString,
       bdad.CurrentBalanceAsDecimal,
       bdad.CustomerIDAsString,
       bdad.EmailAsString,
       bdad.EndPointIDAsString,
       bdad.ErrorCodeAsString,
       bdad.FirstNameAsString, 
       bdad.ErrorTypeAsString,
       bdad.IBANCodeAsString,
       bdad.InitialTransactionIDAsString,
       bdad.IPAsString, 
       bdad.LanguageIDAsInteger,
       bdad.LastNameAsString, 
       bdad.MD5AsString, 
       bdad.PayerAsString,
       bdad.PayerBusiness,
       bdad.PayerIDAsString,
       bdad.PayerPurseAsString,
       bdad.PaymentAmountAsDecimal,
       bdad.PayerStatus,
       bdad.PaymentDateAsDateTime,
       bdad.PaymentGuaranteeAsString,
       bdad.PaymentModeAsInteger,
       bdad.PaymentProviderTransactionStatusAsString,
       bdad.PaymentStatusAsInteger, 
       bdad.PaymentTypeAsString,
       bdad.PlaidItemIDAsString,
       bdad.PlaidNamesAsString,
       bdad.PlatformIDAsInteger, 
       bdad.PromotionCodeAsString,
       bdad.PSPCodeAsString,
       bdad.RapidFirstNameAsString, 
       bdad.RapidLastNameAsString,
       bdad.ResponseMessageAsString,
       bdad.ResponseTimeAsString,
       bdad.SecretKeyAsString,
       bdad.ThreeDsAsJson,
       bdad.ThreeDsResponseType,
       bdad.TokenAsString,
       bdad.TransactionIDAsString,
       bdad.ZipCodeAsString,
       bdad.AccountIDAsString,
       bdad.AccountTypeAsString,
       bdad.BankAccountAsString,
       bdad.BankAddressAsString,
       bdad.BankCodeAsDecimal,
       bdad.BankDetailsAccountIDAsString,
       bdad.BankIDAsString,
       bdad.BankNameAsString,
       bdad.BICCodeAsString,
       bdad.BinCodeAsString,
       bdad.BinCountryIDAsInteger,
       bdad.CardTypeIDAsInteger,
       bdad.CIDAsString,
       bdad.ClientBankNameAsString,
       bdad.CountryIDAsInteger,
       bdad.CustomerAddressAsString,
       bdad.CustomerNameAsString,
       bdad.ExpirationDateAsString,
       bdad.MaskedAccountIDAsString,
       bdad.PurseAsString,
       bdad.RoutingNumberAsString,
       bdad.SecuredCardDataAsString,
       bdad.SecureIDAsDecimal,
       bdad.SortCodeAsString,
       bdad.SwiftCodeAsString,
       bdad.BaseExchangeRate
      ,dp.Product+' '+dp.Platform+' '+' '+dp.SubPlatform Platform
      ,fbd.MOPCountry
      ,dc.Region [Region (Custom SQL Query)]
	  ,dc.EU
	  ,dc.Name
	  ,CASE WHEN fbd.ThreeDsAsJson IS NOT NULL  THEN 1 ELSE 0 END IsThreeDS 
      ,dc2.Region MOPRegion
      ,dc3.Name WireCountry
      ,dc3.Region WireRegion
	  ,fbd.BankName
	  ,fbd.CardCategory
FROM BI_DB_dbo.BI_DB_AllDeposits bdad 
LEFT JOIN BI_DB_dbo.BI_DB_All_Deposit_Hourly bdadh1
    ON bdad.DepositID = bdadh1.DepositID
LEFT JOIN DWH_dbo.Dim_Country dc
	ON dc.Name = bdad.BINCountry
LEFT JOIN DWH_dbo.Fact_BillingDeposit fbd
    ON bdad.DepositID = fbd.DepositID
LEFT JOIN DWH_dbo.Dim_Product dp
    ON dp.ProductID = fbd.PlatformID
LEFT JOIN DWH_dbo.Dim_Country dc2
	ON dc2.Name = fbd.MOPCountry
LEFT JOIN DWH_dbo.Dim_Country dc3
    ON dc3.CountryID = CAST(bdad.CountryIDAsInteger AS INT)
WHERE bdad.ModificationDateID>=CAST(FORMAT(CAST(DATEADD(YEAR,-2,GETDATE()-1) AS DATE),'yyyyMMdd') as INT)