SELECT a.TransferDirection
	 , a.Regulation
	 , a.IsCreditReportValidCB
	 , a.DidRegulationTransfer
	 , a.DidCBValidTransfer
	 , a.IsEtoroTradingCID
	 , a.eToroTradingGroupUser
	 , a.IsGlenEagleAccount
	 , a.Region
	 , a.FromRegulation
	 , a.ToRegulation
	 , a.AccountType
	 , a.Label
	 , a.Country
	 , a.MifidCategory
	 , a.Club
	 , a.PlayerStatus
	 , a.DateID
	 , CASE WHEN a.RNAsc = 1 THEN a.OpeningBalance ELSE 0 END AS OpeningBalance
	 , a.Deposits
	 , a.CompensationDeposit
	 , a.Bonus
	 , a.Compensation
	 , a.CompensationPI
	 , a.CompensationToAffiliate
	 , a.NWAAdjustment
	 , a.NegativeRefill
	 , a.Cashouts
	 , a.CashoutsIncludingRedeem
	 , a.CompensationCashouts
	 , a.CashoutFee
	 , a.Chargeback
	 , a.Refund
	 , a.OvernightFee
	 , a.LostDebt
	 , a.ChargebackLoss
	 , a.OtherNegatives
	 , a.Foreclosure
	 , a.CompensationPnLAdjustments
	 , a.CompensationDormantFee
	 , a.ClientBalanceRealizedPnL
	 , a.ClientBalanceRealizedPnLCFD
	 , a.ClientBalanceRealizedPnLRealStocks
	 , a.ClientBalanceRealizedPnLRealCrypto
	 , a.TransferCoins
	 , a.TransferCoinFees
	 , CASE WHEN RNDesc = 1 THEN  a.ClosingBalance ELSE 0 END AS ClosingBalance
	 , a.realizedEquity
	 , a.RealCryptoOpenBalance
	 , a.RealCryptoClosingBalance
	 , a.ClientMoneyOpenBalance
	 , a.ClientMoneyClosingBalance
	 , a.RealStocksOpeningBalance
	 , a.RealStocksClosingBalance
	 , a.ClientBalanceFullCommission
	 , a.ClientBalanceCommission
	 , a.ClientBalanceFullCommissionCFD
	 , a.ClientBalanceCommissionCFD
	 , a.ClientBalanceFullCommissionRealCrypto
	 , a.ClientBalanceCommissionRealCrypto
	 , a.ClientBalanceFullCommissionRealStocks
	 , a.ClientBalanceCommissionRealStocks
	 , a.DividendsPaid
	 , a.TotalLiability
	 , a.TotalNegativeLiability
	 , a.WithdrawableLiability
	 , a.NegativeWithdrawableLiability
	 , a.LiabilityInUsedMargin
	 , a.NegativeLiabilityInUsedMargin
	 , a.InProcessCashout
	 , a.NegativeInProcessCashout
	 , a.NOPCrypto
	 , a.NOPCryptoCFD
	 , a.NOPStocks
	 , a.NOPStocksCFD
	 , a.TotalRealCryptoLoan
	 , a.TotalRealCrypto
	 , a.TotalRealStocks
	 , a.PositionPNLCryptoReal
	 , a.PositionPNLStocksReal
	 , a.PositionPNL
	 , a.AvailableCash
	 , a.CashInCopy
	 , a.NOP
	 , a.PositionAmount
	 , a.StockOrders
	 , a.actualNWA
	 , a.UsedBonus
	 , a.UnrealizedCommissionChange
	 , a.UnrealizedFullCommissionChange
	 , a.UnrealizedPnLChange
	 , a.UnrealizedPnLChangeCFD
	 , a.UnrealizedPnLChangeCryptoReal
	 , a.UnrealizedPnLChangeStocksReal
	 , a.UnrealizedFullCommissionChangeRealStocks
	 , a.TotalNetTransfers
	 , a.TotalTransfersInvestedRealStocks
	 , a.TotalTransfersInvestedRealCrypto
	 , a.NetTransfersNWA
	 , a.NetTransfersUnrealizedPnL
	 , a.NetTransfersLiability
	 , a.NetLiabilityTransferStocks
	 , a.NetUnrealizedPnLTransferStocks
	 , a.UpdateDate
	 , a.PositionPnLCrypto
	 , a.PositionPnLStocks
	 , a.TotalCryptoPositionAmount
	 , a.TotalStocksPositionAmount
	 , a.IsGermanBaFin
	 , a.IsValidCustomer
	 , a.Date
	 , a.YearMonth
	 , a.YearQuarter
	 , a.Year
	 , a.RNAsc
	 , a.RNDesc
        , a.UnrealizedCommissionChangeRealStocks
        , a.TotalRealStocksEquityChange 
FROM 
(
select TransferDirection
	 , Regulation
	 , IsCreditReportValidCB
	 , DidRegulationTransfer
	 , DidCBValidTransfer
	 , IsEtoroTradingCID
	 , eToroTradingGroupUser
	 , IsGlenEagleAccount
	 , Region
	 , FromRegulation
	 , ToRegulation
	 , AccountType
	 , Label
	 , Country
	 , MifidCategory
	 , Club
	 , PlayerStatus
	 , DateID
	 , OpeningBalance
	 , Deposits
	 , CompensationDeposit
	 , Bonus
	 , Compensation
	 , CompensationPI
	 , CompensationToAffiliate
	 , NWAAdjustment
	 , NegativeRefill
	 , Cashouts
	 , CashoutsIncludingRedeem
	 , CompensationCashouts
	 , CashoutFee
	 , Chargeback
	 , Refund
	 , OvernightFee
	 , LostDebt
	 , ChargebackLoss
	 , OtherNegatives
	 , Foreclosure
	 , CompensationPnLAdjustments
	 , CompensationDormantFee
	 , ClientBalanceRealizedPnL
	 , ClientBalanceRealizedPnLCFD
	 , ClientBalanceRealizedPnLRealStocks
	 , ClientBalanceRealizedPnLRealCrypto
	 , TransferCoins
	 , TransferCoinFees
	 , ClosingBalance
	 , realizedEquity
	 , RealCryptoOpenBalance
	 , RealCryptoClosingBalance
	 , ClientMoneyOpenBalance
	 , ClientMoneyClosingBalance
	 , RealStocksOpeningBalance
	 , RealStocksClosingBalance
	 , ClientBalanceFullCommission
	 , ClientBalanceCommission
	 , ClientBalanceFullCommissionCFD
	 , ClientBalanceCommissionCFD
	 , ClientBalanceFullCommissionRealCrypto
	 , ClientBalanceCommissionRealCrypto
	 , ClientBalanceFullCommissionRealStocks
	 , ClientBalanceCommissionRealStocks
	 , DividendsPaid
	 , TotalLiability
	 , TotalNegativeLiability
	 , WithdrawableLiability
	 , NegativeWithdrawableLiability
	 , LiabilityInUsedMargin
	 , NegativeLiabilityInUsedMargin
	 , InProcessCashout
	 , NegativeInProcessCashout
	 , NOPCrypto
	 , NOPCryptoCFD
	 , NOPStocks
	 , NOPStocksCFD
	 , TotalRealCryptoLoan
	 , TotalRealCrypto
	 , TotalRealStocks
	 , PositionPNLCryptoReal
	 , PositionPNLStocksReal
	 , PositionPNL
	 , AvailableCash
	 , CashInCopy
	 , NOP
	 , PositionAmount
	 , StockOrders
	 , actualNWA
	 , UsedBonus
	 , UnrealizedCommissionChange
	 , UnrealizedFullCommissionChange
	 , UnrealizedPnLChange
	 , UnrealizedPnLChangeCFD
	 , UnrealizedPnLChangeCryptoReal
	 , UnrealizedPnLChangeStocksReal
	 , UnrealizedFullCommissionChangeRealStocks
	 , TotalNetTransfers
	 , TotalTransfersInvestedRealStocks
	 , TotalTransfersInvestedRealCrypto
	 , NetTransfersNWA
	 , NetTransfersUnrealizedPnL
	 , NetTransfersLiability
	 , NetLiabilityTransferStocks
	 , NetUnrealizedPnLTransferStocks
	 , UpdateDate
	 , PositionPnLCrypto
	 , PositionPnLStocks
	 , TotalCryptoPositionAmount
	 , TotalStocksPositionAmount
	 , IsGermanBaFin
	 , IsValidCustomer
	 , Date
	 , YearMonth
	 , YearQuarter
	 , Year
	 , DENSE_RANK () OVER (ORDER BY DateID) AS RNAsc
	 , DENSE_RANK () OVER (ORDER BY DateID desc) AS RNDesc
        ,UnrealizedCommissionChangeRealStocks
        , TotalRealStocksEquityChange 
from BI_DB_Client_Balance_Aggregate_Level_New  with (nolock)
where DateID between 
CAST(CONVERT(VARCHAR(8), <[Parameters].[ToDateID (copy)]>, 112) AS INT)
and 
CAST(CONVERT(VARCHAR(8), <[Parameters].[ToDateID (copy 2)]>, 112) AS INT)
) a