SELECT [Dealing_CopiersAnalysis_AdHoc].[Amount] AS [Amount],
  [Dealing_CopiersAnalysis_AdHoc].[Amt_Balance_Ratio] AS [Amt_Balance_Ratio],
  [Dealing_CopiersAnalysis_AdHoc].[CID] AS [CID],
  [Dealing_CopiersAnalysis_AdHoc].[Category] AS [Category],
  [Dealing_CopiersAnalysis_AdHoc].[CopyType] AS [CopyType],
  [Dealing_CopiersAnalysis_AdHoc].[CountryName] AS [CountryName],
  [Dealing_CopiersAnalysis_AdHoc].[Date_Diff] AS [Date_Diff],
  [Dealing_CopiersAnalysis_AdHoc].[DepositSummary] AS [DepositSummary],
  [Dealing_CopiersAnalysis_AdHoc].[InitialInvestment] AS [InitialInvestment],
  [Dealing_CopiersAnalysis_AdHoc].[NegativePnL] AS [NegativePnL],
  [Dealing_CopiersAnalysis_AdHoc].[PnL1Y] AS [PnL1Y],
  [Dealing_CopiersAnalysis_AdHoc].[PnL3M] AS [PnL3M],
  [Dealing_CopiersAnalysis_AdHoc].[RealziedPnL] AS [RealziedPnL],
  [Dealing_CopiersAnalysis_AdHoc].[SubCategory] AS [SubCategory],
  [Dealing_CopiersAnalysis_AdHoc].[TotalEquity] AS [TotalEquity],
  [Dealing_CopiersAnalysis_AdHoc].[TradeID] AS [TradeID],
  [Dealing_CopiersAnalysis_AdHoc].[UpdateDate] AS [UpdateDate],
  [Dealing_CopiersAnalysis_AdHoc].[Year] AS [Year],
Case when [InitialInvestment] <>0 then [InitialInvestment] else [Amount] end as InitInvest
FROM [Dealing_dbo].[Dealing_CopiersAnalysis_AdHoc] [Dealing_CopiersAnalysis_AdHoc]