SELECT [BI_DB_SF_Users].[AccountManagerID] AS [AccountManagerID],
  [BI_DB_SF_Users].[Alias] AS [Alias],
  [BI_DB_SF_Users].[Department] AS [Department],
  [BI_DB_SF_Users].[Department_BOB] AS [Department_BOB],
  [BI_DB_SF_Users].[Desk_BOB] AS [Desk_BOB],
  [BI_DB_SF_Users].[Desk_CS] AS [Desk_CS],
  [BI_DB_SF_Users].[FirstName] AS [FirstName],
  [BI_DB_SF_Users].[FullName] AS [FullName],
  [BI_DB_SF_Users].[GroupName] AS [GroupName],
  [BI_DB_SF_Users].[Id] AS [Id],
  [BI_DB_SF_Users].[IsActive] AS [IsActive],
  [BI_DB_SF_Users].[IsAssignable] AS [IsAssignable],
  [BI_DB_SF_Users].[IsChatUser] AS [IsChatUser],
  [BI_DB_SF_Users].[IsDummyUser] AS [IsDummyUser],
  [BI_DB_SF_Users].[IsOutsourced] AS [IsOutsourced],
  [BI_DB_SF_Users].[IsSupportUser] AS [IsSupportUser],
  [BI_DB_SF_Users].[LastName] AS [LastName],
  [BI_DB_SF_Users].[ManagerId] AS [ManagerId],
  [BI_DB_SF_Users].[Manager] AS [Manager],
  [BI_DB_SF_Users].[ReportsToID_BOB] AS [ReportsToID_BOB],
  [BI_DB_SF_Users].[ReportsTo_BOB] AS [ReportsTo_BOB],
  [BI_DB_SF_Users].[ServiceLevel] AS [ServiceLevel],
  [BI_DB_SF_Users].[Site] AS [Site],
  [BI_DB_SF_Users].[SubDepartment_BOB] AS [SubDepartment_BOB],
  [BI_DB_SF_Users].[SubRole] AS [SubRole],
  [BI_DB_SF_Users].[Team] AS [Team],
  [BI_DB_SF_Users].[Title] AS [Title],
  [BI_DB_SF_Users].[UpdateDate] AS [UpdateDate],
  [BI_DB_SF_Users].[UserRole] AS [UserRole],
  [BI_DB_SF_Users].[Username] AS [Username]
FROM [dbo].[BI_DB_SF_Users] [BI_DB_SF_Users]
where [IsActive]='1'