SELECT ([TR_MIFID_UK_FCA_TRAX_Response].[TRAX1_AACK]+ISNULL([TR_MIFID_UK_FCA_TRAX_Response].[TRAX2_AACK],0))-
[TR_MIFID_UK_FCA_TRAX_Response].[FCA_RACK]+[TR_MIFID_UK_FCA_TRAX_Response].[FCA_NPND] AS [FCA_NPND],
  [TR_MIFID_UK_FCA_TRAX_Response].[FCA_RACK] AS [FCA_RACK],
  [TR_MIFID_UK_FCA_TRAX_Response].[FCA_RREJ] AS [FCA_RREJ],
  [TR_MIFID_UK_FCA_TRAX_Response].[FCA_Total] AS [FCA_Total],
  [TR_MIFID_UK_FCA_TRAX_Response].[Submission Date] AS [Submission Date],
  [TR_MIFID_UK_FCA_TRAX_Response].[TRAX1_AACK] AS [TRAX1_AACK],
  [TR_MIFID_UK_FCA_TRAX_Response].[TRAX1_AREJ] AS [TRAX1_AREJ],
  [TR_MIFID_UK_FCA_TRAX_Response].[TRAX1_HELD] AS [TRAX1_HELD],
  [TR_MIFID_UK_FCA_TRAX_Response].[TRAX2_AACK] AS [TRAX2_AACK],
  [TR_MIFID_UK_FCA_TRAX_Response].[TRAX2_AREJ] AS [TRAX2_AREJ],
  ([TR_MIFID_UK_FCA_TRAX_Response].[TRAX1_AACK]+ISNULL([TR_MIFID_UK_FCA_TRAX_Response].[TRAX2_AACK],0)) AS [TOTAL],
  [TR_MIFID_UK_FCA_TRAX_Response].[TRAX_Total] AS [TRAX_Total],
  [TR_MIFID_UK_FCA_TRAX_Response].[UpdateDate] AS [UpdateDate]
FROM [dbo].[TR_MIFID_UK_FCA_TRAX_Response] [TR_MIFID_UK_FCA_TRAX_Response]