-- =============================================================================
-- Codepoint-name remediation -- Tier-1 vs Tier > 1 judge
-- Generated by tools/remediate_codepoint_claims.py
-- Truth source: knowledge/_dictionary_truth.json (live DWH_dbo.Dim_* tables).
-- Verified: 2026-05-13
-- =============================================================================

