-- =============================================================================
-- Residual PI-slop remediation (paraphrased 'Popular Investor' surgical fix)
-- Generated by tools/audit_pi_residual.py
-- Replaces 'Popular Investor' with 'Internal' in column COMMENTs of columns
-- that are NOT about PI (i.e. NOT GuruStatusID / IsPI / NumOfGurus / etc.).
-- =============================================================================

ALTER TABLE main.bi_db.gold_sql_dp_prod_we_exw_dbo_exw_dimuser ALTER COLUMN `IsValidCustomer` COMMENT 'DWH-computed: 1 when not Internal (PlayerLevelID != 4), not label 30/26, and not CountryID=250. Used in reporting to filter out non-standard customers. (Tier 2 - SP_Dim_Customer)';
