-- =============================================================================
-- Sync pii_data.<X> and main.{dwh,bi_db}.<X>_masked column comments.
-- Generated by tools/sync_pii_masked_comments.py.
-- =============================================================================

-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `Address` COMMENT 'Street address line (street name and number). NULL in many records, indicating partial submissions where only Zip was required for the specific KYC workflow. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `AddressTypeID` COMMENT 'Address classification: 1=Mailing (only current type). FK to Dictionary.AddressType. Designed for future expansion (billing, residential, etc.). See AddressType for full definitions. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `BeginTime` COMMENT 'System-generated temporal period start. Set automatically by SQL Server when the row is created or when a previous version''s EndTime closes. Marks when this version of the address became effective. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `BuildingNumber` COMMENT 'Building or apartment number, separate from the street address line. NULL in most records. Supports address formats (common in some European countries) where building number is a separate field from street name. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `City` COMMENT 'City/locality of the address. NULL in many records - optional depending on country-specific KYC requirements. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `CountryID` COMMENT 'Country of the address. FK to Dictionary.Country. Always populated - the minimum required field for tax and KYC purposes. Determines which tax treaty rules apply. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `EndTime` COMMENT 'System-generated temporal period end. Value of ''9999-12-31 23:59:59.9999999'' indicates the current active version. SQL Server sets this to the actual change time when the row is superseded. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `GCID` COMMENT 'Global Customer ID - part of composite PK. Identifies the customer globally across eToro systems. References the same GCID in Customer.CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `RegionID` COMMENT 'IP-based geographic region. FK to Dictionary.RegionByIP (RegionByIP_ID). Optionally populated to correlate declared address with IP-inferred region for fraud/compliance checks. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `SubRegionID` COMMENT 'Sub-regional geographic division (e.g., US state, Canadian province). FK to Dictionary.SubRegion. NULL for most records; populated for countries where regulatory compliance requires sub-region tracking. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_etoro_customer_address  [masked->pii]
ALTER TABLE main.pii_data.bronze_etoro_customer_address ALTER COLUMN `Zip` COMMENT 'Postal/ZIP code. The most frequently populated address field - used for country-level verification, mailing zone determination, and tax jurisdiction. (Tier 1 - upstream wiki, etoro.Customer.Address)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `Action` COMMENT 'Type of change: ''INSERT'', ''UPDATE'', or ''DELETE''. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `AdditionalDetails` COMMENT 'Additional data at the time of the change. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `CountryId` COMMENT 'Country context at the time of the change. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `FieldId` COMMENT 'Which extended field was changed. Maps to Dictionary.ExtendedUserField. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `GCID` COMMENT 'Global Customer ID whose field was changed. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `ID` COMMENT 'Primary key. Auto-incrementing audit record identifier. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `LastModified` COMMENT 'Original LastModified timestamp from the source record. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `Occurred` COMMENT 'When this history record was created (the actual change timestamp). (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `TypeId` COMMENT 'Value subtype at the time of the change. Maps to Dictionary.ExtendedUserValueType. (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- bronze_userapidb_customer_extendeduserfield_history  [pii->masked]
ALTER TABLE main.bi_db.bronze_userapidb_customer_extendeduserfield_history_masked ALTER COLUMN `Value` COMMENT 'The field value at the time of the change (new value for INSERT/UPDATE, old value for DELETE). (Tier 1 - upstream wiki, UserApiDB.Customer.ExtendedUserField_History)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Bankruptcy` COMMENT 'DEPRECATED - Bankruptcy flag. Nullified 2022-02-22. All values are NULL. Do not use. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `BannerID` COMMENT 'Affiliate banner ID. From Dim_Customer.BannerID. 0 = no banner/direct. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `BirthDate` COMMENT 'Customer''s date of birth. PII. 1900-01-02 = unknown/not provided. From Dim_Customer.BirthDate. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Blocked` COMMENT 'Whether customer account is blocked/restricted. 0 = active, 1 = blocked. Computed from PlayerStatusID IN (2,4,6,7,8,9). Blocked != closed - check Dim_Customer.PendingClosureStatusID for closure. (Tier 2 - SP code, Dim_PlayerStatus)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `CID` COMMENT 'Customer ID - primary identifier for a customer in the eToro platform. Maps to Dim_Customer.RealCID. Distribution key; always filter/join on CID. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `CertifiedGuru` COMMENT 'Whether the customer is a certified Popular Investor (guru). 1 = certified, NULL = not certified. Very rare (~515 out of 45M). (Tier 3 - live data)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Channel` COMMENT 'Marketing acquisition channel. Resolved from Dim_Channel via Dim_Affiliate.SubChannelID. Values: Direct, Affiliate, SEM, SEO, Mobile Acquisition, Media Performance, Friend Referral, etc. Default ''Direct'' when NULL. (Tier 2 - SP code, Dim_Channel)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Club` COMMENT 'Customer''s eToro Club tier level. Resolved from Dim_PlayerLevel.Name via PlayerLevelID. Values: Bronze, Silver, Gold, Platinum, Platinum Plus, Diamond. Updated daily. (Tier 2 - SP code, Dim_PlayerLevel)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `CommunicationLanguage` COMMENT 'Customer''s preferred communication language (emails, notifications). Resolved from Dim_Language.Name via CommunicationLanguageID. May differ from platform Language. (Tier 2 - SP code, Dim_Language)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Country` COMMENT 'Customer''s country of registration. Resolved from Dim_Country.Name via CountryID. (Tier 2 - SP code, Dim_Country)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `CountryID` COMMENT 'Country ID - FK to Dim_Country.CountryID. Use Dim_Country for country name, region, regulation mapping, and risk group. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Credit` COMMENT 'Current credit balance (USD). From V_Liabilities. Updated only when @date = yesterday. Represents available trading credit including bonuses. (Tier 2 - SP code, V_Liabilities)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `DepositGroup` COMMENT 'DEPRECATED - Customer deposit tier. Low/Mid/High. ETL disabled 2023-05-09. Historical values only. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `DesignatedRegulationID` COMMENT 'Designated regulation entity ID. FK to Dim_Regulation.ID. Same value map as RegulationID. May differ when designated regulation differs from operating regulation. From Dim_Customer.DesignatedRegulationID. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `DocsOK` COMMENT 'Whether customer''s documents have been approved. 1 = approved, NULL = not yet approved. Mostly NULL (~99.9%). (Tier 3 - live data)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `DownloadID` COMMENT 'Download tracking ID from customer acquisition. From Dim_Customer.DownloadID. Typically 0. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Email` COMMENT 'Customer''s email address. PII - use masked UC table for non-privileged access. From Dim_Customer.Email. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `EmailVerifiedDate` COMMENT 'Date customer''s email was verified. From Fact_SnapshotCustomer (MIN date where IsEmailVerified=1). (Tier 2 - SP code, Fact_SnapshotCustomer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `EvMatchStatus` COMMENT 'Electronic verification match status. FK to Dim_EvMatchStatus.EvMatchStatusID. Values: 0=None, 1=PartiallyVerified, 2=Verified, 3=NotVerified. From Dim_Customer.EvMatchStatus. (Tier 2 - SP code, Dim_EvMatchStatus)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `EvMatchStatusDate` COMMENT 'Date customer reached EvMatchStatus=2 (Verified) for electronic verification. From Fact_SnapshotCustomer. (Tier 2 - SP code, Fact_SnapshotCustomer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Evangelist` COMMENT 'Whether customer is an eToro evangelist/ambassador. 1 = evangelist, NULL = not. Very rare (~208). (Tier 3 - live data)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FTDIsLessThanAWeek` COMMENT 'Whether first deposit occurred within 7 days of registration AND deposit > 0. 1 = fast depositor, 0 = slower or no deposit. Computed: DATEDIFF(DAY, registered, FirstDepositDate) < 8 AND FirstDepositAmount > 0. (Tier 2 - SP code)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FeedUnBlocked` COMMENT '[UNVERIFIED] Whether the customer''s social feed is unblocked. Entirely NULL - not populated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FeedUnlocked` COMMENT 'Whether the customer has unlocked their social feed. 0 = locked, 1 = unlocked, NULL = not evaluated. (Tier 3 - live data)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstCampaignAmount` COMMENT 'Amount of the first campaign payment/credit received (USD). (Tier 2 - SP code, History.Credit)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstCampaignDate` COMMENT 'Date of the first marketing campaign received. (Tier 2 - SP code, History.Credit)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstCampaignID` COMMENT 'ID of the first marketing campaign the customer received. From History.Credit.CampaignID (via External_etoro_History_Credit). (Tier 2 - SP code, History.Credit)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstCashierLogin` COMMENT 'First cashier page login. From Fact_CustomerAction where ActionTypeID=29 (MIN). First time customer visited the deposit/cashier page. (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstCashoutDate` COMMENT 'First withdrawal/cashout date. From Fact_CustomerAction where ActionTypeID=8 (MIN). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstContactAttemptDate` COMMENT 'First contact attempt date (any channel). From BI_DB_UsageTracking_SF (MIN). (Tier 2 - SP code, BI_DB_UsageTracking_SF)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstContactAttemptDate_ByPhone` COMMENT '[UNVERIFIED] First phone contact attempt date. Not explicitly set in current SP code. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstContactDate` COMMENT 'First successful contact date (any channel). From BI_DB_UsageTracking_SF (MIN). (Tier 2 - SP code, BI_DB_UsageTracking_SF)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstContactDate_ByPhone` COMMENT '[UNVERIFIED] First successful phone contact date. Not explicitly set in current SP code. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDateRetained` COMMENT '[UNVERIFIED] Whether customer was retained on first-date basis. 1 = retained, 0 = not retained, NULL = not yet evaluated. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDemoLoggedIn` COMMENT '[UNVERIFIED] First demo account login timestamp. Not updated by current SP code. May contain historical values only. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDemoMirrorPosOpenDate` COMMENT '[UNVERIFIED] First demo copy-trade position open date. Not updated by current SP code. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDemoMirrorRegistrationDate` COMMENT '[UNVERIFIED] First demo copy-trade registration date. Not updated by current SP code. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDemoPosOpenDate` COMMENT '[UNVERIFIED] First demo position open date. Not updated by current SP code. May contain historical values only. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositAmount` COMMENT 'Amount of the first successful deposit in USD. Default 0. From Dim_Customer.FirstDepositAmount. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositAmountExtended` COMMENT '[UNVERIFIED] Extended first deposit amount - may include bonuses or promotions. Not updated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositAttempt` COMMENT 'First deposit attempt timestamp (regardless of success). From Fact_FirstCustomerAction where ActionTypeID=27. (Tier 2 - SP code, Fact_FirstCustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositAttemptAmount` COMMENT 'Amount of the first deposit attempt in USD. Computed as Amount * ExchangeRate. (Tier 2 - SP code)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositAttemptFundingType` COMMENT 'Funding type for the first deposit attempt. Currently set to ''NA'' (not available from current data source). (Tier 2 - SP code)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositAttemptProcessor` COMMENT 'Payment processor for the first deposit attempt. Currently set to ''NA'' (not available from current data source). (Tier 2 - SP code)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositDate` COMMENT 'First successful deposit date. From Dim_Customer.FirstDepositDate via Fact_BillingDeposit. 1900-01-01 = no deposit (sentinel). Filter with YEAR(FirstDepositDate) != 1900. (Tier 2 - SP code, Fact_BillingDeposit)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositFundingType` COMMENT 'Funding type for the first deposit. Resolved from Dim_FundingType.Name via FundingTypeID. Values: CreditCard, Wire, PayPal, eToroMoney, IXOPAY-Nuvei, etc. (Tier 2 - SP code, Dim_FundingType)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstDepositProcessor` COMMENT 'Payment processor for the first deposit. Resolved from Dim_BillingDepot.Name via DepotID. (Tier 2 - SP code, Dim_BillingDepot)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstEngagementDate` COMMENT 'DEPRECATED - First social engagement date. ETL section commented out. May contain historical values. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstInstallDate` COMMENT 'First mobile app install date. From BI_DB_AppFlyer_Reports (EventName=''install'') via AppsFlyer tracking. (Tier 2 - SP code, BI_DB_AppFlyer_Reports)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstLeadDate` COMMENT 'DEPRECATED - First lead date. Nullified 2022-02-22. 1900-01-01 = sentinel for older records. Do not use. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstLoggedIn` COMMENT 'First real-money login timestamp. From Fact_CustomerAction where ActionTypeID=14. Set once, never overwritten (MIN logic). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstMenualPosOpenDate` COMMENT 'First manually opened position date (NOT copy-trade). From Fact_CustomerAction where ActionTypeID=1. Note: "Menual" is a typo for "Manual." (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstMirrorPosOpenDate` COMMENT 'First copy-trade position open date. From Fact_CustomerAction where ActionTypeID=2. (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstMirrorRegistrationDate` COMMENT 'First copy-trade (mirror) registration date. From Fact_CustomerAction where ActionTypeID=17. (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstNewFundedDate` COMMENT 'First date customer crossed the fully-funded threshold. Computed as GREATEST(FTDDateID, FirstVerifiedDateID, LEAST(FirstTradeDateID, FirstIOBDateID, FirstOptionsTradeDateID)) -- the date when all four funded criteria were first simultaneously satisfied. Set once via WHERE FirstNewFundedDate IS NULL, never overwritten. Source: Function_Population_First_Time_Funded. (Tier 1)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstPosOpenDate` COMMENT 'First position open date (manual or copy-trade). From Fact_CustomerAction where ActionTypeID IN (1,2). Uses MIN logic. (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstStocksOpenDate` COMMENT 'First date the customer opened a real stocks position. From Fact_CustomerAction where ActionTypeID=34. (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstTimeBeingCopied` COMMENT 'First time another customer copied this customer''s trades. From Dim_Mirror.OpenOccurred (MIN for this CID as ParentCID). (Tier 2 - SP code, Dim_Mirror)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstTimeSocialConnect` COMMENT 'DEPRECATED - First social account connection date. Source not updated since 2018. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstTimeUser` COMMENT '[UNVERIFIED] First time the user engaged with the platform as a new user. Rarely populated - not updated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstToSevenDayRetained` COMMENT '[UNVERIFIED] Whether customer was retained between first deposit and day 7. 1 = retained, 0 = not retained, NULL = not yet evaluated. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstToThirtyDayRetained` COMMENT '[UNVERIFIED] Whether customer was retained between first deposit and day 30. 1 = retained, 0 = not retained, NULL = not yet evaluated. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FirstWallEngagement` COMMENT 'DEPRECATED - First social wall engagement date. ETL section commented out. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Follow5UsersDate` COMMENT '[UNVERIFIED] Date when the customer followed 5 users (social onboarding milestone). Not populated in current data. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FunnelFromName` COMMENT 'Name of the originating marketing funnel. Resolved from Dim_Funnel.Name via FunnelFromID. Shows specific landing page/campaign funnel (eToro Homepage, Stocks Offering, reToroiOS, etc.). (Tier 2 - SP code, Dim_Funnel)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `FunnelName` COMMENT 'Registration funnel name. Resolved from Dim_Funnel.Name via FunnelID. Values: Retoro, reToroiOS, reToroAndroid, Web Trader, etc. Indicates which app/platform was used for registration. (Tier 2 - SP code, Dim_Funnel)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `GCID` COMMENT 'Global Customer ID - globally unique customer identifier across all eToro entities. From Dim_Customer.GCID. Used for cross-system joins (e.g., ComplianceStateDB uses GCID). (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Gender` COMMENT 'Customer gender. M=Male, F=Female, U=Unknown, NULL=not provided. From Dim_Customer.Gender. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `HasPic` COMMENT 'Whether customer has a profile picture. 1 = has picture, 0 = no picture. Mostly NULL (~98.6%). (Tier 3 - live data)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `IP` COMMENT 'Customer''s IP address (as numeric). PII. From Dim_Customer.IP. Mostly NULL in recent records. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `IsAirDropBefore` COMMENT 'Whether customer received a crypto airdrop in the last 30 days AND has deposited. 1 = received airdrop. From Fact_CustomerAction (ActionTypeID=1, IsAirDrop=1, InstrumentTypeID=5). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `IsFundedNew` COMMENT 'Funded status flag. 1 if ALL four criteria hold on the balance date: (1) real deposit excl. bad-FTD cohort (Aug 18-20 2025); (2) KYC verification level 3; (3) at least one non-airdrop activity (TP trade, copy IOB, or Options trade); (4) positive equity across TP/eMoney/Options. Updated daily for all customers. Source: Function_Population_Funded. (Tier 1)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `IsSales` COMMENT 'Whether customer is flagged as a sales account. 0 = not sales, 1 = sales. Mostly NULL (~94%). (Tier 3 - live data)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `KYC` COMMENT 'DEPRECATED - KYC status. Nullified 2022-02-22. All values are NULL. Do not use. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `KycModeID` COMMENT 'KYC verification mode. Values: 1 (~48%), 2 (~9%), 3 (~0.3%), 4 (~6%), NULL (~37%). From ComplianceStateDB.Compliance.CustomerKycMode. Joined on GCID. (Tier 2 - SP code, ComplianceStateDB)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LabelName` COMMENT 'Platform brand/label the customer registered under. Resolved from Dim_Label.Name via LabelID. Values: eToro (~97%), eToroRussia, ICMarkets, eToroChina, Royal-CM, eToroUSA, etc. (Tier 2 - SP code, Dim_Label)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Language` COMMENT 'Customer''s platform language preference. Resolved from Dim_Language.Name via LanguageID. (Tier 2 - SP code, Dim_Language)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastActionDateForLifeStage` COMMENT 'Most recent "life stage" action date (manual pos open, mirror pos open, mirror registration, or cashout). From Fact_CustomerAction where ActionTypeID IN (1,15,17). Used for lifecycle stage classification. (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastCampaignSentDate` COMMENT 'Date of the most recent marketing campaign sent to this customer. (Tier 2 - SP code)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastCashierLogin` COMMENT 'Most recent cashier page login. From Fact_CustomerAction where ActionTypeID=29 (MAX). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastCashoutDate` COMMENT 'Most recent withdrawal/cashout date. From Fact_CustomerAction where ActionTypeID=8 (MAX). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastContactAttemptDate` COMMENT 'Most recent contact attempt date (any channel). From BI_DB_UsageTracking_SF. (Tier 2 - SP code, BI_DB_UsageTracking_SF)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastContactAttemptDate_ByPhone` COMMENT 'Most recent phone contact attempt date. From BI_DB_UsageTracking_SF - Salesforce usage tracking. (Tier 2 - SP code, BI_DB_UsageTracking_SF)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastContactDate` COMMENT 'Most recent successful contact date (any channel). From BI_DB_UsageTracking_SF where ActionName IN (''Completed_Contact_Email__c'', ''Phone_Call_Succeed__c''). (Tier 2 - SP code, BI_DB_UsageTracking_SF)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastContactDate_ByPhone` COMMENT 'Most recent successful phone contact date. From BI_DB_UsageTracking_SF where ActionName = ''Phone_Call_Succeed__c''. (Tier 2 - SP code, BI_DB_UsageTracking_SF)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastDemoLoggedIn` COMMENT '[UNVERIFIED] Last demo login date. Not updated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastDemoMirrorPosOpenDate` COMMENT '[UNVERIFIED] Last demo copy-trade position date. Not updated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastDemoMirrorRegistrationDate` COMMENT '[UNVERIFIED] Last demo copy-trade registration date. Not updated by current SP code. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastDemoPosOpenDate` COMMENT '[UNVERIFIED] Last demo position open date. Not updated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastDepositAmount` COMMENT 'Amount of the most recent deposit in USD. From Fact_BillingDeposit (Amount * ExchangeRate). (Tier 2 - SP code, Fact_BillingDeposit)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastDepositDate` COMMENT 'Most recent deposit date. From Fact_BillingDeposit via #fundingLast (ModificationDate). Updated daily for new deposits. (Tier 2 - SP code, Fact_BillingDeposit)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastDepositFundingType` COMMENT 'Funding type of the most recent deposit. Resolved from Dim_FundingType.Name. Values: CreditCard, Wire, PayPal, eToroMoney, etc. (Tier 2 - SP code, Dim_FundingType)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastEngagementDate` COMMENT 'DEPRECATED - Last social engagement date. ETL section commented out. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastLoggedIn` COMMENT 'Most recent real-money login timestamp. From Fact_CustomerAction where ActionTypeID=14 (MAX). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastMenualPosOpenDate` COMMENT 'Most recent manually opened position date. From Fact_CustomerAction where ActionTypeID=1 (MAX). Note: "Menual" is a typo for "Manual." (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastMirrorPosOpenDate` COMMENT 'Most recent copy-trade position open date. From Fact_CustomerAction where ActionTypeID=2 (MAX). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastMirrorRegistrationDate` COMMENT 'Most recent copy-trade registration date. From Fact_CustomerAction where ActionTypeID=17 (MAX). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastNewFundedDate` COMMENT 'Most recent date the customer held funded status. COALESCE of yesterday''s Function_Population_Funded result and MAX(Date) from BI_DB_DDR_Customer_Daily_Status WHERE IsFunded=1. Updated daily. Source: Function_Population_Funded + DDR daily status. (Tier 1)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastPosOpenDate` COMMENT 'Most recent position open date (manual or copy). From Fact_CustomerAction where ActionTypeID IN (1,2) (MAX). (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastPublishedPostDate` COMMENT 'Most recent date the customer published a post on the social feed. From Fact_CustomerAction where ActionTypeID=21. (Tier 2 - SP code, Fact_CustomerAction)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `LastTimeBeingCopied` COMMENT 'Most recent time another customer copied this customer''s trades. From Dim_Mirror.OpenOccurred (MAX for this CID as ParentCID). (Tier 2 - SP code, Dim_Mirror)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Manager` COMMENT 'Account manager''s full name (FirstName + LastName). Resolved from Dim_Manager via AccountManagerID. ''System'' = no assigned manager. (Tier 2 - SP code, Dim_Manager)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Model_FTDsOTDs` COMMENT '[UNVERIFIED] ML model score predicting FTD (First Time Deposit) / OTD conversion probability. Not populated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Model_Leads` COMMENT '[UNVERIFIED] ML model score for lead quality/conversion. Not populated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Model_ReDepositor` COMMENT '[UNVERIFIED] ML model score predicting re-deposit probability. Not populated by current SP. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `NewMarketingRegion` COMMENT 'Updated marketing region classification. From Dim_Country.MarketingRegionManualName. Values: SEA, UK, French, Latam, German, CEE, Arabic, USA, Italian, ROW, Nordics, Spain, Australia. (Tier 2 - SP code, Dim_Country)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `NumberOfUsersFollowed` COMMENT '[UNVERIFIED] Number of users this customer is following on the social feed. Not populated in current data. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `OriginalCID` COMMENT 'Original CID before account merge or migration. From Dim_Customer.OriginalCID. Useful for tracking merged accounts. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PEPCreatedTime` COMMENT 'DEPRECATED - PEP (Politically Exposed Person) check creation time. Nullified 2022-02-22. 1900-01-01 = sentinel. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PEPStatusID` COMMENT 'DEPRECATED - PEP screening status ID. Nullified 2022-02-22. All NULL. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PEPStatusUpdatedDate` COMMENT 'DEPRECATED - PEP status last update date. Nullified 2022-02-22. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PassedSuitabilityTest` COMMENT 'DEPRECATED - Whether customer passed the suitability test. Nullified 2022-02-22. All NULL. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PhoneVerifiedDate` COMMENT 'Date customer''s phone was verified. From History.BackOfficeCustomer where PhoneVerifiedID IN (1=AutomaticallyVerified, 2=ManuallyVerified). (Tier 2 - SP code, History.BackOfficeCustomer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PopularInvestor` COMMENT 'Whether customer is part of the Popular Investor program. 1 = yes, NULL = no. Very rare (~360). (Tier 3 - live data)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PotentialDesk` COMMENT 'Sales desk assignment. Resolved from Dim_Country.Desk. Indicates which sales/support desk handles this customer''s region. (Tier 2 - SP code, Dim_Country)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PremiumAccount` COMMENT '[UNVERIFIED] Whether customer has a premium account type. Entirely NULL in current data - not populated. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `PrivacyPolicyID` COMMENT 'Privacy policy version accepted by the customer. Values: 1 (~47%), 2 (~53%). From Dim_Customer.PrivacyPolicyID. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `ProfessionalApplicationDate` COMMENT 'Date the customer applied for professional (non-retail) classification. From ComplianceStateDB.Compliance.CustomerProfessionalQuestionnaireResult. (Tier 2 - SP code, ComplianceStateDB)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `RealizedEquity` COMMENT 'Current realized equity (USD). From V_Liabilities. Updated only when @date = yesterday. Represents deposits + realized P&L - withdrawals. (Tier 2 - SP code, V_Liabilities)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `ReferralID` COMMENT 'CID of the customer who referred this customer. 0 = no referral. From Dim_Customer.ReferralID. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Region` COMMENT 'Geographic region for business reporting. Resolved from Dim_Country.Region. Values: UK, French, German, Italian, Other Asia, USA, Spanish, Eastern Europe, etc. (Tier 2 - SP code, Dim_Country)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `RegulationID` COMMENT 'Regulatory entity ID. FK to Dim_Regulation.ID. Values: 0=None, 1=CySEC, 2=FCA, 3=NFA, 4=ASIC, 5=BVI (~80%), 6=eToroUS, 7=FinCEN, 8=FinCEN+FINRA, 9=FSA Seychelles, 10=ASIC & GAML, 11=FSRA, 12=FINRAONLY, 13=MAS, 14=NYDFS+FINRA. (Tier 2 - SP code, Dim_Regulation)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `RiskGroup` COMMENT 'DEPRECATED - Customer risk classification. A/B/C. ETL disabled 2023-05-09. Historical values only. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `SerialID` COMMENT 'Affiliate serial ID. From Dim_Customer.AffiliateID. Identifies the affiliate partner who referred this customer. 0 = no affiliate. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `SevenDayRetained` COMMENT '[UNVERIFIED] Whether customer was retained at day 7 after first deposit. 1 = retained, 0 = not retained, NULL = not yet evaluated. (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `SignedW8Date` COMMENT '[UNVERIFIED] Date the customer signed the W-8BEN tax form (for non-US customers trading US securities). Not populated by current SP (section disabled). (Tier 4 - column name inference)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `SocialConnect` COMMENT 'DEPRECATED - Whether customer connected a social account. 1 = connected, NULL = not. Source table not updated since Sep 2018. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `State` COMMENT 'Customer''s state/province. Resolved from Dim_State_and_Province.Name via RegionByIP_ID. Populated for US, Italy, and select countries. (Tier 2 - SP code, Dim_State_and_Province)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `SubAffiliateID` COMMENT 'Sub-affiliate tracking ID. From Dim_Customer.SubSerialID. Can contain URLs, campaign tags, or partner codes. Free-text. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `SubChannel` COMMENT 'Sub-channel within the acquisition channel. Resolved from Dim_Channel. Values: Direct Mobile, Affiliate, Direct, SEO, Mobile CPA, Google UAC, Google Brand, FB, YT, ASA, etc. Default ''Direct'' when NULL. (Tier 2 - SP code, Dim_Channel)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `SuitabilityTestCompletedAt` COMMENT 'DEPRECATED - Suitability test completion date. Nullified 2022-02-22. 1900-01-01 = sentinel in older records. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `UpdateDate` COMMENT 'Last ETL update timestamp for this row. Set to GETDATE() on every INSERT or UPDATE. Use to verify data freshness. (Tier 2 - SP code)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `UserName` COMMENT 'Customer''s eToro username (display name on the platform). PII. From Dim_Customer.UserName. (Tier 2 - SP code, Dim_Customer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `VerificationLevel1Date` COMMENT 'Date customer first reached Verification Level 1. From Fact_SnapshotCustomer (MIN date where VerificationLevelID=1). May be backfilled from higher levels. (Tier 2 - SP code, Fact_SnapshotCustomer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `VerificationLevel2Date` COMMENT 'Date customer first reached Verification Level 2. From Fact_SnapshotCustomer (MIN date where VerificationLevelID=2). Backfilled from Level 3 if NULL. (Tier 2 - SP code, Fact_SnapshotCustomer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `VerificationLevel3Date` COMMENT 'Date customer first reached Verification Level 3 (fully verified). From Fact_SnapshotCustomer (MIN date where VerificationLevelID=3). (Tier 2 - SP code, Fact_SnapshotCustomer)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `Verified` COMMENT 'Customer verification level ID. Resolved via Dim_VerificationLevel. Values: 0=Unverified, 1=Level 1, 2=Level 2, 3=Fully Verified. NOT a boolean - do not treat as 0/1. (Tier 2 - SP code, Dim_VerificationLevel)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `isPassedPEP` COMMENT 'DEPRECATED - Whether customer passed PEP screening. Nullified 2022-02-22. All NULL. (Tier 2 - SP code, deprecated)';
-- gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates  [pii->masked]
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_bi_db_cidfirstdates_masked ALTER COLUMN `registered` COMMENT 'Customer registration date - the earlier of RegisteredDemo and RegisteredReal from Dim_Customer. First-ever interaction with the platform. (Tier 2 - SP code, Dim_Customer)';
