-- =============================================================================
-- Databricks ALTER Script: DWH_dbo.Dim_Position
-- UC Target: _Not_Migrated — not exported via Generic Pipeline; mapped Gold name
--   does not exist in Unity Catalog. Semantic wiki only until UC export exists.
-- =============================================================================
