-- =============================================================================
-- Databricks ALTER Script: DWH_dbo.Fact_Cashout_Rollback
-- Generated: 2026-05-14 15:04:32 UTC | _tmp_phase1_remediation.py
-- UC Target: main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback
-- =============================================================================

-- ---- Table Comment ----
-- (table comment intentionally omitted; regen tool only manages column comments)

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN CID COMMENT 'Customer ID of the account whose withdrawal is being rolled back. Not passed directly by the caller - derived inside AddCashoutRollbackTrackingRecord by querying Billing.Withdraw for the given WithdrawID. Implicit FK to Customer.CustomerStatic(CID). DWH note: clustered index key for Synapse query performance. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN WithdrawprocessingID COMMENT 'Surrogate primary key of the payment execution leg in `Billing.WithdrawToFunding`. Identifies which specific payment leg (card/bank/wallet payout attempt) was rolled back. Implicit FK to Billing.WithdrawToFunding(ID). DWH note: renamed from `WithdrawToFunding.ID` via the production SP alias `[Withdraw processing ID]`. (Tier 1 - upstream wiki, Billing.WithdrawToFunding)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN WithdrawID COMMENT 'The parent withdrawal request ID (Billing.Withdraw.WithdrawID). Never NULL in practice. Implicit FK to Billing.Withdraw. Enables grouping rollback events by withdrawal in reconciliation queries. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ProcessTime COMMENT 'Value date from the payment processor - when funds are considered available on the processor side. Set for wire/ACH payouts; NULL for instant payment methods. DWH note: renamed from `WithdrawToFunding.ProcessorValueDate`. (Tier 1 - upstream wiki, Billing.WithdrawToFunding)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN NetAmount COMMENT 'Refund amount expressed in the original deposit''s currency. May differ from NetUSDAmount when exchange rates changed between deposit and refund. ISNULL(0) applied - zero when NULL in source. DWH note: renamed from `WithdrawToFunding.RefundAmountInDepositCurrency`. (Tier 1 - upstream wiki, Billing.WithdrawToFunding)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Currency COMMENT 'Currency abbreviation (e.g., USD, EUR, GBP) of the payment processing currency. Resolved from `Dictionary.Currency.Abbreviation` via `WithdrawToFunding.ProcessCurrencyID` JOIN in the production SP. (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN NetUSDAmount COMMENT 'Payout amount in the processing currency (despite the "USD" suffix, this is actually in ProcessCurrencyID currency). MONEY type in source, CAST to decimal(16,2). ISNULL(0) applied. DWH note: renamed from `WithdrawToFunding.Amount`. (Tier 1 - upstream wiki, Billing.WithdrawToFunding)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackDate COMMENT 'Date/time when the rollback event occurred (as reported by the caller via @RollbackDate). Distinct from the record creation date - allows back-dating when recording a rollback that was initiated at a different time. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackAmount COMMENT 'The incremental amount in the original transaction currency for this rollback event. Parallel to RollbackUSDAmount. DWH note: renamed from `CashoutRollbackTracking.RollbackAmountInCurrency`. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ExchangeRate COMMENT 'Exchange rate between the rollback currency and USD applicable at the time of this rollback event. Passed by the caller, distinct from the original withdrawal exchange rate. ISNULL(1) + CAST to decimal(16,4) applied in the production SP. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN FeeInPIPs COMMENT 'Exchange fee in provider-specific integer units from the original payment leg. DWH note: renamed from `WithdrawToFunding.ExchangeFee`. Not a rollback-specific fee - it reflects the fee structure of the original withdrawal, carried forward for context. (Tier 1 - upstream wiki, Billing.WithdrawToFunding)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackUSDAmount COMMENT 'The incremental amount (in USD) reversed in this specific rollback event. Negative values indicate a rollback correction (reversal of a previous rollback). SUM this column grouped by WithdrawID to compute net rollback totals. DWH note: renamed from `CashoutRollbackTracking.RollbackAmountInUSD`. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ReferenceNumber COMMENT 'Optional external reference number for the rollback transaction (e.g., payment provider reference for the refund). NULL when no external reference is available. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackReason COMMENT 'Reason code for the rollback. Maps to @RollbackType parameter in AddCashoutRollbackTrackingRecord. No Dictionary lookup table exists. Observed values: 0=default/unknown, 1=standard rollback, 3=dominant reason (83% of events), 4=correction events. DWH note: renamed from `CashoutRollbackTracking.RollbackReasonID`. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN PaymentStatusID COMMENT 'Status of the rollback at time of recording. Always 2 (InProcess) across all production rows - set from @CashoutStatusID parameter. Uses Dictionary.PaymentStatus: 1=New, 2=Approved, 3=Decline, 4=Technical, 5=InProcess, 6=Canceled, 7=Confirmed. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN FundingMethod COMMENT 'Payment method type name resolved from `Dictionary.FundingType.Name` via `Billing.FundingPaymentDetailsForWithdraw.FundingTypeID`. Examples: credit card, bank transfer, PayPal, eToroMoney. (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Brand COMMENT 'Card brand name resolved from `Dictionary.CardType.Name` via XML-parsed `CardTypeID` from `Billing.FundingPaymentDetailsForWithdraw.FundingData`. Examples: Visa, Mastercard. NULL for non-card payment methods (bank transfers, PayPal, etc.). (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN PaymentDetails COMMENT 'Payment-specific details extracted from XML data, varying by payment method. Bank transfers (FundingTypeID=2): BSB number + client address. PayPal cashouts (FundingTypeID=3, CashoutTypeID=1): email. eToroMoney (FundingTypeID=10): AccountID + PurseID. Trustly (FundingTypeID=33): GCID, PlatformAccountID, IBAN, BIC, SortCode. Skrill (FundingTypeID=35): details + BirthDate. PayID (FundingTypeID=39): PayId + Email. Otherwise: standard payment details string. (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN FundingID COMMENT 'The payment instrument to which the withdrawal was being sent. References `Billing.Funding` implicitly (no explicit FK). Identifies the specific card, bank account, or wallet used for this payment leg. (Tier 1 - upstream wiki, Billing.WithdrawToFunding)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Depot COMMENT 'Acquirer or payment gateway configuration name used for this payment leg. Resolved from `Billing.Depot.Name` via `WithdrawToFunding.DepotID`. Identifies which payment processor handled the original withdrawal (e.g., specific bank integration, card processor). (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN VerificationCode COMMENT 'Verification code supplied or received during withdrawal processing. Used to validate the payout authorization. Same pattern as Billing.Deposit.RefundVerificationCode. (Tier 1 - upstream wiki, Billing.WithdrawToFunding)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Regulation COMMENT 'Regulatory jurisdiction under which the customer operates, resolved from `Dictionary.Regulation.Name` via `BackOffice.Customer.RegulationID`. Examples: CySEC, FCA, ASIC, FinCEN, FSA Seychelles, MAS, FSRA. (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN MIDName COMMENT 'Merchant Identifier Name - the human-readable name of the merchant account used for payment routing. Resolved via complex DepotID-specific CASE logic: for DepotIDs 35-43 uses deposit-side ProtocolMIDSettings regulation name; for DepotIDs 1,24,25,26,78,79,80,4,75,86 uses `GetMerchantDetailsForOneAccountByDepotOnly`; for bank transfers uses ProtocolMIDSettings description; otherwise falls back through `GetMerchantDetails` and regulation names. (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN MID COMMENT 'Merchant Identifier value - the technical MID code used for payment routing. Resolved via similar DepotID-specific CASE logic as MIDName but returns the MID value. Falls through ProtocolMIDSettings value, `GetMerchantDetailsForOneAccountByDepotOnly`, `GetMerchantDetails`, BPMS descriptions, and `MapMerchantCodeToMid`. (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN PaymentOrderStatus COMMENT 'Cashout status of the payment order from `History.WithdrawToFundingAction.CashoutStatusID` at the time of the rollback action. Uses Dictionary.CashoutStatus values: 3=Processed, 16=Reversed, 17=Partially Reversed. The production SP filters to only include rows where CashoutStatusID IN (3, 16, 17). (Tier 2 - SP code, Billing.GetRollbackedPaymentOrdersReport)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN StatusModificationTime COMMENT 'UTC timestamp when the rollback tracking record was last modified. Set to GETUTCDATE() at INSERT in production. DWH note: renamed from `CashoutRollbackTracking.ModificationDate`; serves as the ETL watermark - `ModificationDateID` is derived from this column. (Tier 1 - upstream wiki, Billing.CashoutRollbackTracking)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ModificationDateID COMMENT 'ETL partition key - integer date derived from StatusModificationTime via `CONVERT(INT, CONVERT(VARCHAR, DATEADD(DAY, DATEDIFF(DAY, 0, StatusModificationTime), 0), 112))`. Format: YYYYMMDD (e.g., 20230721). Used for incremental delete-insert ETL pattern and date-range filtering. (Tier 2 - SP code, SP_Fact_Cashout_Rollback_DL_To_Synapse)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN UpdateDate COMMENT 'ETL metadata: timestamp when this row was last loaded by the ETL pipeline. Set to GETDATE() on each reload by the Synapse ETL SP. (Tier 2 - SP code, SP_Fact_Cashout_Rollback_DL_To_Synapse)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN CID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN WithdrawprocessingID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN WithdrawID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ProcessTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN NetAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Currency SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN NetUSDAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackDate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ExchangeRate SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN FeeInPIPs SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackUSDAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ReferenceNumber SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN RollbackReason SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN PaymentStatusID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN FundingMethod SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Brand SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN PaymentDetails SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN FundingID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Depot SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN VerificationCode SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN Regulation SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN MIDName SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN MID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN PaymentOrderStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN StatusModificationTime SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN ModificationDateID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_dwh_dbo_fact_cashout_rollback ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');

