-- =============================================================================
-- STUB: Fact_SnapshotEquity — no direct Unity Catalog entry.
-- View Proxy Fallback applied (§4b-VP): V_Fact_SnapshotEquity was the expected
-- UC proxy, but main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity
-- does NOT exist in UC (confirmed 2026-04-12 via system.information_schema.tables).
--
-- DOWNSTREAM PROPAGATION (2026-04-12):
-- 26 Fact_SnapshotEquity base-table column descriptions were propagated to the
-- sibling view V_Fact_SnapshotEquity_FromDateID (generic_id=1121), which IS
-- present in UC at:
--   main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity_fromdateid
-- The inherited column comments are appended in:
--   knowledge/synapse/Wiki/DWH_dbo/Views/V_Fact_SnapshotEquity_FromDateID.alter.sql
-- Deploy status: Deployed via downstream 2026-04-12 — 26 cols to V_Fact_SnapshotEquity_FromDateID
-- =============================================================================
-- Databricks ALTER Script: DWH_dbo.Fact_SnapshotEquity
-- Synapse object: DWH_dbo.Fact_SnapshotEquity (base fact table)
-- UC Target (intended):  main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity
--                        (exported V_Fact_SnapshotEquity - generic_id=416) — NOT FOUND IN UC
-- Downstream (exists):   main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity_fromdateid
--   → Column comments deployed via V_Fact_SnapshotEquity_FromDateID.alter.sql (2026-04-12)
-- =============================================================================

-- ---- TABLE COMMENT (reference only — no UC target available) ----
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity SET TBLPROPERTIES (
--     'comment' = 'Synapse table DWH_dbo.Fact_SnapshotEquity - daily customer equity snapshot (cash, positions, cashouts, realized equity, AUM, asset-class splits). UC object is the exported view V_Fact_SnapshotEquity (generic_id=416): adds DateKey via Dim_Range + Dim_Date; all fact columns pass through. Downstream: V_Liabilities and reporting. See wiki Fact_SnapshotEquity.md.'
-- );

-- ---- TABLE TAGS (reference only) ----
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity SET TAGS (
--     'domain' = 'finance',
--     'object_type' = 'fact',
--     'source_schema' = 'DWH_dbo',
--     'synapse_object' = 'Fact_SnapshotEquity',
--     'uc_export_view' = 'V_Fact_SnapshotEquity',
--     'refresh_frequency' = 'daily',
--     'source_system' = 'Synapse',
--     'synapse_distribution' = 'HASH(CID)',
--     'synapse_index' = 'CLUSTERED COLUMNSTORE; NCI on CID',
--     'pipeline' = 'dwh-semantic-doc',
--     'pipeline_version' = '15-phase'
-- );

-- ---- COLUMN COMMENTS (reference only) ----
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN DateKey COMMENT 'Calendar date key from Dim_Date (YYYYMMDD). One row per CID per day for each day in [Dim_Range.FromDateID, Dim_Range.ToDateID]; view filters DateKey < today. (Tier 2 - V_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN CID COMMENT 'Customer ID. Grouping key for all equity aggregations. FK to Dim_Customer (CID = RealCID). HASH distribution key and part of PK. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN DateRangeID COMMENT 'Encoded date range as 12-digit bigint (YYYYMMDDYYYY). FromDate in first 8 digits, ToDate suffix in last 4 digits. New rows get @date+1231; updated rows get end-date set to @daybefore. Decoded via Dim_Range. Part of PK. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalPositionsAmount COMMENT 'Sum of all open position amounts (NewAmount) for this CID on this date. Includes all asset classes: CFD, stocks, crypto, futures, margin. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalCash COMMENT 'Customer''s total cash balance for the day. Running-balance approach introduced 2020-06-07. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN InProcessCashouts COMMENT 'Sum of pending withdrawal amounts not yet finalized. (Tier 2 - SP_Fact_SnapshotEquity_InProcessCashouts)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalMirrorPositionsAmount COMMENT 'Sum of position amounts where MirrorID > 0 AND ParentPositionID != 0 (copy-trading positions only). (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalMirrorCash COMMENT 'Cash available for copy-trading. Formula: TotalCash - Credit. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalStockOrders COMMENT 'Legacy column, hardcoded to 0. Removed 2019-03-03. Kept for schema compatibility. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalMirrorStockOrders COMMENT 'Legacy column, hardcoded to 0. Removed 2019-03-03. Kept for schema compatibility. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN RealizedEquity COMMENT 'Total account value: TotalCash + TotalPositionsAmount + InProcessCashouts (or direct from History.ActiveCredit.RealizedEquity if non-zero). (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN Credit COMMENT 'Outstanding credit/bonus balance from History.ActiveCredit, last event per CID per day. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN AUM COMMENT 'Assets Under Management. Formula: TotalMirrorPositionAmount + TotalCash - Credit. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN BonusCredit COMMENT 'Bonus credit balance from History.ActiveCredit.BonusCredit. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN CreditID COMMENT 'Last CreditID for this CID on this date from History.ActiveCredit. (Tier 2 - SP_Fact_SnapshotEquity_DL_To_Synapse)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN UpdateDate COMMENT 'ETL load timestamp (GETDATE() at MERGE/INSERT time). (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalStockPositionAmount COMMENT 'Sum of position amounts where InstrumentTypeID IN (5,6) AND not a future. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalMirrorStockPositionAmount COMMENT 'Mirror subset of TotalStockPositionAmount. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalCryptoPositionAmount COMMENT 'Sum of position amounts where InstrumentTypeID = 10 AND not a future. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalMirrorCryptoPositionAmount COMMENT 'Mirror subset of TotalCryptoPositionAmount. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalRealStocks COMMENT 'Sum of position amounts where IsSettled = 1 AND InstrumentTypeID IN (5,6) AND not a future. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalRealCrypto COMMENT 'Sum of position amounts where IsSettled = 1 AND InstrumentTypeID = 10 AND not a future. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalRealCryptoLoan COMMENT 'Sum of InitialAmount where IsSettled = 1 AND InstrumentTypeID = 10 AND NOT future AND Leverage = 2. Changed from Amount to InitialAmount 2020-03-25. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalCashCalculation COMMENT 'Parallel computation of TotalCash for audit/validation purposes. (Tier 2 - SP_Fact_SnapshotEquity)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalCryptoPositionAmount_TRS COMMENT 'Sum of crypto position amounts where SettlementTypeID = 2 (TRS). Added 2022-01-27. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalMirrorCryptoPositionAmount_TRS COMMENT 'Mirror subset of TotalCryptoPositionAmount_TRS. Added 2022-01-27. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN Total_TRSCrypto COMMENT 'Sum of crypto position amounts where IsSettled = 0 AND InstrumentTypeID = 10 AND SettlementTypeID = 2. Added 2022-01-27. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalMirrorRealFuturesPositionAmount COMMENT 'Sum of futures position amounts where MirrorID > 0. Added 2024-10-30. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalRealFutures COMMENT 'Sum of all futures position amounts. Added 2024-10-30. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalFuturesProviderMargin COMMENT 'Sum of provider margin for futures: LotCountDecimal x Dim_Instrument_Snapshot.ProviderMarginPerLot. Added 2024-10-30. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalFuturesLockedCash COMMENT 'Cash locked in futures beyond provider margin: NewAmount - (LotCountDecimal x ProviderMarginPerLot). Added 2024-10-30. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalStocksMargin COMMENT 'Sum of stock margin position amounts where SettlementTypeID = 5. Added 2025-09-30. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';
-- ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_v_fact_snapshotequity ALTER COLUMN TotalStockMarginLoanValue COMMENT 'Loan value for leveraged stock margin positions. Formula updated 2025-12-10. (Tier 2 - SP_Fact_SnapshotEquity_TotalPositionAmount)';

-- ---- COLUMN PII TAGS (reference only) ----
-- (All columns: pii = none)

-- =============================================================================
-- END OF ALTER SCRIPT (STUB)
-- =============================================================================
