-- =============================================================================
-- Databricks ALTER Script: DWH_dbo.Fact_BillingDeposit
-- Generated: 2026-03-22 | 15-phase pipeline
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit
-- Resolved via: information_schema bulk query
-- Classification: Standard
-- =============================================================================

ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit SET TBLPROPERTIES (
    'comment' = '`DWH_dbo.Fact_BillingDeposit` is the DWH''s authoritative record of every deposit attempt on the eToro platform - approved, declined, pending, charged back, or refunded. With 73.9M rows, it is the primary billing analytics table, used for FTD (First Time Deposit) attribution, payment provider performance, fraud analysis, exchange revenue reporting, regulatory compliance segmentation, and customer lifecycle analytics. The table combines data from three production sources: 1. **`Billing.Deposit`** - the core deposit ledger (direct passthrough for 35 columns) 2. **`Billing.Funding`** - payment instrument details (FundingTypeID, IsRefundExcluded, DocumentRequired, AFT flags) 3. **`Billing.RecurringDeposit`** - recurring deposit configuration (OUTER APPLY for IsRecurring flag) Additionally, ~91 columns are extracted from XML blobs stored in `Billing.Deposit.PaymentData` and `Billing.Deposit.FundingData` using the DWH UDF `ExtractXMLValue`. These cover payment-method-specific fields that vary by funding type (cre...'
);

ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit SET TAGS (
    'domain' = 'billing',
    'object_type' = 'fact',
    'source_schema' = 'DWH_dbo',
    'refresh_frequency' = 'daily',
    'source_system' = 'Synapse',
    'synapse_distribution' = 'HASH (DepositID)',
    'synapse_index' = 'CLUSTERED (DepositID ASC) + NC (PaymentStatusID ASC, ExpirationDateID ASC)',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = '15-phase'
);

-- ---- Column Comments ----
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CID COMMENT 'Passthrough `d.CID` from `DWH_staging.etoro_Billing_Deposit`. Production `Billing.Deposit.CID` (same semantics as upstream wiki section 4). (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CurrencyID COMMENT 'Passthrough `d.CurrencyID` from staging. Production `Billing.Deposit.CurrencyID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Commission COMMENT 'Passthrough `d.Commission`. Production defaults 0. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Approved COMMENT 'Passthrough `d.Approved`. Legacy flag; `PaymentStatusID` is authoritative. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ModificationDate COMMENT 'Passthrough `d.ModificationDate`. ETL incremental watermark. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ModificationDateID COMMENT 'ETL `convert(int,convert(varchar,dateadd(day,datediff(day,0,d.ModificationDate),0),112))` (`SP_Fact_BillingDeposit_DL_To_Synapse` Ext_FBD SELECT). (Tier 2 - Billing.Deposit.ModificationDate)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FundingID COMMENT 'Passthrough `d.FundingID`; JOIN to `etoro_Billing_Funding` `f`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExchangeRate COMMENT 'Passthrough `d.ExchangeRate`; also used in `Amount * ExchangeRate` for `AmountUSD`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN DepositID COMMENT 'Passthrough `d.DepositID`. `HASH(DepositID)` distribution + clustered index. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ProcessorValueDate COMMENT 'Passthrough `d.ProcessorValueDate`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN DepotID COMMENT 'Passthrough `d.DepotID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SecuredCardDataAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''SecuredCardDataAsString'',f.FundingData)`. Token / secured card reference; PSP semantics `[UNVERIFIED]`. (Tier 3 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BinCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BinCodeAsString'',f.FundingData)`. Downstream `SP_Fact_BillingDeposit`: `CAST(BinCodeAsString AS INT) = Dim_CountryBin.BinCode`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BinCountryIDAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''BinCountryIDAsInteger'',f.FundingData)` assigned to `int` (implicit cast from string). Prefer `TRY_CAST` for analytics. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardTypeIDAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''CardTypeIDAsInteger'',f.FundingData)` assigned to `int`. Dictionary meaning beyond SQL `[UNVERIFIED]`. (Tier 3 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentStatusID COMMENT 'Passthrough `d.PaymentStatusID`. Enum per upstream wiki section 4 (1=New, 2=Approved, …, 35=DeclineByRRE). (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ManagerID COMMENT 'Passthrough `d.ManagerID`. `0` = automated. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RiskManagementStatusID COMMENT 'Passthrough `d.RiskManagementStatusID`. Upstream risk reason catalogue. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Amount COMMENT 'ETL `CASE WHEN d.Amount >= 1000000000 THEN 99999999 WHEN d.Amount <= -1000000000 THEN -99999999 ELSE d.Amount END` (2025-04-17 cap). (Tier 2 - Billing.Deposit.Amount)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentDate COMMENT 'Passthrough `d.PaymentDate` (submission UTC). (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IPAddress COMMENT 'Passthrough `d.IPAddress` as `numeric(18,0)` (prod IPv4 encoding). (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ClearingHouseEffectiveDate COMMENT 'Passthrough `d.ClearingHouseEffectiveDate`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsFTD COMMENT 'ETL `ISNULL(CAST(d.IsFTD AS int),0)` (bit -> int). FTD rules upstream wiki section 2.2. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RefundVerificationCode COMMENT 'Passthrough `d.RefundVerificationCode`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MatchStatusID COMMENT 'Passthrough `d.MatchStatusID`. PSP reconciliation match. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BonusStatusID COMMENT 'Passthrough `d.BonusStatusID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BonusAmount COMMENT 'Passthrough `d.BonusAmount`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BonusErrorCode COMMENT 'Passthrough `d.BonusErrorCode`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExTransactionID COMMENT 'Passthrough `ExTransactionID` from `d` (SELECT list). External provider txn id. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FundingTypeID COMMENT 'JOIN `f.FundingTypeID` where `d.FundingID = f.FundingID`. (Tier 2 - Billing.Funding.FundingTypeID)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsRefundExcluded COMMENT 'ETL `CAST(f.IsRefundExcluded AS int)`. (Tier 2 - Billing.Funding.IsRefundExcluded)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN DocumentRequired COMMENT 'ETL `CAST(f.DocumentRequired AS int)`. (Tier 2 - Billing.Funding.DocumentRequired)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN UpdateDate COMMENT 'ETL `GETDATE()` at Ext_FBD build. (Tier 2 - SP_Fact_BillingDeposit_DL_To_Synapse)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExpirationDateID COMMENT 'ETL CASE on `[DWH_dbo].[ExtractXMLValue](''ExpirationDateAsString'',f.FundingData)$`: NULL or `LEN<4` -> `190001` else `200000 + RIGHT(val,2)*100 + LEFT(val,2)` where `val` = extracted string (`SP…`). `[DWH_dbo].[ExtractXMLValue]` = `[DWH_dbo].[ExtractXMLValue]`. Non-card / format edge cases `[UNVERIFIED]`. (Tier 3 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CountryIDAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''CountryIDAsInteger'',f.FundingData)` (Funding XML, despite column name). (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN StateIDAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''StateIDAsInteger'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankIDAsInteger COMMENT 'COALESCE(`[DWH_dbo].[ExtractXMLValue](''BankIDAsInteger'',d.PaymentData)`, `[DWH_dbo].[ExtractXMLValue](''BankIDAsInteger'',f.FundingData)`). (Tier 2 - Billing.Deposit.PaymentData / Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''AccountNameAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountTypeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''AccountTypeAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankAccountAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BankAccountAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankAddressAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BankAddressAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankCodeAsDecimal COMMENT '`[DWH_dbo].[ExtractXMLValue](''BankCodeAsDecimal'',f.FundingData)` stored as nvarchar(max). (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankDetailsAccountIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BankDetailsAccountIDAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BankIDAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BankNameAsString'',f.FundingData)` (XML). Distinct from `BankName` column enriched from `Dim_CountryBin`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BICCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BICCodeAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CIDAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN v COMMENT '`[DWH_dbo].[ExtractXMLValue](''ClientBankNameAsString'',f.FundingData)` **aliased** `AS v` - duplicate payload versus `ClientBankNameAsString` column (same XML key loaded twice). (Tier 3 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CustomerAddressAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CustomerAddressAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CustomerNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CustomerNameAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FundingType COMMENT '`[DWH_dbo].[ExtractXMLValue](''FundingType'',f.FundingData)` textual label alongside typed `FundingTypeID`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MaskedAccountIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''MaskedAccountIDAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PurseAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PurseAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RoutingNumberAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''RoutingNumberAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SecureIDAsDecimal COMMENT '`[DWH_dbo].[ExtractXMLValue](''SecureIDAsDecimal'',f.FundingData)` (nvarchar storage). (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SortCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''SortCodeAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountBalanceAsDecimal COMMENT '`[DWH_dbo].[ExtractXMLValue](''AccountBalanceAsDecimal'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountHolderAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''AccountHolderAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountIDAsDecimal COMMENT 'COALESCE(`[DWH_dbo].[ExtractXMLValue](''AccountIDAsDecimal'',d.PaymentData)`, `[DWH_dbo].[ExtractXMLValue](''AccountIDAsDecimal'',f.FundingData)`). (Tier 2 - Billing.Deposit.PaymentData / Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ACHBankAccountIDAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''ACHBankAccountIDAsInteger'',d.PaymentData)` (DDL `nvarchar(max)`). (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Address1AsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''Address1AsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Address2AsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''Address2AsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AdviseAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''AdviseAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AvailableBalanceAsDecimal COMMENT '`[DWH_dbo].[ExtractXMLValue](''AvailableBalanceAsDecimal'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankCodeAsString COMMENT 'COALESCE(`[DWH_dbo].[ExtractXMLValue](''BankCodeAsString'',d.PaymentData)`, `[DWH_dbo].[ExtractXMLValue](''BankCodeAsString'',f.FundingData)`). (Tier 2 - Billing.Deposit.PaymentData / Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BillNumberAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BillNumberAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BuildingNumberAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''BuildingNumberAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardHolderPhoneNumberBodyAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CardHolderPhoneNumberBodyAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardHolderPhoneNumberPrefixAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CardHolderPhoneNumberPrefixAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardNumberAsString COMMENT 'COALESCE(`[DWH_dbo].[ExtractXMLValue](''CardNumberAsString'',d.PaymentData)`, `[DWH_dbo].[ExtractXMLValue](''CardNumberAsString'',f.FundingData)`). (Tier 2 - Billing.Deposit.PaymentData / Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CityAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CityAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CountryIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CountryIDAsString'',d.PaymentData)`. Feeds `MOPCountry` resolution in `SP_Fact_BillingDeposit` via `Dim_Country` joins. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CountryNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CountryNameAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CreatedAtAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CreatedAtAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CurrentBalanceAsDecimal COMMENT '`[DWH_dbo].[ExtractXMLValue](''CurrentBalanceAsDecimal'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CustomerIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''CustomerIDAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN EmailAsString COMMENT 'COALESCE(`[DWH_dbo].[ExtractXMLValue](''EmailAsString'',d.PaymentData)`, `[DWH_dbo].[ExtractXMLValue](''EmailAsString'',f.FundingData)`). (Tier 2 - Billing.Deposit.PaymentData / Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN EndPointIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''EndPointIDAsString'',d.PaymentData)`. PSP endpoint id; business label `[UNVERIFIED]`. (Tier 3 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ErrorCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''ErrorCodeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ErrorTypeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''ErrorTypeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FirstNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''FirstNameAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IBANCodeAsString COMMENT 'COALESCE(`[DWH_dbo].[ExtractXMLValue](''IBANCodeAsString'',d.PaymentData)`, `[DWH_dbo].[ExtractXMLValue](''IBANCodeAsString'',f.FundingData)`). (Tier 2 - Billing.Deposit.PaymentData / Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN InitialTransactionIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''InitialTransactionIDAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IPAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''IPAsString'',d.PaymentData)`. Parallel to numeric `IPAddress`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN LanguageIDAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''LanguageIDAsInteger'',d.PaymentData)` (nvarchar(max) column). (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN LastNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''LastNameAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MD5AsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''MD5AsString'',d.PaymentData)` provider hash / fingerprint `[UNVERIFIED]`. (Tier 3 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PayerAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerBusiness COMMENT '`[DWH_dbo].[ExtractXMLValue](''PayerBusiness'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerIDAsString COMMENT 'COALESCE(`[DWH_dbo].[ExtractXMLValue](''PayerIDAsString'',d.PaymentData)`, `[DWH_dbo].[ExtractXMLValue](''PayerIDAsString'',f.FundingData)`). (Tier 2 - Billing.Deposit.PaymentData / Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerPurseAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PayerPurseAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerStatus COMMENT '`[DWH_dbo].[ExtractXMLValue](''PayerStatus'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentAmountAsDecimal COMMENT '`[DWH_dbo].[ExtractXMLValue](''PaymentAmountAsDecimal'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentDateAsDateTime COMMENT '`[DWH_dbo].[ExtractXMLValue](''PaymentDateAsDateTime'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentGuaranteeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PaymentGuaranteeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentModeAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''PaymentModeAsInteger'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentProviderTransactionStatusAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PaymentProviderTransactionStatusAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentStatusAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''PaymentStatusAsInteger'',d.PaymentData)`. Provider status integer echo; not identical to `PaymentStatusID` semantics. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentTypeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PaymentTypeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlaidItemIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PlaidItemIDAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlaidNamesAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PlaidNamesAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlatformIDAsInteger COMMENT '`[DWH_dbo].[ExtractXMLValue](''PlatformIDAsInteger'',d.PaymentData)`. Separate from fact `PlatformID` (session join). (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PromotionCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PromotionCodeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PSPCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''PSPCodeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RapidFirstNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''RapidFirstNameAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RapidLastNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''RapidLastNameAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ResponseMessageAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''ResponseMessageAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ResponseTimeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''ResponseTimeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SecretKeyAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''SecretKeyAsString'',d.PaymentData)`. Masked / reference only; treat as sensitive. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ThreeDsAsJson COMMENT '`[DWH_dbo].[ExtractXMLValue](''ThreeDsAsJson'',d.PaymentData)`. Raw 3DS payload JSON string. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ThreeDsResponseType COMMENT '`[DWH_dbo].[ExtractXMLValue](''ThreeDsResponseType'',d.PaymentData)`. Outcome id as string; analysts `TRY_CAST` -> `Dim_ThreeDsResponseTypes`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN TokenAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''TokenAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN TransactionIDAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''TransactionIDAsString'',d.PaymentData)`. Distinct from `Billing.Deposit.TransactionID` (internal 6-char) - this is provider string from XML. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ZipCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''ZipCodeAsString'',d.PaymentData)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BaseExchangeRate COMMENT 'Passthrough `d.BaseExchangeRate`. Upstream: reference rate before fee markup. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExchangeFee COMMENT 'Passthrough `d.ExchangeFee`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ProtocolMIDSettingsID COMMENT 'Passthrough `d.ProtocolMIDSettingsID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FunnelID COMMENT 'Passthrough `d.FunnelID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AmountUSD COMMENT 'Second INSERT: `Amount * ExchangeRate AS AmountUSD` from `Ext_FBD_Fact_BillingDeposit` snapshot (post-cap `Amount`). (Tier 2 - Billing.Deposit.Amount/ExchangeRate)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SessionID COMMENT 'ETL `ISNULL(d.SessionID,0)` (Ext_FBD). Platform enrichment JOIN uses `CID`+`SessionID`. (Tier 2 - Billing.Deposit.SessionID)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlatformID COMMENT 'Pass-1 INSERT leaves NULL; then `UPDATE a SET PlatformID=b.PlatformID FROM Fact_BillingDeposit a JOIN #Fact_BillingDepositAction b ON `a.CID=b.RealCID AND a.SessionID=b.SessionID` where `#Fact_BillingDepositAction` is built from `Fact_CustomerAction` `ActionTypeID=14` (`SP_Fact_BillingDeposit_DL_To_Synapse`). (Tier 2 - Fact_CustomerAction.PlatformID)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MOPCountry COMMENT '`UPDATE … SET MOPCountry=m.MOPCountry` from `#MOPCountryFinal` built off `CountryIDAsString` with nested `LEFT JOIN Dim_Country` on numeric id vs `LongAbbreviation` vs `Abbreviation` (`SP_Fact_BillingDeposit`, `@dateID` slice). (Tier 2 - Dim_Country.Name via CountryIDAsString)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SwiftCodeAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''SwiftCodeAsString'',f.FundingData)`. (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ClientBankNameAsString COMMENT '`[DWH_dbo].[ExtractXMLValue](''ClientBankNameAsString'',f.FundingData)` **AS ClientBankNameAsString** (same XML key also loaded into `v`). (Tier 2 - Billing.Funding.FundingData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankName COMMENT '`UPDATE fbw SET BankName = cb.IssuingBank` JOIN `Dim_CountryBin cb` ON `CAST(fbw.BinCodeAsString AS INT) = cb.BinCode` (`SP_Fact_BillingDeposit`). (Tier 2 - Dim_CountryBin.IssuingBank)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardCategory COMMENT '`UPDATE fbw SET CardCategory = cb.CardCategory` same JOIN as `BankName` (`SP_Fact_BillingDeposit`). (Tier 2 - Dim_CountryBin.CardCategory)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentGeneration COMMENT 'Passthrough `d.PaymentGeneration`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ProcessRegulationID COMMENT 'Passthrough `d.ProcessRegulationID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MerchantAccountID COMMENT 'Passthrough `d.MerchantAccountID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsSetBalanceCompleted COMMENT 'ETL `CAST(d.IsSetBalanceCompleted AS INT)` (`SP…` Ext_FBD). Production `bit`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RoutingReasonID COMMENT 'Passthrough `d.RoutingReasonID`. (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsRecurring COMMENT 'ETL `ISNULL(Recurring.IsRecurring,0)` from `OUTER APPLY (SELECT 1 AS IsRecurring FROM etoro_Billing_RecurringDeposit WHERE DepositID=d.DepositID) Recurring`. (Tier 2 - Billing.RecurringDeposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FlowID COMMENT 'Passthrough `d.FlowID` (SELECT list uses bare `FlowID`). (Tier 1 - Billing.Deposit)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsAftSupportedAsBool COMMENT 'ETL `ISNULL([DWH_dbo].[ExtractXMLValue](''IsAftSupportedAsBool'',d.PaymentData),0)` cast to `bit` column. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsAftEligibleAsBool COMMENT 'ETL `ISNULL([DWH_dbo].[ExtractXMLValue](''IsAftEligibleAsBool'',d.PaymentData),0)`. (Tier 2 - Billing.Deposit.PaymentData)';
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsAftProcessedAsBool COMMENT 'ETL `ISNULL([DWH_dbo].[ExtractXMLValue](''IsAftProcessedAsBool'',d.PaymentData),0)`. (Tier 2 - Billing.Deposit.PaymentData)';

-- ---- Column PII Tags ----
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN DepositID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentStatusID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsFTD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ModificationDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RiskManagementStatusID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MatchStatusID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Amount SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CurrencyID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExchangeRate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BaseExchangeRate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExchangeFee SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Commission SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AmountUSD SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FundingID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FundingTypeID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN DepotID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ProtocolMIDSettingsID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MerchantAccountID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RoutingReasonID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ProcessRegulationID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FlowID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Approved SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ProcessorValueDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ClearingHouseEffectiveDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExTransactionID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RefundVerificationCode SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IPAddress SET TAGS ('pii' = 'direct');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SessionID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ManagerID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FunnelID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentGeneration SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ModificationDateID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ExpirationDateID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BonusStatusID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BonusAmount SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BonusErrorCode SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlatformID SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsRecurring SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsSetBalanceCompleted SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsRefundExcluded SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN DocumentRequired SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsAftSupportedAsBool SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsAftEligibleAsBool SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IsAftProcessedAsBool SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SecuredCardDataAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BinCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BinCountryIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardTypeIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CountryIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN StateIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountTypeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankAccountAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankAddressAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankCodeAsDecimal SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankDetailsAccountIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BICCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN v SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CustomerAddressAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CustomerNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FundingType SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MaskedAccountIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PurseAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RoutingNumberAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SecureIDAsDecimal SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SortCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountBalanceAsDecimal SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountHolderAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AccountIDAsDecimal SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ACHBankAccountIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Address1AsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN Address2AsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AdviseAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN AvailableBalanceAsDecimal SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BillNumberAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BuildingNumberAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardHolderPhoneNumberBodyAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardHolderPhoneNumberPrefixAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardNumberAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CityAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CountryIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CountryNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CreatedAtAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CurrentBalanceAsDecimal SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CustomerIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN EmailAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN EndPointIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ErrorCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ErrorTypeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN FirstNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IBANCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN InitialTransactionIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN IPAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN LanguageIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN LastNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MD5AsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerBusiness SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerPurseAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PayerStatus SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentAmountAsDecimal SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentDateAsDateTime SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentGuaranteeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentModeAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentProviderTransactionStatusAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentStatusAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PaymentTypeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlaidItemIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlaidNamesAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PlatformIDAsInteger SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PromotionCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN PSPCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RapidFirstNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN RapidLastNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ResponseMessageAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ResponseTimeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SecretKeyAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ThreeDsAsJson SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ThreeDsResponseType SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN TokenAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN TransactionIDAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ZipCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN MOPCountry SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN SwiftCodeAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN ClientBankNameAsString SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN BankName SET TAGS ('pii' = 'none');
ALTER TABLE main.dwh.gold_sql_dp_prod_we_dwh_dbo_fact_billingdeposit ALTER COLUMN CardCategory SET TAGS ('pii' = 'none');

