-- =============================================================================
-- Databricks ALTER Script: main.bi_db.bronze_usabroker_apex_optionsreasoningform  (TABLE)
-- Generated: 2026-05-19 | scaffold_alter_for_uc_targets.py
-- Source wiki: knowledge/ProdSchemas/ComplianceDBs/USABroker/Wiki/Apex/Tables/Apex.OptionsReasoningForm.md
-- Target: Unity Catalog comments (1024 char limit per comment)
-- Drift guard: pre-flight uc_comment_validator.validate_alter_sql
-- =============================================================================

-- ---- Table comment intentionally not emitted (--cols-only) ----

-- ---- Column Comments ----
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN ReasoningFormID COMMENT 'GUID identifying this specific reasoning form instance. Generated by the application before calling CreateOptionsReasoningFormQuestion. Part of the composite PK with GCID. Also has a separate UNIQUE constraint enabling single-column lookups. Referenced by Apex.Options.ReasoningFormID and Apex.OptionsReasoningFormQuestionsAnswers.ReasoningFormID.';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN GCID COMMENT 'Global Customer ID of the customer who initiated the reasoning form. Part of the composite PK with ReasoningFormID. A customer can have multiple reasoning forms over time (one per suitability change attempt).';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN DateCreated COMMENT 'UTC timestamp when the reasoning form was created. Set to GETUTCDATE() by CreateOptionsReasoningFormQuestion. Marks the start of the reasoning process.';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN DateSubmitted COMMENT 'UTC timestamp when the reasoning form was submitted by the customer. NULL while the form is in progress or abandoned. A non-NULL value indicates the customer completed and submitted their reasoning. The time difference between DateCreated and DateSubmitted indicates how long the customer took to complete the form.';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN PreviousAppropriatenessTestDate COMMENT 'UTC timestamp of the customer''s previous appropriateness/suitability test, captured at form creation time. Provides the "before" reference point for the regulatory audit trail - when was the last test before the customer decided to change their answers. NULL for forms created before this column was added.';

-- NOTE: PII tags intentionally NOT emitted by scaffold_alter_for_uc_targets.py.
-- Blanket-tagging every column 'pii=none' would risk silently misclassifying
-- PII-masked columns. Run the dedicated PII classifier afterwards.

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-19 13:29:20 UTC
-- Statements: 5/5 succeeded
-- ====================
