-- =============================================================================
-- Databricks ALTER Script: bronze USABroker.apex.OptionsReasoningForm
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/ComplianceDBs/USABroker/Wiki/apex/Tables/apex.OptionsReasoningForm.md
-- Layer: bronze
-- UC Target: main.bi_db.bronze_usabroker_apex_optionsreasoningform
-- =============================================================================

-- ---- UC Target: main.bi_db.bronze_usabroker_apex_optionsreasoningform (business_group=bi_db) ----
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform SET TBLPROPERTIES (
    'comment' = 'Tracks options reasoning form instances created when customers want to change their suitability questionnaire answers or re-apply for options trading after a previous assessment. Source: USABroker.apex.OptionsReasoningForm on the USABroker production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/ComplianceDBs/USABroker/Wiki/apex/Tables/apex.OptionsReasoningForm.md).'
);

ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'USABroker',
    'source_schema' = 'apex',
    'source_table' = 'OptionsReasoningForm',
    'business_group' = 'bi_db',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN ReasoningFormID COMMENT 'GUID identifying this specific reasoning form instance. Generated by the application before calling CreateOptionsReasoningFormQuestion. Part of the composite PK with GCID. Also has a separate UNIQUE constraint enabling single-column lookups. Referenced by Apex.Options.ReasoningFormID and Apex.OptionsReasoningFormQuestionsAnswers.ReasoningFormID. (Tier 1 - upstream wiki, USABroker.apex.OptionsReasoningForm)';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN GCID COMMENT 'Global Customer ID of the customer who initiated the reasoning form. Part of the composite PK with ReasoningFormID. A customer can have multiple reasoning forms over time (one per suitability change attempt). (Tier 1 - upstream wiki, USABroker.apex.OptionsReasoningForm)';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN DateCreated COMMENT 'UTC timestamp when the reasoning form was created. Set to GETUTCDATE() by CreateOptionsReasoningFormQuestion. Marks the start of the reasoning process. (Tier 1 - upstream wiki, USABroker.apex.OptionsReasoningForm)';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN DateSubmitted COMMENT 'UTC timestamp when the reasoning form was submitted by the customer. NULL while the form is in progress or abandoned. A non-NULL value indicates the customer completed and submitted their reasoning. The time difference between DateCreated and DateSubmitted indicates how long the customer took to complete the form. (Tier 1 - upstream wiki, USABroker.apex.OptionsReasoningForm)';
ALTER TABLE main.bi_db.bronze_usabroker_apex_optionsreasoningform ALTER COLUMN PreviousAppropriatenessTestDate COMMENT 'UTC timestamp of the customer''s previous appropriateness/suitability test, captured at form creation time. Provides the "before" reference point for the regulatory audit trail - when was the last test before the customer decided to change their answers. NULL for forms created before this column was added. (Tier 1 - upstream wiki, USABroker.apex.OptionsReasoningForm)';

