-- =============================================================================
-- Databricks ALTER Script: main.de_output.de_output_appsflyer_silver_reports
-- Generated: 2026-06-10 | one-shot AppsFlyer deployment (PDF-grounded)
-- Target: Unity Catalog EXTERNAL Delta table comment + column comments (1024 char limit per comment)
-- Source-of-truth: AppsFlyer Raw Data Export API documentation (proposals/AppsFlyer_Fields.pdf)
-- Source wiki:    knowledge/UC_generated/de_output/Tables/de_output_appsflyer_silver_reports.md
-- Layer notes:    Silver carries IP (which the bi_db gold mirror drops) and is exactly 1:1
--                 with AppsFlyer's documented schema (81 vendor fields + 5 eToro pipeline fields).
-- =============================================================================

-- ---- Table Comment ----
COMMENT ON TABLE main.de_output.de_output_appsflyer_silver_reports IS
'Silver-tier AppsFlyer mobile-attribution fact for the eToro OneApp Android / OneApp iOS apps. 133.9M rows, dates 2022-10-25 -> live (yesterday). Each row is one AppsFlyer raw-data-export record: Installs (paid attributed), OrganicInstalls (no paid touch / SKAdNetwork-restricted), or InAppEvents (post-install business events such as Open Trade, Registration_S2S, FTD_S2S, Verification Level - 1/2/3, Redeposit_S2S). Schema is exactly 1:1 with the AppsFlyer Raw Data Export API: 81 vendor-documented fields (attribution & touch, campaign & creative, cost, event & revenue, URL & referrer, location incl IP, device & network, device identifiers, app, multi-touch contributors 1/2/3) plus 5 eToro pipeline-added fields (DateID / Date / EtoroAppID / EtoroAppName / EtoroReport). Always filter EtoroReport (3 classes never sum cleanly) and EventSource IN (''SDK'',''S2S'') (~1M rows carry malformed JSON-fragment values). _S2S events are server-to-server postbacks and survive ATT-opt-out / ad-blockers / SDK init failures - prefer them over SDK siblings for revenue, FTD, registration counts. CID resolution: join AppsFlyerID -> bronze_marketperformance_tracking_customer.AppsflyerID.';

-- ---- Table Tags ----
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports SET TAGS (
    'domain' = 'marketing_attribution',
    'object_type' = 'silver_fact',
    'source_schema' = 'de_output',
    'source_system' = 'AppsFlyer Raw Data Export API',
    'refresh_frequency' = 'daily',
    'pipeline' = 'one-shot-appsflyer-deploy',
    'pipeline_version' = '2026-06-10',
    'primary_upstream' = 'AppsFlyer Raw Data Export API',
    'cid_bridge_table' = 'main.bi_db.bronze_marketperformance_tracking_customer',
    'permissioned_view' = 'main.bridgeclaw_permitted_data.appflyer_reports',
    'pdf_source' = 'proposals/AppsFlyer_Fields.pdf',
    'semantic_grade' = '4'
);

-- ---- Column Comments (86 columns) ----

-- Attribution & Touch -----------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AttributedTouchType COMMENT 'Classification of the attributed engagement that won the install / event credit: `click` (user clicked an ad), `impression` (view-through attribution), `download`, or `pre-install`. Empty / NULL on `OrganicInstalls`. Distribution on the bi_db mirror: ~88M empty (organic), ~32M click, ~8M impression. (Tier 1 — AppsFlyer field `attributed_touch_type`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AttributedTouchTime COMMENT 'For UA: timestamp of the touch attributed to. For Retargeting: engagement time. NULL on organic installs (the AppsFlyer ''None'' string is normalised to NULL by SP_AppFlyer_Reports upstream of this layer). (Tier 1 — AppsFlyer field `attributed_touch_time`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN InstallTime COMMENT 'Timestamp when the app install was first recorded. Present on every row (installs and post-install in-app events alike). For `InAppEvents` this is the original install date and may be far in the past — for event-period analysis filter `Date` instead. (Tier 1 — AppsFlyer standard export field `install_time`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AttributionLookback COMMENT 'Maximum period of time during which an install can be attributed to a specific ad. Duration string set by the campaign (e.g. `''1d''`, `''7d''`, `''30d''`). (Tier 1 — AppsFlyer field `af_attribution_lookback`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN ReengagementWindow COMMENT 'Retargeting time period for event attribution. Not populated in retargeting reports per AppsFlyer documentation. eToro is not currently running retargeting / re-engagement campaigns through the MMP integration — column observed all-NULL on the bi_db mirror. (Tier 1 — AppsFlyer field `af_reengagement_window`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN IsPrimaryAttribution COMMENT 'For UA: always `True`. For Retargeting: `True` if this is the primary attribution, `False` if the original install source. eToro stores it as a `''true''` / `''false''` string. (Tier 1 — AppsFlyer field `is_primary_attribution`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN IsRetargeting COMMENT 'For UA: always `False`. For Retargeting: `True` for retargeting conversions and events. eToro stores it as a `''true''` / `''false''` string. As of 2026-06, zero rows carry `''true''` — the column is wired but eToro does not run re-engagement campaigns through AppsFlyer. (Tier 1 — AppsFlyer field `is_retargeting`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN RetargetingConversionType COMMENT 'For UA: `Re-install`. For Retargeting: `Re-engagement` or `Re-attribution`. Empty / NULL on UA rows; expected NULL across the eToro corpus while retargeting is dormant. (Tier 1 — AppsFlyer field `retargeting_conversion_type`)';

-- Campaign & Creative -----------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN MediaSource COMMENT 'The media source attributed to an event - the ad network or channel credited with this install / event (e.g. `Facebook`, `Google`, `TikTok`). eToro values include `googleadwords_int` (Google UAC), `Apple Search Ads`, `tiktokglobal_int`, `bytedanceglobal_int`, `snapchat_int`, `Facebook Ads`, plus eToro first-party sources `eToroWeb`, `Website`, `DesktopLogoutScreen`, `QR_code`, and the iOS14 ATT-opt-out bucket `restricted`. Empty string is the pre-attribution bucket; ~1M rows carry data-quality artifacts (`''0.0''` / numeric strings). (Tier 1 — AppsFlyer field `media_source`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Partner COMMENT 'Agency or partner identifier that ran the campaign. For SKAN (SKAdNetwork) attribution this may not be populated. (Tier 1 — AppsFlyer field `af_prt`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Channel COMMENT 'Media-source channel — sub-classifier within the MediaSource. Examples: `YouTube` for Google, `Instagram` for Meta Ads, `ACI_Search` / `GoogleSearch` for Google search campaigns. (Tier 1 — AppsFlyer field `af_channel`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Campaign COMMENT 'Campaign name the user was exposed to. Format varies by network — eToro campaigns embed AFFID and locale (e.g. `AFFID_77015_Smadex_FR_IOS_zoomdtrackingdata`). (Tier 1 — AppsFlyer field `campaign`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN CampaignID COMMENT 'A unique identifier for a specific advertising campaign as issued by the ad network. Numeric or alphanumeric string. (Tier 1 — AppsFlyer field `campaign_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Adset COMMENT 'Adset name identifying the group of ads containing the ad shown. (Tier 1 — AppsFlyer field `af_adset`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AdsetID COMMENT 'Adset ID identifying the group of ads containing the ad shown. (Tier 1 — AppsFlyer field `af_adset_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Ad COMMENT 'Ad name — the exact creative shown to the user. (Tier 1 — AppsFlyer field `af_ad`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AdID COMMENT 'Ad ID — unique identifier of the creative as issued by the ad network. (Tier 1 — AppsFlyer field `af_ad_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AdType COMMENT 'Ad format type. Examples: `banner`, `footer`, `interstitial`, `video`, `ClickToDownload`. (Tier 1 — AppsFlyer field `af_ad_type`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SiteID COMMENT 'Publisher ID — the app or website that displayed the ad. (Tier 1 — AppsFlyer field `af_siteid`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SubSiteID COMMENT 'Sub-publisher ID — more granular placement within the publisher. (Tier 1 — AppsFlyer field `af_sub_siteid`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Keywords COMMENT 'Word(s) used in the user''s online search, as reported by the ad network. Relevant for paid-search campaigns. (Tier 1 — AppsFlyer field `af_keywords`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SubParam1 COMMENT 'Custom parameter populated by the advertiser in the attribution link. Used for eToro-side tracking dimensions passed through the AppsFlyer OneLink / S2S URL. (Tier 1 — AppsFlyer field `af_sub1`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SubParam2 COMMENT 'Custom parameter populated by the advertiser in the attribution link. Used for eToro-side tracking dimensions passed through the AppsFlyer OneLink / S2S URL. (Tier 1 — AppsFlyer field `af_sub2`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SubParam3 COMMENT 'Custom parameter populated by the advertiser in the attribution link. Used for eToro-side tracking dimensions passed through the AppsFlyer OneLink / S2S URL. (Tier 1 — AppsFlyer field `af_sub3`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SubParam4 COMMENT 'Custom parameter populated by the advertiser in the attribution link. Used for eToro-side tracking dimensions passed through the AppsFlyer OneLink / S2S URL. (Tier 1 — AppsFlyer field `af_sub4`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SubParam5 COMMENT 'Custom parameter populated by the advertiser in the attribution link. Used for eToro-side tracking dimensions passed through the AppsFlyer OneLink / S2S URL. (Tier 1 — AppsFlyer field `af_sub5`)';

-- Cost --------------------------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN CostModel COMMENT 'Cost model used for this placement: `CPC`, `CPI`, `CPM`, or `Other`. (Tier 1 — AppsFlyer field `af_cost_model`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN CostValue COMMENT 'Amount in the cost currency. Up to 4 decimal digits permitted. Stored as STRING — cast before arithmetic. (Tier 1 — AppsFlyer field `af_cost_value`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN CostCurrency COMMENT '3-letter currency code complying with ISO-4217 (e.g. `USD`, `EUR`). Defaults to USD. (Tier 1 — AppsFlyer field `af_cost_currency`)';

-- Event & Revenue ---------------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EventTime COMMENT 'Time of the event occurrence (when the in-app event fired). For install rows, equals `InstallTime`. Stored as STRING — not cast to TIMESTAMP. (Tier 1 — AppsFlyer field `event_time`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EventName COMMENT 'Attribution event type or in-app event name. For install rows: `''install''`. For `InAppEvents`: business event names — top-volume on the eToro corpus are `Open Trade` (~26M), `Redeposit_S2S` (~2.4M), `Registration_S2S` (~2.2M), `registration` (~1.9M), `Verification Level - 1/2/3`, `Redeposit`, `FTD_S2S` (~272k), `FTD` (~204k), `FTDE_S2S`. Suffix `_S2S` = server-to-server postback from the eToro backend (more reliable than the SDK twin — survives ATT-opt-out, ad-blockers, SDK init failures). (Tier 1 — AppsFlyer field `event_name`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EventValue COMMENT 'Event content from the AppsFlyer SDK, stored as JSON. For `Open Trade` events: `{"af_content":"Bitcoin","af_content_type":"Crypto","af_content_id":"100000","is_copy":"False","af_revenue":"14"}`. Empty for install events. (Tier 1 — AppsFlyer field `event_value`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EventRevenue COMMENT 'Value of revenue using the EventRevenueCurrency. Populated for trade events (e.g. `''14''`, `''250''`, `''2244''`); stored as STRING — cast before arithmetic. (Tier 1 — AppsFlyer field `event_revenue`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EventRevenueCurrency COMMENT 'The event revenue currency code as reported to the SDK. Predominantly `''USD''` in observed data. (Tier 1 — AppsFlyer field `event_revenue_currency`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EventRevenueUSD COMMENT 'The amount of revenue converted to USD by AppsFlyer. Equals `EventRevenue` when `EventRevenueCurrency = ''USD''`. (Tier 1 — AppsFlyer field `event_revenue_usd`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EventSource COMMENT 'Source of the engagement event: `s2s` (server-to-server), `sdk`, or `unknown`. eToro uppercases to `''SDK''` (~95M rows on the bi_db mirror) / `''S2S''` (~31.5M) / `''None''`. ALWAYS filter `EventSource IN (''SDK'',''S2S'')` — ~1M rows carry malformed JSON-fragment values (e.g. `""af_revenue"":""0""}"`, `USD`, `""is_copy"":""False""`) leaked from upstream AppsFlyer export bug. (Tier 1 — AppsFlyer field `event_source`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN IsReceiptValidated COMMENT 'Receipt validation status for in-app purchases: `TRUE`, `FALSE`, or `NULL` when not implemented in SDK. eToro is not an app-store-purchase business; typically empty. (Tier 1 — AppsFlyer field `is_receipt_validated`)';

-- URL & Referrer ----------------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN HTTPReferrer COMMENT 'URL of the web page that immediately preceded the customer''s website visit (the referrer of the AppsFlyer attribution redirect). Often very long — the bi_db SP truncates with `LEFT(4000)` at load time. (Tier 1 — AppsFlyer field `http_referrer`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN OriginalURL COMMENT 'For UA: the click or impression URL used. For Retargeting: the retargeting link or deep link. Carries full tracking parameters; eToro deep links use the `etoro://...` scheme (e.g. `etoro://markets/gold`). (Tier 1 — AppsFlyer field `original_url`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN UserAgent COMMENT 'String identifying the browser, OS, device type, and app version at the time of the attributed touch. Often empty for app-installed events. (Tier 1 — AppsFlyer field `user_agent`)';

-- Multi-Touch Contributors (1, 2, 3) ---------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor1Partner COMMENT 'Agency or PMD (Preferred Marketing Developer) of the 1st contributing touchpoint - always lowercase. (Tier 1 - AppsFlyer field `contributor1_af_prt`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor1MediaSource COMMENT 'Media source of the 1st (most recent) touchpoint that contributed to the conversion. (Tier 1 - AppsFlyer field `contributor1_media_source`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor1Campaign COMMENT 'Campaign name of the 1st (most recent) contributing touchpoint. (Tier 1 - AppsFlyer field `contributor1_campaign`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor1TouchType COMMENT 'How the user interacted at the 1st (most recent) contributing touchpoint: `click` or `impression`. (Tier 1 - AppsFlyer field `contributor1_touch_type`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor1TouchTime COMMENT 'Date and time of the 1st (most recent) contributing touchpoint. Stored as STRING - SP_AppFlyer_Reports normalises placeholder strings (''None'', ''USD'', ''usd'') to NULL upstream of this layer; cast with try_to_timestamp before chronological ordering. (Tier 1 - AppsFlyer field `contributor1_touch_time`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor2Partner COMMENT 'Agency or PMD of the 2nd contributing touchpoint - always lowercase. (Tier 1 - AppsFlyer field `contributor2_af_prt`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor2MediaSource COMMENT 'Media source of the 2nd touchpoint that contributed to the conversion. (Tier 1 - AppsFlyer field `contributor2_media_source`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor2Campaign COMMENT 'Campaign name of the 2nd contributing touchpoint. (Tier 1 - AppsFlyer field `contributor2_campaign`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor2TouchType COMMENT 'How the user interacted at the 2nd contributing touchpoint: `click` or `impression`. (Tier 1 - AppsFlyer field `contributor2_touch_type`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor2TouchTime COMMENT 'Date and time of the 2nd contributing touchpoint. Stored as STRING with the same NULL-normalisation as Contributor1TouchTime. (Tier 1 - AppsFlyer field `contributor2_touch_time`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor3Partner COMMENT 'Agency or PMD of the 3rd (oldest) contributing touchpoint - always lowercase. (Tier 1 - AppsFlyer field `contributor3_af_prt`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor3MediaSource COMMENT 'Media source of the 3rd (oldest) touchpoint that contributed to the conversion. (Tier 1 - AppsFlyer field `contributor3_media_source`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor3Campaign COMMENT 'Campaign name of the 3rd (oldest) contributing touchpoint. (Tier 1 - AppsFlyer field `contributor3_campaign`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor3TouchType COMMENT 'How the user interacted at the 3rd contributing touchpoint: `click` or `impression`. (Tier 1 - AppsFlyer field `contributor3_touch_type`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Contributor3TouchTime COMMENT 'Date and time of the 3rd (oldest) contributing touchpoint. Stored as STRING on silver (the bi_db gold mirror stores it as TIMESTAMP - the type-asymmetry is a known anomaly). (Tier 1 - AppsFlyer field `contributor3_touch_time`)';

-- Location (8 incl IP) -------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Region COMMENT 'Region derived from device IP as reported by SDK. For SKAN: derived from country_code. eToro values are AppsFlyer macro-region codes (`EU`, `AS`, `AU`, `SA`, `AF`, `NA`) - NOT eToro''s marketing-region SCD. (Tier 1 - AppsFlyer field `region`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN CountryCode COMMENT 'Country code using ISO 3166 alpha-2. AppsFlyer per-vendor convention: `UK` is used, NOT `GB`. The bi_db SP normalises UK->GB but the silver layer preserves the raw value. (Tier 1 - AppsFlyer field `country_code`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN State COMMENT 'State or province of the device location. (Tier 1 - AppsFlyer field `state`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN City COMMENT 'City of the device location. Can be districts or boroughs. **DDM-masked** with `default()` on the bi_db gold mirror; verify masking on this silver path before exposing in user-facing dashboards. (Tier 1 - AppsFlyer field `city`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN PostalCode COMMENT 'Postal or ZIP code of the device location. (Tier 1 - AppsFlyer field `postal_code`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN DMA COMMENT 'Designated Market Area as defined by Nielsen (US-focused). ''None'' for non-US. (Tier 1 - AppsFlyer field `dma`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN IP COMMENT 'IP address (IPv4 or IPv6). Used to determine user location. **PRESENT on silver - DROPPED on the bi_db gold mirror by SP_AppFlyer_Reports.** Treat as PII. (Tier 1 - AppsFlyer field `ip`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN WIFI COMMENT 'Whether the device was connected via Wi-Fi at the time of the event: `TRUE` or `FALSE`. eToro stores it as ''true'' / ''false'' string. (Tier 1 - AppsFlyer field `wifi`)';

-- Device & Network (9) -------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Operator COMMENT 'Name of the mobile operator derived from SIM MCCMNC code (e.g. ''Vodafone''). Empty when on Wi-Fi or unknown. (Tier 1 - AppsFlyer field `operator`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Carrier COMMENT 'The carrier name provided by Android''s `getSimCarrierIdName()`. May differ from Operator under roaming. (Tier 1 - AppsFlyer field `carrier`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Language COMMENT 'Language (locale) reported by the device per IETF BCP 47 standard (e.g. ''Deutsch'', ''English''). (Tier 1 - AppsFlyer field `language`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Platform COMMENT 'The operating system or ecosystem on which the application runs: `''android''` or `''ios''`. ~75% android / ~23% ios on the bi_db mirror; ~2% ''None'' / GUID-shaped dirty values - filter `Platform IN (''android'',''ios'',''None'')` for clean grouping. (Tier 1 - AppsFlyer field `platform`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN DeviceType COMMENT 'Commercial model name of the device. **DEPRECATED Feb 2022** - replaced by `device_model` in the AppsFlyer schema. Often empty in observed data. (Tier 1 - AppsFlyer field `device_type` - deprecated)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN OSVersion COMMENT 'Version of the operating system on the device (e.g. ''13'', ''16.1.1''). (Tier 1 - AppsFlyer field `os_version`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AppVersion COMMENT 'Version of the customer''s app as reported by the SDK or S2S APIs (e.g. ''651.114.0'', ''618.0.0''). (Tier 1 - AppsFlyer field `app_version`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN SDKVersion COMMENT 'AppsFlyer SDK version installed in the app (e.g. ''v6.12.2''). (Tier 1 - AppsFlyer field `sdk_version`)';

-- Device Identifiers (7) -----------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AppsFlyerID COMMENT 'A unique ID generated by the SDK when the app is first installed. AppsFlyer''s privacy-safe device+install identifier - the primary device key for iOS post-ATT (use this, NOT IDFA). Joins to `bronze_marketperformance_tracking_customer.AppsflyerID` for CID resolution. (Tier 1 - AppsFlyer field `appsflyer_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AdvertisingID COMMENT 'User-resettable device ID, also known as GAID (Google Advertising ID, Android). For CTV: CTV ID such as RIDA. Empty for iOS devices. ~62% coverage across the bi_db mirror. (Tier 1 - AppsFlyer field `advertising_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN IDFA COMMENT 'User-resettable advertising ID found on iOS devices (Identifier for Advertisers). **Empty for the majority of iOS rows post-iOS14.5 ATT framework** - Apple''s App Tracking Transparency requires per-app opt-in. ~8% total coverage / ~36% of iOS rows on the bi_db mirror. For iOS attribution use `AppsFlyerID` as the primary device key. (Tier 1 - AppsFlyer field `idfa`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AndroidID COMMENT 'Permanent hardware-level device ID (Android). Empty for iOS. (Tier 1 - AppsFlyer field `android_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN CustomerUserID COMMENT 'The Customer User ID (CUID) - unique app user identifier set by the advertiser. eToro passes a hashed CID at registration / login, so this column links AppsFlyer events back to eToro user accounts. **NULL on Installs and OrganicInstalls** (no CID exists pre-registration); ~26% of total bi_db rows carry a populated value. For per-CID rollups, prefer the `bronze_marketperformance_tracking_customer.AppsflyerID` bridge. (Tier 1 - AppsFlyer field `customer_user_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN IMEI COMMENT 'Permanent hardware device ID. Collection is restricted in many markets - typically empty on modern devices. (Tier 1 - AppsFlyer field `imei`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN IDFV COMMENT 'Vendor ID provided by iOS - unique per app vendor on a device. Empty for Android. (Tier 1 - AppsFlyer field `idfv`)';

-- App (3) ---------------------------------------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AppID COMMENT 'Unique app identifier in AppsFlyer. eToro values: `''com.etoro.openbook''` (Android, dot notation - Google Play package) or `''id674984916''` (iOS, App Store ID). Differs from `EtoroAppID` which uses underscore notation. (Tier 1 - AppsFlyer field `app_id`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN AppName COMMENT 'Official name of the application as it appears in the app stores. Not a constant - changed over time (e.g. `''eToro: Investing made social''` -> `''eToro: Trade. Invest. Connect.''`). (Tier 1 - AppsFlyer field `app_name`)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN BundleID COMMENT 'iOS: Bundle ID to match the app. Android: equivalent to App ID. Same value as `AppID` in observed data. (Tier 1 - AppsFlyer field `bundle_id`)';

-- Custom eToro Fields (5, pipeline-added) -------------------------------
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN DateID COMMENT 'Event date as YYYYMMDD integer (e.g. 20260610). ETL partition key. Equals `Date` formatted as YYYYMMDD. (Tier 2 - eToro pipeline)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN Date COMMENT 'Event date - the date the install or in-app event occurred. **Not the install date** for InAppEvents - may differ significantly from `InstallTime`. For event-period analysis filter on `Date` / `DateID`; for install-cohort analysis filter on `InstallTime`. (Tier 2 - eToro pipeline)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EtoroAppID COMMENT 'AppsFlyer-export-config app key: `''com_etoro_openbook''` (Android, underscore separator) or `''id674984916''` (iOS). Differs from `AppID` (dot notation). (Tier 2 - eToro pipeline)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EtoroAppName COMMENT 'Human-readable platform label set by the AppsFlyer export config: `''OneApp Android''` or `''OneApp iOS''`. (Tier 2 - eToro pipeline)';
ALTER TABLE main.de_output.de_output_appsflyer_silver_reports ALTER COLUMN EtoroReport COMMENT 'AppsFlyer report-type partition - the most important filter on this table. Values: `''OrganicInstalls''` (~86.5M, no paid touch / SKAdNetwork-restricted), `''InAppEvents''` (~37.8M, post-install business events), `''Installs''` (~7.0M, paid attributed installs). **ALWAYS filter EtoroReport** - the three classes never sum cleanly: `Installs + OrganicInstalls = total installs` but `InAppEvents` are events on already-installed devices, not installs. (Tier 2 - eToro pipeline)';

-- == LAST EXECUTION ==
-- Timestamp: 2026-06-10 13:01:13 UTC
-- Batch: appsflyer one-shot deploy (proposals/appsflyer_one_shot/deploy.py)
-- Statements: 88/88 succeeded
-- ====================
