-- =============================================================================
-- Databricks ALTER Script: bronze etoro.Hedge.ManualOrderExecutionLog
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Hedge/Tables/Hedge.ManualOrderExecutionLog.md
-- Layer: bronze
-- UC Target: main.dealing.bronze_etoro_hedge_manualorderexecutionlog
-- =============================================================================

-- ---- UC Target: main.dealing.bronze_etoro_hedge_manualorderexecutionlog (business_group=dealing) ----
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog SET TBLPROPERTIES (
    'comment' = 'Audit log of every hedge order submitted to the hedge server - both by human dealing desk operators manually intervening in hedge positions and by the automated ExposureBalancer service correcting residual exposure imbalances. Source: etoro.Hedge.ManualOrderExecutionLog on the etoro production database, ingested via the Generic Pipeline (Override strategy, 60-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Hedge/Tables/Hedge.ManualOrderExecutionLog.md).'
);

ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'Hedge',
    'source_table' = 'ManualOrderExecutionLog',
    'business_group' = 'dealing',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '60'
);

-- Column Comments
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN OrderID COMMENT 'Primary key. GUID generated by the submitting system (HedgeClient or ExposureBalancer) before submission. GUID format means the key is generated client-side, not by the database - enabling pre-insert order tracking. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN Sender COMMENT 'Identifies the order source. "ExposureBalancer" for automated correction orders. "HedgeClientN (by \<username\>)" for manual dealing desk orders, where N is the HedgeClient instance number and \<username\> is the authenticated operator. Used for audit attribution. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN IP COMMENT 'IP address of the submitting machine. NULL for the ExposureBalancer service (internal process). Populated with internal network address (e.g., "10.160.0.212") for dealing desk operators connecting via HedgeClient. Confirms the physical location of manual interventions. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN ClientSendTime COMMENT 'Timestamp when the order was submitted by the client or service. For ExposureBalancer rows, this equals HedgeStartTime (submitted and started simultaneously). For manual orders, this reflects when the operator clicked "Submit" in HedgeClient. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN HedgeStartTime COMMENT 'Timestamp when the hedge server began processing the order. Difference from ClientSendTime reveals hedge server queue latency. In practice, both timestamps are nearly identical for all current records. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN RequestTypeID COMMENT 'Classification of the manual request. FK to Dictionary.HedgeManualRequestType: 0=Custom Request (freeform manual), 1=Set Hedge Exposure, 2=Settle Requested Exposure, 3=SetTradeExposure, 4=Manual Exposure, 5=Custom Update Queued, 6=Clear Queued, 7=Move Netting. Special value -1 is used exclusively by ExposureBalancer (not in dictionary). See HedgeManualRequestType for full definitions. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN InstrumentID COMMENT 'The financial instrument for the hedge order. FK to Trade.Instrument (implicit - no declared constraint). NULL would indicate a non-instrument-specific operation. In practice always populated for actual trade orders. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN IsBuy COMMENT 'Direction of the hedge order. true = buy (long hedge position), false = sell (short hedge position). 87% of current records are buys, reflecting that eToro''s net book position typically requires more buy-side hedging. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN AmountInUnits COMMENT 'The actual executed order size in units of the instrument. For ExposureBalancer rows, this is the calculated imbalance amount. For manual orders, this is the dealer-specified quantity. 6 decimal places supports fractional unit positions (e.g., crypto). (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN RequestedIsBuy COMMENT 'Original requested direction before any hedge server adjustment. Always NULL in current data - this column was designed to capture intent vs execution discrepancies but is not currently populated by any active code path. Likely a forward-looking audit field. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN RequestedAmountInUnits COMMENT 'Original requested amount before any hedge server adjustment. Always NULL in current data - paired with RequestedIsBuy as an unused intent-tracking mechanism. If the hedge server modified an order, the original amount would appear here. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN TradeDescription COMMENT 'Textual description of the order''s purpose. "Exposure Balancer Saga" for all ExposureBalancer rows (hardcoded by the service). NULL for dealing desk manual orders. The varchar(39) length cap limits descriptive detail. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN Rate COMMENT 'Execution rate or price for the hedge order. Populated with actual market price for ExposureBalancer orders (e.g., 245.0865 for BTC). Set to 0 for manual dealing desk market orders (rate=0 signals "execute at best available market price"). NULL for Manual Exposure type (RequestTypeID=4). (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN UpdateNetting COMMENT 'Whether this order should trigger netting position recalculation after execution. true for ExposureBalancer orders (which directly correct netting imbalances and must update the netting table). NULL for manual dealing desk orders (netting recalculation not triggered). Added to the SP in January 2022 by Ran Ovadia. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN ReasonID COMMENT 'A reason code for the order. No FK declared. Mostly NULL (manual orders) or 0 (ExposureBalancer). Three records contain value 3 - the meaning is undocumented. May reference an internal enum in application code or be a legacy field. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN OrderType COMMENT 'FIX protocol order type specifying execution method. "Market" for manual dealing desk orders (execute at best available price). NULL for ExposureBalancer orders (internal routing bypasses FIX type specification). Populated via a direct insert path separate from Hedge.InsertManualOrderExecutionLog SP. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN TimeInForce COMMENT 'FIX protocol TimeInForce value specifying order duration. "Day" for manual dealing desk orders (order expires at end of trading day if unfilled). NULL for ExposureBalancer orders. Part of the FIX order specification group with OrderType. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN ExpirationInSeconds COMMENT 'Custom order expiration time in seconds. 0 for manual market orders that use Day TimeInForce (expiry governed by day boundary, not custom timeout). NULL for ExposureBalancer orders. A non-zero value would set a specific execution deadline. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_manualorderexecutionlog ALTER COLUMN SlippagePercentage COMMENT 'Maximum allowable price slippage percentage. 0 for manual dealing desk orders (exact execution required - no price deviation tolerated). NULL for ExposureBalancer orders. A non-zero value would permit partial fills at slightly different rates. (Tier 1 - upstream wiki, etoro.Hedge.ManualOrderExecutionLog)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:35:25 UTC
-- Bronze deploy: etoro batch 1
-- ====================
