-- =============================================================================
-- Databricks ALTER Script: bronze etoro.Hedge.HBCOrderLog
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Hedge/Tables/Hedge.HBCOrderLog.md
-- Layer: bronze
-- UC Target: main.dealing.bronze_etoro_hedge_hbcorderlog
-- =============================================================================

-- ---- UC Target: main.dealing.bronze_etoro_hedge_hbcorderlog (business_group=dealing) ----
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog SET TBLPROPERTIES (
    'comment' = 'HBC individual FIX order log: child of Hedge.HBCExecutionLog; one row per FIX order placed within an HBC execution attempt, capturing GUID order identity, HedgeID (cross-reference to ExecutionLog), order state, lot amounts, and execution rate; written atomically with the parent execution row by Hedge.LogHBCExecution. Source: etoro.Hedge.HBCOrderLog on the etoro production database, ingested via the Generic Pipeline (Append strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Hedge/Tables/Hedge.HBCOrderLog.md).'
);

ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'Hedge',
    'source_table' = 'HBCOrderLog',
    'business_group' = 'dealing',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Append',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN OrderID COMMENT 'GUID primary key (NONCLUSTERED). Generated by the HedgeServer application - globally unique order identifier. FILLFACTOR=85 on PK to accommodate inserts without page splits. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN ExecutionID COMMENT 'FK to Hedge.HBCExecutionLog.ExecutionID (WITH CHECK). Groups orders by their parent execution attempt. Part of NC index (StartTime, ExecutionID) for execution-scoped time queries. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN HedgeID COMMENT 'The execution log identifier for this order. Join: HBCOrderLog.HedgeID = ExecutionLog.OrderID. Enables cross-referencing between HBC order flow and the main Hedge.ExecutionLog audit trail. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN IsBuy COMMENT 'Direction: 1=BUY order, 0=SELL order. Matches the parent HBCExecutionLog.IsBuy. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN IsCancelOrder COMMENT '1 if this order is a cancellation of a previous order within this execution. Corresponds to parent''s IsCancelExecution flag. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN OrderState COMMENT 'FK to Dictionary.HBCOrderState. Current/final state of this FIX order: 0=New, 1=Pending, 2=Filled, 3=Rejected, 4=Cancelled, 5=UnRecoverable. 91% are Filled in this environment. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN RequestAmountInLots COMMENT 'Pre-rounding lot amount requested for this order. May differ from ExecutionAmountInLots due to lot-size rounding (same as parent execution). (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN ExecutionAmountInLots COMMENT 'Actual lots executed after rounding. For Filled orders: the whole-lot amount that was filled. 0 for failed/rejected orders. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN ExecutionRate COMMENT 'The execution rate recorded for this order (dbo.dtPrice = high-precision decimal). For Filled orders: the fill price. For failed orders: the attempted price. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN StartTime COMMENT 'When the FIX order was submitted. Part of the NC index (StartTime, ExecutionID). Same as or very close to parent HBCExecutionLog.StartTime. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN EndTime COMMENT 'When the order reached its terminal state. EndTime - StartTime = order-level execution latency. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';
ALTER TABLE main.dealing.bronze_etoro_hedge_hbcorderlog ALTER COLUMN FailReason COMMENT 'Failure description for non-Filled orders. NULL for successful fills. Similar to HBCExecutionLog.FailReason but at order granularity. (Tier 1 - upstream wiki, etoro.Hedge.HBCOrderLog)';

