-- =============================================================================
-- Databricks ALTER Script: bronze WalletConversionDB.C2F.FiatTransactions
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/CryptoDBs/WalletConversionDB/Wiki/C2F/Tables/C2F.FiatTransactions.md
-- Layer: bronze
-- UC Target: main.bi_db.bronze_walletconversiondb_c2f_fiattransactions
-- =============================================================================

-- ---- UC Target: main.bi_db.bronze_walletconversiondb_c2f_fiattransactions (business_group=BI_DB) ----
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions SET TBLPROPERTIES (
    'comment' = 'Records the actual fiat transaction details for completed crypto-to-fiat conversions, including locked exchange rates, final amounts, account routing, and conversion fees. Source: WalletConversionDB.C2F.FiatTransactions on the WalletConversionDB production database, ingested via the Generic Pipeline (Append strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/CryptoDBs/WalletConversionDB/Wiki/C2F/Tables/C2F.FiatTransactions.md).'
);

ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'WalletConversionDB',
    'source_schema' = 'C2F',
    'source_table' = 'FiatTransactions',
    'business_group' = 'BI_DB',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Append',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN Id COMMENT 'Auto-incrementing surrogate PK. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN ConversionId COMMENT 'FK to C2F.Conversions.Id. 1:1 relationship when present (only completed conversions). Created by InsertFiatTransaction with dedup check. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN CryptoToFiatRate COMMENT 'Actual exchange rate from crypto to fiat at execution time. May differ from EstimatedFiatTransactions.CryptoToFiatRate due to market movement. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN FiatToUsdRate COMMENT 'Actual fiat-to-USD exchange rate at execution time. 1.0 when target currency is USD. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN CryptoToUsdRate COMMENT 'Actual crypto-to-USD rate at execution time. Primary pricing rate. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN FiatAmount COMMENT 'Actual fiat amount credited to the customer in the target currency. This is the post-fee amount the customer receives. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN UsdAmount COMMENT 'USD equivalent of the fiat amount. Used for regulatory limit calculations. Preferred over EstimatedFiatTransactions.UsdAmount when available. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN AccountId COMMENT 'Customer''s fiat account identifier where the funds were credited. Format varies by target platform (IBAN account number, platform account ID, etc.). (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN Details COMMENT 'Unique client-load reference ID in format "C2F" + 8 digits. Generated by GenerateUniqueClientLoadReferenceId. Serves as external payment reference. Indexed for lookups. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN RateTimestamp COMMENT 'UTC timestamp when the exchange rate was locked for this transaction. May precede the Occurred timestamp if rate was locked before the fiat credit was recorded. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN Occurred COMMENT 'UTC timestamp when the fiat transaction was recorded. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';
ALTER TABLE main.bi_db.bronze_walletconversiondb_c2f_fiattransactions ALTER COLUMN ConversionFeeAmount COMMENT 'Actual fee amount deducted from the conversion. Derived from Conversions.ConversionFeePercentage. NULL for zero-fee conversions. (Tier 1 - upstream wiki, WalletConversionDB.C2F.FiatTransactions)';

