-- =============================================================================
-- Databricks ALTER Script: BI_DB_dbo.V_BI_DB_KYC_Score_CID_Level
-- Generated: 2026-05-07 | scaffold_missing_uc_alter_files.py
-- Target: Unity Catalog table comment + column comments (1024 char limit)
-- UC Target: main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level
-- Resolved via: _generic_pipeline_mapping.json (sql_dp_prod_we)
-- =============================================================================

-- ---- Table Comment ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level SET TBLPROPERTIES (
    'comment' = 'BI_DB_dbo.V_BI_DB_KYC_Score_CID_Level > ~19.7M-row passthrough view over `BI_DB_dbo.BI_DB_KYC_Score_CID_Level` - one row per `RealCID` carrying the customer''s KYC-derived risk/wealth segmentation: Q11 wealth-bracket answer, age-on-registration bucket, MAX(33,35) score band, last-30-days revenue, and a final `Cluster` 1-10 (or `''No Cluster''`) used by risk and revenue-modelling pipelines. Two columns are renamed in the view: `[Max(33,35)_IND]` -> `MAX_33_35_IND`, `[Max(33,35)]` -> `MAX_33_25` (the latter rename appears to be a typo - see Gotchas). | Property | Value | |----------|-------| | **Schema** | BI_DB_dbo | | **Object Type** | View (passthrough over BI_DB_KYC_Score_CID_Level) | | **Production Source** | `BI_DB_dbo.BI_DB_KYC_Score_CID_Level` (writer SP TBD) | | **Refresh** | Inherits from base table - typically daily | | **Row Count** | ~19,732,000 | | **Grain** | One row per `RealCID'
);

-- ---- Table Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level SET TAGS (
    'source_schema' = 'BI_DB_dbo',
    'source_system' = 'Synapse',
    'pipeline' = 'dwh-semantic-doc',
    'pipeline_version' = 'scaffold-uc-alter'
);

-- ---- Column Comments ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN RealCID COMMENT 'Real customer identifier - FK to `DWH_dbo.Dim_Customer.RealCID`. Primary join key out of this view. (Tier 1 - DDL)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Q11_Answer_Grouped_IND COMMENT 'Numeric ordinal of the wealth bucket: 1, 2, 3, or 99 (Not_Answered). Use this for ordering/numeric calculations. (Tier 2 - UC distribution)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Q11_Answer_Grouped COMMENT 'Wealth bucket label: `''Up to $10K''`, `''$10K-$50K & $1M-$5M''`, `''$50K-$1M''`, or `''Not_Answered''`. (Tier 2 - UC distribution)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Age_On_Reg_Grouped_IND COMMENT 'Numeric ordinal of the age-on-registration bucket. (Tier 1 - DDL)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Age_On_Reg_Grouped COMMENT 'Age-on-registration bucket label (typical 5-10-year ranges). (Tier 1 - DDL)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN MAX_33_35_IND COMMENT 'Numeric ordinal of the MAX(field_33, field_35) score band. The underlying source name is `Max(33,35)_IND`; renamed for UC compatibility. (Tier 1 - view definition)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN MAX_33_25 COMMENT 'MAX(field_33, field_35) score band label. Source column is `[Max(33,35)]` - alias `MAX_33_25` appears to be a typo (the alias name). The value is the MAX of fields 33 AND 35, not 33 and 25. (Tier 1 - view definition + suspected naming bug)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Revenue30days COMMENT 'Revenue (USD) generated by the customer in the trailing 30 days. Used by the cluster algorithm and downstream revenue-modelling. NULL or 0 for inactive customers. (Tier 1 - DDL)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Reg_Date COMMENT 'Customer registration date (when the eToro account was opened). FK-equivalent to `Dim_Customer.Reg_Date`. (Tier 1 - DDL)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Cluster COMMENT 'Final segmentation cluster: integer string `''1''`-`''10''` or `''No Cluster''` for inactive customers. Higher integer = higher avg 30-day revenue (cluster 10 ≈ $208 avg vs cluster 1 ≈ $26). (Tier 2 - UC distribution audit, 2026-05-07)';
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN UpdateDate COMMENT 'Timestamp of the most recent ETL touch on this row. (Tier 1 - DDL)';

-- ---- Column PII Tags ----
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN RealCID SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Q11_Answer_Grouped_IND SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Q11_Answer_Grouped SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Age_On_Reg_Grouped_IND SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Age_On_Reg_Grouped SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN MAX_33_35_IND SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN MAX_33_25 SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Revenue30days SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Reg_Date SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN Cluster SET TAGS ('pii' = 'none');
ALTER TABLE main.bi_db.gold_sql_dp_prod_we_bi_db_dbo_v_bi_db_kyc_score_cid_level ALTER COLUMN UpdateDate SET TAGS ('pii' = 'none');

-- == LAST EXECUTION ==
-- Timestamp: 2026-05-07 10:50:48 UTC
-- Batch deploy resume: BI_DB_dbo deploy batch 13
-- Statements: 24/24 succeeded
-- ====================
