"""
Enumerate the tables/views that constitute a domain's PRODUCTION GROUND TRUTH,
per the Authority Hierarchy (knowledge/skills/_AUTHORITY_HIERARCHY.md):

  Tier 1 — every table referenced (directly or transitively) by the domain's
           KPI view DDLs (kpi_seeds in the domain's seed YAML).
  Tier 2 — every table in the curated table set of each Genie space matching
           genie_seeds (case-insensitive substring on title).

The output is a Markdown report that becomes the FIRST input into the rest of
the domain-build pipeline. Any downstream analysis (Louvain brief, subgraph,
authored SKILL.md) must respect the tables listed here as required_tables.

Usage:
  python tools/skills/enumerate_production_anchors.py --domain compliance

Output:
  knowledge/skills/_<domain>_production_anchors.md

Reads:
  tools/skills/_seeds/<domain>.yaml
  knowledge/skills/_kpi_views_index.json
  knowledge/skills/_genie_spaces_index.json
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SKILLS = ROOT / "knowledge" / "skills"
SEEDS = Path(__file__).resolve().parent / "_seeds"


def load_seed(domain: str) -> dict:
    p = SEEDS / f"{domain}.yaml"
    if not p.exists():
        print(f"Seed not found: {p}", file=sys.stderr)
        sys.exit(2)
    return yaml.safe_load(p.read_text(encoding="utf-8"))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", required=True, help="seed YAML id under tools/skills/_seeds/")
    ap.add_argument("--output", default=None, help="override output path")
    args = ap.parse_args()

    seed = load_seed(args.domain)
    kpi_seeds = set(seed.get("kpi_seeds") or [])
    genie_seeds = [t.lower() for t in (seed.get("genie_seeds") or [])]

    kpi_idx = json.loads((SKILLS / "_kpi_views_index.json").read_text(encoding="utf-8"))
    genie_idx = json.loads((SKILLS / "_genie_spaces_index.json").read_text(encoding="utf-8"))

    # Tier 1 — every table touched by any seed KPI view (closure over refs)
    by_self: dict[str, dict] = {v["self_ref"]: v for v in kpi_idx}
    tier1: dict[str, list[str]] = defaultdict(list)  # table -> [via_kpi_view, ...]
    seen_views: set[str] = set()

    def crawl_kpi(view_ref: str, path: list[str]) -> None:
        if view_ref in seen_views:
            return
        seen_views.add(view_ref)
        rec = by_self.get(view_ref)
        if not rec:
            return
        tier1[view_ref].append(" -> ".join(path + [view_ref]))
        for r in rec.get("refs", []):
            tier1[r].append(" -> ".join(path + [view_ref, r]))
            if r in by_self:
                crawl_kpi(r, path + [view_ref])

    unresolved_kpi: list[str] = []
    for seed_view in sorted(kpi_seeds):
        if seed_view not in by_self:
            unresolved_kpi.append(seed_view)
            continue
        crawl_kpi(seed_view, [])

    # Tier 2 — every table in every matching Genie space's curated tables list
    tier2: dict[str, list[dict]] = defaultdict(list)
    matched_genies: list[dict] = []
    unresolved_genies: list[str] = list(genie_seeds)
    for sp in genie_idx:
        title = sp.get("title", "")
        title_lc = title.lower()
        hits = [t for t in genie_seeds if t in title_lc]
        if not hits:
            continue
        matched_genies.append({
            "title": title,
            "space_id": sp.get("space_id", ""),
            "n_tables": sp.get("n_tables", 0),
            "is_prod": _is_prod(title),
            "description": (sp.get("description") or "")[:200],
            "tables": sp.get("canonical_tables") or sp.get("tables") or [],
            "matched_by_seed": hits,
        })
        for t in (sp.get("canonical_tables") or sp.get("tables") or []):
            tier2[t].append({"genie_title": title, "is_prod": _is_prod(title)})
        for h in hits:
            if h in unresolved_genies:
                unresolved_genies.remove(h)

    out_path = Path(args.output) if args.output else SKILLS / f"_{args.domain}_production_anchors.md"

    lines = []
    lines.append(f"# {seed.get('display_name', args.domain)} — Production Anchors")
    lines.append("")
    lines.append(f"_Generated by `tools/skills/enumerate_production_anchors.py --domain {args.domain}`._")
    lines.append("")
    lines.append(f"_Seed: `tools/skills/_seeds/{args.domain}.yaml`_")
    lines.append("")
    lines.append("This document lists the tables/views that constitute the")
    lines.append(f"**production ground truth** for the {seed.get('display_name', args.domain)} domain,")
    lines.append("per `knowledge/skills/_AUTHORITY_HIERARCHY.md`.")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Tier 1 (KPI-touched) nodes: **{len(tier1)}**")
    lines.append(f"- Tier 2 (Genie-only) nodes: **{len([t for t in tier2 if t not in tier1])}**")
    lines.append(f"- Genie spaces matched: **{len(matched_genies)}** ({sum(1 for g in matched_genies if g['is_prod'])} production, {sum(1 for g in matched_genies if not g['is_prod'])} non-prod)")
    lines.append(f"- KPI seeds resolved: **{len(kpi_seeds) - len(unresolved_kpi)} / {len(kpi_seeds)}**")
    if unresolved_kpi:
        lines.append("")
        lines.append("**Unresolved KPI seeds** (not in `_kpi_views_index.json`):")
        for v in unresolved_kpi:
            lines.append(f"- `{v}`")
    if unresolved_genies:
        lines.append("")
        lines.append("**Unmatched Genie seeds** (no title match in `_genie_spaces_index.json`):")
        for g in unresolved_genies:
            lines.append(f"- `{g}`")
    lines.append("")

    lines.append("## Tier 1 — KPI-touched tables")
    lines.append("")
    lines.append("Tables reached by transitive closure of KPI view `refs`. Each row's")
    lines.append("`via` column shows the chain from a seed KPI view down to the table.")
    lines.append("")
    lines.append("| Table / View | Via |")
    lines.append("|---|---|")
    for t in sorted(tier1.keys()):
        via_str = "<br>".join(f"`{v}`" for v in sorted(set(tier1[t]))[:3])
        if len(set(tier1[t])) > 3:
            via_str += f"<br>_(+{len(set(tier1[t])) - 3} more)_"
        lines.append(f"| `{t}` | {via_str} |")
    lines.append("")

    lines.append("## Tier 2 — Genie-curated tables (not already in Tier 1)")
    lines.append("")
    lines.append("Tables in matched Genie configs that are NOT reached from KPI views.")
    lines.append("")
    lines.append("| Table | Genie space(s) | Prod? |")
    lines.append("|---|---|---|")
    for t in sorted(tier2.keys()):
        if t in tier1:
            continue
        genies = tier2[t]
        titles = ", ".join(f"`{g['genie_title']}`" for g in genies)
        is_prod = "yes" if any(g["is_prod"] for g in genies) else "no"
        lines.append(f"| `{t}` | {titles} | {is_prod} |")
    lines.append("")

    lines.append("## Matched Genie spaces")
    lines.append("")
    for g in sorted(matched_genies, key=lambda x: (-int(x["is_prod"]), x["title"])):
        prod_tag = " **(PRODUCTION)**" if g["is_prod"] else " _(non-prod)_"
        lines.append(f"### `{g['title']}`{prod_tag}")
        lines.append("")
        lines.append(f"- `space_id`: `{g['space_id']}`")
        lines.append(f"- Tables: {g['n_tables']}")
        lines.append(f"- Matched by seed term(s): {', '.join(repr(h) for h in g['matched_by_seed'])}")
        if g["description"]:
            lines.append(f"- Description: {g['description']}")
        lines.append("")
        lines.append("**Tables in this Genie:**")
        for t in sorted(g["tables"]):
            lines.append(f"- `{t}`")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path.relative_to(ROOT)}")
    print(f"  Tier 1: {len(tier1)} tables")
    print(f"  Tier 2: {len([t for t in tier2 if t not in tier1])} additional tables")
    print(f"  Matched Genies: {len(matched_genies)}")
    return 0


def _is_prod(title: str) -> bool:
    """Heuristic: a Genie title is 'production' unless it contains DEV/TEST/WIP/etc."""
    bad = ("dev", "test", "wip", "sandbox", "scratch", "tmp", "draft", "play")
    return not any(b in title.lower() for b in bad)


if __name__ == "__main__":
    sys.exit(main())
