"""
lint_skill.py - Local mirror of eToro DataPlatform DE CI checks for SKILL.md

Run before committing any SKILL.md authored or generated by this SpecKit.
Exit 0 means the file conforms to the DE schema mirrored at
.specify/memory/skill-schema.md and would pass workspace-level CI.

Constitution: Principle X (NON-NEGOTIABLE).
DE source:    /Workspace/.assistant/skills/skill-creator/SKILL.md

Usage:
    python tools/skills/lint_skill.py <path-to-SKILL.md> [<path-to-SKILL.md> ...]

Exit codes:
    0 - all files pass
    1 - one or more files failed (errors printed line-by-line)
    2 - usage error (no files given, file not found)
"""

from __future__ import annotations

import datetime as _dt
import os
import re
import sys
from pathlib import Path

MAX_LINES = 500
MAX_BYTES = 100 * 1024
MIN_DESCRIPTION_CHARS = 30
LAST_VERIFIED_MAX_AGE_DAYS = 90

REQUIRED_FRONTMATTER = ("id", "name", "description", "triggers", "required_tables", "version", "owner")

SECRET_PATTERNS = (
    re.compile(r"(?i)\b(?:api[_-]?key|secret|token|password|passwd|pwd|connectionstring)\s*[:=]\s*['\"][^'\"]{6,}['\"]"),
    re.compile(r"\bsk-[A-Za-z0-9]{20,}\b"),
    re.compile(r"\bdapi[A-Za-z0-9]{20,}\b"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
)

ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$")
UC_TABLE_PATTERN = re.compile(r"^[a-z0-9_]+\.[a-z0-9_]+\.[a-z0-9_]+$", re.IGNORECASE)
ABSOLUTE_PATH_PATTERN = re.compile(r"(?:^|[\s\"'`(])(?:[A-Za-z]:[\\/]|/(?:home|users|workspace|mnt|opt|var|tmp|etc)/)")
BACKSLASH_PATH_PATTERN = re.compile(r"[A-Za-z0-9_.\-]+\\[A-Za-z0-9_.\-]+\\[A-Za-z0-9_.\-]")
FIRST_PERSON_PATTERN = re.compile(r"\b(?:I help|I can|you can use this|use this to help)\b", re.IGNORECASE)


class LintError(Exception):
    pass


def _read(path: Path) -> tuple[str, list[str]]:
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        raise LintError("HYGIENE: file starts with UTF-8 BOM (not allowed)")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise LintError(f"HYGIENE: file is not valid UTF-8 ({exc})") from exc
    return text, text.splitlines()


def _split_frontmatter(lines: list[str]) -> tuple[list[str], list[str], int]:
    """Return (frontmatter_lines, body_lines, frontmatter_end_index_inclusive)."""
    if not lines or lines[0].strip() != "---":
        raise LintError("FRONTMATTER: file does not start with --- (YAML frontmatter required)")
    end = -1
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
    if end == -1:
        raise LintError("FRONTMATTER: closing --- not found")
    return lines[1:end], lines[end + 1:], end


def _parse_frontmatter(fm_lines: list[str]) -> dict:
    """Minimal YAML parse: scalar key:value, list of strings via leading '- ',
    multi-line scalars via '|' or '>' folded blocks. Sufficient for SKILL.md frontmatter."""
    result: dict = {}
    i = 0
    n = len(fm_lines)
    while i < n:
        raw = fm_lines[i]
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            i += 1
            continue
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_-]*\s*:", line):
            i += 1
            continue
        key, _, rest = line.partition(":")
        key = key.strip()
        rest = rest.strip()
        if rest in ("|", ">", "|-", ">-"):
            buf: list[str] = []
            i += 1
            while i < n and (not fm_lines[i].strip() or fm_lines[i].startswith((" ", "\t"))):
                buf.append(fm_lines[i].lstrip())
                i += 1
            result[key] = ("\n" if rest.startswith("|") else " ").join(s for s in buf if s).strip()
            continue
        if rest == "":
            items: list[str] = []
            i += 1
            while i < n and fm_lines[i].lstrip().startswith("- "):
                items.append(fm_lines[i].lstrip()[2:].strip().strip("\"'"))
                i += 1
            result[key] = items if items else ""
            continue
        if rest.startswith("[") and rest.endswith("]"):
            inner = rest[1:-1].strip()
            result[key] = [s.strip().strip("\"'") for s in inner.split(",") if s.strip()] if inner else []
            i += 1
            continue
        result[key] = rest.strip("\"'")
        i += 1
    return result


def _has_trailing_whitespace(lines: list[str]) -> list[int]:
    return [i + 1 for i, line in enumerate(lines) if line != line.rstrip()]


def _lint_file(path: Path) -> list[str]:
    errors: list[str] = []

    if not path.exists():
        return [f"FILE: {path} not found"]

    size = path.stat().st_size
    if size > MAX_BYTES:
        errors.append(f"HYGIENE: file size {size} bytes exceeds {MAX_BYTES} (100 KB)")

    try:
        text, lines = _read(path)
    except LintError as exc:
        return [str(exc)]

    if len(lines) > MAX_LINES:
        errors.append(f"QUAL-003: file has {len(lines)} lines, max {MAX_LINES}")

    try:
        fm_lines, body_lines, fm_end = _split_frontmatter(lines)
    except LintError as exc:
        return errors + [str(exc)]

    bad_ws = _has_trailing_whitespace(fm_lines)
    if bad_ws:
        errors.append(f"HYGIENE: trailing whitespace in frontmatter at lines {bad_ws}")

    try:
        fm = _parse_frontmatter(fm_lines)
    except Exception as exc:  # noqa: BLE001
        return errors + [f"FRONTMATTER: parse error ({exc})"]

    for field in REQUIRED_FRONTMATTER:
        if field not in fm or fm[field] in (None, "", []):
            errors.append(f"FRONTMATTER: missing or empty required field '{field}'")

    skill_id = fm.get("id", "")
    if skill_id:
        if not ID_PATTERN.match(skill_id):
            errors.append(
                f"FRONTMATTER: 'id' = '{skill_id}' violates pattern ^[a-z0-9][a-z0-9-]*[a-z0-9]$ "
                "(kebab-case, lowercase, no underscores)"
            )
        stem = path.stem
        if stem.lower() == "skill" and path.parent.name:
            stem = path.parent.name
        if skill_id != stem:
            errors.append(
                f"FRONTMATTER: 'id' = '{skill_id}' does not match filename stem / parent dir = '{stem}'"
            )

    desc = fm.get("description", "") or ""
    if isinstance(desc, list):
        desc = " ".join(desc)
    if len(desc) < MIN_DESCRIPTION_CHARS:
        errors.append(f"QUAL-001: description has {len(desc)} chars, minimum {MIN_DESCRIPTION_CHARS}")
    if FIRST_PERSON_PATTERN.search(desc):
        errors.append("AUTHOR-002: description not in third person (avoid 'I help' / 'you can use this')")

    req_tables = fm.get("required_tables", []) or []
    if isinstance(req_tables, str):
        req_tables = [req_tables]
    if not req_tables:
        errors.append("FRONTMATTER: 'required_tables' must list ≥1 fully qualified UC object")
    for tbl in req_tables:
        if not UC_TABLE_PATTERN.match(tbl.strip()):
            errors.append(
                f"FRONTMATTER: 'required_tables' entry '{tbl}' is not fully qualified (expected catalog.schema.table)"
            )

    triggers = fm.get("triggers", []) or []
    if isinstance(triggers, str):
        triggers = [triggers]
    if not triggers:
        errors.append("FRONTMATTER: 'triggers' should list ≥1 keyword (recommended; embedding signal)")

    last_validated = fm.get("last_validated_at", "")
    if last_validated:
        try:
            d = _dt.date.fromisoformat(last_validated)
            age = (_dt.date.today() - d).days
            if age > LAST_VERIFIED_MAX_AGE_DAYS:
                errors.append(
                    f"DOMAIN-003 (frontmatter): 'last_validated_at' = {last_validated} is "
                    f"{age} days old (max {LAST_VERIFIED_MAX_AGE_DAYS})"
                )
            if age < 0:
                errors.append(f"FRONTMATTER: 'last_validated_at' = {last_validated} is in the future")
        except ValueError:
            errors.append(f"FRONTMATTER: 'last_validated_at' = '{last_validated}' is not ISO YYYY-MM-DD")

    body_text = "\n".join(body_lines)
    body_stripped = body_text.strip()
    if not body_stripped:
        errors.append("QUAL-002: body is empty")

    for pattern in SECRET_PATTERNS:
        m = pattern.search(text)
        if m:
            line_no = text[: m.start()].count("\n") + 1
            errors.append(f"SEC-001: possible secret on line {line_no}: '{m.group(0)[:60]}...'")

    for line_no, line in enumerate(lines, start=1):
        if line_no <= fm_end + 1:
            continue
        if ABSOLUTE_PATH_PATTERN.search(line):
            errors.append(f"QUAL-004: absolute path detected on line {line_no}: '{line.strip()[:80]}'")
        if BACKSLASH_PATH_PATTERN.search(line) and "```" not in line:
            errors.append(f"AUTHOR-001: backslash path detected on line {line_no}: '{line.strip()[:80]}'")

    headers = [(i + fm_end + 2, ln.strip()) for i, ln in enumerate(body_lines) if ln.startswith("##")]

    when_to_use = [(ln_no, h) for ln_no, h in headers if re.match(r"^##\s+When to Use\b", h, re.IGNORECASE)]
    if not when_to_use:
        errors.append("DOMAIN-004: missing '## When to Use' section")

    scope_idx = next((i for i, (_, h) in enumerate(headers) if re.match(r"^##\s+Scope\b", h, re.IGNORECASE)), None)
    if scope_idx is None:
        errors.append("DOMAIN-001: missing '## Scope' section")
    else:
        scope_start_line = headers[scope_idx][0]
        scope_end_line = headers[scope_idx + 1][0] - 1 if scope_idx + 1 < len(headers) else len(lines)
        scope_block = lines[scope_start_line:scope_end_line]
        scope_text = "\n".join(scope_block)
        if not re.search(r"^In scope:\s*\S+", scope_text, re.MULTILINE):
            errors.append("DOMAIN-001: '## Scope' missing or empty 'In scope:' line")
        if not re.search(r"^Out of scope:\s*\S+", scope_text, re.MULTILINE):
            errors.append("DOMAIN-001: '## Scope' missing or empty 'Out of scope:' line")
        m_lv = re.search(r"^Last verified:\s*(\S+)", scope_text, re.MULTILINE)
        if not m_lv:
            errors.append("DOMAIN-002: '## Scope' missing 'Last verified: YYYY-MM-DD' line")
        else:
            iso = m_lv.group(1).strip()
            try:
                d = _dt.date.fromisoformat(iso)
                age = (_dt.date.today() - d).days
                if age > LAST_VERIFIED_MAX_AGE_DAYS:
                    errors.append(
                        f"DOMAIN-003: 'Last verified: {iso}' is {age} days old (max {LAST_VERIFIED_MAX_AGE_DAYS})"
                    )
                if age < 0:
                    errors.append(f"DOMAIN-002: 'Last verified: {iso}' is in the future")
            except ValueError:
                errors.append(f"DOMAIN-002: 'Last verified: {iso}' is not ISO YYYY-MM-DD")

    cw_idx = next(
        (i for i, (_, h) in enumerate(headers) if re.match(r"^##\s+Critical Warnings\b", h, re.IGNORECASE)),
        None,
    )
    if cw_idx is None:
        errors.append("DOMAIN-005: missing '## Critical Warnings' section")
    else:
        cw_start_line = headers[cw_idx][0]
        cw_end_line = headers[cw_idx + 1][0] - 1 if cw_idx + 1 < len(headers) else len(lines)
        cw_block = lines[cw_start_line:cw_end_line]
        cw_text_raw = "\n".join(cw_block)
        cw_text = re.sub(r"<!--.*?-->", "", cw_text_raw, flags=re.DOTALL)
        numbered = re.findall(r"^\s*(\d+)\.\s", cw_text, re.MULTILINE)
        if len(numbered) < 1:
            errors.append("DOMAIN-006: '## Critical Warnings' must be a numbered list with ≥1 item")
        else:
            ints = [int(n) for n in numbered]
            if ints != list(range(1, len(ints) + 1)):
                errors.append(
                    f"DOMAIN-006: '## Critical Warnings' numbering must be sequential starting at 1, got {ints}"
                )
        tier_matches = re.findall(r"\bTier\s*([123])\b", cw_text, re.IGNORECASE)
        if tier_matches:
            tiers = [int(t) for t in tier_matches]
            if tiers != sorted(tiers):
                errors.append(
                    f"DOMAIN-007: '## Critical Warnings' tier order must be ascending Tier 1 → 3, got {tiers}"
                )

    vague_terms = ("all data", "everything", "various data", "all kinds of")
    in_scope_match = re.search(r"^In scope:\s*(.+)$", body_text, re.MULTILINE)
    if in_scope_match:
        in_scope = in_scope_match.group(1).strip().lower()
        if any(v in in_scope for v in vague_terms):
            errors.append(f"QUAL-005: 'In scope:' is vague ('{in_scope[:80]}'). List explicit tables/metrics.")

    return errors


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("Usage: python tools/skills/lint_skill.py <path-to-SKILL.md> [...]", file=sys.stderr)
        return 2

    any_failed = False
    for arg in argv[1:]:
        path = Path(arg).resolve()
        print(f"=== {path} ===")
        if not path.exists():
            print(f"  FILE: {path} not found")
            any_failed = True
            continue
        errs = _lint_file(path)
        if not errs:
            print("  PASS (DE schema compliant)")
        else:
            any_failed = True
            for e in errs:
                print(f"  FAIL: {e}")
        print()

    return 1 if any_failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
