-- =============================================================================
-- Databricks ALTER Script: bronze etoro.Customer.Customer
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Customer/Views/Customer.Customer.md
-- Layer: bronze
-- UC Targets (2):
--   main.pii_data.bronze_etoro_customer_customer
--   main.general.bronze_etoro_customer_customer_masked
-- =============================================================================

-- ---- UC Target: main.pii_data.bronze_etoro_customer_customer (business_group=pii_data) ----
ALTER TABLE main.pii_data.bronze_etoro_customer_customer SET TBLPROPERTIES (
    'comment' = 'The unified customer view: joins CustomerStatic (identity, profile, settings) with CustomerMoney (balance fields) to present the complete customer record in a single queryable surface. The primary read interface for customer data across the platform. Source: etoro.Customer.Customer on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Customer/Views/Customer.Customer.md).'
);

ALTER TABLE main.pii_data.bronze_etoro_customer_customer SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'Customer',
    'source_table' = 'Customer',
    'business_group' = 'pii_data',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN CID COMMENT 'Customer ID - platform-internal primary key. From CustomerStatic. Used as the universal customer identifier across all tables. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN OriginalProviderID COMMENT 'Provider ID from which this account was originally migrated or registered. From CustomerStatic. Together with OriginalCID, forms the original identity key for migration tracing. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN OriginalCID COMMENT 'Original customer ID from the source provider before any migration. From CustomerStatic. Default=0 for non-migrated accounts. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN ProviderID COMMENT 'Current active provider/broker ID. From CustomerStatic. FK to Trade.Provider. Determines the trading provider for this customer. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN RealProviderID COMMENT 'The underlying real provider ID when different from ProviderID. From CustomerStatic. Nullable. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN CountryID COMMENT 'Country of residence. From CustomerStatic. FK to Dictionary.Country. Determines regulatory framework, available instruments, and leverage limits. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN CountryIDByIP COMMENT 'Country detected from the customer''s IP address at registration. From CustomerStatic. Used for fraud detection and geo-comparison (CountryID vs CountryIDByIP mismatch flagging). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN CitizenshipCountryID COMMENT 'Country of citizenship (may differ from CountryID/residence). From CustomerStatic. FK to Dictionary.Country. Added 2018 (changelog: 50308) for enhanced KYC. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN StateID COMMENT 'US state ID for US customers, or 0 for others. From CustomerStatic. FK to Dictionary.State. Required for certain regulatory and tax purposes. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN LanguageID COMMENT 'Customer''s preferred platform language. From CustomerStatic. FK to Dictionary.Language. Controls UI language. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN CommunicationLanguageID COMMENT 'Language for customer communications (emails, notifications). From CustomerStatic. May differ from LanguageID. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN CurrencyID COMMENT 'Customer''s account base currency. From CustomerStatic. FK to Dictionary.Currency (1=USD). Currently all USD in practice; central to the multi-currency migration roadmap. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN TimeZoneID COMMENT 'Customer''s time zone. From CustomerStatic. FK to Dictionary.TimeZone. Used for time-aware notifications. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PlayerStatusID COMMENT 'Compliance and trading account status. From CustomerStatic. FK to Dictionary.PlayerStatus. 1=Active (97.5%); other values indicate restricted, closed, banned, or special states. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN CampaignID COMMENT 'Marketing campaign ID under which the customer was acquired. From CustomerStatic. FK to BackOffice.Campaign. NULL for organically acquired customers. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PlayerLevelID COMMENT 'Customer experience/permission level. From CustomerStatic. FK to Dictionary.PlayerLevel. 1=Standard (94%); 4=Popular Investor (triggers IsHedged=0); 7=VIP. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN TradeLevelID COMMENT 'Trading knowledge/experience classification. From CustomerStatic. FK to Dictionary.TradeLevel. Used for MiFID suitability assessment. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN SpreadGroupID COMMENT 'Spread/pricing group. From CustomerStatic. FK to Trade.SpreadGroup. Determines which pricing table the customer uses. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN LabelID COMMENT 'Internal segment label. From CustomerStatic. FK to Dictionary.Label. LabelID=26 = BonusOnly (triggers IsHedged=0). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN FunnelID COMMENT 'Registration funnel ID. From CustomerStatic. FK to Dictionary.Funnel. Tracks which user journey/funnel variant the customer came through. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN UserName COMMENT 'Customer''s login username. From CustomerStatic. Unique (case-insensitive). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Password COMMENT 'Hashed password. From CustomerStatic. varchar(20) stores a hash. Password changes are NOT versioned in History.Customer. Use Customer.CustomerSafty instead when password field should be hidden. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Registered COMMENT 'Account registration date. From CustomerStatic. Default=getdate() at INSERT time. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN IsReal COMMENT 'Account type: 1=real-money account, 0=demo account. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN IP COMMENT 'Registration IP address. From CustomerStatic. Dynamic Data Masking applied on the base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Credit COMMENT 'Customer''s current available trading balance in USD. From CustomerMoney (LEFT JOIN). The core field updated by every financial transaction (deposit, withdrawal, position). NULL if no CustomerMoney row exists. See Customer.CustomerMoney for full balance write architecture. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN BirthDate COMMENT 'Customer date of birth. From CustomerStatic. Dynamic Data Masking on base table. Used in KYC age verification and duplicate detection (LinkedAccountHash1). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Gender COMMENT 'Gender: ''M'', ''F'', or ''U'' (Unknown). From CustomerStatic. CHECK constraint on base table. Used in duplicate detection hash. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN FirstName COMMENT 'Legal first name in Unicode. From CustomerStatic. Dynamic Data Masking on base table. nvarchar supports non-Latin scripts. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN LastName COMMENT 'Legal last name in Unicode. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN MiddleName COMMENT 'Middle name in Unicode. From CustomerStatic. Dynamic Data Masking on base table. Added 2018 (changelog: 50094). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Address COMMENT 'Street address in Unicode. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN City COMMENT 'City. From CustomerStatic. Not masked (unlike Address/Zip). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Zip COMMENT 'Postal code. From CustomerStatic. Dynamic Data Masking on base table. Used in duplicate detection hash. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN SerialID COMMENT 'Affiliate (partner/introducing broker) ID. From CustomerStatic. FK to BackOffice.Affiliate. NULL for direct/organic registrations. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN ReferralID COMMENT 'Referral CID - the customer who referred this one. From CustomerStatic. Used for RAF (Refer-a-Friend) program tracking. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN SubSerialID COMMENT 'Sub-affiliate identifier string. From CustomerStatic. Up to 1024 chars for complex affiliate tracking paths. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Email COMMENT 'Customer email address. From CustomerStatic. Dynamic Data Masking on base table. Unique (case-insensitive). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN IsEmailVerified COMMENT 'Whether the email was verified by clicking a confirmation link. From CustomerStatic. NULL for accounts predating this flag. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Phone COMMENT 'Primary phone number. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Fax COMMENT 'Fax number. From CustomerStatic. Legacy field; rarely populated in modern registrations. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Mobile COMMENT 'Mobile number. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN Comments COMMENT 'Internal comment field. From CustomerStatic. BackOffice operators can add notes. varchar(8000). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN DownloadID COMMENT 'Platform download source ID. From CustomerStatic. Legacy tracking for which platform installer the customer used. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN BannerID COMMENT 'Advertising banner ID that led to registration. From CustomerStatic. Legacy acquisition tracking. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN ClientVersion COMMENT 'Client application version at registration. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PersonID COMMENT 'External person identifier. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN BonusCredit COMMENT 'Promotional/bonus credits separate from real funds. From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. Tracked separately to distinguish promotional funds from deposited funds. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN DownloadCounter COMMENT 'Number of times the customer has downloaded the platform client. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN AccountExpirationDate COMMENT 'Expiration date for demo or time-limited accounts. From CustomerStatic. NULL for standard real-money accounts. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN HelpDeskType COMMENT 'Customer service tier assignment. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN LotCountGroupID COMMENT 'Lot/quantity group. From CustomerStatic. FK to Dictionary.LotCountGroup. Controls min/max lot sizes for trading. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PrivacyPolicyID COMMENT 'Privacy policy version accepted by the customer. From CustomerStatic. FK to Dictionary.PrivacyPolicy. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN GCID COMMENT 'Group Customer ID - cross-product identity key linking same person across eToro products. From CustomerStatic. NULL for accounts predating GCID introduction. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN WeekendFeePrecentage COMMENT 'Weekend swap fee percentage (100=full fee, <100=discounted). From CustomerStatic. Note: column name has typo "Precentage". (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN IsEmailActivated COMMENT 'Email activation status flag. From CustomerStatic. Separate from IsEmailVerified - tracks account email activation step completion. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN UserName_LOWER COMMENT 'Computed: lower(UserName). From CustomerStatic. Used for case-insensitive username uniqueness enforcement. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN RealizedEquity COMMENT 'Running total of realized account value (deposits + closed-position proceeds - withdrawals). From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. Answers: "How much realized value does this customer have?" (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN AccountStatusID COMMENT 'Account operational status. From CustomerStatic. 1=Active/Normal (93.9%); 2=Closed/Restricted; NULL=pre-AccountStatusID era. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PendingClosureStatusID COMMENT 'Status in the pending account closure workflow. From CustomerStatic. Default=1 (no pending closure). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN IsRequestedCall COMMENT 'Whether the customer has requested a callback from sales/support. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN FunnelFromID COMMENT 'Source funnel variant tracking within the acquisition funnel. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN LeverageType COMMENT 'Leverage setting type (default=1). From CustomerStatic. Determines the leverage scheme applied to this account. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN TotalCash COMMENT 'Reconciled total cash balance maintained by the Trade.UpdateTotalCash reconciliation job. From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN ClientTypeID COMMENT 'Client classification type for MiFID2 categorization (retail, professional, etc.). From CustomerStatic. FK to Dictionary.ClientType. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN IsHedged COMMENT 'Whether this customer''s trades are hedged on the broker side. From CustomerStatic. Managed by CustomerVersionInsert/Update triggers: 0 (not hedged) for Popular Investors (PlayerLevelID=4) or BonusOnly (LabelID=26) or CEP/BonusOnlyCustomers list members; 1 (hedged) for all others. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN LowerEmail COMMENT 'Computed: lower(Email). From CustomerStatic. Used for case-insensitive email uniqueness enforcement. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN ID COMMENT 'System GUID for REST API identity. From CustomerStatic. Default=newsequentialid(). Unique index on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN VerificationTitle COMMENT 'KYC verification title/level text. From CustomerStatic. Default from Customer.VerificationTitle_Default() function. Changes are versioned in History.Customer. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN VerificationTitleVersion COMMENT 'Version GUID for optimistic concurrency on verification title updates. From CustomerStatic. Default=newid(). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN BuildingNumber COMMENT 'Building/apartment number. From CustomerStatic. Dynamic Data Masking on base table. Structured address field added 2015 (changelog: 02/08/2015). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PhonePrefix COMMENT 'International dialing prefix (e.g., +1, +44). From CustomerStatic. Added 2015 (changelog: 27/10/2015). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PhoneBody COMMENT 'Local phone number without country prefix. From CustomerStatic. Dynamic Data Masking on base table. Added 2015 (changelog: 27/10/2015). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN ExternalID COMMENT 'APEX broker external ID. From CustomerStatic. Unique index on base table. Decimal(38,0) accommodates APEX''s large numeric ID format. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN RegionID COMMENT 'Geographic region ID (GeoIP-derived or set). From CustomerStatic. Added 2016 (changelog: 40722) alongside CountryIDByIP for granular regulation. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN RegionByIP_ID COMMENT 'Region detected from IP address. From CustomerStatic. Added 2016 (changelog: 40722). Separate from RegionID (profile-based) for mismatch detection. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PlatformID COMMENT 'Platform/product identifier (web, mobile, etc.). From CustomerStatic. Added 2016 (changelog: 40618). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN BSLRealFunds COMMENT 'Real funds threshold for Balance Stop Loss (BSL) - safety floor that triggers position liquidation if equity drops below this level. From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. Updated by PostMIMOOperations pipeline. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN OptOutReasonID COMMENT 'Reason for GDPR/marketing opt-out. From CustomerStatic. Added 2017 (changelog: 18-07-2017). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PlayerStatusReasonID COMMENT 'Reason code for current PlayerStatusID ("why" behind a non-Active status). From CustomerStatic. Added 2017 (changelog: 24/07/2017). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PlayerStatusSubReasonID COMMENT 'Sub-reason code for PlayerStatus (hierarchical). From CustomerStatic. FK to Dictionary.PlayerStatusSubReasons. Added 2019 (changelog: RD-1752). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN PlayerStatusSubReasonComment COMMENT 'Free-text comment for the PlayerStatusSubReasonID. From CustomerStatic. Max 64 chars. Added 2019. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN POBCountryID COMMENT 'Place of birth country. From CustomerStatic. FK to Dictionary.Country. Added 2019 (HLD: RD-4436 Add Place of Birth to KYC). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN SubRegionID COMMENT 'Sub-region (province/state for non-US countries). From CustomerStatic. FK to Dictionary.SubRegion. Added 2019 (changelog: 09/07/2019). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN EmailVerificationProviderID COMMENT 'External email verification provider used for this customer''s email. From CustomerStatic. FK to Dictionary.EmailVerificationProvider. Added 2020. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.pii_data.bronze_etoro_customer_customer ALTER COLUMN DltID COMMENT 'Distributed Ledger Technology integration ID. From CustomerStatic. Added per HLD: COAKVU-2880 DLT Integration. Links customer to DLT/blockchain system. (Tier 1 - upstream wiki, etoro.Customer.Customer)';

-- ---- UC Target: main.general.bronze_etoro_customer_customer_masked (business_group=general) ----
ALTER TABLE main.general.bronze_etoro_customer_customer_masked SET TBLPROPERTIES (
    'comment' = 'The unified customer view: joins CustomerStatic (identity, profile, settings) with CustomerMoney (balance fields) to present the complete customer record in a single queryable surface. The primary read interface for customer data across the platform. Source: etoro.Customer.Customer on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Customer/Views/Customer.Customer.md).'
);

ALTER TABLE main.general.bronze_etoro_customer_customer_masked SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'Customer',
    'source_table' = 'Customer',
    'business_group' = 'general',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN CID COMMENT 'Customer ID - platform-internal primary key. From CustomerStatic. Used as the universal customer identifier across all tables. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN OriginalProviderID COMMENT 'Provider ID from which this account was originally migrated or registered. From CustomerStatic. Together with OriginalCID, forms the original identity key for migration tracing. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN OriginalCID COMMENT 'Original customer ID from the source provider before any migration. From CustomerStatic. Default=0 for non-migrated accounts. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN ProviderID COMMENT 'Current active provider/broker ID. From CustomerStatic. FK to Trade.Provider. Determines the trading provider for this customer. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN RealProviderID COMMENT 'The underlying real provider ID when different from ProviderID. From CustomerStatic. Nullable. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN CountryID COMMENT 'Country of residence. From CustomerStatic. FK to Dictionary.Country. Determines regulatory framework, available instruments, and leverage limits. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN CountryIDByIP COMMENT 'Country detected from the customer''s IP address at registration. From CustomerStatic. Used for fraud detection and geo-comparison (CountryID vs CountryIDByIP mismatch flagging). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN CitizenshipCountryID COMMENT 'Country of citizenship (may differ from CountryID/residence). From CustomerStatic. FK to Dictionary.Country. Added 2018 (changelog: 50308) for enhanced KYC. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN StateID COMMENT 'US state ID for US customers, or 0 for others. From CustomerStatic. FK to Dictionary.State. Required for certain regulatory and tax purposes. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN LanguageID COMMENT 'Customer''s preferred platform language. From CustomerStatic. FK to Dictionary.Language. Controls UI language. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN CommunicationLanguageID COMMENT 'Language for customer communications (emails, notifications). From CustomerStatic. May differ from LanguageID. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN CurrencyID COMMENT 'Customer''s account base currency. From CustomerStatic. FK to Dictionary.Currency (1=USD). Currently all USD in practice; central to the multi-currency migration roadmap. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN TimeZoneID COMMENT 'Customer''s time zone. From CustomerStatic. FK to Dictionary.TimeZone. Used for time-aware notifications. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PlayerStatusID COMMENT 'Compliance and trading account status. From CustomerStatic. FK to Dictionary.PlayerStatus. 1=Active (97.5%); other values indicate restricted, closed, banned, or special states. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN CampaignID COMMENT 'Marketing campaign ID under which the customer was acquired. From CustomerStatic. FK to BackOffice.Campaign. NULL for organically acquired customers. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PlayerLevelID COMMENT 'Customer experience/permission level. From CustomerStatic. FK to Dictionary.PlayerLevel. 1=Standard (94%); 4=Popular Investor (triggers IsHedged=0); 7=VIP. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN TradeLevelID COMMENT 'Trading knowledge/experience classification. From CustomerStatic. FK to Dictionary.TradeLevel. Used for MiFID suitability assessment. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN SpreadGroupID COMMENT 'Spread/pricing group. From CustomerStatic. FK to Trade.SpreadGroup. Determines which pricing table the customer uses. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN LabelID COMMENT 'Internal segment label. From CustomerStatic. FK to Dictionary.Label. LabelID=26 = BonusOnly (triggers IsHedged=0). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN FunnelID COMMENT 'Registration funnel ID. From CustomerStatic. FK to Dictionary.Funnel. Tracks which user journey/funnel variant the customer came through. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN UserName COMMENT 'Customer''s login username. From CustomerStatic. Unique (case-insensitive). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Password COMMENT 'Hashed password. From CustomerStatic. varchar(20) stores a hash. Password changes are NOT versioned in History.Customer. Use Customer.CustomerSafty instead when password field should be hidden. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Registered COMMENT 'Account registration date. From CustomerStatic. Default=getdate() at INSERT time. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN IsReal COMMENT 'Account type: 1=real-money account, 0=demo account. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN IP COMMENT 'Registration IP address. From CustomerStatic. Dynamic Data Masking applied on the base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Credit COMMENT 'Customer''s current available trading balance in USD. From CustomerMoney (LEFT JOIN). The core field updated by every financial transaction (deposit, withdrawal, position). NULL if no CustomerMoney row exists. See Customer.CustomerMoney for full balance write architecture. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN BirthDate COMMENT 'Customer date of birth. From CustomerStatic. Dynamic Data Masking on base table. Used in KYC age verification and duplicate detection (LinkedAccountHash1). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Gender COMMENT 'Gender: ''M'', ''F'', or ''U'' (Unknown). From CustomerStatic. CHECK constraint on base table. Used in duplicate detection hash. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN FirstName COMMENT 'Legal first name in Unicode. From CustomerStatic. Dynamic Data Masking on base table. nvarchar supports non-Latin scripts. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN LastName COMMENT 'Legal last name in Unicode. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN MiddleName COMMENT 'Middle name in Unicode. From CustomerStatic. Dynamic Data Masking on base table. Added 2018 (changelog: 50094). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Address COMMENT 'Street address in Unicode. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN City COMMENT 'City. From CustomerStatic. Not masked (unlike Address/Zip). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Zip COMMENT 'Postal code. From CustomerStatic. Dynamic Data Masking on base table. Used in duplicate detection hash. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN SerialID COMMENT 'Affiliate (partner/introducing broker) ID. From CustomerStatic. FK to BackOffice.Affiliate. NULL for direct/organic registrations. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN ReferralID COMMENT 'Referral CID - the customer who referred this one. From CustomerStatic. Used for RAF (Refer-a-Friend) program tracking. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN SubSerialID COMMENT 'Sub-affiliate identifier string. From CustomerStatic. Up to 1024 chars for complex affiliate tracking paths. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Email COMMENT 'Customer email address. From CustomerStatic. Dynamic Data Masking on base table. Unique (case-insensitive). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN IsEmailVerified COMMENT 'Whether the email was verified by clicking a confirmation link. From CustomerStatic. NULL for accounts predating this flag. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Phone COMMENT 'Primary phone number. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Fax COMMENT 'Fax number. From CustomerStatic. Legacy field; rarely populated in modern registrations. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Mobile COMMENT 'Mobile number. From CustomerStatic. Dynamic Data Masking on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN Comments COMMENT 'Internal comment field. From CustomerStatic. BackOffice operators can add notes. varchar(8000). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN DownloadID COMMENT 'Platform download source ID. From CustomerStatic. Legacy tracking for which platform installer the customer used. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN BannerID COMMENT 'Advertising banner ID that led to registration. From CustomerStatic. Legacy acquisition tracking. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN ClientVersion COMMENT 'Client application version at registration. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PersonID COMMENT 'External person identifier. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN BonusCredit COMMENT 'Promotional/bonus credits separate from real funds. From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. Tracked separately to distinguish promotional funds from deposited funds. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN DownloadCounter COMMENT 'Number of times the customer has downloaded the platform client. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN AccountExpirationDate COMMENT 'Expiration date for demo or time-limited accounts. From CustomerStatic. NULL for standard real-money accounts. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN HelpDeskType COMMENT 'Customer service tier assignment. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN LotCountGroupID COMMENT 'Lot/quantity group. From CustomerStatic. FK to Dictionary.LotCountGroup. Controls min/max lot sizes for trading. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PrivacyPolicyID COMMENT 'Privacy policy version accepted by the customer. From CustomerStatic. FK to Dictionary.PrivacyPolicy. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN GCID COMMENT 'Group Customer ID - cross-product identity key linking same person across eToro products. From CustomerStatic. NULL for accounts predating GCID introduction. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN WeekendFeePrecentage COMMENT 'Weekend swap fee percentage (100=full fee, <100=discounted). From CustomerStatic. Note: column name has typo "Precentage". (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN IsEmailActivated COMMENT 'Email activation status flag. From CustomerStatic. Separate from IsEmailVerified - tracks account email activation step completion. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN UserName_LOWER COMMENT 'Computed: lower(UserName). From CustomerStatic. Used for case-insensitive username uniqueness enforcement. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN RealizedEquity COMMENT 'Running total of realized account value (deposits + closed-position proceeds - withdrawals). From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. Answers: "How much realized value does this customer have?" (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN AccountStatusID COMMENT 'Account operational status. From CustomerStatic. 1=Active/Normal (93.9%); 2=Closed/Restricted; NULL=pre-AccountStatusID era. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PendingClosureStatusID COMMENT 'Status in the pending account closure workflow. From CustomerStatic. Default=1 (no pending closure). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN IsRequestedCall COMMENT 'Whether the customer has requested a callback from sales/support. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN FunnelFromID COMMENT 'Source funnel variant tracking within the acquisition funnel. From CustomerStatic. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN LeverageType COMMENT 'Leverage setting type (default=1). From CustomerStatic. Determines the leverage scheme applied to this account. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN TotalCash COMMENT 'Reconciled total cash balance maintained by the Trade.UpdateTotalCash reconciliation job. From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN ClientTypeID COMMENT 'Client classification type for MiFID2 categorization (retail, professional, etc.). From CustomerStatic. FK to Dictionary.ClientType. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN IsHedged COMMENT 'Whether this customer''s trades are hedged on the broker side. From CustomerStatic. Managed by CustomerVersionInsert/Update triggers: 0 (not hedged) for Popular Investors (PlayerLevelID=4) or BonusOnly (LabelID=26) or CEP/BonusOnlyCustomers list members; 1 (hedged) for all others. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN LowerEmail COMMENT 'Computed: lower(Email). From CustomerStatic. Used for case-insensitive email uniqueness enforcement. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN ID COMMENT 'System GUID for REST API identity. From CustomerStatic. Default=newsequentialid(). Unique index on base table. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN VerificationTitle COMMENT 'KYC verification title/level text. From CustomerStatic. Default from Customer.VerificationTitle_Default() function. Changes are versioned in History.Customer. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN VerificationTitleVersion COMMENT 'Version GUID for optimistic concurrency on verification title updates. From CustomerStatic. Default=newid(). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN BuildingNumber COMMENT 'Building/apartment number. From CustomerStatic. Dynamic Data Masking on base table. Structured address field added 2015 (changelog: 02/08/2015). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PhonePrefix COMMENT 'International dialing prefix (e.g., +1, +44). From CustomerStatic. Added 2015 (changelog: 27/10/2015). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PhoneBody COMMENT 'Local phone number without country prefix. From CustomerStatic. Dynamic Data Masking on base table. Added 2015 (changelog: 27/10/2015). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN ExternalID COMMENT 'APEX broker external ID. From CustomerStatic. Unique index on base table. Decimal(38,0) accommodates APEX''s large numeric ID format. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN RegionID COMMENT 'Geographic region ID (GeoIP-derived or set). From CustomerStatic. Added 2016 (changelog: 40722) alongside CountryIDByIP for granular regulation. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN RegionByIP_ID COMMENT 'Region detected from IP address. From CustomerStatic. Added 2016 (changelog: 40722). Separate from RegionID (profile-based) for mismatch detection. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PlatformID COMMENT 'Platform/product identifier (web, mobile, etc.). From CustomerStatic. Added 2016 (changelog: 40618). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN BSLRealFunds COMMENT 'Real funds threshold for Balance Stop Loss (BSL) - safety floor that triggers position liquidation if equity drops below this level. From CustomerMoney (LEFT JOIN). NULL if no CustomerMoney row. Updated by PostMIMOOperations pipeline. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN OptOutReasonID COMMENT 'Reason for GDPR/marketing opt-out. From CustomerStatic. Added 2017 (changelog: 18-07-2017). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PlayerStatusReasonID COMMENT 'Reason code for current PlayerStatusID ("why" behind a non-Active status). From CustomerStatic. Added 2017 (changelog: 24/07/2017). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PlayerStatusSubReasonID COMMENT 'Sub-reason code for PlayerStatus (hierarchical). From CustomerStatic. FK to Dictionary.PlayerStatusSubReasons. Added 2019 (changelog: RD-1752). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN PlayerStatusSubReasonComment COMMENT 'Free-text comment for the PlayerStatusSubReasonID. From CustomerStatic. Max 64 chars. Added 2019. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN POBCountryID COMMENT 'Place of birth country. From CustomerStatic. FK to Dictionary.Country. Added 2019 (HLD: RD-4436 Add Place of Birth to KYC). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN SubRegionID COMMENT 'Sub-region (province/state for non-US countries). From CustomerStatic. FK to Dictionary.SubRegion. Added 2019 (changelog: 09/07/2019). (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN EmailVerificationProviderID COMMENT 'External email verification provider used for this customer''s email. From CustomerStatic. FK to Dictionary.EmailVerificationProvider. Added 2020. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
ALTER TABLE main.general.bronze_etoro_customer_customer_masked ALTER COLUMN DltID COMMENT 'Distributed Ledger Technology integration ID. From CustomerStatic. Added per HLD: COAKVU-2880 DLT Integration. Links customer to DLT/blockchain system. (Tier 1 - upstream wiki, etoro.Customer.Customer)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:35:25 UTC
-- Bronze deploy: etoro batch 1
-- ====================
