-- =============================================================================
-- Databricks ALTER Script: bronze etoro.Trade.Orders
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Trade/Tables/Trade.Orders.md
-- Layer: bronze
-- UC Target: main.dealing.bronze_etoro_trade_orders
-- =============================================================================

-- ---- UC Target: main.dealing.bronze_etoro_trade_orders (business_group=dealing) ----
ALTER TABLE main.dealing.bronze_etoro_trade_orders SET TBLPROPERTIES (
    'comment' = 'Active (currently open or pending) trading orders awaiting execution or closure on the eToro platform. Source: etoro.Trade.Orders on the etoro production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/DB_Schema/etoro/Wiki/Trade/Tables/Trade.Orders.md).'
);

ALTER TABLE main.dealing.bronze_etoro_trade_orders SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'etoro',
    'source_schema' = 'Trade',
    'source_table' = 'Orders',
    'business_group' = 'dealing',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN OrderID COMMENT 'Primary key identifying a unique order. Generated by Internal.GetOrderID during Trade.OrdersAdd. Moves to History.Orders.OrderID on closure. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN CID COMMENT 'Customer ID of the account that placed the order. References Customer.Customer.CID. Used to look up client version and restrictions. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN CurrencyID COMMENT 'Currency denomination of the order amount. References Dictionary.Currency. Typically the customer''s account currency. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN ProviderID COMMENT 'Liquidity provider executing this order. References Trade.Provider. Used with InstrumentID to look up current price from Trade.CurrencyPrice. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN OrderTypeID COMMENT 'Type of trading operation. FK to Dictionary.OrderType: 0=PendingOrderByAmount, 1=OpenTrade, 2=OpenTradeFromOrder, 3=CloseTrade, 4=OpenEntryBuyStopOrder, 5=OpenEntryBuyLimitOrder, 6=OpenEntrySellStopOrder, 7=OpenEntrySellLimitOrder, 8=CloseTradeOrder, 9=EditStopLoss, 10=EditTakeProfit, 11=EditOverWeekend, 12=EditOverWeekendWithStopLossRate, 13=EntryOrderByAmount, 14=ExitOrder, 15=PendingOrderByUnits, 16=EntryOrderByUnits, 17=OrderForExecutionByAmount, 18=OrderForExecutionByUnits, 19=OrderForCloseByUnits, 20=OrderForCloseMultiple. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN InstrumentID COMMENT 'Financial instrument being traded. References Trade.Instrument.InstrumentID. Validated against parent order''s instrument in copy-trade scenarios. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN Leverage COMMENT 'Leverage multiplier applied to the order. Must be non-zero (validated by Trade.OrdersAdd with RAISERROR). Determines margin requirement. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN Amount COMMENT 'Order monetary amount in the customer''s currency. Must be positive (enforced by CHECK constraint CH_TradeOrders_Amount). Validated in OrdersAdd to be > 0. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN Units COMMENT 'Number of discrete units (shares/lots) for the order. Used with LotCountDecimal for position sizing. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN UnitMargin COMMENT 'Margin requirement per unit. Represents the collateral required for each unit of the position. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN LotCountDecimal COMMENT 'Precise lot count for the order. Must be positive (CHECK constraint CH_TradeOrders_LotCountDecimal). Multiplied by Units to compute AmountInUnitsDecimal in Trade.GetOpenOrders. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN RateFrom COMMENT 'Opening/trigger price rate for the order. For market orders, the execution rate; for entry orders, the price level that triggers execution. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN RateTo COMMENT 'Target/limit price rate for the order. Used as the upper bound in range-based orders. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN IsBuy COMMENT 'Trade direction: 1 = Buy/Long (customer profits when price rises), 0 = Sell/Short (customer profits when price falls). Converted to INT in Trade.GetOrders view. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN ForexResultID COMMENT 'Deprecated. Always set to -1 in Trade.OrdersAdd per code comment: "ForexResultID is not being used anymore and we got few errors about foreign key violation." Retained for backward compatibility. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN GameID COMMENT 'Legacy identifier from eToro''s social trading game era. Default = 0 in OrdersAdd. No longer actively used in current trading logic. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN SpreadID COMMENT 'Spread configuration applied to this order. References Trade.Spread. Default = 0 in OrdersAdd. Determines bid-ask spread pricing. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN LoginID COMMENT 'Session login identifier of the user who placed the order. Default = 0. Links to the Customer.Login session that created this order. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN IsOverWeekend COMMENT 'Whether the order can remain open over weekends. 1 = position stays open over the weekend (default), 0 = position is closed before weekend market closure. Converted to INT in Trade.GetOrders. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN StopLosAmount COMMENT 'Stop-loss protection amount in monetary terms. Amount of loss (in customer currency) at which the position auto-closes to prevent further loss. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN TakeProfitAmount COMMENT 'Take-profit target amount in monetary terms. Amount of profit at which the position auto-closes to lock in gains. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN MarketSpreadPips COMMENT 'Market spread at order time, expressed in pips (smallest price increment for forex instruments). Captured for execution quality tracking. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN MarketSpreadCents COMMENT 'Market spread at order time, expressed in cents (for equity/stock instruments). Captured for execution quality tracking. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN StopLosRate COMMENT 'Stop-loss trigger price rate. When the market hits this rate, the position is automatically closed. Indexed via IX_instrumentID INCLUDE. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN TakeProfitRate COMMENT 'Take-profit trigger price rate. When the market hits this rate, the position is automatically closed to lock in gains. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN OccurredTime COMMENT 'Timestamp when the order was created. Set to GETDATE() during Trade.OrdersAdd. Moved to History.Orders.OpenOccurred on closure. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN TradeRange COMMENT 'Market range tolerance for order execution. Defines the acceptable price deviation from the requested rate during execution. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN ParentOrderID COMMENT 'Copy-trade parent order reference. 0 or NULL = independent/manual order. Positive value = this order was created as a copy of the referenced parent order (CopyTrader). Validated in OrdersAdd to ensure parent exists and has the same InstrumentID. Default = 1. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN LastOpPriceRateID COMMENT 'Price rate record ID from Trade.CurrencyPrice.PriceRateID at the time of order creation. Auto-populated from CurrencyPrice if not provided by caller. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN LastOpPriceRate COMMENT 'Mid-market price ((Bid+Ask)/2) from Trade.CurrencyPrice at order creation time. Used for reference pricing and PnL baseline. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN LastOpConversionRate COMMENT 'Currency conversion rate at order creation. For major instruments = 1. For others, derived from CurrencyPrice via the instrument''s currency pair. Stored as 0 when conversion rate is 1. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN LastOpConversionRateID COMMENT 'Conversion rate record ID from Trade.CurrencyPrice.PriceRateID. Stored as 0 when no conversion is needed (major instruments). (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN IsTslEnabled COMMENT 'Trailing Stop Loss flag: 1 = trailing stop-loss is active (stop-loss rate follows favorable price movement), 0 = fixed stop-loss. Stored as IIF(ISNULL(@IsTslEnabled,0)=0,0,1) in OrdersAdd. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN AmountInUnitsDecimal COMMENT 'Precise position size in decimal units. Added in FB 47233 (Aug 2017) to support fractional share trading. When NULL, the GetOpenOrders view computes it as LotCountDecimal * Units. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN IsDiscounted COMMENT 'Whether the order receives a discounted fee/spread rate. 1 = discounted pricing applies, NULL/0 = standard pricing. Added for promotional or loyalty-based fee reductions. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN IsSettled COMMENT 'Legacy settlement flag predating SettlementTypeID: 1 = real stock position (customer owns actual shares), 0/NULL = CFD (contract for difference). When SettlementTypeID is NULL, this flag is used as fallback. See Section 2.3. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN IsNoStopLoss COMMENT 'Whether the order has no stop-loss protection. 1 = order was explicitly placed without stop-loss, NULL = standard stop-loss rules apply. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN IsNoTakeProfit COMMENT 'Whether the order has no take-profit target. 1 = order was explicitly placed without take-profit, NULL = standard take-profit rules apply. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
ALTER TABLE main.dealing.bronze_etoro_trade_orders ALTER COLUMN SettlementTypeID COMMENT 'Settlement model classification. References Dictionary.SettlementTypes: 0=CFD, 1=REAL (stock ownership), 2=TRS (total return swap), 3=CMT, 4=REAL_FUTURES, 5=MARGIN_TRADE. Modern replacement for legacy IsSettled flag. See Section 2.3. (Tier 1 - upstream wiki, etoro.Trade.Orders)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:35:25 UTC
-- Bronze deploy: etoro batch 1
-- ====================
