-- =============================================================================
-- Databricks ALTER Script: bronze WalletDB.Staking.Staking
-- Generated: 2026-04-30 | tools/uc_bronze/generate_bronze_alters.py
-- Source wiki: knowledge/ProdSchemas/CryptoDBs/WalletDB/Wiki/Staking/Tables/Staking.Staking.md
-- Layer: bronze
-- UC Target: main.wallet.bronze_walletdb_staking_staking
-- =============================================================================

-- ---- UC Target: main.wallet.bronze_walletdb_staking_staking (business_group=Wallet) ----
ALTER TABLE main.wallet.bronze_walletdb_staking_staking SET TBLPROPERTIES (
    'comment' = 'Core table recording each crypto staking transfer operation, linking a user''s wallet to the amount of assets delegated for Proof-of-Stake rewards. Source: WalletDB.Staking.Staking on the WalletDB production database, ingested via the Generic Pipeline (Override strategy, 1440-minute refresh). Doc source: Tier 1 wiki (knowledge/ProdSchemas/CryptoDBs/WalletDB/Wiki/Staking/Tables/Staking.Staking.md).'
);

ALTER TABLE main.wallet.bronze_walletdb_staking_staking SET TAGS (
    'layer' = 'bronze',
    'source_system' = 'SQL Server',
    'source_database' = 'WalletDB',
    'source_schema' = 'Staking',
    'source_table' = 'Staking',
    'business_group' = 'Wallet',
    'pipeline' = 'generic_pipeline',
    'doc_source' = 'tier1_wiki',
    'doc_generated' = '2026-04-30',
    'copy_strategy' = 'Override',
    'refresh_minutes' = '1440'
);

-- Column Comments
ALTER TABLE main.wallet.bronze_walletdb_staking_staking ALTER COLUMN Id COMMENT 'Auto-incrementing surrogate key. PK referenced by Staking.StakingStatuses.StakingId and Staking.StakingTransactions.StakingId via explicit FKs. (Tier 1 - upstream wiki, WalletDB.Staking.Staking)';
ALTER TABLE main.wallet.bronze_walletdb_staking_staking ALTER COLUMN WalletId COMMENT 'The customer wallet from which crypto is being staked. FK to Wallet.Wallets.WalletId. Identifies the user and blockchain. Used by Staking.GetStakingTotals to filter per-wallet totals and by Staking.InsertStaking to resolve CryptoId via Wallet.CustomerWalletsView for backward compatibility. (Tier 1 - upstream wiki, WalletDB.Staking.Staking)';
ALTER TABLE main.wallet.bronze_walletdb_staking_staking ALTER COLUMN Amount COMMENT 'Quantity of cryptocurrency being staked, in the asset''s native units (e.g., 1.345547 ETH). Summed by Staking.GetStakingTotals for total staked calculation (only Completed operations). High precision (18 decimals) to handle sub-unit amounts. (Tier 1 - upstream wiki, WalletDB.Staking.Staking)';
ALTER TABLE main.wallet.bronze_walletdb_staking_staking ALTER COLUMN CorrelationId COMMENT 'Idempotency key for the staking operation. Generated by the calling service to uniquely identify each staking request. Used by InsertStaking for duplicate detection (NOT EXISTS check), and by InsertStakingStatus and InsertStakingTransaction as the lookup key to find the staking record. (Tier 1 - upstream wiki, WalletDB.Staking.Staking)';
ALTER TABLE main.wallet.bronze_walletdb_staking_staking ALTER COLUMN CryptoId COMMENT 'The cryptocurrency being staked. FK to Wallet.CryptoTypes.CryptoID. Currently all records are CryptoId=2 (ETH) in this environment. For backward compatibility, InsertStaking resolves this from Wallet.CustomerWalletsView if the parameter is NULL. See Crypto Activity Status for asset details. (Tier 1 - upstream wiki, WalletDB.Staking.Staking)';
ALTER TABLE main.wallet.bronze_walletdb_staking_staking ALTER COLUMN Occurred COMMENT 'Timestamp when the staking operation was initiated. Defaults to UTC now. Used by Staking.StakingData view for date-based reporting columns (Staking_DateTime, Staking_Date, Staking_DateID). (Tier 1 - upstream wiki, WalletDB.Staking.Staking)';
-- == LAST EXECUTION ==
-- Timestamp: 2026-05-03 10:10:21 UTC
-- Bronze deploy: WalletDB batch 1
-- ====================
